import { Component, computed, signal } from '@angular/core';
import { RouteMode, distributiveRoute } from './rings-ch2-model';

@Component({selector:'app-rings-ch2-mixed-route-machine',standalone:true,template:`
<article class="algebra-v3-lesson rings-lesson">
  <header class="hero"><p class="eyebrow">Rings & Ideals · 2.2</p><h2>拿掉 rectangle，留下真正的骨架：兩條 mixed-operation routes 必須同終點</h2><p class="lede">回到 Ch1 的 modulo clock。上路先把 b、c 相加再乘 a；下路先把 a 分別送進兩個 branches，再把 products 相加。</p></header>
  <section class="prediction"><div><p class="kicker">先預測</p><h3>在 ℤ/6ℤ 中，a=4、b=2、c=3：兩路最後落在哪裡？</h3></div><div class="choice-row"><button type="button" (click)="prediction.set(2)">都落在 2</button><button type="button" (click)="prediction.set(4)">都落在 4</button><button type="button" (click)="prediction.set(-1)">會分岔</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()!==2">{{prediction()===2?'對。現在逐段打開 histories，不只核對 final answer。':'沿上路：2+3→5，再做 4×5 mod 6→2。下路也會抵達 2。'}}</p>}</section>
  <div class="control-row"><span class="kicker">a</span>@for(v of residues;track v){<button type="button" [class.active]="a()===v" (click)="a.set(v)">{{v}}</button>}<span class="kicker">b</span>@for(v of residues;track v){<button type="button" [class.active]="b()===v" (click)="b.set(v)">{{v}}</button>}<span class="kicker">c</span>@for(v of residues;track v){<button type="button" [class.active]="c()===v" (click)="c.set(v)">{{v}}</button>}<div class="route-toggle"><button type="button" [class.active]="mode()==='whole'" (click)="mode.set('whole')">WHOLE</button><button type="button" class="multiply" [class.active]="mode()==='split'" (click)="mode.set('split')">SPLIT</button><button type="button" [class.active]="mode()==='both'" (click)="mode.set('both')">BOTH</button></div></div>
  <section class="stage stage-grid"><div class="route-stack" role="img" [attr.aria-label]="ariaLabel()">
    <div class="route-lane whole" [class.active]="mode()!=='split'"><div class="route-node"><strong>{{b()}}, {{c()}}</strong><small>same inputs</small></div><div class="route-arrow">ADD →</div><div class="route-node"><strong>{{route().wholeSum}}</strong><small>b+c mod 6</small></div><div class="route-arrow">× a →</div><div class="route-node endpoint"><strong>{{route().wholeEnd}}</strong><small>a(b+c)</small></div></div>
    <div class="route-lane split" [class.active]="mode()!=='whole'"><div class="route-node"><strong>{{b()}}, {{c()}}</strong><small>same inputs</small></div><div class="route-arrow">× a separately →</div><div class="route-node"><strong>{{route().leftProduct}}, {{route().rightProduct}}</strong><small>ab, ac</small></div><div class="route-arrow">ADD →</div><div class="route-node endpoint"><strong>{{route().splitEnd}}</strong><small>ab+ac</small></div></div>
    <div class="same-stamp">SAME ENDPOINT · {{route().wholeEnd}}</div>
  </div><aside class="console" aria-live="polite"><p class="kicker">ROUTE HISTORY</p><h3>中間 states 不同，final socket 相同</h3><p>WHOLE：{{b()}}+{{c()}}→{{route().wholeSum}}→{{a()}}×{{route().wholeSum}}→{{route().wholeEnd}}</p><p>SPLIT：{{a()}}×{{b()}}→{{route().leftProduct}}；{{a()}}×{{c()}}→{{route().rightProduct}}；ADD→{{route().splitEnd}}</p><div class="readout">a(b+c) = ab+ac = {{route().wholeEnd}} in ℤ/6ℤ</div></aside></section>
  <section class="insight"><span class="insight-icon">⇉</span><div><strong>Distributivity 是 route equality</strong><span>中間可以不同，endpoint 不可分岔。</span></div></section>
  <details><summary>把固定 multiplier 寫成一台 machine</summary><p>令 <code>mₐ(x)=ax</code>，distributivity 可讀成 <code>mₐ(b+c)=mₐ(b)+mₐ(c)</code>：這台 multiplication machine 尊重 addition 組好的結構。</p></details>
</article>`})
export class RingsCh2MixedRouteMachineComponent{
  readonly residues=[0,1,2,3,4,5] as const;readonly a=signal(4);readonly b=signal(2);readonly c=signal(3);readonly mode=signal<RouteMode>('both');readonly prediction=signal<number|null>(null);readonly route=computed(()=>distributiveRoute(this.a(),this.b(),this.c()));readonly ariaLabel=computed(()=>`模六世界 distributivity two-route machine，whole route 與 split route 都抵達 ${this.route().wholeEnd}`);
}
