import { Component, computed, signal } from '@angular/core';
import { RouteMode, functionRoute } from './rings-ch2-model';

@Component({selector:'app-rings-ch2-function-distribution',standalone:true,template:`
<article class="algebra-v3-lesson rings-lesson">
  <header class="hero"><p class="eyebrow">Rings & Ideals · 2.4</p><h2>Distributivity 不是 rectangle 的特權：function cards 也走同一對 routes</h2><p class="lede">每張 card 是一個 <code>&#123;A,B,C&#125;→ℤ</code> function。固定 multiplier function h；在每條 input lane，上路計算 h(f+g)，下路計算 hf+hg。</p></header>
  <section class="prediction"><div><p class="kicker">先預測</p><h3>要判斷兩個 output functions 相同，只核對 B lane 足夠嗎？</h3></div><div class="choice-row"><button type="button" (click)="prediction.set(false)">不夠，所有 lanes</button><button type="button" (click)="prediction.set(true)">夠，一條 lane</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'一條 lane 只證明一個 input 的 values 相同；function equality 要逐 input 對齊。':'對。操作時聚焦一條 lane，但 whole-card verdict 會一直核對 A、B、C。'}}</p>}</section>
  <div class="control-row"><span class="kicker">FOCUS LANE</span>@for(name of names;track name;let index=$index){<button type="button" [class.active]="focus()===index" (click)="focus.set(index)">{{name}}</button>}<label class="compact-control">f({{focusedName()}}) <input type="range" min="-3" max="3" [value]="focusedF()" (input)="setFocusedF($event)"><strong>{{focusedF()}}</strong></label><div class="route-toggle"><button type="button" [class.active]="mode()==='whole'" (click)="mode.set('whole')">WHOLE</button><button type="button" class="multiply" [class.active]="mode()==='split'" (click)="mode.set('split')">SPLIT</button><button type="button" [class.active]="mode()==='both'" (click)="mode.set('both')">OVERLAY</button></div><button type="button" (click)="reset()">重設</button></div>
  <section class="stage stage-grid"><div class="function-routes" role="img" [attr.aria-label]="ariaLabel()">
    <div class="function-route whole" [style.opacity]="mode()==='split'?'.4':'1'"><strong>WHOLE</strong><div class="cell"><small>f(x)+g(x)</small><strong>{{route().sum}}</strong></div><div class="cell"><small>h(x)·sum</small><strong>{{h()[focus()]}}×{{route().sum}}</strong></div><div class="cell"><small>endpoint</small><strong>{{route().whole}}</strong></div></div>
    <div class="function-route split" [style.opacity]="mode()==='whole'?'.4':'1'"><strong>SPLIT</strong><div class="cell"><small>h(x)f(x)</small><strong>{{route().hf}}</strong></div><div class="cell"><small>h(x)g(x)</small><strong>{{route().hg}}</strong></div><div class="cell"><small>add endpoints</small><strong>{{route().split}}</strong></div></div>
    <div class="function-summary">@for(name of names;track name;let index=$index){<span [class.focus]="focus()===index"><strong>{{name}}</strong> · {{allRoutes()[index].whole}} = {{allRoutes()[index].split}}</span>}</div><div class="same-stamp">3/3 LANES ALIGNED · SAME OUTPUT FUNCTION</div>
  </div><aside class="console" aria-live="polite"><p class="kicker">POINTWISE ROUTE · {{focusedName()}}</p><h3>{{route().whole}} = {{route().split}}</h3><p>WHOLE：{{h()[focus()]}}({{focusedF()}}+{{g()[focus()]}}) → {{route().whole}}</p><p>SPLIT：{{h()[focus()]}}·{{focusedF()}} + {{h()[focus()]}}·{{g()[focus()]}} → {{route().split}}</p><div class="readout">調整一條 lane 只改該處 values；two-route agreement 保持不變。</div></aside></section>
  <section class="insight"><span class="insight-icon">ƒ</span><div><strong>Multiplication action 保留 addition structure</strong><span>這是 operation 的關係，不是 numbers 或面積的偶然外觀。</span></div></section>
  <details><summary>Pointwise derivation 與左右版本</summary><p>對每個 input x，integer distributivity 給 <code>h(x)(f(x)+g(x))=h(x)f(x)+h(x)g(x)</code>，所以兩張 output functions 在所有 inputs 相同。一般 noncommutative ring 需分別要求 left 與 right distributivity；本課主線先採 commutative rings。</p></details>
</article>`})
export class RingsCh2FunctionDistributionComponent{
  readonly names=['A','B','C'] as const;readonly f=signal([2,-1,1]);readonly g=signal([1,2,-2]);readonly h=signal([3,-2,2]);readonly focus=signal(1);readonly mode=signal<RouteMode>('both');readonly prediction=signal<boolean|null>(null);readonly focusedName=computed(()=>this.names[this.focus()]);readonly focusedF=computed(()=>this.f()[this.focus()]);readonly allRoutes=computed(()=>this.names.map((_,index)=>functionRoute(this.h()[index],this.f()[index],this.g()[index])));readonly route=computed(()=>this.allRoutes()[this.focus()]);readonly ariaLabel=computed(()=>`三點 function distributivity，聚焦 ${this.focusedName()} lane，whole 與 split endpoints 都是 ${this.route().whole}，全部三條 lanes 對齊`);
  setFocusedF(event:Event){const input=event.currentTarget;if(input instanceof HTMLInputElement)this.f.update(values=>values.map((value,index)=>index===this.focus()?+input.value:value));}reset(){this.f.set([2,-1,1]);this.g.set([1,2,-2]);this.h.set([3,-2,2]);this.focus.set(1);this.mode.set('both');this.prediction.set(null);}
}
