import { Component, computed, signal } from '@angular/core';
import { WiringMode, countDistributiveTriples, faultRoute, multiplyMod3 } from './rings-ch2-model';

@Component({selector:'app-rings-ch2-compatibility-fault',standalone:true,template:`
<article class="algebra-v3-lesson rings-lesson">
  <header class="hero"><p class="eyebrow">Rings & Ideals · 2.3</p><h2>所有 outputs 都留在 world，中央齒輪仍可能接錯</h2><p class="lede">只把 modulo-3 multiplication table 的一格從 0 改接成 1。Closure 完全沒壞：九格 outputs 仍都是 0、1、2；但 mixed routes 已不再同步。</p></header>
  <section class="prediction"><div><p class="kicker">先判斷</p><h3>只要改接後的 output 仍在 world，distributivity 會自動保留嗎？</h3></div><div class="choice-row"><button type="button" (click)="prediction.set(false)">不會</button><button type="button" (click)="prediction.set(true)">會，closure 足夠</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'Closure 只檢查單台 machine 的邊界；它沒有比較 operations 交錯後的 routes。':'對。接著固定同一個 witness，看一格 miswire 如何讓 endpoints 分岔。'}}</p>}</section>
  <div class="control-row"><button type="button" [class.active]="wiring()==='correct'" (click)="wiring.set('correct')">CORRECT WIRING</button><button type="button" class="multiply" [class.active]="wiring()==='miswired'" (click)="wiring.set('miswired')">MISWIRE (0,0) → 1</button><button type="button" [class.active]="test()==='closure'" (click)="test.set('closure')">TEST CLOSURE</button><button type="button" [class.active]="test()==='routes'" (click)="test.set('routes')">TEST MIXED ROUTES</button></div>
  <section class="stage stage-grid"><div class="fault-layout">
    <div><p class="kicker">MULTIPLICATION TABLE · ℤ/3ℤ</p><div class="operation-table" role="table" [attr.aria-label]="tableLabel()"><span class="table-cell header">×</span>@for(v of values;track v){<span class="table-cell header">{{v}}</span>}@for(row of values;track row){<span class="table-cell header">{{row}}</span>@for(column of values;track column){<span class="table-cell" [class.changed]="wiring()==='miswired'&&row===0&&column===0">{{product(row,column)}}</span>}}</div><div class="test-badges"><span class="pass">✓ closure 9/9</span><span [class.pass]="passing()===27" [class.fail]="passing()!==27">{{passing()}}/27 routes align</span></div></div>
    <div class="route-stack" role="img" [attr.aria-label]="routeLabel()"><div class="route-lane whole active"><div class="route-node"><strong>0, 0</strong><small>b,c</small></div><div class="route-arrow">ADD →</div><div class="route-node"><strong>0</strong><small>b+c</small></div><div class="route-arrow">0 × →</div><div class="route-node endpoint" [class.mismatch]="!aligned()"><strong>{{route().wholeEnd}}</strong><small>whole end</small></div></div><div class="route-lane split active"><div class="route-node"><strong>0, 0</strong><small>b,c</small></div><div class="route-arrow">0 × separately →</div><div class="route-node"><strong>{{route().leftProduct}}, {{route().rightProduct}}</strong><small>products</small></div><div class="route-arrow">ADD →</div><div class="route-node endpoint" [class.mismatch]="!aligned()"><strong>{{route().splitEnd}}</strong><small>split end</small></div></div><div class="same-stamp" [class.fail]="!aligned()">{{aligned()?'SAME ENDPOINT':'SPLIT ENDPOINTS · WITNESS FOUND'}}</div></div>
  </div><aside class="console" aria-live="polite"><p class="kicker">{{test()==='closure'?'BOUNDARY CHECK':'COMPATIBILITY CHECK'}}</p><h3>{{test()==='closure'?'Outputs 仍全在 0、1、2':'同一個 triple，兩條 routes '+(aligned()?'對齊':'分岔')}}</h3><p>{{reading()}}</p><div class="readout">{{test()==='closure'?'closure: 9/9 cells inside':'whole → '+route().wholeEnd+' · split → '+route().splitEnd}}</div></aside></section>
  <section class="insight"><span class="insight-icon">⚙</span><div><strong>Closure 管邊界；distributivity 管交錯時是否一致</strong><span>兩項檢查彼此不能替代。</span></div></section>
  <details><summary>完整 finite scan 與 mismatch</summary><p>這個三元素 model 可掃完 27 個 triples：correct wiring 通過 27/27；miswire 只通過 {{countDistributiveTriples('miswired')}}/27。主流程只需 witness <code>a=b=c=0</code>：whole end 是 1，split end 是 2。</p></details>
</article>`})
export class RingsCh2CompatibilityFaultComponent{
  readonly values=[0,1,2] as const;readonly wiring=signal<WiringMode>('correct');readonly test=signal<'closure'|'routes'>('closure');readonly prediction=signal<boolean|null>(null);readonly route=computed(()=>faultRoute(this.wiring()));readonly passing=computed(()=>countDistributiveTriples(this.wiring()));readonly aligned=computed(()=>this.route().wholeEnd===this.route().splitEnd);readonly reading=computed(()=>this.test()==='closure'?'唯一改動的 cell 仍輸出 1，所以沒有 result 逃出 world；closure badge 保持通過。':this.aligned()?'Correct table 讓 whole 與 split routes 都抵達 0。':'Miswire 被兩條 routes 使用的次數不同：whole 得 1，split 把 1+1 合成 2。');readonly tableLabel=computed(()=>`模三 multiplication table，${this.wiring()==='correct'?'正常 wiring':'零乘零被改接為一'}`);readonly routeLabel=computed(()=>`固定 a b c 都是零，whole endpoint ${this.route().wholeEnd}，split endpoint ${this.route().splitEnd}`);
  product(a:number,b:number){return multiplyMod3(a,b,this.wiring());}countDistributiveTriples(wiring:WiringMode){return countDistributiveTriples(wiring);}
}
