import { Component, computed, signal } from '@angular/core';
import { allPairs, aSupportedFunctions, constantFunctions, containsPair, pairKey, pairLabel, Pair } from './rings-ch6-model';

@Component({selector:'app-rings-ch6-identity-convention',standalone:true,template:`
<article class="algebra-v3-lesson rings-lesson"><header class="hero"><p class="eyebrow">Rings & Ideals · 6.4</p><h2>「有自己的 identity」不等於「包含 ambient identity」</h2><p class="lede">這一頁只隔離definition choice。A-supported functions能自行相乘，卻使用(1,0)作internal identity；本課要求的是ambient constant-one function (1,1)。</p></header><div class="general-banner"><span>COURSE CONVENTION · SAME AMBIENT 1_R</span><code>1_R = (1,1) must belong to S</code></div>
<section class="prediction"><div><p class="kicker">先預測</p><h3>E=&#123;(r,0)&#125; closed under difference與product，也有identity (1,0)。它符合本課subring convention嗎？</h3></div><div class="choice-row"><button type="button"(click)="prediction.set(false)">不符合，缺ambient 1_R</button><button type="button"(click)="prediction.set(true)">符合，有任何identity即可</button></div>@if(prediction()!==null){<p class="feedback"[class.warning]="prediction()">{{prediction()?'本課固定same-identity convention；(1,0)不能替代R的(1,1)。':'對。這是scope verdict，不是否定E能在其他convention下成為ring。'}}</p>}</section>
<div class="control-row"><span class="kicker">CANDIDATE</span><button type="button"[class.active]="candidate()==='D'"(click)="setCandidate('D')">CONSTANT FUNCTIONS D</button><button type="button"[class.active]="candidate()==='E'"(click)="setCandidate('E')">A-SUPPORTED E</button><button type="button"(click)="differenceChecked.set(true)">TEST DIFFERENCE</button><button type="button"(click)="productChecked.set(true)">TEST PRODUCT</button><button type="button"(click)="identityChecked.set(true)">DOCK AMBIENT 1_R</button><button type="button"(click)="reset()">RESET</button></div>
<section class="stage stage-grid"><div class="identity-lab"><div class="function-world"><div class="candidate-label"><strong>{{candidateLabel()}}</strong><span>{{candidateRule()}}</span></div><div class="function-board"style="--board-size:4">@for(pair of board;track key(pair)){<span class="function-slot"[class.member]="isMember(pair)"[class.output]="identityChecked()&&key(pair)==='1,1'"[class.escape]="identityChecked()&&key(pair)==='1,1'&&!isMember(pair)"><strong>{{label(pair)}}</strong></span>}</div></div><div class="identity-docks"><div class="identity-card ambient"[class.outside]="identityChecked()&&!ambientIdentityInside()"><p class="kicker">AMBIENT 1_R</p><strong>(1,1)</strong><span>constant-one function</span></div><div class="identity-card internal"[class.outside]="candidate()==='D'"><p class="kicker">INTERNAL-ONLY CARD</p><strong>(1,0)</strong><span>{{candidate()==='E'?'identity for E':'not identity for D'}}</span></div></div></div><aside class="console"aria-live="polite"><span class="evidence-badge">CONVENTION CHECK</span><h3>{{verdictTitle()}}</h3><div class="status-pair"><span class="status-chip"[class.pass]="differenceChecked()">DIFFERENCE · {{differenceChecked()?'CLOSED':'UNTESTED'}}</span><span class="status-chip"[class.pass]="productChecked()">PRODUCT · {{productChecked()?'CLOSED':'UNTESTED'}}</span></div><p>{{statusText()}}</p><div class="readout">AMBIENT 1_R · {{!identityChecked()?'UNTESTED':ambientIdentityInside()?'INSIDE':'OUTSIDE'}}</div></aside></section>
<section class="insight"><span class="insight-icon">1</span><div><strong>本課的subring與ambient ring共用operations，也共用同一個1_R</strong><span>E的difference／product沒有失敗；它只落在本課definition scope之外。</span></div></section><details><summary>其他教材可能怎麼定義？</summary><p>有些教材允許non-unital subrings，或允許subring擁有不同identity；E在某些conventions下會被接受。這不是誰算錯，而是definition scope不同。本課後續maps與ideals固定採same ambient identity。</p></details></article>`})
export class RingsCh6IdentityConventionComponent{readonly board=allPairs(4);readonly candidate=signal<'D'|'E'>('E');readonly differenceChecked=signal(false);readonly productChecked=signal(false);readonly identityChecked=signal(false);readonly prediction=signal<boolean|null>(null);readonly members=computed(()=>this.candidate()==='D'?constantFunctions(4):aSupportedFunctions());readonly ambientIdentityInside=computed(()=>containsPair(this.members(),[1,1]));key=pairKey;label=pairLabel;isMember(pair:Pair){return containsPair(this.members(),pair);}candidateLabel(){return this.candidate()==='D'?'D · CONSTANT FUNCTIONS':'E · A-SUPPORTED FUNCTIONS';}candidateRule(){return this.candidate()==='D'?'h(A)=h(B)':'h(B)=0';}verdictTitle(){return !this.identityChecked()?'THREE CHECKS STAY SEPARATE':this.ambientIdentityInside()?'INSIDE COURSE CONVENTION':'OUTSIDE COURSE CONVENTION';}statusText(){return !this.identityChecked()?'Difference與product通過不會自動替identity port補票。':this.ambientIdentityInside()?'D包含同一張constant-one function (1,1)。':'E中的(1,0)只對E內cards像identity；ambient (1,1)仍在boundary外。';}setCandidate(candidate:'D'|'E'){this.candidate.set(candidate);this.differenceChecked.set(false);this.productChecked.set(false);this.identityChecked.set(false);}reset(){this.setCandidate('E');}}
