import { Component, computed, signal } from '@angular/core';
import { almostConstantFunctions, constantFunctions, containsPair, operatePair, pairKey, pairLabel, Pair, PairOperation } from './rings-ch6-model';

interface AuditRecord { key:string; passed:boolean; output:Pair; }

@Component({
  selector: 'app-rings-ch6-universal-closure',standalone:true,
  template:`<article class="algebra-v3-lesson rings-lesson"><header class="hero"><p class="eyebrow">Rings & Ideals · 6.2</p><h2>Closure 是所有 pairs 都不逃逸，不是幾次成功紀錄</h2><p class="lede">很多綠色examples只能增加信心；一個有完整inputs與output的escape witness，才足以立即否決universal no-escape claim。</p></header><div class="general-banner"><span>FINITE CANDIDATE AUDIT</span><code>∀ s,t∈S · s−t∈S and st∈S</code></div>
  <section class="prediction"><div><p class="kicker">先預測</p><h3>C 已有兩筆成功紀錄。這足以證明所有 pairs 都不逃逸嗎？</h3></div><div class="choice-row"><button type="button"(click)="prediction.set(false)">仍然不足</button><button type="button"(click)="prediction.set(true)">兩次成功就足夠</button></div>@if(prediction()!==null){<p class="feedback"[class.warning]="prediction()">{{prediction()?'Universal claim仍藏著許多untested cells。':'對。一個failure能否決；成功則需要general argument或finite exhaustion。'}}</p>}</section>
  <div class="control-row"><span class="case-badge">{{candidate()==='C'?'C · ALMOST CONSTANT':'D · CONSTANT FUNCTIONS'}}</span><span class="kicker">OPERATION</span><button type="button"[class.active]="operation()==='difference'"(click)="setOperation('difference')">DIFFERENCE</button><button type="button"[class.active]="operation()==='multiply'"(click)="setOperation('multiply')">MULTIPLY</button><button type="button"(click)="trySafeSample()">TRY SAFE SAMPLE</button><button type="button"(click)="tryWitness()">TRY DECISIVE PAIR</button>@if(dUnlocked()){<button type="button"(click)="switchToD()">AUDIT D</button><button type="button"(click)="completeAudit()">COMPLETE FINITE AUDIT</button>}<button type="button"(click)="reset()">RESET</button></div>
  <section class="stage stage-grid"><div class="audit-lab"><div class="function-world"><div class="candidate-label"><strong>{{candidateLabel()}}</strong><span>{{records().length}} tested</span></div><div class="function-board"style="--board-size:4">@for(pair of board;track key(pair)){<span class="function-slot"[class.member]="isMember(pair)"[class.escape]="latestEscape()&&key(latestEscape()!)===key(pair)"><strong>{{label(pair)}}</strong></span>}</div></div><div class="audit-matrix"><p class="kicker">INPUT-PAIR HISTORY · {{operation().toUpperCase()}}</p><div class="audit-grid"[style.--audit-size]="members().length">@for(left of members();track key(left)){@for(right of members();track key(right)){<span class="audit-cell"[class.untested]="!recordFor(left,right)"[class.pass]="recordFor(left,right)?.passed"[class.fail]="recordFor(left,right)&&!recordFor(left,right)?.passed">{{cellText(left,right)}}</span>}}</div>@if(exhausted()){<div class="fixed-point">FINITE EXHAUSTION · THIS OPERATION ON D</div>}</div></div><aside class="console"aria-live="polite"><span class="evidence-badge">{{evidenceLabel()}}</span><h3>{{verdictTitle()}}</h3><p>{{verdictText()}}</p><div class="readout">{{latestEquation()}}</div></aside></section>
  <section class="insight"><span class="insight-icon">∀</span><div><strong>Closure 是對所有inputs的 no-escape 承諾</strong><span>成功sample留下untested；一個escape witness立刻推翻candidate。</span></div></section><details><summary>Evidence strength</summary><p>EXAMPLE只能展示可能性；WITNESS足以推翻universal claim；完整finite scan能證明目前finite candidate，但不自動推廣到infinite worlds。</p></details></article>`})
export class RingsCh6UniversalClosureComponent{
 readonly board=Array.from({length:4},(_,a)=>Array.from({length:4},(_,b)=>[a,b]as Pair)).flat();readonly candidate=signal<'C'|'D'>('C');readonly operation=signal<PairOperation>('difference');readonly records=signal<AuditRecord[]>([]);readonly dUnlocked=signal(false);readonly prediction=signal<boolean|null>(null);
 readonly members=computed(()=>this.candidate()==='C'?almostConstantFunctions():constantFunctions(4));readonly candidateLabel=computed(()=>this.candidate()==='C'?'C = constant functions + (1,0)':'D = all constant functions');readonly exhausted=computed(()=>this.records().length===this.members().length**2);readonly latest=computed(()=>this.records().at(-1)??null);readonly latestEscape=computed(()=>this.latest()&&!this.latest()!.passed?this.latest()!.output:null);
 key=pairKey;label=pairLabel;isMember(p:Pair){return containsPair(this.members(),p);}recordFor(l:Pair,r:Pair){const k=`${pairKey(l)}|${pairKey(r)}`;return this.records().find(x=>x.key===k);}cellText(l:Pair,r:Pair){const rec=this.recordFor(l,r);return rec?rec.passed?'IN':`OUT ${pairLabel(rec.output)}`:'UNTESTED';}
 test(l:Pair,r:Pair){const output=operatePair(l,r,this.operation(),4),passed=this.isMember(output),key=`${pairKey(l)}|${pairKey(r)}`;this.records.update(items=>[...items.filter(item=>item.key!==key),{key,passed,output}]);if(!passed)this.dUnlocked.set(true);}
 trySafeSample(){this.test([1,0],[0,0]);}tryWitness(){this.operation.set('difference');this.test([1,0],[3,3]);}
 setOperation(op:PairOperation){this.operation.set(op);this.records.set([]);}switchToD(){this.candidate.set('D');this.records.set([]);}completeAudit(){const entries:AuditRecord[]=[];for(const l of this.members())for(const r of this.members()){const output=operatePair(l,r,this.operation(),4);entries.push({key:`${pairKey(l)}|${pairKey(r)}`,passed:containsPair(this.members(),output),output});}this.records.set(entries);}
 evidenceLabel(){return this.latest()&&!this.latest()!.passed?'WITNESS':this.exhausted()?'FINITE EXHAUSTION':this.records().length?'EXAMPLE':'UNTESTED';}verdictTitle(){return this.latest()&&!this.latest()!.passed?'CANDIDATE DISPROVED':this.exhausted()?'NO ESCAPES IN COMPLETE SCAN':'UNIVERSAL CLAIM STILL OPEN';}verdictText(){return this.latest()&&!this.latest()!.passed?'Inputs都在boundary內，但output保留label穿到外面；一個witness已足夠。':this.exhausted()?'目前finite candidate在這個operation下所有ordered pairs都通過。':'成功紀錄不會自動填滿其餘untested cells。';}latestEquation(){const latest=this.latest();return latest?`latest output ${pairLabel(latest.output)} · ${latest.passed?'inside':'outside'}`:'No pair tested yet.';}reset(){this.candidate.set('C');this.operation.set('difference');this.records.set([]);}
}
