import { Component, computed, signal } from '@angular/core';

type ContractLens='laws'|'ports';type Port='identity'|'difference'|'product';

@Component({selector:'app-rings-ch6-subring-contract',standalone:true,template:`
<article class="algebra-v3-lesson rings-lesson"><header class="hero"><p class="eyebrow">Rings & Ideals · 6.3</p><h2>Ambient laws 已通過；boundary 只需證明三個 autonomy ports</h2><p class="lede">Subring test不是把ring axioms再考一次。Operations沒有改，所以equational laws會繼承；新的工作是確保每一步仍能在subset內完成。</p></header><div class="general-banner"><span>GENERAL ARGUMENT</span><code>1_R ∈ S · s−t ∈ S · st ∈ S</code></div>
<section class="prediction"><div><p class="kicker">先預測</p><h3>若 s,t,u 與所有 intermediate products 都留在 S，還需重新證明 (st)u=s(tu) 嗎？</h3></div><div class="choice-row"><button type="button"(click)="prediction.set(false)">不用，ambient已保證</button><button type="button"(click)="prediction.set(true)">必須從頭重證</button></div>@if(prediction()!==null){<p class="feedback"[class.warning]="prediction()">{{prediction()?'兩邊使用的就是R中同一套multiplication，因此ambient equality仍成立。':'對。真正需要新證據的是intermediate outputs會不會逃逸。'}}</p>}</section>
<div class="control-row"><span class="kicker">INSPECTION LENS</span><button type="button"[class.active]="lens()==='laws'"(click)="lens.set('laws')">INHERITED LAWS</button><button type="button"[class.active]="lens()==='ports'"(click)="lens.set('ports')">BOUNDARY OBLIGATIONS</button><button type="button"(click)="inspect('identity')">TEST 1_R</button><button type="button"(click)="inspect('difference')">TEST s−t</button><button type="button"(click)="inspect('product')">TEST st</button><button type="button"(click)="reset()">RESET</button></div>
<section class="stage stage-grid"><div class="contract-lab"><div class="law-module"[class.focus]="lens()==='laws'"><p class="kicker">ALREADY TRUE IN R</p>@for(law of laws;track law.name){<div class="law-seal"><strong>{{law.name}}</strong><span>{{law.readout}}</span></div>}<p>Same cards + same operations = same equalities.</p></div><div class="port-module"[class.focus]="lens()==='ports'"><p class="kicker">STILL MUST STAY IN S</p><button type="button"class="autonomy-port"[class.checked]="checked('identity')"(click)="inspect('identity')"><strong>IDENTITY PORT · 1_R</strong><span class="port-result">{{checked('identity')?'constant-one (1,1) belongs to D':'not inspected'}}</span></button><button type="button"class="autonomy-port"[class.checked]="checked('difference')"(click)="inspect('difference')"><strong>DIFFERENCE PORT · s−t</strong><span class="port-result">{{checked('difference')?'(r,r)−(q,q)=(r−q,r−q) · still constant':'not inspected'}}</span></button><button type="button"class="autonomy-port"[class.checked]="checked('product')"(click)="inspect('product')"><strong>PRODUCT PORT · st</strong><span class="port-result">{{checked('product')?'(r,r)(q,q)=(rq,rq) · still constant':'not inspected'}}</span></button></div></div><aside class="console"aria-live="polite"><span class="evidence-badge">GENERAL ARGUMENT</span><h3>{{allChecked()?'THREE PORTS ACCOUNTED FOR':lens()==='laws'?'LAWS ARRIVE SEALED':'CHECK INTERNAL AUTONOMY'}}</h3><p>{{statusText()}}</p><div class="readout">{{checkedPorts().length}} / 3 boundary obligations inspected</div></aside></section>
<section class="insight"><span class="insight-icon">3</span><div><strong>Subring test只檢查subset能否留在原規則裡自給自足</strong><span>Ambient identities of equations are inherited；membership obligations才是新工作。</span></div></section><details><summary>為什麼 subtraction 能壓縮 additive checks？</summary><p>若S非空且對subtraction closed，取s∈S可得0=s−s；再得−s=0−s，最後s+t=s−(−t)。因此difference closure一次包住additive identity、inverse與addition closure。本課另要求1_R∈S與multiplication closure。</p></details></article>`})
export class RingsCh6SubringContractComponent{readonly lens=signal<ContractLens>('laws');readonly inspected=signal<Port[]>([]);readonly prediction=signal<boolean|null>(null);readonly laws=[{name:'ASSOCIATIVITY',readout:'same endpoints in R'},{name:'DISTRIBUTIVITY',readout:'same mixed routes in R'},{name:'COMMUTATIVE MAIN LANE',readout:'same order promise'}];readonly checkedPorts=computed(()=>this.inspected());readonly allChecked=computed(()=>this.inspected().length===3);checked(port:Port){return this.inspected().includes(port);}inspect(port:Port){this.lens.set('ports');this.inspected.update(items=>items.includes(port)?items:[...items,port]);}statusText(){return this.lens()==='laws'?'S中的cards仍是R的cards，沒有理由重新證明同一條ambient equality。':this.allChecked()?'Identity、difference與product三個ports合起來，讓D能獨立運行本課ring contract。':'每個port回答一個membership問題，不是再背一條ambient law。';}reset(){this.lens.set('laws');this.inspected.set([]);}}
