import { Component, computed, signal } from '@angular/core';
@Component({selector:'app-algebra-v3-overlap-snap',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch12-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 12.3</p><h2>Cosets 不會只重疊一角：碰到一點，就整塊對齊</h2><p class="lede">使用 ℤ₈ 的 H=⟨2⟩。調整 a、b 比較兩個 translates；如果它們共享一個 element，那個共同點足以把兩張相同模板完全校準。</p></header>
<section class="prediction"><p class="kicker">先預測</p><h3>兩個同一 H 的 cosets 可能「部分重疊但不相等」嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不可能</button><button type="button" (click)="prediction.set(true)">可能</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'Cosets obey same-or-disjoint：只要有一個共同點，就能證出兩邊每個點都相同。':'對。下面拖動代表元會看到兩塊只能 snap together 或完全分離。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Overlap snap detector</p><h3>拖動兩個代表元，追蹤每個 ambient node</h3></div><p>A／B／A+B 文字直接標記 membership；不以混色暗示 partial overlap。</p></div><div class="pair-sliders"><label>a <input type="range" min="0" max="7" [value]="a()" (input)="a.set(+$any($event.target).value)"><strong>{{a()}}</strong></label><label>b <input type="range" min="0" max="7" [value]="b()" (input)="b.set(+$any($event.target).value)"><strong>{{b()}}</strong></label></div><div class="stage overlap-layout"><div class="ambient-strip">@for(x of universe;track x){<div [class.in-a]="tileA().includes(x)" [class.in-b]="tileB().includes(x)"><strong>{{x}}</strong><span>{{membership(x)}}</span></div>}</div><section class="tile-console" aria-live="polite"><p class="kicker">OVERLAP STATUS</p><div class="two-tiles"><span>a+H={{label(tileA())}}</span><span>b+H={{label(tileB())}}</span></div><div class="tile-verdict" [class.disjoint]="!same()">{{same()?'✓ SAME TILE · FULL OVERLAP':'∥ DISJOINT TILES · ZERO OVERLAP'}}</div><p>{{same()?'共同點 '+shared()[0]+' 讓兩張 translate templates 完全對齊。':'找不到 shared node；兩塊保持完全分離。'}}</p></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>touch once</span><i>→</i><span>same tile</span><i>else</i><span>disjoint</span></div><p><strong>Same-or-disjoint 來自 subgroup 的封閉性。</strong>Cosets 不是隨手畫出的 sets，而是同一 template 經 group action 搬出的剛性副本。</p></aside>
<section class="transfer"><p class="kicker">代表元</p><h3>若 a+H=b+H，a 與 b 必須是同一 element 嗎？</h3><div class="choice-row"><button type="button" (click)="transfer.set(false)">不必</button><button type="button" (click)="transfer.set(true)">必須</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="transfer()">{{transfer()?'例如 0+H 與 2+H 是同一 even tile。':'對。同一 coset 內的任何 element 都可當代表元。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>Proof Lab：一個交點為何迫使相等？</summary><div>若 x∈aH∩bH，則 x=ah₁=bh₂。故 a=bh₂h₁⁻¹∈bH，所以 aH⊆bH；對稱地 bH⊆aH，因此 aH=bH。</div></details></section></article>`})
export class AlgebraV3OverlapSnapComponent{readonly universe=[0,1,2,3,4,5,6,7];readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly a=signal(0);readonly b=signal(1);readonly h=[0,2,4,6];readonly tileA=computed(()=>this.h.map(x=>(x+this.a())%8).sort((x,y)=>x-y));readonly tileB=computed(()=>this.h.map(x=>(x+this.b())%8).sort((x,y)=>x-y));readonly shared=computed(()=>this.tileA().filter(x=>this.tileB().includes(x)));readonly same=computed(()=>this.shared().length>0);membership(x:number):string{const a=this.tileA().includes(x),b=this.tileB().includes(x);return a&&b?'A + B':a?'A ONLY':b?'B ONLY':'OUTSIDE BOTH';}label(xs:number[]):string{return`{${xs.join(',')}}`;}}
