import { Component, computed, signal } from '@angular/core';
type TileH='h3'|'h2';
@Component({selector:'app-algebra-v3-whole-tile-translator',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch12-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 12.1</p><h2>Coset 是整塊搬家，不是把一個 g 塞進 subgroup</h2><p class="lede">固定 H，再把同一個 shift g 加到 H 的每個 element。原 tile 內的相對 pattern 沒有重算；它只是被整體搬到 group 的另一區。</p></header>
<section class="prediction"><p class="kicker">先預測</p><h3>在 ℤ₆ 中，1+{{'{0,3}'}} 會得到 {{'{1,4}'}} 嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(true)">是</button><button type="button" (click)="prediction.set(false)">不是</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="!prediction()">{{prediction()?'對。1 要一致地加到 tile 中每一點：1+0=1、1+3=4。':'Shift 不是只作用一次；它作用在 H 的每個 member。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Whole-tile translator</p><h3>調整 g，看所有 mapping arrows 同步移動</h3></div><p>每列保留 source、同一 shift、target，讓「整塊」成為可追蹤操作。</p></div><div class="tile-controls"><div role="group" aria-label="選 subgroup"><button type="button" [attr.aria-pressed]="h()==='h3'" (click)="selectH('h3')">H={{'{0,3}'}}</button><button type="button" [attr.aria-pressed]="h()==='h2'" (click)="selectH('h2')">H={{'{0,2,4}'}}</button></div><label>shift g <input type="range" min="0" max="5" [value]="g()" (input)="g.set(+$any($event.target).value)"><strong>{{g()}}</strong></label></div><div class="stage translate-layout"><div class="tile-mappings">@for(value of members();track value){<div><span>{{value}}</span><i>+ {{g()}}</i><b>→</b><strong>{{translate(value)}}</strong></div>}</div><section class="tile-console" aria-live="polite"><p class="kicker">TRANSLATED TILE</p><div class="tile-chip">{{g()}} + H = {{cosetLabel()}}</div><div class="relative-pattern"><span>原 offsets</span><strong>{{members().join(' → ')}}</strong><span>搬後 offsets</span><strong>{{translated().join(' → ')}}</strong></div><p>每個 h 都走同一條「+{{g()}}」規則；沒有單獨增刪 tile 內的點。</p></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>H template</span><i>+ g</i><span>g+H</span></div><p><strong>Coset 是 subgroup template 的 translate。</strong>在 additive notation，g+H={{'{g+h:h∈H}'}}；乘法 notation 則是 gH={{'{gh:h∈H}'}}。</p></aside>
<section class="transfer"><p class="kicker">邊界</p><h3>g+H 一定仍是 subgroup 嗎？</h3><div class="choice-row"><button type="button" (click)="transfer.set(false)">不一定</button><button type="button" (click)="transfer.set(true)">一定</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="transfer()">{{transfer()?'例如 1+{0,3}={1,4} 不含 identity 0。':'對。Coset 是 tile，不必以 identity 為中心；只有含 identity 的 coset 才是 H 本身。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>Left coset 的正式定義</summary><div>對 H≤G 與 g∈G，left coset gH={{'{gh:h∈H}'}}。在 abelian additive group 中寫 g+H。</div></details><details><summary>Non-abelian boundary</summary><div>一般群中 left coset gH 與 right coset Hg 可能不同。本章主模型使用 additive cyclic groups；Ch16 才研究何時左右 translates 對齊。</div></details></section></article>`})
export class AlgebraV3WholeTileTranslatorComponent{readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly h=signal<TileH>('h3');readonly g=signal(1);readonly members=computed(()=>this.h()==='h3'?[0,3]:[0,2,4]);readonly translated=computed(()=>this.members().map(x=>this.translate(x)));translate(x:number):number{return(x+this.g())%6;}cosetLabel():string{return`{${this.translated().join(',')}}`;}selectH(h:TileH):void{this.h.set(h);this.g.set(1);}}
