import { Component, computed, signal } from '@angular/core';
@Component({selector:'app-algebra-v3-partition-sorter',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch12-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 12.4</p><h2>所有 translates 會無縫接起來：不重疊，也不留下孤點</h2><p class="lede">在 ℤ₁₂ 中用 H=⟨4⟩={{'{0,4,8}'}} 當模板。逐一送入 ambient elements；每個 x 自己就保證 x∈x+H，所以一定有歸宿，而 same-or-disjoint 保證不會同時住兩塊。</p></header>
<section class="prediction"><p class="kicker">先判斷</p><h3>列出所有 H-cosets 後，可能有某個 g∈G 不屬於任何一塊嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不可能</button><button type="button" (click)="prediction.set(true)">可能</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'g=g+0，而 0∈H，所以 g 必在 g+H。':'對。每個 element 都自帶至少一個 coset address。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Partition sorter</p><h3>逐點吸入唯一 tile，直到沒有 leftovers</h3></div><p>同餘位置決定 tile address；分類順序不會改變最後 partition。</p></div><div class="stage partition-layout"><div class="partition-board">@for(tile of tiles;track tile.label){<section><h4>{{tile.label}}</h4><div>@for(x of tile.items;track x){<span [class.sorted]="isSorted(x)">{{x}}<small>{{sortStatus(x)}}</small></span>}</div></section>}</div><section class="tile-console" aria-live="polite"><p class="kicker">SORTED {{sorted()}} / 12</p><div class="control-row"><button type="button" class="primary" [disabled]="sorted()===12" (click)="sortNext()">分類下一點</button><button type="button" (click)="sorted.set(0)">清空</button></div><div class="partition-checks"><span>{{sorted()===12?'✓':'…'}} NO LEFTOVERS</span><span>{{sorted()===12?'✓':'…'}} NO OVERLAP</span><span>{{sorted()===12?'✓':'…'}} ALL TILES ARE H-TRANSLATES</span></div>@if(sorted()===12){<div class="tile-verdict">✓ COSETS PARTITION ℤ₁₂</div>}<p>{{currentReading()}}</p></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>every g</span><i>in one</i><span>coset tile</span></div><p><strong>Cosets partition the group。</strong>「覆蓋全部」來自 g∈gH；「不重疊」來自 same-or-disjoint。這兩個結構事實合起來，才會在下一章產生整除。</p></aside>
<section class="transfer"><p class="kicker">預告，不計數</p><h3>如果每塊都與 H 一樣大，又無重疊地鋪滿 finite G，group size 會呈現什麼形狀？</h3><div class="transfer-answer"><span>每塊大小</span><i>×</i><span>distinct tiles 數</span><i>=</i><span>全部大小</span></div></section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>Partition proof 的兩個零件</summary><div>Coverage：任意 g∈G 都滿足 g=ge∈gH。Uniqueness：若 g 同時落在 aH、bH，兩 cosets 有交點，因此相等。故每個 element 恰屬一個 distinct coset。</div></details><details><summary>為何本頁不先寫 Lagrange theorem？</summary><div>本頁先確立 partition 的原因。Ch13 才把「等大、無重疊、無遺漏」翻成 |G|=[G:H]|H|，避免只背整除結論。</div></details></section></article>`})
export class AlgebraV3PartitionSorterComponent{readonly prediction=signal<boolean|null>(null);readonly sorted=signal(0);readonly tiles=[{label:'0+H',items:[0,4,8]},{label:'1+H',items:[1,5,9]},{label:'2+H',items:[2,6,10]},{label:'3+H',items:[3,7,11]}];isSorted(x:number):boolean{return x<this.sorted();}sortStatus(x:number):string{return this.isSorted(x)?'SORTED':'WAITING';}sortNext():void{this.sorted.update(v=>Math.min(12,v+1));}currentReading():string{if(this.sorted()===0)return'所有 ambient elements 尚未分類。';if(this.sorted()===12)return'每一點已有唯一 tile address；沒有 orphan，也沒有 duplicate residence。';const x=this.sorted()-1;return`${x} 已送入 ${x%4}+H；因為 ${x}=${x}+0。`;}}
