import { Component, computed, signal } from '@angular/core';
@Component({selector:'app-algebra-v3-reversible-transport',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch12-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 12.2</p><h2>每塊一樣大，因為平移有一顆完整 undo button</h2><p class="lede">「看起來沒有變形」還不夠。把 H 的每個 h 送到 g+h，再按 −g 回來；若每條 arrow 都能原路復原，就不會 collision、遺漏或憑空增點。</p></header>
<section class="prediction"><p class="kicker">先判斷</p><h3>有限 subgroup H 與任一 coset g+H 的 element 數會相同嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(true)">一定相同</button><button type="button" (click)="prediction.set(false)">不一定</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="!prediction()">{{prediction()?'對。Forward +g 與 undo −g 互為 inverse maps。':'可逆 translation 不會壓縮或複製 elements。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Reversible transport</p><h3>逐條接通 forward 與 undo</h3></div><p>模型使用 ℤ₈ 的 H=⟨2⟩={{'{0,2,4,6}'}}，shift 可任意改變。</p></div><div class="tile-controls"><label>shift g <input type="range" min="0" max="7" [value]="g()" (input)="reset(+$any($event.target).value)"><strong>{{g()}}</strong></label><div class="control-row"><button type="button" class="primary" [disabled]="revealed()===4" (click)="revealNext()">接通下一條</button><button type="button" (click)="revealed.set(0)">重設</button></div></div><div class="stage reversible-layout"><div class="reversible-arrows">@for(h of members;track h;let index=$index){<div [class.connected]="isConnected(index)"><span>{{h}}<small>H</small></span><p><b>+{{g()}} →</b><i>← −{{g()}}</i></p><span>{{target(h)}}<small>g+H</small></span><strong>{{connectionStatus(index)}}</strong></div>}</div><section class="tile-console" aria-live="polite"><p class="kicker">BIJECTION CHECK</p><div class="measure-pair"><div><span>SOURCE COUNT</span><strong>4</strong></div><div><span>TARGET COUNT</span><strong>{{revealed()===4?'4':'?'}}</strong></div></div>@if(revealed()===4){<div class="tile-verdict">✓ NO COLLISION · NO OMISSION · SAME SIZE</div>}<p>{{revealed()===4?'每個 target 都能用 −g 回到唯一 source；translation 是 bijection。':'逐條 reveal 不能取代 proof，但讓 inverse map 的因果可見。'}}</p></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>h</span><i>+g</i><span>g+h</span><i>−g</i><span>h</span></div><p><strong>Cosets 等大不是計數巧合，而是可逆 transport 的結果。</strong>只要存在 forward 與 undo，tile 就不能被壓扁、合併或漏點。</p></aside>
<section class="transfer"><p class="kicker">泛化</p><h3>這個理由需要 G 是 finite group 嗎？</h3><div class="choice-row"><button type="button" (click)="transfer.set(false)">不需要</button><button type="button" (click)="transfer.set(true)">需要</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="transfer()">{{transfer()?'Bijection h↦gh 對 infinite groups 也成立。':'對。有限時可翻成相同數量；無限時仍是 bijection。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>Equal-size proof</summary><div>Define L_g:H→gH by h↦gh。若 gh₁=gh₂，左乘 g⁻¹ 得 h₁=h₂，所以 injective；每個 gH element 依定義都是 gh，所以 surjective。Inverse 是 x↦g⁻¹x。</div></details></section></article>`})
export class AlgebraV3ReversibleTransportComponent{readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly g=signal(3);readonly revealed=signal(0);readonly members=[0,2,4,6];target(h:number):number{return(h+this.g())%8;}isConnected(index:number):boolean{return index<this.revealed();}connectionStatus(index:number):string{return this.isConnected(index)?'ROUND TRIP OK':'LOCKED';}revealNext():void{this.revealed.update(v=>Math.min(4,v+1));}reset(g:number):void{this.g.set(g);this.revealed.set(0);}}
