import{Component,computed,signal}from'@angular/core';import{D3_ELEMENTS,type D3Element,conjugate,label}from'../algebra-v3-ch16/d3-model';type GroupId='d3'|'c4';
@Component({selector:'app-algebra-v3-global-fixed-core',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch25-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 25.3</p><h2>Center 是在每一個 observation frame 中都維持原名的 global fixed core</h2><p class="lede">這次固定 h、掃完所有 k。只要有一個 frame 讓 khk⁻¹≠h，h 就不是 global fixed point；若所有 frames 都不改它，它就在 center。</p></header>
<section class="prediction"><p class="kicker">先預測</p><h3>若 h 與每個 k 都 commute，任何 re-framing 會改變 h 嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不會，khk⁻¹=h</button><button type="button" (click)="prediction.set(true)">會，nontrivial k 總會改名</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'commuting 讓 k 穿過 h，接著 kk⁻¹ 消掉；每個 frame 都仍看見 h。':'對。center 同時是「與所有 elements commute」和「conjugation 全域 fixed」兩種描述。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Global fixed-core scanner</p><h3>比較 nonabelian D₃ 與 abelian C₄</h3></div><p>實線 card 在全部 frames 中固定；虛線 card 至少有一個 frame 會改名。切換群可避免把 D₃ 的小 center 誤當通則。</p></div><div class="group-toggle"><button type="button" [attr.aria-pressed]="group()==='d3'" (click)="setGroup('d3')">D₃ · NONABELIAN</button><button type="button" [attr.aria-pressed]="group()==='c4'" (click)="setGroup('c4')">C₄ · ABELIAN</button></div><div class="element-picker">@for(x of elements();track x){<button type="button" [attr.aria-pressed]="selected()===x" (click)="selected.set(x)">h={{name(x)}}</button>}</div>
<div class="stage center-stage"><section class="frame-scan"><header><span>FIX h = {{name(selected())}}</span><strong>scan every frame k</strong></header>@for(k of elements();track k){<article [class.changed]="conj(k,selected())!==selected()"><span>k={{name(k)}}</span><b>{{name(selected())}} → {{name(conj(k,selected()))}}</b><small>{{conj(k,selected())===selected()?'FIXED':'CHANGED'}}</small></article>}</section><section class="center-console" aria-live="polite"><p class="kicker">GLOBAL FIXED-POINT DECK</p><div class="center-deck">@for(h of elements();track h){<article [class.central]="isCentral(h)"><strong>{{name(h)}}</strong><span>{{isCentral(h)?'FIXED IN ALL FRAMES':'CHANGES IN SOME FRAME'}}</span></article>}</div><div class="center-readout"><span>CENTER Z({{group()==='d3'?'D₃':'C₄'}})</span><b>{{centerLabel()}}</b><small>{{center().length}} / {{elements().length}} ELEMENTS GLOBAL-FIXED</small></div></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>all k: khk⁻¹=h</span><i>same as</i><span>all k: kh=hk</span></div><p><strong>Center 是對任何 coordinate change 都免疫的 core。</strong>在 abelian group 中所有 elements 都彼此 commute，所以整個群都是 center；nonabelian group 只留下真正 frame-independent 的部分。</p></aside>
<section class="transfer"><p class="kicker">遷移</p><h3>如果 Z(G)=G，可以推出 G 有什麼性質？</h3><div class="choice-row"><button type="button" (click)="transfer.set(true)">G abelian</button><button type="button" (click)="transfer.set(false)">G 一定 trivial</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="!transfer()">{{transfer()?'對。每個 h 都與每個 k commute，正是 abelian。':'C₄ 有四個 elements 並不 trivial，但 center 仍是整個 C₄。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>Center 的正式定義與 subgroup 性質</summary><div>Z(G) 由所有與 G 中每個 element commute 的 elements 組成；等價地，它是 conjugation action 的 global fixed-point set。identity 在其中，products 與 inverses 也保持「與所有 elements commute」，所以 Z(G) 是 normal subgroup。</div></details></section></article>`})
export class AlgebraV3GlobalFixedCoreComponent{readonly group=signal<GroupId>('d3');readonly selected=signal(1);readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly elements=computed(()=>this.group()==='d3'?[...D3_ELEMENTS]:[0,1,2,3]);readonly center=computed(()=>this.elements().filter(h=>this.isCentral(h)));setGroup(g:GroupId){this.group.set(g);this.selected.set(g==='d3'?1:0)}name(x:number){return this.group()==='d3'?label(x as D3Element):['0','a','a²','a³'][x]}conj(k:number,h:number){return this.group()==='d3'?conjugate(k as D3Element,h as D3Element):h}isCentral(h:number){return this.elements().every(k=>this.conj(k,h)===h)}centerLabel(){return `{${this.center().map(x=>this.name(x)).join(', ')}}`}}
