import{Component,computed,signal}from'@angular/core';import{D3_ELEMENTS,type D3Element,conjugate,label}from'../algebra-v3-ch16/d3-model';
@Component({selector:'app-algebra-v3-reframing-orbit',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch25-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 25.2</p><h2>Conjugacy class 收集同一個 action 在所有 group frames 下的名字</h2><p class="lede">固定 h，只讓 frame k 改變。每個 khk⁻¹ 都是同一 internal action type 的 re-description；重複 names 合併後，就是 h 在 conjugation action 下的 orbit。</p></header>
<section class="prediction"><p class="kicker">先預測</p><h3>s 與 rs 是兩條不同 reflection axes；它們可能在同一 conjugacy class 嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(true)">可能，旋轉 frame 會搬動 axis</button><button type="button" (click)="prediction.set(false)">不可能，名字不同就不同 class</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="!prediction()">{{prediction()?'對。re-framing 能把一條 reflection axis 轉成另外兩條，但不會把 reflection 變成 rotation。':'conjugacy 正是在忽略 frame-dependent names，同一 reflection type 會聚在一起。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Re-framing orbit collector</p><h3>固定 h，逐張套用六個 frame cards</h3></div><p>上列保留每次 experiment；下方只收集 distinct results，讓 duplicates 可見但不重算。</p></div><div class="object-picker">@for(x of elements;track x){<button type="button" [attr.aria-pressed]="h()===x" (click)="select(x)">h = {{name(x)}}</button>}</div><div class="stage class-stage"><section class="frame-experiments">@for(row of rows();track row.frame){<article [class.scanned]="row.scanned"><span>FRAME {{name(row.frame)}}</span><b>{{row.scanned?name(row.output):'?'}}</b><small>{{row.scanned?(firstIndex(row.output)===$index?'NEW NAME':'DUPLICATE'):'WAITING'}}</small></article>}</section><section class="class-collector" aria-live="polite"><p class="kicker">COLLECTED {{count()}} / 6 FRAMES</p><div class="class-bin">@for(x of collected();track x){<span>{{name(x)}}</span>}@if(collected().length===0){<i>NO RESULTS YET</i>}</div><div class="class-readout"><span>CONJUGACY CLASS OF {{name(h())}}</span><b>{{classLabel()}}</b><small>{{collected().length}} DISTINCT NAMES · SAME ACTION TYPE</small></div><button type="button" class="primary" [disabled]="count()>=6" (click)="advance()">套用下一個 frame</button><button type="button" (click)="count.set(6)">掃描全部</button><button type="button" (click)="count.set(0)">重設</button></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>fix h</span><i>vary all frames k</i><span>Cl(h) = reframing orbit</span></div><p><strong>Conjugacy class 是「忽略 observation frame 後」的 action type。</strong>D₃ 中 identity、nontrivial rotations、reflections 形成三種彼此不混合的 families。</p></aside>
<section class="transfer"><p class="kicker">遷移</p><h3>r 與 r² 為什麼能在同一 class，但 r 與 s 不行？</h3><div class="choice-row"><button type="button" (click)="transfer.set(true)">re-frame 可反轉 rotation 方向，但不改 action type</button><button type="button" (click)="transfer.set(false)">因為 class 只看符號長度</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="!transfer()">{{transfer()?'對。reflection frame 把 clockwise 與 counterclockwise 對換；order 與 rotation/reflection type 仍保持。':'符號是 description；真正被保留的是 conjugation 下的 structural behavior。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>Conjugacy class 的正式版本</summary><div>h 的 conjugacy class 是所有 khk⁻¹（k 跑遍 G）的集合，也就是 conjugation action 的 orbit。Conjugacy 是 equivalence relation，所以 classes partition G。</div></details></section></article>`})
export class AlgebraV3ReframingOrbitComponent{readonly elements=D3_ELEMENTS;readonly h=signal<D3Element>(3);readonly count=signal(0);readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly rows=computed(()=>this.elements.map((frame,index)=>({frame,output:conjugate(frame,this.h()),scanned:index<this.count()})));readonly collected=computed(()=>[...new Set(this.rows().filter(x=>x.scanned).map(x=>x.output))]);name=label;select(x:D3Element){this.h.set(x);this.count.set(0)}advance(){this.count.update(v=>Math.min(6,v+1))}firstIndex(output:D3Element){return this.rows().findIndex(x=>x.output===output)}classLabel(){return `{${this.collected().map(label).join(', ')}}`}}
