import{Component,computed,signal}from'@angular/core';import{D3_ELEMENTS,type D3Element,conjugate,inverse,label}from'../algebra-v3-ch16/d3-model';
@Component({selector:'app-algebra-v3-coordinate-sandwich',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch25-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 25.1</p><h2>Conjugation sandwich 是把同一個 action 搬進新的 observation frame</h2><p class="lede">外觀看起來是三個 factors，但因 action 從右往左執行，故事很具體：先用 k⁻¹ 回到舊 frame，做熟悉的 h，再用 k 搬回新 frame。</p></header>
<section class="prediction"><p class="kicker">先預測</p><h3>要執行 khk⁻¹，時間上第一個動作是哪一個？</h3><div class="choice-row"><button type="button" (click)="prediction.set('inverse')">k⁻¹，先搬回舊 frame</button><button type="button" (click)="prediction.set('k')">k，照式子從左讀</button></div>@if(prediction()){<p class="feedback" [class.warning]="prediction()==='k'">{{prediction()==='inverse'?'對。composition 的最右側先作用；sandwich 兩側負責來回換 frame。':'khk⁻¹ 作為 action 時從右側開始：k⁻¹ → h → k。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Coordinate sandwich</p><h3>選 k 與 h，再逐步穿過三道 frame gates</h3></div><p>每按一次只揭露一個因果步驟；完成後才把整條 pipeline 壓成單一卡。</p></div><div class="sandwich-controls"><fieldset><legend>FRAME MOVER k</legend>@for(x of elements;track x){<button type="button" [attr.aria-pressed]="k()===x" (click)="setK(x)">{{name(x)}}</button>}</fieldset><fieldset><legend>OLD-FRAME ACTION h</legend>@for(x of elements;track x){<button type="button" [attr.aria-pressed]="h()===x" (click)="setH(x)">{{name(x)}}</button>}</fieldset></div>
<div class="stage sandwich-stage"><section class="sandwich-pipeline"><div class="frame-card active"><span>NEW FRAME</span><strong>observe h through k</strong></div><i [class.active]="phase()>=1">k⁻¹</i><div class="frame-card" [class.active]="phase()>=1"><span>BACK TO OLD FRAME</span><strong>{{phase()>=1?name(inverseK()):'?'}}</strong></div><i [class.active]="phase()>=2">h</i><div class="frame-card" [class.active]="phase()>=2"><span>DO ORIGINAL ACTION</span><strong>{{phase()>=2?name(h()):'?'}}</strong></div><i [class.active]="phase()>=3">k</i><div class="frame-card" [class.active]="phase()>=3"><span>RETURN TO NEW FRAME</span><strong>{{phase()>=3?name(result()):'?'}}</strong></div><div class="compressed-card" [class.revealed]="phase()>=3"><span>ONE RE-FRAMED CARD</span><b>{{name(k())}} {{name(h())}} {{name(inverseK())}} = {{phase()>=3?name(result()):'?'}}</b><small>{{actionType(h())}} → {{phase()>=3?actionType(result()):'waiting'}}</small></div></section><section class="sandwich-console"><p class="kicker">FRAME CLOCK {{phase()}} / 3</p><strong>{{phaseLabel()}}</strong><button type="button" class="primary" [disabled]="phase()>=3" (click)="advance()">執行下一道 gate</button><button type="button" (click)="phase.set(0)">重設</button></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>old action h</span><i>change frame by k</i><span>new description khk⁻¹</span></div><p><strong>Conjugation 是 action 的 coordinate change。</strong>中間的 h 做事情；外側 k⁻¹、k 負責把 input 搬進 h 看得懂的 frame，再把 output 搬回來。</p></aside>
<section class="transfer"><p class="kicker">遷移</p><h3>若 k 與 h commute，換 frame 後 khk⁻¹ 會變成什麼？</h3><div class="choice-row"><button type="button" (click)="transfer.set(true)">仍是 h</button><button type="button" (click)="transfer.set(false)">一定變成另一個 element</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="!transfer()">{{transfer()?'對。khk⁻¹=hkk⁻¹=h；這個 frame 看見相同 description。':'commuting 讓 k 可以穿過 h，sandwich 會直接消掉。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>Conjugation 真的是 group action 嗎？</summary><div>令 k 作用在 h 上為 k·h=khk⁻¹。identity frame 不改 h；而 k₁·(k₂·h)=k₁k₂h(k₁k₂)⁻¹=(k₁k₂)·h，所以這是 G 在自身上的 action by conjugation。</div></details></section></article>`})
export class AlgebraV3CoordinateSandwichComponent{readonly elements=D3_ELEMENTS;readonly k=signal<D3Element>(1);readonly h=signal<D3Element>(3);readonly phase=signal(0);readonly prediction=signal<'inverse'|'k'|null>(null);readonly transfer=signal<boolean|null>(null);readonly inverseK=computed(()=>inverse(this.k()));readonly result=computed(()=>conjugate(this.k(),this.h()));name=label;setK(x:D3Element){this.k.set(x);this.phase.set(0)}setH(x:D3Element){this.h.set(x);this.phase.set(0)}advance(){this.phase.update(v=>Math.min(3,v+1))}phaseLabel(){return['READY · still in new frame','STEP 1 · returned to old frame','STEP 2 · original h executed','STEP 3 · description returned to new frame'][this.phase()]}actionType(x:D3Element){if(x===0)return'IDENTITY';return x<3?'ROTATION TYPE':'REFLECTION TYPE'}}
