import { Component, computed, signal } from '@angular/core';
import { D3_ELEMENTS, label } from '../algebra-v3-ch16/d3-model';
import { SCENE_POINTS, type ScenePoint, actOnScene, pointLabel, stabilizerOf } from './orbit-model';

@Component({selector:'app-algebra-v3-local-symmetry-filter',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch23-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 23.2</p><h2>Stabilizer 收集的是「保住這個 point」的 local symmetries</h2><p class="lede">這次不收集 destinations，而是把 output 和原 point 比較。actor 可以移動世界其他部分；只要它讓目前的 x 留在原位，就通過 local filter。</p></header>
<section class="prediction"><p class="kicker">先預測</p><h3>reflection s 固定 ▲，但交換另外兩個 vertices；它屬於 Stab(▲) 嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(true)">屬於，只需固定 ▲</button><button type="button" (click)="prediction.set(false)">不屬於，必須固定全部 points</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="!prediction()">{{prediction()?'對。固定所有 points 是 action kernel；stabilizer 只對目前 point 提問。':'那是 kernel 的 global 條件。Stab(▲) 允許其他 points 移動。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Local symmetry filter</p><h3>固定 observation point，逐一放入 actors</h3></div><p>✓ FIXES 與 → MOVES 連同形狀和文字呈現，結果不依賴顏色。</p></div><div class="point-picker">@for(candidate of points;track candidate){<button type="button" [attr.aria-pressed]="point()===candidate" (click)="selectPoint(candidate)">x = {{pointName(candidate)}}</button>}</div>
<div class="stage stabilizer-stage"><section class="local-scene"><div class="anchor-point"><span>OBSERVATION POINT</span><strong>{{pointName(point())}}</strong><small>must remain here</small></div><div class="actor-filter">@for(row of rows();track row.actor){<article [class.scanned]="row.scanned" [class.fixes]="row.scanned&&row.fixes"><strong>{{name(row.actor)}}</strong><span>{{row.scanned?(row.fixes?'✓ FIXES':'→ MOVES'):'WAITING'}}</span><small>{{row.scanned?pointName(point())+' → '+pointName(row.output):'not tested'}}</small></article>}</div></section><section class="stabilizer-console" aria-live="polite"><p class="kicker">LOCAL FILTER {{count()}} / 6</p><div class="stabilizer-readout"><span>STAB({{pointName(point())}})</span><b>{{stabilizerLabel()}}</b><small>ACTORS THAT FIX THIS POINT</small></div><button type="button" class="primary" [disabled]="count()>=6" (click)="scanNext()">測試下一個 actor</button><button type="button" (click)="count.set(6)">測試全部</button><button type="button" (click)="count.set(0)">重設</button></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>kernel fixes every x</span><i>vs</i><span>Stab(x) fixes this x</span></div><p><strong>Stabilizer 是 point-relative 的 local symmetry。</strong>同一個 actor 對一個 point 可能不可見，對另一個 point 卻造成明顯移動。</p></aside>
<section class="transfer"><p class="kicker">遷移</p><h3>center ● 的 stabilizer 會包含哪些 D₃ actors？</h3><div class="choice-row"><button type="button" (click)="transfer.set(6)">全部 6 個</button><button type="button" (click)="transfer.set(1)">只有 identity</button></div>@if(transfer()){<p class="feedback" [class.warning]="transfer()!==6">{{transfer()===6?'對。每個 triangle symmetry 都固定 center。':'center 對所有 rotations 與 reflections 都留在原位，所以 stabilizer 是整個 D₃。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>Stabilizer 為什麼是 subgroup？</summary><div>Gₓ 由所有滿足 g·x=x 的 g∈G 組成。identity 固定 x；若 g、h 固定 x，則 gh 也固定 x；若 g 固定 x，對等式 g·x=x 作用 g⁻¹ 可見 g⁻¹ 也固定 x。因此 Gₓ≤G。</div></details></section></article>`})
export class AlgebraV3LocalSymmetryFilterComponent{readonly points=SCENE_POINTS;readonly elements=D3_ELEMENTS;readonly point=signal<ScenePoint>(0);readonly count=signal(0);readonly prediction=signal<boolean|null>(null);readonly transfer=signal<number|null>(null);readonly rows=computed(()=>this.elements.map((actor,index)=>{const output=actOnScene(actor,this.point());return{actor,output,fixes:output===this.point(),scanned:index<this.count()};}));name=label;pointName=pointLabel;selectPoint(point:ScenePoint):void{this.point.set(point);this.count.set(0);}scanNext():void{this.count.update(value=>Math.min(6,value+1));}stabilizerLabel():string{const actors=this.rows().filter(row=>row.scanned&&row.fixes).map(row=>label(row.actor));return `{${actors.join(', ')}}`;}fullStabilizerSize():number{return stabilizerOf(this.point()).length;}}
