import { Component, computed, signal } from '@angular/core';
import { D3_ELEMENTS, type D3Element, conjugate, label } from '../algebra-v3-ch16/d3-model';
import { type ScenePoint, actOnScene, pointLabel, stabilizerOf } from './orbit-model';

@Component({selector:'app-algebra-v3-moving-local-frame',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch23-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 23.4</p><h2>搬動 observation point 時，local symmetry 會一起做 conjugation transport</h2><p class="lede">先用 k 把 ▲ 搬到 k·▲。原本固定 ▲ 的 h 不能原封不動留下；正確的新 actor 是先搬回來、做 h、再搬過去的 khk⁻¹。</p></header>
<section class="prediction"><p class="kicker">先預測</p><h3>用 r 把 ▲ 搬到 ▶ 後，原本穿過 ▲ 的 reflection axis 應該怎麼辦？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">跟著 point 一起旋轉</button><button type="button" (click)="prediction.set(true)">留在原 axis，不必改 actor</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'原 reflection 固定的是舊 point；搬到新 point 後，需要把整個 local frame 一起 transport。':'對。conjugation 就是在新的 observation frame 重寫同一個 local symmetry。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Moving local frame</p><h3>選 mover k，同步搬 point 與 fixing actors</h3></div><p>左、右使用相同三角形座標；實線／虛線 axes 表示 transport 前後，不只靠顏色。</p></div><div class="mover-picker">@for(actor of elements;track actor){<button type="button" [attr.aria-pressed]="mover()===actor" (click)="mover.set(actor)">k = {{name(actor)}}</button>}</div>
<div class="stage transport-stage"><section class="frame before-frame"><p>OLD FRAME</p><div class="mini-triangle"><i class="axis old-axis"></i><span data-point="0" class="active">▲</span><span data-point="1">▶</span><span data-point="2">◀</span></div><div><span>basepoint x</span><b>▲</b><span>Stab(x)</span><b>{{oldLabel()}}</b></div></section><div class="transport-arrow"><strong>{{name(mover())}}</strong><span>move point</span><i>→</i><small>h ↦ khk⁻¹</small></div><section class="frame after-frame"><p>NEW FRAME</p><div class="mini-triangle" [attr.data-target]="target()"><i class="axis new-axis" [style.transform]="axisRotation()"></i><span data-point="0" [class.active]="target()===0">▲</span><span data-point="1" [class.active]="target()===1">▶</span><span data-point="2" [class.active]="target()===2">◀</span></div><div><span>new point kx</span><b>{{pointName(target())}}</b><span>Stab(kx)</span><b>{{newLabel()}}</b></div></section><section class="transport-console" aria-live="polite"><p class="kicker">CONJUGATION TRANSPORT</p>@for(row of transported();track row.old){<article><span>{{name(row.old)}}</span><i>k ( · ) k⁻¹</i><strong>{{name(row.next)}}</strong><small>{{row.fixesTarget?'✓ FIXES NEW POINT':'✗ DOES NOT FIX'}}</small></article>}<div class="transport-verdict">{{allFix()?'ALL TRANSPORTED ACTORS FIX kx':'TRANSPORT BROKEN'}}</div></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>Stab(x)</span><i>move by k</i><span>k Stab(x) k⁻¹ = Stab(kx)</span></div><p><strong>Conjugation 是 local symmetry 的換觀察座標。</strong>同一 orbit 上的 points 擁有同型的 stabilizers；差別只是它們在群裡被哪個 frame 描述。</p></aside>
<section class="transfer"><p class="kicker">遷移</p><h3>若 k 本來就固定 ▲，搬運後的 basepoint 會去哪裡？</h3><div class="choice-row"><button type="button" (click)="transfer.set('same')">仍是 ▲</button><button type="button" (click)="transfer.set('other')">一定換到另一個 vertex</button></div>@if(transfer()){<p class="feedback" [class.warning]="transfer()!=='same'">{{transfer()==='same'?'對。k∈Stab(▲) 正是 k·▲=▲ 的意思。':'stabilizer 裡的 mover 定義上就不移動 basepoint。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>為什麼 Gₖₓ = kGₓk⁻¹？</summary><div>若 h·x=x，則 (khk⁻¹)·(kx)=k·(h·x)=kx，所以 kGₓk⁻¹⊆Gₖₓ。反向用 k⁻¹ 做同樣論證，得到 equality。這裡只比較 subgroups 的 transport；size counting 留到下一章。</div></details></section></article>`})
export class AlgebraV3MovingLocalFrameComponent{readonly elements=D3_ELEMENTS;readonly mover=signal<D3Element>(1);readonly prediction=signal<boolean|null>(null);readonly transfer=signal<'same'|'other'|null>(null);readonly base=0 as ScenePoint;readonly target=computed(()=>actOnScene(this.mover(),this.base));readonly oldStabilizer=stabilizerOf(this.base);readonly newStabilizer=computed(()=>stabilizerOf(this.target()));readonly transported=computed(()=>this.oldStabilizer.map(old=>{const next=conjugate(this.mover(),old);return{old,next,fixesTarget:actOnScene(next,this.target())===this.target()};}));readonly allFix=computed(()=>this.transported().every(row=>row.fixesTarget));name=label;pointName=pointLabel;oldLabel():string{return `{${this.oldStabilizer.map(label).join(', ')}}`;}newLabel():string{return `{${this.newStabilizer().map(label).join(', ')}}`;}axisRotation():string{return `rotate(${this.target()*120}deg)`;}}
