import { Component, computed, signal } from '@angular/core';
import { D3_ELEMENTS, label } from '../algebra-v3-ch16/d3-model';
import { SCENE_POINTS, type ScenePoint, actOnScene, orbitOf, pointLabel, pointSetLabel } from './orbit-model';

@Component({selector:'app-algebra-v3-reachability-sweep',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch23-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 23.1</p><h2>Orbit 是從一個 seed 出發，所有 group moves 能抵達的完整世界</h2><p class="lede">把 seed 固定，依序試完 D₃ 的六個 actors。重複抵達同一點不另算；從未被任何 actor 點亮的位置，就不在這個 seed 的 orbit。</p></header>
<section class="prediction"><p class="kicker">先預測</p><h3>三角形 center ● 能被某個 symmetry 搬到 vertex ▲ 嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不能，它們在不同 reachable components</button><button type="button" (click)="prediction.set(true)">能，試完全部 actors 應該能到</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'symmetry 可旋轉或翻面，但中心仍是中心；可達性不保證整個 X 都連在一起。':'對。center orbit 只有 center；vertices 形成另一個 orbit。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Reachability sweep</p><h3>選 seed，逐張掃過 action cards</h3></div><p>實線圈是已抵達；虛線圈尚未被 sweep 找到。標籤同時保留，不只靠顏色。</p></div><div class="seed-picker" aria-label="選擇 orbit seed">@for(point of points;track point){<button type="button" [attr.aria-pressed]="seed()===point" (click)="selectSeed(point)">seed {{pointName(point)}}</button>}</div>
<div class="stage reach-stage"><section class="scene-map" [attr.aria-label]="sceneLabel()"><div class="scene-triangle"></div>@for(point of points;track point){<article class="scene-point" [attr.data-point]="point" [class.seed]="seed()===point" [class.reached]="reached().includes(point)"><strong>{{pointName(point)}}</strong><small>{{seed()===point?'SEED':reached().includes(point)?'REACHED':'NOT REACHED'}}</small></article>}</section><section class="sweep-console" aria-live="polite"><p class="kicker">ACTOR SWEEP {{count()}} / 6</p><div class="actor-tape">@for(row of rows();track row.actor){<article [class.scanned]="row.scanned"><span>{{name(row.actor)}}</span><b>{{row.scanned?pointName(row.output):'?'}}</b><small>{{row.scanned?'OUTPUT':'WAITING'}}</small></article>}</div><div class="orbit-readout"><span>DISCOVERED OUTPUTS</span><b>{{reachedLabel()}}</b><small>{{reached().length}} DISTINCT POINTS</small></div><button type="button" class="primary" [disabled]="count()>=6" (click)="scanNext()">掃描下一個 actor</button><button type="button" (click)="count.set(6)">掃描全部</button><button type="button" (click)="count.set(0)">重設</button></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>fix seed x</span><i>vary every g</i><span>Orb(x) = reachable points</span></div><p><strong>Orbit 不是一條特定路徑，而是所有可能 group moves 的可達範圍。</strong>一旦進入某個 orbit，group action 不會把你送到另一個 orbit。</p></aside>
<section class="transfer"><p class="kicker">遷移</p><h3>從 ▶ 出發的 orbit，會和從 ▲ 出發的 orbit 相同嗎？</h3><div class="choice-row"><button type="button" (click)="transfer.set(true)">相同，兩者彼此可達</button><button type="button" (click)="transfer.set(false)">不同，每個 seed 都有獨立 orbit</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="!transfer()">{{transfer()?'對。只要兩點彼此可達，它們產生同一個完整 orbit。':'▲ 能被 rotation 送到 ▶，所以兩個 seeds 落在同一 orbit。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>Orbit 的正式定義與 partition</summary><div>Orb(x) 是所有 g·x（其中 g 跑遍 G）組成的 set。關係 y∼x 當且僅當存在 g 使 y=g·x，是 equivalence relation，因此不同 orbits 要麼相同、要麼 disjoint，並 partition X。</div></details></section></article>`})
export class AlgebraV3ReachabilitySweepComponent{readonly points=SCENE_POINTS;readonly elements=D3_ELEMENTS;readonly seed=signal<ScenePoint>(0);readonly count=signal(0);readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly rows=computed(()=>this.elements.map((actor,index)=>({actor,output:actOnScene(actor,this.seed()),scanned:index<this.count()})));readonly reached=computed(()=>[...new Set(this.rows().filter(row=>row.scanned).map(row=>row.output))]);name=label;pointName=pointLabel;selectSeed(point:ScenePoint):void{this.seed.set(point);this.count.set(0);}scanNext():void{this.count.update(value=>Math.min(6,value+1));}reachedLabel():string{return pointSetLabel(this.reached());}sceneLabel():string{return `Seed ${pointLabel(this.seed())}; discovered ${this.reachedLabel()}; full orbit ${pointSetLabel(orbitOf(this.seed()))}`;}}
