import { Component, computed, signal } from '@angular/core';
import { D3_ELEMENTS, label } from '../algebra-v3-ch16/d3-model';
import { SCENE_POINTS, type ScenePoint, actOnScene, pointLabel, pointSetLabel } from './orbit-model';
type ReadingMode='orbit'|'stabilizer';

@Component({selector:'app-algebra-v3-two-readings-table',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch23-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 23.3</p><h2>同一欄 action experiments，可以讀出「去哪裡」或「誰留下來」</h2><p class="lede">固定 x、讓 g 往下掃。Orbit reading 收集右側 output points；stabilizer reading 則回頭收集那些 output=x 的左側 actor labels。</p></header>
<section class="prediction"><p class="kicker">先預測</p><h3>Orb(▲) 與 Stab(▲) 都從同一欄讀出，它們會是同一種物件嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不會，一個裝 points、一個裝 actors</button><button type="button" (click)="prediction.set(true)">會，只是兩個名字</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'看表的兩端：orbit 收集 X 裡的 destinations；stabilizer 收集 G 裡的 row labels。':'對。共同的是 experiments，不是結果所屬的 set。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">One table, two readings</p><h3>切換 reading mode，看 highlight 改收集哪一端</h3></div><p>橫列是 actors、直欄是 input points；選定的 x 欄會保持高亮。</p></div><div class="table-controls"><div>@for(candidate of points;track candidate){<button type="button" [attr.aria-pressed]="point()===candidate" (click)="point.set(candidate)">x={{pointName(candidate)}}</button>}</div><div><button type="button" [attr.aria-pressed]="mode()==='orbit'" (click)="mode.set('orbit')">Collect outputs → orbit</button><button type="button" [attr.aria-pressed]="mode()==='stabilizer'" (click)="mode.set('stabilizer')">Collect actors → stabilizer</button></div></div>
<div class="stage table-stage"><section class="action-table" role="table" aria-label="D3 action table"><header role="row"><span>g \ x</span>@for(column of points;track column){<b [class.focus-column]="column===point()">{{pointName(column)}}</b>}</header>@for(actor of elements;track actor){<article role="row" [class.collected-actor]="mode()==='stabilizer'&&fixes(actor)"><strong>{{name(actor)}}</strong>@for(column of points;track column){<span [class.focus-column]="column===point()" [class.return-cell]="column===point()&&fixes(actor)">{{pointName(output(actor,column))}}</span>}</article>}</section><section class="reading-console" aria-live="polite"><p class="kicker">{{mode()==='orbit'?'DESTINATION READING':'ACTOR READING'}}</p><div class="reading-flow"><span>FIX x = {{pointName(point())}}</span><i>scan all six rows</i><b>{{mode()==='orbit'?'collect right-side outputs':'collect left-side g when output=x'}}</b></div><div class="reading-result"><span>{{mode()==='orbit'?'ORBIT ⊂ X':'STABILIZER ⊂ G'}}</span><strong>{{resultLabel()}}</strong><small>{{mode()==='orbit'?'RESULTS ARE POINTS':'RESULTS ARE GROUP ELEMENTS'}}</small></div></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>same action column</span><i>two questions</i><span>outputs vs actors</span></div><p><strong>Orbit 與 stabilizer 不是競爭的答案。</strong>一個描述 point 的可達範圍；另一個描述這個 point 周圍仍然存在的 local symmetry。</p></aside>
<section class="transfer"><p class="kicker">遷移</p><h3>如果 x=●，table 右欄六次都輸出 ●；stabilizer reading 收集什麼？</h3><div class="choice-row"><button type="button" (click)="transfer.set('all')">全部六個 row actors</button><button type="button" (click)="transfer.set('point')">只收集 ●</button></div>@if(transfer()){<p class="feedback" [class.warning]="transfer()!=='all'">{{transfer()==='all'?'對。● 是 output point；stabilizer 收集的是造成 return 的六個 actor labels。':'● 屬於 orbit result；stabilizer result 必須是 G 裡的 actors。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>符號的 type check</summary><div>Orb(x) 收集所有 g·x，所以是 X 的 subset；Gₓ 收集所有滿足 g·x=x 的 g，所以是 G 的 subgroup。把「結果屬於哪個 ambient set」寫清楚，能避免把 orbit points 與 stabilizer elements 混成一件事。</div></details></section></article>`})
export class AlgebraV3TwoReadingsTableComponent{readonly points=SCENE_POINTS;readonly elements=D3_ELEMENTS;readonly point=signal<ScenePoint>(0);readonly mode=signal<ReadingMode>('orbit');readonly prediction=signal<boolean|null>(null);readonly transfer=signal<'all'|'point'|null>(null);name=label;pointName=pointLabel;output(actor:(typeof D3_ELEMENTS)[number],point:ScenePoint):ScenePoint{return actOnScene(actor,point);}fixes(actor:(typeof D3_ELEMENTS)[number]):boolean{return this.output(actor,this.point())===this.point();}readonly orbitResult=computed(()=>[...new Set(this.elements.map(actor=>this.output(actor,this.point())))]);readonly stabilizerResult=computed(()=>this.elements.filter(actor=>this.fixes(actor)));resultLabel():string{return this.mode()==='orbit'?pointSetLabel(this.orbitResult()):`{${this.stabilizerResult().map(label).join(', ')}}`;}}
