import{Component,computed,signal}from'@angular/core';import{compose,key,S3}from'../algebra-v3-ch19/permutation-model';
interface WordSample{count:number;word:string;total:number;}
@Component({selector:'app-algebra-v3-parity-scanner',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch20-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 20.4</p><h2>Swap decomposition 可以不同，但 count 永遠跨不過 even／odd 這條軌道</h2><p class="lede">對 S₃ 完整枚舉長度 0–5 的 transposition words，按 result permutation 分組。Recipe 數量會暴增，但同一 result 只佔 even columns 或只佔 odd columns。</p></header>
<section class="prediction"><p class="kicker">先預測</p><h3>同一 permutation 若有 2-swap decomposition，還可能有 3-swap decomposition 嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不可能</button><button type="button" (click)="prediction.set(true)">可能</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'Decompositions 可差 2、4… 個 swaps，但不會差奇數個。':'對。Even／odd parity 是 permutation 本身的 invariant。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Bounded parity scanner</p><h3>選 S₃ result，查看所有 length≤5 recipes 落在哪些 columns</h3></div><p>EMPTY／FOUND 與 recipe count 明示，顏色不是唯一線索。</p></div><div class="target-picker" role="group" aria-label="選擇 S3 permutation result">@for(permutation of deck;track key(permutation);let i=$index){<button type="button" [attr.aria-pressed]="target()===i" (click)="target.set(i)">P{{i+1}} · {{mapping(permutation)}}</button>}</div><div class="stage parity-stage"><section class="length-columns" aria-label="不同 transposition word length 的搜尋結果">@for(sample of samples();track sample.count){<article [class.found]="sample.total>0"><span>{{sample.count}} SWAPS</span><strong>{{sample.total>0?sample.total+' RECIPES':'EMPTY'}}</strong><small>{{sample.word||'—'}}</small><b>{{sample.count%2===0?'EVEN':'ODD'}}</b></article>}</section><section class="parity-console" aria-live="polite"><p class="kicker">TARGET P{{target()+1}}</p><div class="parity-rail"><span>EVEN COLUMNS</span><i [class.active]="parity()==='EVEN'">{{evenTotal()}} found</i><span>ODD COLUMNS</span><i [class.active]="parity()==='ODD'">{{oddTotal()}} found</i></div><div class="map-verdict">✓ ALL FOUND RECIPES ARE {{parity()}}</div><p>Scanner 覆蓋 1+3+9+27+81+243=364 個 words；general theorem 在下方證明任意長度也不會跨 parity。</p></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>many swap recipes</span><i>same result forces</i><span>one parity</span></div><p><strong>Permutation 的 parity（奇偶性）屬於 transformation，不屬於某一份 decomposition。</strong>Even recipes 只會重寫成 even；odd 只會重寫成 odd。</p></aside>
<section class="transfer"><p class="kicker">遷移</p><h3>Even permutation 與 odd permutation composition 後是什麼 parity？</h3><div class="choice-row"><button type="button" (click)="transfer.set(true)">odd</button><button type="button" (click)="transfer.set(false)">even</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="!transfer()">{{transfer()?'對。Swap counts 相加：even+odd=odd。':'Parity 在 composition 下像 mod 2 addition。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>Parity invariant 的 general proof idea</summary><div>可用 inversion count：每個 transposition 改變 inversion parity。Identity inversion count 為 even，因此任何表示同一 σ 的 transposition word，其 length parity 都等於 σ 的 inversion parity。</div></details><details><summary>Sign homomorphism</summary><div>sgn:Sₙ→{{'{+1,−1}'}}，even 映到 +1、odd 映到 −1，且 sgn(στ)=sgn(σ)sgn(τ)。Kernel 是 alternating group Aₙ。</div></details></section></article>`})
export class AlgebraV3ParityScannerComponent{readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly target=signal(1);readonly deck=S3;readonly transpositions=[[1,0,2],[2,1,0],[0,2,1]];readonly names=['(A B)','(A C)','(B C)'];readonly samples=computed(()=>Array.from({length:6},(_,count)=>this.sampleAt(count)));key=key;mapping(p:number[]):string{return p.map((v,i)=>`${'ABC'[i]}→${'ABC'[v]}`).join(' ');}sampleAt(length:number):WordSample{let matches:string[]=[];const walk=(depth:number,current:number[],word:string[])=>{if(depth===length){if(key(current)===key(this.deck[this.target()]))matches.push(word.join(' '));return;}this.transpositions.forEach((t,i)=>walk(depth+1,compose(t,current),[...word,this.names[i]]));};walk(0,[0,1,2],[]);return{count:length,word:matches[0]||'',total:matches.length};}evenTotal():number{return this.samples().filter(s=>s.count%2===0).reduce((n,s)=>n+s.total,0);}oddTotal():number{return this.samples().filter(s=>s.count%2===1).reduce((n,s)=>n+s.total,0);}parity():string{return this.evenTotal()>0?'EVEN':'ODD';}}
