import{Component,computed,signal}from'@angular/core';import{cycleLabel,DEMO_PERMUTATION,LABELS6,orbit}from'./cycle-model';
@Component({selector:'app-algebra-v3-disjoint-extractor',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch20-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 20.2</p><h2>整張 permutation wiring 會唯一裂成互不搶 state 的 disjoint cycles</h2><p class="lede">完成一條 orbit 後，從尚未造訪的 state 再出發。因 permutation 一進一出，兩條 orbits 不可能中途合流；最後每個 state 恰落在一條 lane。</p></header>
<section class="prediction"><p class="kicker">先預測</p><h3>兩個不同 cycles 若共享一個 state，還能代表同一張 permutation 嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不能</button><button type="button" (click)="prediction.set(true)">能</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'共享 state 會要求它同時有兩個 next destinations，違反 function。':'對。不同 orbit lanes 必須 disjoint。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Disjoint-orbit extractor</p><h3>每次從第一個 UNASSIGNED state 抽出完整 orbit</h3></div><p>抽出的 lane 立即鎖定；剩餘 states 不會被既有 lane 再碰到。</p></div><div class="stage extractor-stage"><section class="state-pool" aria-label="六個 states 的 cycle assignment">@for(label of labels;track $index){<article [class.assigned]="cycleIndex($index)>=0"><strong>{{label}}</strong><small>{{cycleIndex($index)>=0?'LANE '+(cycleIndex($index)+1):'UNASSIGNED'}}</small></article>}</section><section class="cycle-lanes" aria-live="polite">@for(items of extracted();track items[0];let i=$index){<article><span>LANE {{i+1}}</span><strong>{{cycleLabel(items)}}</strong><small>{{items.length===1?'FIXED POINT':items.length+'-CYCLE'}}</small></article>}@if(!complete()){<article class="pending"><span>NEXT SEED</span><strong>{{labels[nextSeed()]}}</strong><small>READY TO TRACE</small></article>}</section><section class="extractor-console"><p class="kicker">ASSIGNED {{assignedCount()}} / 6</p><div class="map-verdict" [class.fail]="!complete()">{{complete()?'✓ ALL STATES PARTITIONED · DISJOINT DECOMPOSITION':'… DECOMPOSITION NOT COMPLETE'}}</div><button type="button" class="primary" [disabled]="complete()" (click)="extractNext()">Extract next orbit</button><button type="button" (click)="extractAll()">Extract all</button><button type="button" (click)="count.set(0)">重設</button><p>{{decomposition()}}</p></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>one permutation</span><i>partitions into</i><span>disjoint closed lanes</span></div><p><strong>Disjoint cycles 是 permutation 的 orbit partition。</strong>不同 lanes 不共享 states，因此 actions 互不干擾，書寫順序可交換。</p></aside>
<section class="transfer"><p class="kicker">遷移</p><h3>(A B C) 與 (D E) 的執行順序會改變結果嗎？</h3><div class="choice-row"><button type="button" (click)="transfer.set(false)">不會，supports disjoint</button><button type="button" (click)="transfer.set(true)">會</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="transfer()">{{transfer()?'兩張 action 操作不同 states，所以 commute。':'對。每張 cycle 對另一張的 states 都是 identity。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>唯一性說明</summary><div>每個 state 的 orbit 由 repeated σ 唯一決定；orbits 要麼相同、要麼 disjoint，因此 decomposition 除了 cycle 起點 rotation 與 lane 排序外唯一。</div></details></section></article>`})
export class AlgebraV3DisjointExtractorComponent{readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly count=signal(0);readonly labels=LABELS6;readonly allCycles=[[0,1,2],[3,4],[5]];readonly extracted=computed(()=>this.allCycles.slice(0,this.count()));readonly assignedCount=computed(()=>this.extracted().flat().length);cycleLabel=cycleLabel;complete():boolean{return this.count()===this.allCycles.length;}nextSeed():number{return this.allCycles[this.count()]?.[0]??0;}cycleIndex(state:number):number{return this.extracted().findIndex(items=>items.includes(state));}extractNext():void{this.count.update(v=>Math.min(this.allCycles.length,v+1));}extractAll():void{this.count.set(this.allCycles.length);}decomposition():string{return this.extracted().map(items=>cycleLabel(items)).join(' ')||'尚未抽出任何 cycle';}}
