import{Component,computed,signal}from'@angular/core';import{cycleLabel,DEMO_PERMUTATION,LABELS6,orbit}from'./cycle-model';
@Component({selector:'app-algebra-v3-orbit-tracer',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch20-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 20.1</p><h2>Cycle 不是括號語法；它是一個 state 重複走同一 action 後形成的 closed orbit</h2><p class="lede">固定 permutation σ：A→B→C→A、D↔E、F→F。先選 seed，再一步一步套用 σ；第一次回到 seed 時，這條閉路才完整。</p></header>
<section class="prediction"><p class="kicker">先預測</p><h3>F 沒有移動，所以它不屬於任何 cycle 嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">它是 length-1 cycle</button><button type="button" (click)="prediction.set(true)">不算 cycle</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'F→F 立即回到 seed，closed orbit 長度是 1。':'對。Fixed point 可寫作 (F)，只是 cycle notation 常省略。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Single-orbit tracer</p><h3>選 seed、逐步前進，直到 path 閉合</h3></div><p>未走過的 nodes 保持 MUTED；RETURN 標籤不只靠顏色。</p></div><div class="seed-picker" role="group" aria-label="選擇 orbit seed">@for(label of labels;track $index){<button type="button" [attr.aria-pressed]="seed()===$index" (click)="selectSeed($index)">{{label}}</button>}</div><div class="stage orbit-stage"><section class="orbit-ring" aria-label="permutation orbit nodes">@for(label of labels;track $index){<article [class.visited]="visited($index)" [class.current]="current()===$index"><strong>{{label}}</strong><small>{{nodeStatus($index)}}</small></article>}<div class="orbit-path"><span>{{pathReading()}}</span><strong>{{closed()?cycleLabel(fullOrbit()):'… OPEN PATH'}}</strong></div></section><section class="orbit-console" aria-live="polite"><p class="kicker">STEP {{steps()}} / {{fullOrbit().length}}</p><div class="current-move"><span>CURRENT</span><strong>{{labels[current()]}}</strong><i>σ → {{labels[permutation[current()]]}}</i></div><div class="map-verdict" [class.fail]="!closed()">{{closed()?'✓ RETURNED TO SEED · CYCLE CLOSED':'… NOT BACK YET · KEEP TRACING'}}</div><div class="control-row"><button type="button" class="primary" [disabled]="closed()" (click)="step()">Apply σ once</button><button type="button" (click)="finish()">Trace full orbit</button><button type="button" (click)="reset()">重設</button></div></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>choose seed</span><i>repeat σ</i><span>first return</span><i>records</i><span>one cycle</span></div><p><strong>Cycle notation 壓縮的是一條 closed action path。</strong><code>(A B C)</code> 的意思是 A→B、B→C、C→A，不是一組 unordered labels。</p></aside>
<section class="transfer"><p class="kicker">遷移</p><h3>若 orbit 是 A→D→B→A，cycle 應寫成什麼？</h3><div class="choice-row"><button type="button" (click)="transfer.set(true)">(A D B)</button><button type="button" (click)="transfer.set(false)">(A B D)</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="!transfer()">{{transfer()?'對。括號內順序就是 action path。':'Cycle 順序不能重新排序；它記錄下一站。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>Cycle notation 的 rotation ambiguity</summary><div>(A B C)=(B C A)=(C A B)，因為三者記錄同一組 directed edges；但 (A C B) 是 inverse cycle。</div></details></section></article>`})
export class AlgebraV3OrbitTracerComponent{readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly seed=signal(0);readonly steps=signal(0);readonly labels=LABELS6;readonly permutation=DEMO_PERMUTATION;readonly fullOrbit=computed(()=>orbit(this.permutation,this.seed()));readonly closed=computed(()=>this.steps()>=this.fullOrbit().length);readonly current=computed(()=>this.closed()?this.seed():this.fullOrbit()[this.steps()]);cycleLabel=cycleLabel;selectSeed(i:number):void{this.seed.set(i);this.steps.set(0);}step():void{this.steps.update(v=>Math.min(this.fullOrbit().length,v+1));}finish():void{this.steps.set(this.fullOrbit().length);}reset():void{this.steps.set(0);}visited(i:number):boolean{return this.fullOrbit().slice(0,Math.min(this.steps()+1,this.fullOrbit().length)).includes(i);}nodeStatus(i:number):string{return this.current()===i?(this.closed()?'RETURNED':'CURRENT'):this.visited(i)?'VISITED':'MUTED';}pathReading():string{return this.fullOrbit().slice(0,Math.min(this.steps()+1,this.fullOrbit().length)).map(i=>this.labels[i]).join(' → ')+(this.closed()?` → ${this.labels[this.seed()]}`:'');}}
