import{Component,computed,signal}from'@angular/core';import{compose,Permutation}from'../algebra-v3-ch19/permutation-model';
@Component({selector:'app-algebra-v3-cycle-swap-machine',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch20-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 20.3</p><h2>一個 k-cycle 可以拆成 k−1 次 swaps；每次只接上一個新位置</h2><p class="lede">以 A 為 anchor，依序做 (A B)、(A C)、…；chronological tape 從左到右執行，正式 composition 則把最後執行的 swap 寫在最左邊。</p></header>
<section class="prediction"><p class="kicker">先預測</p><h3>要做出 (A B C D)，最少需要幾個 transpositions？</h3><div class="choice-row"><button type="button" (click)="prediction.set(true)">3</button><button type="button" (click)="prediction.set(false)">4</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="!prediction()">{{prediction()?'對。每個 swap 把一個新 state 接進 anchor chain。':'四個 states 的 cycle 只需要 k−1=3 swaps。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Cycle-to-swap machine</p><h3>改變 cycle length，再逐個套用 anchored swaps</h3></div><p>Mapping cards 顯示目前 composite，不只展示符號 expansion。</p></div><div class="length-picker" role="group" aria-label="選擇 cycle length">@for(k of [2,3,4,5,6];track k){<button type="button" [attr.aria-pressed]="length()===k" (click)="selectLength(k)">{{k}}-cycle</button>}</div><div class="stage swap-stage"><section class="swap-tape"><span>CHRONOLOGICAL ACTIONS</span><div>@for(swap of swaps();track $index;let i=$index){<article [class.applied]="isApplied(i)"><strong>({{labels[swap[0]]}} {{labels[swap[1]]}})</strong><small>{{swapStatus(i)}}</small></article>}</div><p>Formal product: <strong>{{formalProduct()}}</strong></p></section><section class="mapping-result" aria-live="polite">@for(i of activeStates();track i){<article><strong>{{labels[i]}}</strong><i>→</i><strong>{{labels[currentMap()[i]]}}</strong><small>{{connectionStatus(i)}}</small></article>}</section><section class="swap-console"><p class="kicker">{{progress()}} / {{length()-1}} SWAPS</p><div class="count-equation"><span>CYCLE LENGTH</span><strong>{{length()}}</strong><i>− 1 =</i><span>TRANSPOSITIONS</span><strong>{{length()-1}}</strong></div><div class="map-verdict" [class.fail]="!complete()">{{complete()?'✓ TARGET CYCLE BUILT '+targetCycle():'… PARTIAL COMPOSITE'}}</div><div class="control-row"><button type="button" class="primary" [disabled]="complete()" (click)="step()">Apply next swap</button><button type="button" (click)="progress.set(length()-1)">Build all</button><button type="button" (click)="progress.set(0)">重設</button></div></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>k-cycle</span><i>anchored expansion</i><span>k−1 transpositions</span></div><p><strong>Transposition 是 permutation 的 swap building block。</strong>Decomposition 不唯一，但 cycle length 立刻給出一個具體的 k−1 construction。</p></aside>
<section class="transfer"><p class="kicker">遷移</p><h3>(A B C)(D E) 用這種分解共需要幾個 swaps？</h3><div class="choice-row"><button type="button" (click)="transfer.set(true)">3</button><button type="button" (click)="transfer.set(false)">5</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="!transfer()">{{transfer()?'對。(3−1)+(2−1)=3。':'每條 disjoint cycle 各自貢獻 length−1。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>Expansion formula</summary><div>(a₁ a₂ … aₖ)=(a₁ aₖ)…(a₁ a₃)(a₁ a₂)。依 composition convention，右端 (a₁ a₂) 最先執行。</div></details></section></article>`})
export class AlgebraV3CycleSwapMachineComponent{readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly length=signal(4);readonly progress=signal(0);readonly labels=['A','B','C','D','E','F'];readonly activeStates=computed(()=>Array.from({length:this.length()},(_,i)=>i));readonly swaps=computed(()=>Array.from({length:this.length()-1},(_,i)=>[0,i+1] as [number,number]));readonly currentMap=computed(()=>{let current:Array<number>=Array.from({length:this.length()},(_,i)=>i);for(const [a,b] of this.swaps().slice(0,this.progress())){const trans=Array.from({length:this.length()},(_,i)=>i);trans[a]=b;trans[b]=a;current=compose(trans,current);}return current;});selectLength(k:number):void{this.length.set(k);this.progress.set(0);}step():void{this.progress.update(v=>Math.min(this.length()-1,v+1));}complete():boolean{return this.progress()===this.length()-1;}isApplied(i:number):boolean{return i<this.progress();}swapStatus(i:number):string{return this.isApplied(i)?'APPLIED':'WAITING';}connectionStatus(i:number):string{return i<this.progress()+1?'CONNECTED':'NOT YET';}formalProduct():string{return[...this.swaps()].reverse().map(([a,b])=>`(${this.labels[a]} ${this.labels[b]})`).join(' ')||'identity';}targetCycle():string{return`(${this.activeStates().map(i=>this.labels[i]).join(' ')})`;}}
