import{Component,computed,signal}from'@angular/core';import{compose,Permutation}from'./permutation-model';type Order='p-after-q'|'q-after-p';
@Component({selector:'app-algebra-v3-composition-order',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch19-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 19.2</p><h2>Composition notation 要從 input 讀：p∘q 是先走 q，再走 p</h2><p class="lede">Permutation composition 仍是 action pipeline。交換兩張可逆 maps 不會破壞可逆性，卻通常會改變 path 與 endpoint。</p></header>
<section class="prediction"><p class="kicker">先預測</p><h3>p∘q 與 q∘p 因為使用同兩張 maps，所以一定相同嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不一定</button><button type="button" (click)="prediction.set(true)">一定</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'Action order 會改變第二張 map 收到的 intermediate state。':'對。Composition 一般不 commutative。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Order pipeline</p><h3>固定 input，交換兩個 stages 的先後</h3></div><p>p swaps A/B；q shifts A→B→C→D→A。</p></div><div class="order-controls"><div role="group" aria-label="選擇 input">@for(label of labels;track $index){<button type="button" [attr.aria-pressed]="input()===$index" (click)="input.set($index)">{{label}}</button>}</div><div role="group" aria-label="選擇 composition order"><button type="button" [attr.aria-pressed]="order()==='p-after-q'" (click)="order.set('p-after-q')">p∘q · q FIRST</button><button type="button" [attr.aria-pressed]="order()==='q-after-p'" (click)="order.set('q-after-p')">q∘p · p FIRST</button></div></div><div class="stage order-stage"><section class="action-pipeline" aria-live="polite"><article><span>INPUT</span><strong>{{labels[input()]}}</strong></article><i>{{firstName()}} →</i><article><span>INTERMEDIATE</span><strong>{{labels[intermediate()]}}</strong></article><i>{{secondName()}} →</i><article><span>OUTPUT</span><strong>{{labels[output()]}}</strong></article></section><section class="order-console"><p class="kicker">{{notation()}}</p><div class="map-verdict">✓ RIGHTMOST ACTION RUNS FIRST</div><div class="comparison"><span>p∘q sends {{labels[input()]}} → {{labels[pAfterQ()]}}</span><span>q∘p sends {{labels[input()]}} → {{labels[qAfterP()]}}</span></div><p>{{pAfterQ()===qAfterP()?'這個 input 剛好同 endpoint；換其他 input 仍需檢查整張 map。':'同一 input 已得到不同 endpoint，足以證明兩個 compositions 不同。'}}</p></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>p∘q</span><i>means</i><span>input → q → p → output</span></div><p><strong>Composition 的順序由資料流決定，不由符號閱讀方向決定。</strong>右邊的 q 先接到 input，左邊的 p 接續處理結果。</p></aside>
<section class="transfer"><p class="kicker">遷移</p><h3>若要 undo p∘q，inverse 的順序是什麼？</h3><div class="choice-row"><button type="button" (click)="transfer.set(true)">q⁻¹∘p⁻¹</button><button type="button" (click)="transfer.set(false)">p⁻¹∘q⁻¹</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="!transfer()">{{transfer()?'對。最後做的 p 要最先 undo。':'Undo pipeline 必須反轉 stages。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>本頁兩張 permutations</summary><div>p=[B,A,C,D]，q=[B,C,D,A]。Composition 定義為 (p∘q)(x)=p(q(x))。</div></details></section></article>`})
export class AlgebraV3CompositionOrderComponent{readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly input=signal(0);readonly order=signal<Order>('p-after-q');readonly labels=['A','B','C','D'];readonly p:Permutation=[1,0,2,3];readonly q:Permutation=[1,2,3,0];readonly pAfterQ=computed(()=>compose(this.p,this.q)[this.input()]);readonly qAfterP=computed(()=>compose(this.q,this.p)[this.input()]);first():Permutation{return this.order()==='p-after-q'?this.q:this.p;}second():Permutation{return this.order()==='p-after-q'?this.p:this.q;}intermediate():number{return this.first()[this.input()];}output():number{return this.second()[this.intermediate()];}firstName():string{return this.order()==='p-after-q'?'q':'p';}secondName():string{return this.order()==='p-after-q'?'p':'q';}notation():string{return this.order()==='p-after-q'?'p∘q · APPLY q THEN p':'q∘p · APPLY p THEN q';}}
