import{Component,computed,signal}from'@angular/core';import{compose,display,inverse,key,S3}from'./permutation-model';
@Component({selector:'app-algebra-v3-symmetric-group-deck',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch19-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 19.3</p><h2>S₃ 不是一張特別的 shuffle；它是三個 objects 的完整可逆 action space</h2><p class="lede">三個 labels 共有六種 bijections。把全部 actions 放進同一副 deck，composition 的結果永遠仍是其中一張，identity 與 inverse 也都在 deck 裡。</p></header>
<section class="prediction"><p class="kicker">先預測</p><h3>三個 objects 的 permutations 有 3³=27 種嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不是，只有 3!=6</button><button type="button" (click)="prediction.set(true)">是</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'27 包含 collisions；bijection 要依序選 3、2、1 個未用 destinations。':'對。3×2×1=6。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">S₃ action deck</p><h3>選 left card 與 right card，composition result 自動落回 deck</h3></div><p>每張 card 顯示完整 mapping，不先使用 cycle notation。</p></div><div class="deck-stage"><section class="permutation-deck" aria-label="S3 的六個 permutations">@for(permutation of deck;track key(permutation);let i=$index){<button type="button" [class.left]="left()===i" [class.right]="right()===i" [class.result]="resultIndex()===i" (click)="choose(i)"><span>CARD {{i+1}}</span><strong>{{display(permutation)}}</strong><small>{{i===0?'IDENTITY':inverseIndex(i)===i?'SELF-INVERSE':'INVERSE CARD '+(inverseIndex(i)+1)}}</small></button>}</section><section class="deck-console" aria-live="polite"><p class="kicker">COMPOSE LEFT ∘ RIGHT</p><div class="card-equation"><strong>{{left()+1}}</strong><i>∘</i><strong>{{right()+1}}</strong><i>=</i><strong>{{resultIndex()+1}}</strong></div><div class="map-verdict">✓ RESULT CARD {{resultIndex()+1}} IS STILL IN S₃</div><p>{{display(result())}}</p><button type="button" (click)="swapOrder()">交換 composition order</button><small>點 deck card 會依序設定 LEFT、RIGHT。</small></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>all bijections of X</span><i>closed under composition</i><span>Sym(X)</span></div><p><strong>Symmetric group Sₙ 是 n 個 objects 的所有 permutations。</strong>Group elements 是 transformations；composition 是 operation。</p></aside>
<section class="transfer"><p class="kicker">遷移</p><h3>S₄ 有幾個 elements？</h3><div class="choice-row"><button type="button" (click)="transfer.set(true)">24</button><button type="button" (click)="transfer.set(false)">16</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="!transfer()">{{transfer()?'對。4!=4×3×2×1=24。':'每個 destination 只能使用一次，計數是 factorial。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>Symmetric group Sₙ</summary><div>Sₙ 是 set {{'{1,…,n}'}} 上所有 bijections，以 function composition 為 operation；|Sₙ|=n!。</div></details><details><summary>為何 group axioms 成立？</summary><div>Bijections composition 仍 bijective；function composition associative；identity map 在 deck；每個 bijection 的 inverse 也 bijective。</div></details></section></article>`})
export class AlgebraV3SymmetricGroupDeckComponent{readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly left=signal(1);readonly right=signal(3);readonly choosingLeft=signal(true);readonly deck=S3;readonly result=computed(()=>compose(this.deck[this.left()],this.deck[this.right()]));readonly resultIndex=computed(()=>this.deck.findIndex(p=>key(p)===key(this.result())));key=key;display=(p:number[])=>display(p,['A','B','C']);inverseIndex(i:number):number{return this.deck.findIndex(p=>key(p)===key(inverse(this.deck[i])));}choose(i:number):void{if(this.choosingLeft()){this.left.set(i);}else{this.right.set(i);}this.choosingLeft.update(v=>!v);}swapOrder():void{const l=this.left();this.left.set(this.right());this.right.set(l);}}
