import{Component,computed,signal}from'@angular/core';import{inverse}from'./permutation-model';
type Preset='swap'|'rotate'|'corrupt';
@Component({selector:'app-algebra-v3-assignment-gate',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch19-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 19.1</p><h2>Permutation 不是「排成一列」；它是每個 state 恰好換到一個新位置的可逆 action</h2><p class="lede">一個 finite set transformation 要能 undo，wires 必須同時沒有 collision 與 hole。只看「每個 source 都有箭頭」還不夠。</p></header>
<section class="prediction"><p class="kicker">先預測</p><h3>A→B、B→B、C→C、D→D 是 permutation 嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不是</button><button type="button" (click)="prediction.set(true)">是</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'A、B collision 在 B，且 A 沒有 preimage；無法唯一 undo。':'對。它是 function，但不是 bijection，因此不是 permutation。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Assignment gate</p><h3>切換 wiring，檢查每個 destination 的 incoming count</h3></div><p>VALID／COLLISION／HOLE 同時用文字與線型呈現。</p></div><div class="preset-picker" role="group" aria-label="選擇 reassignment"><button type="button" [attr.aria-pressed]="preset()==='swap'" (click)="preset.set('swap')">swap A↔B</button><button type="button" [attr.aria-pressed]="preset()==='rotate'" (click)="preset.set('rotate')">shift right</button><button type="button" [attr.aria-pressed]="preset()==='corrupt'" (click)="preset.set('corrupt')">collision map</button></div><div class="stage assignment-stage"><section class="wire-board"><div class="source-column">@for(label of labels;track label){<article><span>SOURCE</span><strong>{{label}}</strong></article>}</div><div class="wire-column" aria-hidden="true">@for(target of mapping();track $index){<i [class.bad]="incoming(target)!==1">{{labels[$index]}} → {{labels[target]}}</i>}</div><div class="destination-column">@for(label of labels;track $index){<article [class.bad]="incoming($index)!==1"><span>DESTINATION</span><strong>{{label}}</strong><small>{{status($index)}}</small></article>}</div></section><section class="assignment-console" aria-live="polite"><p class="kicker">REVERSIBILITY GATE</p><div class="count-strip">@for(label of labels;track $index){<div><span>{{label}} incoming</span><strong>{{incoming($index)}}</strong></div>}</div><div class="map-verdict" [class.fail]="!valid()">{{valid()?'✓ BIJECTION · VALID PERMUTATION':'× COLLISION + HOLE · NOT A PERMUTATION'}}</div>@if(valid()){<div class="inverse-readout"><span>INVERSE ACTION</span><strong>{{inverseReading()}}</strong></div>}@else{<p>Output B 無法判斷原本來自 A 還是 B；inverse 不是 function。</p>}</section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>one outgoing each</span><i>+</i><span>one incoming each</span><i>=</i><span>reversible reassignment</span></div><p><strong>Permutation（置換）是 set 到自身的 bijection。</strong>圖樣怎麼排不重要；可逆的一進一出 wiring 才是結構。</p></aside>
<section class="transfer"><p class="kicker">遷移</p><h3>Finite set 上 injective self-map 是否自動是 permutation？</h3><div class="choice-row"><button type="button" (click)="transfer.set(true)">是</button><button type="button" (click)="transfer.set(false)">不一定</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="!transfer()">{{transfer()?'對。有限且 source=target，同 size injective 便自動 surjective。':'有限 self-map 沒有 collisions 就不可能留下 hole。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>Permutation 的正式定義</summary><div>Set X 的 permutation 是 bijection σ:X→X。所有 permutations 在 composition 下形成 symmetric group Sym(X)；若 X={{'{1,…,n}'}}，記作 Sₙ。</div></details></section></article>`})
export class AlgebraV3AssignmentGateComponent{readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly preset=signal<Preset>('swap');readonly labels=['A','B','C','D'];readonly mapping=computed(()=>this.preset()==='swap'?[1,0,2,3]:this.preset()==='rotate'?[1,2,3,0]:[1,1,2,3]);incoming(target:number):number{return this.mapping().filter(value=>value===target).length;}valid():boolean{return this.labels.every((_,i)=>this.incoming(i)===1);}status(i:number):string{return this.incoming(i)===0?'HOLE':this.incoming(i)>1?'COLLISION':'ONE IN';}inverseReading():string{return inverse(this.mapping()).map((value,index)=>`${this.labels[index]}→${this.labels[value]}`).join(' · ');}}
