import { Component, computed, signal } from '@angular/core';
import { diagonalPoint, diagonalTarget, isDiagonal, MOD4_VALUES, pointKey, pointLabel } from './rings-ch18-model';

@Component({
  selector:'app-rings-ch18-effective-image',standalone:true,
  template:`
  <article class="algebra-v3-lesson rings-lesson rings-ch18-lesson">
    <header class="hero"><p class="eyebrow">Rings & Ideals · 18.4</p><h2>Kernel 能移除 input redundancy，不能替 map 創造新 outputs</h2><p class="lede">Diagonal map沒有collisions，卻只抵達16格target中的4格。把四張effective inputs逐一接到reachable sockets，分清target宣告的空間與image真正活著的部分。</p></header>
    <span class="map-convention">FINITE INSTANCE · Δ:ℤ/4ℤ→ℤ/4ℤ×ℤ/4ℤ · Δ(n)=(n,n) · IMAGE SHAPE IS CASE-SPECIFIC</span>
    <section class="prediction"><div><p class="kicker">先預測</p><h3>ker Δ只有0；因此R/ker Δ應該對準16格target，還是4格reachable image？</h3></div><div class="choice-row"><button type="button" (click)="prediction.set('image')">4格image</button><button type="button" (click)="prediction.set('target')">整個16格target</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()==='target'">{{prediction()==='image'?'對。Kernel處理inputs的collision，surjectivity才決定是否填滿target。':'No collision只代表injective；它沒有替off-diagonal cells製造preimage。'}}</p>}</section>
    <div class="control-row"><button type="button" (click)="routeNext()">ROUTE NEXT INPUT</button><button type="button" (click)="routeAll()">REVEAL WHOLE IMAGE</button><button type="button" (click)="reset()">RESET</button></div>
    <section class="stage stage-grid"><div class="image-target-lab"><div class="image-route"><section class="image-inputs"><span class="mini-label">R/ker Δ = ℤ/4ℤ</span>@for(v of values;track v){<button type="button" [class.routed]="isRouted(v)" (click)="route(v)"><strong>{{v}}+ker Δ</strong><span>{{isRouted(v)?'→ '+label(image(v)):'waiting'}}</span></button>}</section><div class="delta-machine"><span class="mini-label">INDUCED MAP</span><strong>Δ̄</strong><span>onto image</span></div><section><span class="mini-label">DECLARED TARGET · 16 SOCKETS</span><div class="target-grid18">@for(point of target;track key(point)){<div class="target-cell18" [class.reachable]="diagonal(point)" [class.lit]="lit(point)"><small>{{lit(point)?'FROM '+point.first:complete()&&diagonal(point)?'IMAGE SOCKET':complete()?'NO PREIMAGE':'TARGET'}}</small><strong>{{label(point)}}</strong></div>}</div></section></div><div class="image-ledger"><div><span class="mini-label">KERNEL CLASSES</span><strong>4</strong><span>no nonzero collisions</span></div><div><span class="mini-label">REACHABLE IMAGE</span><strong>{{routed().length}} / 4</strong><span>actual outputs</span></div><div><span class="mini-label">DECLARED TARGET</span><strong>16</strong><span>{{complete()?'12 have no preimage':'audit pending'}}</span></div></div></div><aside class="console" aria-live="polite"><span class="evidence-badge">{{complete()?'FINITE EXHAUSTION · THIS MAP':'IMAGE REACHABILITY AUDIT'}}</span><h3>{{complete()?'R/ker Δ MATCHES im Δ · NOT THE WHOLE TARGET':'ROUTE THE EFFECTIVE INPUTS'}}</h3><p>{{complete()?'四張quotient cards恰好對準四格image；另外十二格target不會因quotient而自動亮起。':'追蹤每張input真正抵達的位置；不要用target大小推測image。'}}</p><div class="readout">|R/ker Δ|=4 · |im Δ|={{routed().length}} · |target|=16</div></aside></section>
    @if(complete()){<section class="transfer-strip"><div><p class="kicker">ACCIDENTAL-SHAPE CHECK</p><strong>Image一定會長成幾何diagonal嗎？</strong></div><div class="choice-row"><button type="button" (click)="transfer.set(true)">不會；evaluation map的image可以填滿target</button><button type="button" (click)="transfer.set(false)">會；image定義就是diagonal</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="!transfer()">{{transfer()?'對。Diagonal只是Δ的公式造成；一般mechanism只說quotient對準reachable image。':'Image是實際outputs的集合，形狀由map決定。'}}</p>}</section>}
    <section class="insight"><span class="insight-icon">im f</span><div><strong>Kernel 告訴你哪些 inputs 應合併；image 告訴你合併後真正剩下哪些 outputs</strong><span>Quotient修正input redundancy，不補齊target gaps；只有surjective map才讓image等於target。</span></div></section>
    <div class="next-question"><strong>NEXT QUESTION · 18.5</strong><p>兩張quotient outputs一起當座標時，沒有共同collision是否已足以保證每個coordinate都能重建？</p></div>
    <details><summary>First Isomorphism Theorem 回扣</summary><p>一般地R/ker f≅im f。主例的finite routing完整列出目前instance；一般theorem不是由4格count推出。Δ的image恰為diagonal subring只是公式的偶然外觀。</p></details>
  </article>`,
})
export class RingsCh18EffectiveImageComponent{
  readonly values=MOD4_VALUES;readonly target=diagonalTarget();readonly prediction=signal<'image'|'target'|null>(null);readonly routed=signal<readonly number[]>([]);readonly transfer=signal<boolean|null>(null);readonly complete=computed(()=>this.routed().length===4);
  key=pointKey;label=pointLabel;diagonal=isDiagonal;image=diagonalPoint;isRouted(v:number):boolean{return this.routed().includes(v);}lit(p:{first:number;second:number}):boolean{return this.isRouted(p.first)&&isDiagonal(p);}route(v:number):void{if(!this.isRouted(v))this.routed.update(xs=>[...xs,v]);}routeNext():void{const v=this.values.find(x=>!this.isRouted(x));if(v!==undefined)this.route(v);}routeAll():void{this.routed.set([...this.values]);}reset():void{this.prediction.set(null);this.routed.set([]);this.transfer.set(null);}
}
