import { Component, computed, signal } from '@angular/core';
import { pairedInjective, pairedSurjective, pairedTarget, pairModuli, PairViewMode, pointKey, pointLabel, reachablePairedAddresses } from './rings-ch18-model';

@Component({
  selector:'app-rings-ch18-paired-reconstruction-gates',standalone:true,
  template:`
  <article class="algebra-v3-lesson rings-lesson rings-ch18-lesson">
    <header class="hero"><p class="eyebrow">Rings & Ideals · 18.5</p><h2>沒有共同 blind spot，仍不代表每個 coordinate 都有來源</h2><p class="lede">Reconstruction要同時通過兩道門：不同inputs不能共用address，而且每個合法address都必須reachable。固定ℤ/12ℤ，只換兩張quotient views。</p></header>
    <span class="map-convention">PAIRED MAP · GATE 1 DISTINGUISHABILITY · GATE 2 REACHABILITY · MODULAR COUNTS ARE INSTANCE-SPECIFIC</span>
    <section class="prediction"><div><p class="kicker">先預測</p><h3>mod 4與mod 6沒有共同input collision。這是否足以讓map填滿4×6 target？</h3></div><div class="choice-row"><button type="button" (click)="prediction.set(false)">不夠，還要檢查reachability</button><button type="button" (click)="prediction.set(true)">足夠，沒有collision就能重建</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'Injective只保護source distinction；24個target addresses仍可能有一半沒有來源。':'對。先過shared-kernel gate，再另外檢查target coverage。'}}</p>}</section>
    <div class="control-row"><button type="button" [class.active]="mode()==='mod46'" (click)="select('mod46')">VIEWS · MOD 4 & MOD 6</button><button type="button" [class.active]="mode()==='mod34'" (click)="select('mod34')">VIEWS · MOD 3 & MOD 4</button><button type="button" [disabled]="stage()>=2" (click)="nextGate()">RUN NEXT GATE</button><button type="button" (click)="reset()">RESET</button></div>
    <section class="stage stage-grid"><div class="paired-gates-lab"><div class="paired-layout"><section class="gate-stack"><div class="logic-gate18" [class.visible]="stage()>=1" [class.pass]="stage()>=1&&injective()"><span class="mini-label">GATE 1 · SHARED BLIND SPOT</span><strong>{{stage()>=1?'I∩J={0} · PASS':'WAITING'}}</strong><span>{{stage()>=1?'12 inputs keep 12 distinct addresses':'check source collisions'}}</span></div><div class="logic-gate18" [class.visible]="stage()>=2" [class.pass]="stage()>=2&&surjective()" [class.fail]="stage()>=2&&!surjective()"><span class="mini-label">GATE 2 · TARGET REACHABILITY</span><strong>{{stage()>=2?(surjective()?'I+J=R · PASS':'I+J≠R · BLOCKED'):'WAITING'}}</strong><span>{{stage()>=2?reachable().length+' / '+target().length+' addresses reachable':'audit target coverage'}}</span></div></section><section><span class="mini-label">TARGET ADDRESS GRID · {{mods()[0]}} × {{mods()[1]}}</span><div class="address-grid18" [style.grid-template-columns]="'repeat('+mods()[1]+',1fr)'">@for(address of target();track key(address)){<div class="address-cell18" [class.reachable]="stage()>=2&&isReachable(address)" [class.missing]="stage()>=2&&!isReachable(address)"><strong>{{label(address)}}</strong><span>{{stage()<2?'?':isReachable(address)?'SOURCE EXISTS':'NO SOURCE'}}</span></div>}</div></section></div></div><aside class="console" aria-live="polite"><span class="evidence-badge">{{stage()===2?'FINITE EXHAUSTION · ACTIVE PAIRED MAP':'TWO-GATE DIAGNOSIS'}}</span><h3>{{heading()}}</h3><p>{{reading()}}</p><div class="readout">inputs 12 · distinct addresses {{reachable().length}} · target {{target().length}}</div></aside></section>
    <section class="insight"><span class="insight-icon">1–1 / onto</span><div><strong>Reconstruction 需要沒有共用地址，也沒有任何合法地址找不到 input</strong><span>Intersection控制shared blind spot；sum控制paired target reachability。Injective與surjective是兩道獨立的門。</span></div></section>
    <div class="next-question"><strong>NEXT QUESTION · 18.6</strong><p>如果需求不再是重建addresses，而是保留multiplication behavior，應切換到哪一種boundary detector？</p></div>
    <details><summary>CRT criterion 與 evidence</summary><p>對canonical paired map，kernel為I∩J；I+J=R時map surjective，得到R/(I∩J)≅R/I×R/J。Grid scan只完整證明兩個ℤ/12ℤ instances；一般criterion依賴kernel與comaximality argument。</p></details>
  </article>`,
})
export class RingsCh18PairedReconstructionGatesComponent{
  readonly mode=signal<PairViewMode>('mod46');readonly stage=signal(0);readonly prediction=signal<boolean|null>(null);readonly mods=computed(()=>pairModuli(this.mode()));readonly target=computed(()=>pairedTarget(this.mode()));readonly reachable=computed(()=>reachablePairedAddresses(this.mode()));readonly injective=computed(()=>pairedInjective(this.mode()));readonly surjective=computed(()=>pairedSurjective(this.mode()));key=pointKey;label=pointLabel;
  isReachable(a:{first:number;second:number}):boolean{return this.reachable().some(r=>pointKey(r)===pointKey(a));}select(m:PairViewMode):void{this.mode.set(m);this.stage.set(0);}nextGate():void{this.stage.update(v=>Math.min(2,v+1));}heading():string{return this.stage()===0?'RUN DISTINGUISHABILITY FIRST':this.stage()===1?'GATE 1 PASSES · RECONSTRUCTION NOT YET PROVEN':this.surjective()?'BOTH GATES PASS · CRT COORDINATES':'GATE 2 FAILS · INJECTIVE BUT NOT SURJECTIVE';}reading():string{return this.stage()===0?'先問有沒有shared collision；不要直接從moduli外觀猜CRT。':this.stage()===1?'每個source留下不同address；現在仍需問target中的每格是否有preimage。':this.surjective()?'12個inputs恰好填滿12個addresses，paired view可逆。':'12個inputs雖保持distinction，卻只填滿24格target的一半。';}reset():void{this.mode.set('mod46');this.stage.set(0);this.prediction.set(null);}
}
