import { Component, computed, signal } from '@angular/core';
import { BehaviorBoundary, boundaryLabel, hasDomainBehavior, hasFieldBehavior, quotientBehaviorLabel } from './rings-ch18-model';

type Requirement='domain'|'field';
@Component({
  selector:'app-rings-ch18-behavior-route-finale',standalone:true,
  template:`
  <article class="algebra-v3-lesson rings-lesson rings-ch18-lesson">
    <header class="hero"><p class="eyebrow">Rings & Ideals · 18.6</p><h2>想保留哪種 multiplication behavior，決定該用哪個 detector</h2><p class="lede">Prime與maximal不是兩個等待背誦的ideal names。先讀client requirement：只要求nonzero product不消失，還是要求every nonzero class都能回到1？</p></header>
    <span class="map-convention">FINAL ROUTE SELECTION · COMMUTATIVE UNITAL RINGS · DETECTOR FOLLOWS THE REQUIRED BEHAVIOR</span>
    <section class="prediction"><div><p class="kicker">選擇client requirement</p><h3>{{requirement()==='domain'?'「兩個nonzero classes相乘後絕不能變zero。」':'「Every nonzero class都必須能做除法、回到1。」'}}</h3></div><div class="choice-row"><button type="button" [class.active]="requirement()==='domain'" (click)="setRequirement('domain')">NO ZERO CRASH</button><button type="button" [class.active]="requirement()==='field'" (click)="setRequirement('field')">INVERSE TO 1</button></div></section>
    <div class="control-row"><span class="kicker">CHOOSE DETECTOR</span><button type="button" [class.active]="selected()==='domain'" (click)="choose('domain')">PRIME / DOMAIN</button><button type="button" [class.active]="selected()==='field'" (click)="choose('field')">MAXIMAL / FIELD</button><span class="kicker">TEST BOUNDARY</span>@for(id of boundaries;track id){<button type="button" [class.active]="boundary()===id" (click)="boundary.set(id)">{{boundaryName(id)}}</button>}<button type="button" (click)="test()">RUN DECISIVE TEST</button><button type="button" (click)="reset()">RESET</button></div>
    <section class="stage stage-grid"><div class="behavior-router-lab"><div class="requirement-card18"><span class="mini-label">ACTIVE CLIENT REQUIREMENT</span><strong>{{requirement()==='domain'?'NONZERO × NONZERO MUST SURVIVE':'EVERY NONZERO CLASS MUST REACH 1'}}</strong><span>{{selected()===null?'detector not selected':selectionCorrect()?'correct route selected':'selected detector answers another question'}}</span></div><div class="detector-choice-grid"><div class="detector-card18" [class.selected]="selected()==='domain'"><span class="mini-label">ZERO-PRODUCT TRACE</span><strong>PRIME IDEAL ⇔ DOMAIN QUOTIENT</strong><span>look for two outsiders whose product enters P</span></div><div class="detector-card18" [class.selected]="selected()==='field'"><span class="mini-label">INVERSE-TO-ONE</span><strong>MAXIMAL IDEAL ⇔ FIELD QUOTIENT</strong><span>look for a nonzero class without inverse</span></div></div><div class="boundary-ledger18">@for(id of boundaries;track id){<div [class.active]="tested()&&boundary()===id"><span class="mini-label">{{quotientName(id)}}</span><strong>{{boundaryName(id)}}</strong><span>NO ZERO CRASH · {{domain(id)?'YES':'NO'}}</span><span>INVERSE TO 1 · {{field(id)?'YES':'NO'}}</span></div>}</div>@if(tested()&&selectionCorrect()){<div class="final-route-map"><div><strong>WHAT MUST DISAPPEAR?</strong><span>relation → difference → generated ideal</span><span>map collisions → kernel</span><span>shared blind spot → intersection</span><span>given ideal → quotient zero</span></div><div><strong>WHAT MUST SURVIVE?</strong><span>map consistency → I⊆ker f</span><span>reachable outputs → image</span><span>paired reachability → sum / CRT</span><span>multiplication → prime or maximal</span></div></div>}</div><aside class="console" aria-live="polite"><span class="evidence-badge">{{tested()?(selectionCorrect()?'ROUTE + DECISIVE TEST':'ROUTE MISMATCH'):'CLIENT-DRIVEN DETECTOR'}}</span><h3>{{heading()}}</h3><p>{{reading()}}</p><div class="readout">boundary {{boundaryName(boundary())}} · quotient {{quotientName(boundary())}}</div></aside></section>
    <section class="insight"><span class="insight-icon">18/18</span><div><strong>Ideal 告訴你哪些 differences 可以安全忽略；quotient 告訴你忽略後哪些 operation behavior 還活著</strong><span>先問目標，再選kernel、image、CRT、prime或maximal；名稱不再是解題起點。</span></div></section>
    <div class="chapter-resolution"><strong>RINGS & IDEALS · COURSE RESOLUTION</strong><p>兩種operations → maps與kernels → ideals與quotients → universal compression → reconstruction → field／domain behavior。現在你擁有的是一組可選擇的lenses，不只是一串definitions。</p></div>
    <details><summary>Evidence 為什麼不是額外一關？</summary><p>本頁只要求選route與first decisive test。6ℤ中的2·3是witness；ℤ與ℤ/5ℤ的universal verdict需要general arguments或先前已完成的finite exhaustion。Evidence label是回饋，不是第二套背誦題。</p></details>
  </article>`,
})
export class RingsCh18BehaviorRouteFinaleComponent{
  readonly boundaries:readonly BehaviorBoundary[]=['six','zero','five'];readonly requirement=signal<Requirement>('domain');readonly selected=signal<Requirement|null>(null);readonly boundary=signal<BehaviorBoundary>('six');readonly tested=signal(false);readonly selectionCorrect=computed(()=>this.selected()===this.requirement());boundaryName=boundaryLabel;quotientName=quotientBehaviorLabel;domain=hasDomainBehavior;field=hasFieldBehavior;
  setRequirement(r:Requirement):void{this.requirement.set(r);this.selected.set(null);this.tested.set(false);this.boundary.set(r==='domain'?'six':'zero');}choose(r:Requirement):void{this.selected.set(r);this.tested.set(false);}test():void{this.tested.set(true);}heading():string{if(!this.tested())return 'CHOOSE THE DETECTOR THAT MATCHES THE REQUEST';if(!this.selectionCorrect())return 'THIS DETECTOR ANSWERS A DIFFERENT CLIENT QUESTION';const pass=this.requirement()==='domain'?this.domain(this.boundary()):this.field(this.boundary());return pass?'ACTIVE QUOTIENT MEETS THE REQUEST':'DECISIVE FAILURE FOUND';}reading():string{if(!this.tested())return '同一個boundary可以接受兩種不同tests；client requirement決定哪個verdict有關。';if(!this.selectionCorrect())return this.requirement()==='domain'?'Inverse不是必要條件；先檢查nonzero product是否會crash。':'No-zero-crash仍不足以做除法；必須檢查every nonzero inverse。';if(this.requirement()==='domain')return this.domain(this.boundary())?'沒有nonzero zero-product witness；此quotient保留domain behavior。':'2與3是nonzero classes，product卻是zero；一張witness已否決需求。';return this.field(this.boundary())?'每張nonzero residue都有inverse，identity dock全開。':'至少一張nonzero class沒有inverse；inverse-to-one需求失敗。';}reset():void{this.requirement.set('domain');this.selected.set(null);this.boundary.set('six');this.tested.set(false);}
}
