import { Component, computed, signal } from '@angular/core';
type SeedMode='r'|'f'|'rf';
interface WaveNode{label:string;round:number;reason:string;}
@Component({selector:'app-algebra-v3-seed-closure-wave',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch11-lesson">
 <header class="hero"><p class="eyebrow">Abstract Algebra · 11.3</p><h2>Seeds 不會停在原地：group contract 會逼出最小穩定世界</h2><p class="lede">在 triangle symmetry group S₃ 中放入一顆 seed，不能任性挑選要不要加入它的 inverse 與 composites。逐輪播放 closure wave，直到沒有新 element 被強迫加入；停下來的世界就是 generated subgroup。</p></header>
 <section class="prediction"><p class="kicker">先預測</p><h3>固定 ambient group 與 seeds S，可能得到兩個不同的「最小」subgroups 嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不可能</button><button type="button" (click)="prediction.set(true)">可能</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'所有 seed words 的 effects 已唯一決定；兩個都聲稱最小也會互相包含。':'對。Closure 不是自由選擇，所以終點唯一。'}}</p>}</section>
 <section class="lab"><div class="lab-heading"><div><p class="kicker">Seed closure wave</p><h3>每一個新 node 都要附上「為何被迫加入」</h3></div><p>選 seeds 後逐輪展開。LOCKED 表示尚未推導，不代表 element 不存在。</p></div>
 <div class="candidate-picker" role="group" aria-label="選擇 seeds"><button type="button" [attr.aria-pressed]="mode()==='r'" (click)="select('r')">seed {{'{r}'}}</button><button type="button" [attr.aria-pressed]="mode()==='f'" (click)="select('f')">seed {{'{f}'}}</button><button type="button" [attr.aria-pressed]="mode()==='rf'" (click)="select('rf')">seeds {{'{r,f}'}}</button></div>
 <div class="stage wave-layout"><div class="symmetry-world" aria-label="S₃ closure wave">@for(node of nodes();track node.label){<div class="wave-node" [class.reached]="node.round<=round()"><strong>{{node.label}}</strong><span>{{node.round<=round()?'ROUND '+node.round:'LOCKED'}}</span><small>{{node.round<=round()?node.reason:'尚未被 closure wave 推到'}}</small></div>}</div><section class="wave-console" aria-live="polite"><p class="kicker">WAVE ROUND {{round()}} / {{maxRound()}}</p><div class="wave-ledger">@for(node of nodes();track node.label){@if(node.round<=round()){<div><b>{{node.label}}</b><span>{{node.reason}}</span></div>}}</div><div class="control-row"><button type="button" class="primary" [disabled]="round()===maxRound()" (click)="nextRound()">展開下一輪</button><button type="button" (click)="round.set(0)">回到 seeds</button></div>@if(round()===maxRound()){<div class="subgroup-verdict">✓ STABLE WORLD: {{generatedSet()}}</div>}<p>{{round()===maxRound()?'沒有新的 identity、inverse 或 composite 被迫加入，closure wave 停止。':'目前還不能把亮起 nodes 宣稱為 subgroup；繼續補齊 contract。'}}</p></section></div>
 </section>
 <aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>seeds S</span><i>closure wave</i><span>⟨S⟩</span></div><p><strong>Generated subgroup 是包含 seeds 的最小自給自足世界。</strong>它不是把「想要的」elements 圈起來，而是接受 group contract 強迫加入的全部 consequences。</p></aside>
 <section class="transfer"><p class="kicker">最小性</p><h3>若 S⊆H≤G，generated subgroup ⟨S⟩ 必須放在哪裡？</h3><div class="choice-row"><button type="button" (click)="transfer.set(true)">必在 H 裡</button><button type="button" (click)="transfer.set(false)">可能跑出 H</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="!transfer()">{{transfer()?'對。H 已含 seeds 且封閉，因此也必含所有被 seeds 強迫出的 effects。':'若跑出 H，就表示 H 沒對相同 operation 封閉，與 H≤G 矛盾。'}}</p>}</section>
 <section class="secondary"><p>SECONDARY LAYER</p><details><summary>⟨S⟩ 的兩種等價定義</summary><div>它既是所有由 S 與 S⁻¹ 組成之 finite words 的 effects，也是所有包含 S 的 subgroups 的 intersection。</div></details><details><summary>Proof Lab：為何兩種定義相同？</summary><div>S-words 的 effects 形成包含 S 的 subgroup W。任何包含 S 的 subgroup 都必含每個 S-word，所以 W 包含於所有候選；而 W 自己也是候選，故正是它們的 intersection。</div></details></section>
</article>`})
export class AlgebraV3SeedClosureWaveComponent{
 readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly mode=signal<SeedMode>('r');readonly round=signal(0);
 readonly nodes=computed<WaveNode[]>(()=>({r:[{label:'r',round:0,reason:'SEED'},{label:'r²',round:1,reason:'inverse of r'},{label:'e',round:1,reason:'r·r⁻¹'} ,{label:'f',round:2,reason:'not forced'},{label:'rf',round:2,reason:'not forced'},{label:'r²f',round:2,reason:'not forced'}],f:[{label:'f',round:0,reason:'SEED · self-inverse'},{label:'e',round:1,reason:'f·f=e'},{label:'r',round:2,reason:'not forced'},{label:'r²',round:2,reason:'not forced'},{label:'rf',round:2,reason:'not forced'},{label:'r²f',round:2,reason:'not forced'}],rf:[{label:'r',round:0,reason:'SEED'},{label:'f',round:0,reason:'SEED'},{label:'e',round:1,reason:'identity forced'},{label:'r²',round:1,reason:'inverse of r'},{label:'rf',round:2,reason:'composite r·f'},{label:'r²f',round:2,reason:'composite r²·f'}]})[this.mode()]);
 readonly maxRound=computed(()=>this.mode()==='rf'?2:1);readonly generatedSet=computed(()=>this.mode()==='r'?'{e,r,r²}':this.mode()==='f'?'{e,f}':'S₃ · all 6 elements');
 select(mode:SeedMode):void{this.mode.set(mode);this.round.set(0);}nextRound():void{this.round.update(value=>Math.min(this.maxRound(),value+1));}
}
