import { Component, computed, signal } from '@angular/core';
type TestSet='h03'|'h024'|'k02'|'odd';
@Component({selector:'app-algebra-v3-subgroup-test-scanner',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch11-lesson">
  <header class="hero"><p class="eyebrow">Abstract Algebra · 11.2</p><h2>一個 a·b⁻¹ test，把三種逃逸壓成同一條掃描</h2><p class="lede">Ambient group 已經提供 associativity。對非空候選 H，我們只問：任取 a、b∈H，先把 b 反轉，再接到 a 後面，output 是否永遠留在 H？在 additive ℤ₆ 中，這就是 a−b。</p></header>
  <section class="prediction"><p class="kicker">先判斷</p><h3>只找到幾對 a−b 留在 H，就能證明 H 是 subgroup 嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不能，要涵蓋任意 pair</button><button type="button" (click)="prediction.set(true)">能</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'Subgroup test 是 universal claim；成功樣本不能代替所有 pairs。':'對。有限集合可完整掃描；無限集合要給 general reason。'}}</p>}</section>
  <section class="lab">
    <div class="lab-heading"><div><p class="kicker">a−b pair scanner</p><h3>點一格看因果，或逐格完成 exhaustive scan</h3></div><p>Row 是 a、column 是 b；每格 output 為 a−b mod 6。FAIL 文字就是 escape witness。</p></div>
    <div class="candidate-picker" role="group" aria-label="選擇候選 subset"><button type="button" [attr.aria-pressed]="setId()==='h03'" (click)="select('h03')">{{'{0,3}'}}</button><button type="button" [attr.aria-pressed]="setId()==='h024'" (click)="select('h024')">{{'{0,2,4}'}}</button><button type="button" [attr.aria-pressed]="setId()==='k02'" (click)="select('k02')">{{'{0,2}'}}</button><button type="button" [attr.aria-pressed]="setId()==='odd'" (click)="select('odd')">{{'{1,3,5}'}}</button></div>
    <div class="stage test-layout">
      <div class="pair-matrix" [style.--matrix-size]="members().length" role="grid" aria-label="a 減 b subgroup test matrix"><span class="corner">a\b</span>@for(b of members();track b){<b>{{b}}</b>}@for(a of members();track a){<b>{{a}}</b>@for(b of members();track b){<button type="button" [class.hidden-cell]="!isRevealed(a,b)" [class.fail-cell]="isRevealed(a,b)&&!inside(a,b)" (click)="inspect(a,b)">{{cellValue(a,b)}}<small>{{cellStatus(a,b)}}</small></button>}}</div>
      <section class="test-console" aria-live="polite"><p class="kicker">SCANNER {{revealed()}} / {{totalPairs()}}</p><div class="operation-tape"><span>{{selectedA()}}</span><i>−</i><span>{{selectedB()}}</span><i>=</i><strong>{{difference(selectedA(),selectedB())}}</strong></div><div class="contract-line" [class.fail]="!inside(selectedA(),selectedB())">{{inside(selectedA(),selectedB())?'✓ SELECTED PAIR STAYS IN H':'× ESCAPE WITNESS FOUND'}}</div><div class="control-row"><button type="button" class="primary" [disabled]="revealed()===totalPairs()" (click)="scanNext()">Scan next pair</button><button type="button" (click)="scanAll()">Scan all</button><button type="button" (click)="revealed.set(0)">重設</button></div>@if(revealed()===totalPairs()){<div class="subgroup-verdict" [class.fail]="!allPass()">{{allPass()?'✓ EVERY PAIR PASSES · SUBGROUP TEST PASSED':'× AT LEAST ONE PAIR ESCAPES · TEST FAILED'}}</div>}<p>{{scopeReading()}}</p></section>
    </div>
  </section>
  <aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>a</span><i>combine with</i><span>b⁻¹</span><i>stays in</i><span>H</span></div><p><strong>a·b⁻¹ 同時探測「能不能回頭」與「接起來會不會逃出」。</strong>它是 group contract 的濃縮檢查，不是另一條要背的無關公式。</p></aside>
  <section class="transfer"><p class="kicker">無限集合</p><h3>Even integers 為何不需逐對列完，也能通過 a−b test？</h3><div class="transfer-answer"><span>a=2m</span><span>b=2n</span><span>a−b=2(m−n) 仍為偶數</span></div></section>
  <section class="secondary"><p>SECONDARY LAYER</p><details><summary>One-step subgroup test</summary><div>非空 H⊆G 是 subgroup，若且唯若對所有 a,b∈H 都有 ab⁻¹∈H。非空條件不能省略，否則空集會讓全稱條件 vacuously true。</div></details><details><summary>Proof Lab：一條 test 如何重建 contract？</summary><div>取 h∈H，令 a=b=h 得 e∈H；令 a=e、b=h 得 h⁻¹∈H。給 x,y∈H，已知 y⁻¹∈H，再把 b 取成 y⁻¹，得到 xy∈H。</div></details></section>
</article>`})
export class AlgebraV3SubgroupTestScannerComponent{
 readonly prediction=signal<boolean|null>(null);readonly setId=signal<TestSet>('k02');readonly revealed=signal(0);readonly selectedA=signal(0);readonly selectedB=signal(0);
 readonly members=computed(()=>({h03:[0,3],h024:[0,2,4],k02:[0,2],odd:[1,3,5]})[this.setId()]);readonly totalPairs=computed(()=>this.members().length**2);readonly allPass=computed(()=>this.members().every(a=>this.members().every(b=>this.inside(a,b))));
 difference(a:number,b:number):number{return(a-b+6)%6;}inside(a:number,b:number):boolean{return this.members().includes(this.difference(a,b));}cellIndex(a:number,b:number):number{return this.members().indexOf(a)*this.members().length+this.members().indexOf(b);}isRevealed(a:number,b:number):boolean{return this.cellIndex(a,b)<this.revealed();}cellValue(a:number,b:number):string{return this.isRevealed(a,b)?String(this.difference(a,b)):'?';}cellStatus(a:number,b:number):string{return this.isRevealed(a,b)?(this.inside(a,b)?'PASS':'FAIL'):'LOCKED';}inspect(a:number,b:number):void{this.selectedA.set(a);this.selectedB.set(b);this.revealed.update(v=>Math.max(v,this.cellIndex(a,b)+1));}scanNext():void{const index=this.revealed();this.selectedA.set(this.members()[Math.floor(index/this.members().length)]??this.members()[0]);this.selectedB.set(this.members()[index%this.members().length]??this.members()[0]);this.revealed.update(v=>Math.min(this.totalPairs(),v+1));}scanAll():void{this.revealed.set(this.totalPairs());const witness=this.members().flatMap(a=>this.members().map(b=>[a,b] as const)).find(([a,b])=>!this.inside(a,b));if(witness){this.selectedA.set(witness[0]);this.selectedB.set(witness[1]);}}
 select(id:TestSet):void{this.setId.set(id);this.revealed.set(0);this.selectedA.set(this.members()[0]);this.selectedB.set(this.members()[0]);}scopeReading():string{return this.revealed()===this.totalPairs()?(this.allPass()?'有限候選的 ordered pairs 已全部覆蓋，沒有只靠 sample 猜測。':'一個 FAIL cell 就是可重現的 counterexample。'):'尚未掃完；目前的 PASS 不能代表未檢查 pairs。';}
}
