import { Component, computed, signal } from '@angular/core';
type LatticeId='g'|'h2'|'h3'|'e';
@Component({selector:'app-algebra-v3-subgroup-lattice',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch11-lesson">
 <header class="hero"><p class="eyebrow">Abstract Algebra · 11.4</p><h2>Subgroup lattice 不列乘法：它畫的是誰住在誰裡面</h2><p class="lede">同一個 group 往往有多個自給自足子世界。清單只告訴我們「有哪些」；lattice 用 inclusion 排序它們，讓限制 actions 與增加能力的方向一眼可見。</p></header>
 <section class="prediction"><p class="kicker">先判斷</p><h3>lattice 上連著兩個 nodes，線條表示它們相乘嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不是，表示直接 inclusion</button><button type="button" (click)="prediction.set(true)">是</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'這張圖的 objects 是整個 subgroups，不是 individual elements；線條只表示包含關係。':'對。往上是容許更多 effects 的較大 subgroup，往下是更強的限制。'}}</p>}</section>
 <section class="lab"><div class="lab-heading"><div><p class="kicker">Inclusion lattice navigator</p><h3>點一個 subworld，同時看它包含誰、又被誰包含</h3></div><p>實線連接 cover relation；CONTAINS／CONTAINED BY 文字提供非色彩辨識。</p></div>
 <div class="stage lattice-layout"><div class="lattice-board" aria-label="ℤ₆ subgroup inclusion lattice"><svg viewBox="0 0 600 360" aria-hidden="true"><line x1="300" y1="55" x2="170" y2="180"/><line x1="300" y1="55" x2="430" y2="180"/><line x1="170" y1="180" x2="300" y2="310"/><line x1="430" y1="180" x2="300" y2="310"/></svg><button type="button" class="lattice-node top" [class.current]="selected()==='g'" [class.related]="relationTo('g')!=='UNRELATED'" (click)="selected.set('g')"><strong>ℤ₆</strong><span>{{relationTo('g')}}</span></button><button type="button" class="lattice-node middle left" [class.current]="selected()==='h2'" [class.related]="relationTo('h2')!=='UNRELATED'" (click)="selected.set('h2')"><strong>⟨2⟩</strong><small>{{'{0,2,4}'}}</small><span>{{relationTo('h2')}}</span></button><button type="button" class="lattice-node middle right" [class.current]="selected()==='h3'" [class.related]="relationTo('h3')!=='UNRELATED'" (click)="selected.set('h3')"><strong>⟨3⟩</strong><small>{{'{0,3}'}}</small><span>{{relationTo('h3')}}</span></button><button type="button" class="lattice-node bottom" [class.current]="selected()==='e'" [class.related]="relationTo('e')!=='UNRELATED'" (click)="selected.set('e')"><strong>{{'{0}'}}</strong><span>{{relationTo('e')}}</span></button></div><section class="lattice-console" aria-live="polite"><p class="kicker">SELECTED {{data().name}}</p><div class="subgroup-verdict">{{data().members}}</div><div class="relation-list"><div><span>CONTAINED BY</span><strong>{{data().above}}</strong></div><div><span>CONTAINS</span><strong>{{data().below}}</strong></div></div><p>{{data().reading}}</p><div class="lattice-legend"><span>↑ 往上：加入可用 effects</span><span>↓ 往下：限制可用 effects</span></div></section></div>
 </section>
 <aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>smaller H</span><i>⊆</i><span>larger K</span><i>⊆</i><span>G</span></div><p><strong>Lattice 把「哪些子世界能嵌在另一些子世界裡」變成地圖。</strong>它關心 inclusion structure；高度不是 subgroup 的物理大小，線長也不是生成步數。</p></aside>
 <section class="transfer"><p class="kicker">交集與聯集</p><h3>⟨2⟩∩⟨3⟩ 在圖上是哪個共同子世界？</h3><div class="choice-row"><button type="button" (click)="transfer.set(true)">{{'{0}'}}</button><button type="button" (click)="transfer.set(false)">ℤ₆</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="!transfer()">{{transfer()?'對。它是兩者共同包含的最大 subgroup，也就是 lattice 的 meet。':'兩者唯一共同 element 是 identity 0。'}}</p>}</section>
 <section class="secondary"><p>SECONDARY LAYER</p><details><summary>Intersection 為何仍是 subgroup？</summary><div>Identity 在每個 subgroup 中；若 a、b 在交集，它們就在每個 subgroup 中，因此 ab⁻¹ 也在每個 subgroup 中，仍落在交集。</div></details><details><summary>Union 為何通常失敗？</summary><div>⟨2⟩∪⟨3⟩={{'{0,2,3,4}'}}，但 2+3=5 不在 union。Lattice 的 join 是「union 所生成的 subgroup」，不一定是 raw union。</div></details><details><summary>線條與層級的正式意義</summary><div>Lattice 以 inclusion 排序全部 subgroups。圖中直接連線表示中間沒有另一個 subgroup；上下位置是排版 convention，不表示距離或 multiplication。</div></details></section>
</article>`})
export class AlgebraV3SubgroupLatticeComponent{
 readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly selected=signal<LatticeId>('h2');
 readonly data=computed(()=>({g:{name:'ℤ₆',members:'{0,1,2,3,4,5}',above:'— top',below:'⟨2⟩, ⟨3⟩, {0}',reading:'全群包含所有 subgroups；它允許最多 effects。'},h2:{name:'⟨2⟩',members:'{0,2,4}',above:'ℤ₆',below:'{0}',reading:'它與 ⟨3⟩ 都在中層，但彼此不包含。'},h3:{name:'⟨3⟩',members:'{0,3}',above:'ℤ₆',below:'{0}',reading:'它與 ⟨2⟩ 是 incomparable branches，不是相乘關係。'},e:{name:'{0}',members:'identity only',above:'⟨2⟩, ⟨3⟩, ℤ₆',below:'— bottom',reading:'Trivial subgroup 被每一個 subgroup 包含。'}})[this.selected()]);
 relationTo(id:LatticeId):string{if(id===this.selected())return'CURRENT';const ancestors:{[K in LatticeId]:LatticeId[]}={g:[],h2:['g'],h3:['g'],e:['h2','h3','g']};if(ancestors[this.selected()].includes(id))return'CONTAINED BY';if(ancestors[id].includes(this.selected()))return'CONTAINS';return'UNRELATED';}
}
