import { Component, computed, signal } from '@angular/core';

const LOOP_NODES=[{label:'e',x:250,y:45},{label:'r',x:405,y:265},{label:'r²',x:95,y:265}] as const;

@Component({selector:'app-algebra-v3-relation-loop',standalone:true,template:`
  <article class="algebra-v3-lesson alg-ch8-lesson">
    <header class="hero"><p class="eyebrow">Abstract Algebra · 8.1</p><h2>Relation 是一條首尾相接的 action path</h2><p class="lede">Ch7 已把 word 當 path、element 當 endpoint。現在多問一步：若一條 nonempty path 回到 identity effect，它就在 Cayley graph 上畫出 closed loop，也能被寫成一條 relation。</p></header>
    <section class="prediction"><p class="kicker">先保留兩層資料</p><h3><code>r³=e</code> 是否表示三次 rotation 的執行歷史從未發生？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不是，只是 effect 為 e</button><button type="button" (click)="prediction.set(true)">是，歷史消失</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'relation 比較總 action，不會抹去曾走過 r、r² 的 path。':'對。word rrr 仍有三個 steps；只是 evaluation 後和 empty word 同一 endpoint。'}}</p>}</section>
    <section class="lab"><div class="lab-heading"><div><p class="kicker">Relation loop player</p><h3>一次按一個 r，直到 path 真正閉合</h3></div><p>舞台保留走過的 edges、目前 effect 與 action tape。第三步之後若繼續走，新的 word 仍要重新檢查 endpoint，不能只因曾經閉合過就永遠叫 relation。</p></div>
      <div class="control-row"><button type="button" class="primary" (click)="step()">執行一次 r</button><button type="button" (click)="steps.set(0)" [disabled]="steps()===0">重設為 empty word</button><button type="button" (click)="steps.set(3)">preset r³</button><button type="button" (click)="steps.set(4)">preset r⁴</button></div>
      <div class="stage loop-layout"><div class="loop-board"><svg viewBox="0 0 500 310" role="img" [attr.aria-label]="graphLabel()"><defs><marker id="loop-arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L8,3 z" fill="currentColor"/></marker></defs><path class="loop-edge" [class.traversed]="steps()>=1" d="M265 66 Q390 90 398 235"/><path class="loop-edge" [class.traversed]="steps()>=2" d="M375 270 Q250 325 125 270"/><path class="loop-edge" [class.traversed]="steps()>=3" d="M102 235 Q110 90 235 66"/>@for(node of nodes;track node.label;let index=$index){<g class="loop-node" [class.current]="currentIndex()===index"><circle [attr.cx]="node.x" [attr.cy]="node.y" r="28"/><text [attr.x]="node.x" [attr.y]="node.y+6">{{node.label}}</text></g>}</svg><div class="path-tape"><span>START e</span>@for(item of tape();track $index){<span>r → {{item}}</span>}@if(steps()===0){<span>ε · no steps</span>}</div></div><section class="loop-console" aria-live="polite"><p class="kicker">WORD r{{superscript(steps())}}</p><h4>目前 endpoint：{{currentLabel()}}</h4><p>{{reading()}}</p><div class="relation-stamp" [class.open]="!isRelation()">{{isRelation()?'✓ CLOSED LOOP · r'+superscript(steps())+' = e':'○ OPEN PATH · endpoint ≠ e'}}</div><div class="button-equation">word length = {{steps()}} · effect = {{currentLabel()}}</div></section></div>
    </section>
    <aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>nonempty word</span><i>evaluate</i><span>endpoint e</span><i>→</i><span>relation loop</span></div><p><strong>Relation 是 effect equality 的 path 版本。</strong>一條 word 若對應 identity action，就能視為可插入或刪除的 closed detour；但 word 本身與 empty history 仍是不同描述。</p></aside>
    <section class="transfer"><p class="kicker">Clock world</p><h3>每次前進一格，連按 12 次是否形成 identity relation？</h3><div class="choice-row"><button type="button" (click)="transfer.set(true)">形成 loop</button><button type="button" (click)="transfer.set(false)">不形成</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="!transfer()">{{transfer()?'對。12-step action 對每個 clock position 都回到原位，所以可寫 a¹²=e。':'從任何鐘點出發都回到同一鐘點；這是 whole-world identity effect。'}}</p>}</section>
    <section class="secondary"><p>SECONDARY LAYER</p><details><summary>Relation 的正式讀法</summary><div>對 generators 形成的 word w，若 evaluation 給出 identity element，就可寫 relation w=e。更一般也會寫 u=v；這等價於 uv⁻¹=e。</div></details><details><summary>為什麼只固定一個 state 不夠？</summary><div>Identity 是 whole-world action。Triangle reflection 可以固定頂點 A，卻交換 B、C；一個 state 沒動只說它是 fixed point，不能推出整個 action 是 e，也不能據此宣告 relation。</div></details><details><summary>由 r³=e 推出 r⁴=r</summary><div>r⁴=r³r=er=r。每個 equality 都替換相同 effect；這個 rewrite 動作會在下一節直接操作。</div></details></section>
  </article>
`})
export class AlgebraV3RelationLoopComponent{
  readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly steps=signal(0);readonly nodes=LOOP_NODES;
  readonly currentIndex=computed(()=>this.steps()%3);readonly currentLabel=computed(()=>['e','r','r²'][this.currentIndex()]);readonly isRelation=computed(()=>this.steps()>0&&this.currentIndex()===0);readonly tape=computed(()=>Array.from({length:this.steps()},(_,index)=>['r','r²','e'][index%3]));
  readonly reading=computed(()=>this.isRelation()?`走過 ${this.steps()} edges 後回到 origin；word 與 empty history 不同，但 effect 相同。`:this.steps()===0?'Empty word 從未離開 e；先執行一個 nonempty path，再檢查是否回來。':`Path 尚未閉合；現在不能把 r${this.superscript(this.steps())} 寫成 e。`);
  step(){this.steps.update(value=>value+1);}superscript(value:number){const digits='⁰¹²³⁴⁵⁶⁷⁸⁹';return String(value).split('').map(digit=>digits[+digit]).join('');}graphLabel(){return `三角形 rotation path，執行 ${this.steps()} 步，目前在 ${this.currentLabel()}`;}
}
