import { Component, computed, signal } from '@angular/core';

type RelationMode='none'|'r3'|'r4';

@Component({selector:'app-algebra-v3-presentation-folder',standalone:true,template:`
  <article class="algebra-v3-lesson alg-ch8-lesson">
    <header class="hero"><p class="eyebrow">Abstract Algebra · 8.4</p><h2>Generators 給走法；relations 決定哪些 paths 要折在一起</h2><p class="lede">只列一顆 button r，finite words 仍可無限延伸。再指定一條 loop relation，才知道哪些 powers 應視為同一 effect；presentation 是生成規則，不是預先列好的元素清單。</p></header>
    <section class="prediction"><p class="kicker">先找缺掉的資料</p><h3>只說「group 由 r 生成」，是否已唯一決定一個 finite group？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">沒有，還缺 relations</button><button type="button" (click)="prediction.set(true)">有</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'沒有 loop rule 時，r 的 powers 可一直代表新 effects；finite size 尚未被決定。':'對。r³=e 與 r⁴=e 使用同一 generator，卻把 word tape 分別折成 3 與 4 個 buckets。'}}</p>}</section>
    <section class="lab"><div class="lab-heading"><div><p class="kicker">Presentation folder</p><h3>同一段 power tape，套用不同 relation stamps</h3></div><p>左側固定顯示 r⁰ 到 r¹¹ 的 word viewport。切換 relation 後，每張卡重新計算 effect bucket；點任一 word 可追蹤它和哪些較短 words 被視為同一 action。</p></div>
      <div class="presentation-controls" role="group" aria-label="選擇施加在 generator r 上的 relation"><button type="button" [attr.aria-pressed]="mode()==='none'" (click)="selectMode('none')"><strong>⟨r | no finite relation⟩</strong><span>viewport 內每個 power 保持 distinct</span></button><button type="button" [attr.aria-pressed]="mode()==='r3'" (click)="selectMode('r3')"><strong>⟨r | r³=e⟩</strong><span>每三步 loop 折回 identity</span></button><button type="button" [attr.aria-pressed]="mode()==='r4'" (click)="selectMode('r4')"><strong>⟨r | r⁴=e⟩</strong><span>每四步 loop 折回 identity</span></button></div>
      <div class="stage fold-layout"><div class="word-viewport" aria-label="r 的前十二個 powers">@for(power of powers;track power){<button type="button" class="power-card" [class.selected]="selectedPower()===power" (click)="selectedPower.set(power)"><strong>{{powerLabel(power)}}</strong><span>→ {{effectLabel(effectOf(power))}}</span></button>}</div><section class="bucket-console" aria-live="polite"><p class="kicker">{{presentationLabel()}}</p><h4>{{bucketIds().length}} {{mode()==='none'?'visible effects in this viewport':'effect buckets'}}</h4><p>{{foldReading()}}</p><div class="effect-buckets">@for(bucket of bucketIds();track bucket){<div class="effect-bucket" [class.selected]="effectOf(selectedPower())===bucket"><strong>{{effectLabel(bucket)}}</strong><span>{{bucketWords(bucket)}}</span></div>}</div><div class="relation-stamp">selected {{powerLabel(selectedPower())}} → {{effectLabel(effectOf(selectedPower()))}}</div></section></div>
    </section>
    <aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>generators S</span><i>build words</i><span>relations R</span><i>fold paths</i><span>effects</span></div><p><strong>Presentation 把「如何走」與「哪些走法相同」分開壓縮。</strong>Generators 產生 word vocabulary；relations 指定合法 loops 與 rewrites，讓許多 descriptions 收進同一 element。</p></aside>
    <section class="transfer"><p class="kicker">Square rotations</p><h3><code>⟨r | r⁴=e⟩</code> 能否描述由 90° rotation 生成的四個 rotation effects？</h3><div class="choice-row"><button type="button" (click)="transfer.set(true)">可以</button><button type="button" (click)="transfer.set(false)">不可以</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="!transfer()">{{transfer()?'對。e、r、r²、r³ 是四個 buckets，r⁴ loop 回到 e，後續 powers 重複。':'四次 90° rotation 是 whole-world identity；這條 relation 正好折出四個 rotation effects。'}}</p>}</section>
    <section class="secondary"><p>SECONDARY LAYER</p><details><summary>Group presentation 的正式讀法</summary><div>記號 ⟨S | R⟩ 表示「由 S 中 symbols 生成，並要求 R 中 relations 成立」的群。完整形式建構會用 free group 再 quotient by the normal closure of R；本節只要求能可靠讀取 buttons 與 loop rules。</div></details><details><summary>Relations 會隱含更多 equalities</summary><div>從 r³=e 可推出 r⁴=r、r⁵=r²，也可在較長 context 中插入或刪除 r³。Presentation 不只承認字面列出的 equality，還承認由 group laws 與它們推得的所有 consequences。</div></details><details><summary>邊界：presentation 通常不唯一</summary><div>同一個 group 可以使用不同 generators 與不同 relation sets 描述；看起來相似的 presentations 也未必容易判定是否給出同一群。這裡的 model 展示分工，不宣稱一般辨識問題很簡單。</div></details></section>
  </article>
`})
export class AlgebraV3PresentationFolderComponent{
  readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly mode=signal<RelationMode>('r3');readonly selectedPower=signal(8);readonly powers=Array.from({length:12},(_,value)=>value);
  readonly period=computed(()=>this.mode()==='r3'?3:this.mode()==='r4'?4:null);readonly bucketIds=computed(()=>this.period()===null?this.powers:Array.from({length:this.period()!},(_,value)=>value));
  selectMode(mode:RelationMode){this.mode.set(mode);}
  effectOf(power:number){return this.period()===null?power:power%this.period()!;}powerLabel(power:number){return power===0?'r⁰ = ε':`r${this.superNumber(power)}`;}effectLabel(effect:number){return effect===0?'e':effect===1?'r':`r${this.superNumber(effect)}`;}
  bucketWords(bucket:number){return this.powers.filter(power=>this.effectOf(power)===bucket).map(power=>this.powerLabel(power).replace(' = ε','')).join(' · ');}
  presentationLabel(){return this.mode()==='none'?'⟨r | no finite relation⟩':this.mode()==='r3'?'⟨r | r³=e⟩':'⟨r | r⁴=e⟩';}
  foldReading(){if(this.mode()==='none')return '沒有 finite loop stamp；畫面只顯示前十二個 powers，word tape 本身仍向外延伸。';const power=this.selectedPower();const loops=Math.floor(power/this.period()!);const remainder=power%this.period()!;return `${this.powerLabel(power)} 包含 ${loops} 個完整 ${this.period()}-step loops，刪除後留下 ${this.effectLabel(remainder)}。`;}
  private superNumber(value:number){const digits='⁰¹²³⁴⁵⁶⁷⁸⁹';return String(value).split('').map(digit=>digits[+digit]).join('');}
}
