import { Component, computed, signal } from '@angular/core';

type WorldId='translations'|'triangle';
interface LaneState{firstAction:string;secondAction:string;start:string;middle:string;end:string;}

@Component({selector:'app-algebra-v3-order-swap',standalone:true,template:`
  <article class="algebra-v3-lesson alg-ch8-lesson">
    <header class="hero"><p class="eyebrow">Abstract Algebra · 8.3</p><h2>交換順序若仍同 endpoint，才得到額外 relation</h2><p class="lede">Associativity 只允許重新分組同一條 ordered tape；它從未允許交換 chips。Commutativity（交換律）必須由兩條相反順序的 paths 真正落到同一 whole-world effect 才成立。</p></header>
    <section class="prediction"><p class="kicker">先拆開兩種規則</p><h3>一個 operation 已知 associative，是否就能推出任意 <code>a·b=b·a</code>？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不能</button><button type="button" (click)="prediction.set(true)">能</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'括號規則不會交換 order；triangle rotation 與 reflection 的兩種順序就是反例。':'對。associativity 比較 (ab)c 與 a(bc)；commutativity 比較 ab 與 ba，是另一條 equality。'}}</p>}</section>
    <section class="lab"><div class="lab-heading"><div><p class="kicker">Order-swap comparator</p><h3>固定兩個 actions，只交換它們的執行順序</h3></div><p>兩條 lanes 同時顯示 start、第一步後的 state 與 final effect。Translations 用 coordinates；triangle symmetries 用三個 vertices 的完整 labeling，避免只追蹤一個點。</p></div>
      <div class="order-worlds" role="group" aria-label="選擇比較 action 順序的 world"><button type="button" [attr.aria-pressed]="world()==='translations'" (click)="world.set('translations')"><strong>Plane translations</strong><span>a = right，b = up</span></button><button type="button" [attr.aria-pressed]="world()==='triangle'" (click)="world.set('triangle')"><strong>Triangle symmetries</strong><span>a = rotation r，b = reflection f</span></button></div>
      <div class="stage order-layout"><section class="order-lane"><p class="kicker">PATH I · a THEN b</p><h4>{{laneAB().firstAction}} → {{laneAB().secondAction}}</h4><div class="state-sequence"><div><span>START</span><strong>{{laneAB().start}}</strong></div><i>→</i><div><span>AFTER {{laneAB().firstAction}}</span><strong>{{laneAB().middle}}</strong></div><i>→</i><div><span>END</span><strong>{{laneAB().end}}</strong></div></div><p>{{pathExplanation('ab')}}</p></section><section class="order-lane"><p class="kicker">PATH II · b THEN a</p><h4>{{laneBA().firstAction}} → {{laneBA().secondAction}}</h4><div class="state-sequence"><div><span>START</span><strong>{{laneBA().start}}</strong></div><i>→</i><div><span>AFTER {{laneBA().firstAction}}</span><strong>{{laneBA().middle}}</strong></div><i>→</i><div><span>END</span><strong>{{laneBA().end}}</strong></div></div><p>{{pathExplanation('ba')}}</p></section></div>
      <div class="order-verdict" [class.fail]="!sameEndpoint()" aria-live="polite">{{sameEndpoint()?'✓ SAME ENDPOINT — a and b commute in this comparison':'≠ DIFFERENT ENDPOINTS — swapping order changes the effect'}}</div>
    </section>
    <aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>a then b</span><i>compare endpoints</i><span>b then a</span><i>{{sameEndpoint()?'=':'≠'}}</i><span>{{sameEndpoint()?'commuting pair':'order matters'}}</span></div><p><strong>Commutativity 是一條需要證據的 path equality。</strong>某一 pair 的 square 能閉合，只能說這兩個 elements commute；要稱整個 group abelian，必須對所有 pairs 都成立。</p></aside>
    <section class="transfer"><p class="kicker">Invertible matrices</p><h3>矩陣都可逆，是否就保證任意 A、B 滿足 AB=BA？</h3><div class="choice-row"><button type="button" (click)="transfer.set(false)">不保證</button><button type="button" (click)="transfer.set(true)">保證</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="transfer()">{{transfer()?'inverse wire 與 order-swap equality 無關；GL₂ 中可以找到不交換的 pair。':'對。例如兩個 shear matrices 可逆，但 AB 與 BA 的 diagonal entries 交換，結果不同。'}}</p>}</section>
    <section class="secondary"><p>SECONDARY LAYER</p><details><summary>Commuting pair 與 abelian group</summary><div>若 ab=ba，稱 a、b commute。若 group G 中每一對 elements 都 commute，G 稱為 abelian group。單一 commuting pair 不是全稱證明；單一 noncommuting pair 則足以推翻 abelian。</div></details><details><summary>具體 matrix counterexample</summary><div>取 A=[[1,1],[0,1]]、B=[[1,0],[1,1]]。兩者 determinant 都是 1，因而 invertible；但 AB=[[2,1],[1,1]]，BA=[[1,1],[1,2]]，所以 AB≠BA。</div></details><details><summary>Notation direction 提醒</summary><div>不同教材對 transformation product 的「先做哪個」可能採相反 convention。本頁刻意寫「a then b」而不靠 ab 猜方向；判斷 commute 時，兩種 convention 都是在比較交換順序後的 total mappings 是否相等。</div></details></section>
  </article>
`})
export class AlgebraV3OrderSwapComponent{
  readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly world=signal<WorldId>('translations');
  readonly laneAB=computed(()=>this.world()==='translations'?{firstAction:'right a',secondAction:'up b',start:'(0,0)',middle:'(1,0)',end:'(1,1)'}:this.triangleLane('r','f'));
  readonly laneBA=computed(()=>this.world()==='translations'?{firstAction:'up b',secondAction:'right a',start:'(0,0)',middle:'(0,1)',end:'(1,1)'}:this.triangleLane('f','r'));
  readonly sameEndpoint=computed(()=>this.laneAB().end===this.laneBA().end);
  pathExplanation(path:'ab'|'ba'){if(this.world()==='translations')return path==='ab'?'水平與垂直 displacement 相加後是同一 vector。':'只換 intermediate corner，net displacement 不變。';return '字串依序記錄 top / right / left 三個 vertex positions 的 labels。';}
  private triangleLane(first:'r'|'f',second:'r'|'f'):LaneState{const start=['A','B','C'];const apply=(state:string[],action:'r'|'f')=>action==='r'?[state[2],state[0],state[1]]:[state[0],state[2],state[1]];const middle=apply(start,first);const end=apply(middle,second);return{firstAction:first==='r'?'rotation r':'reflection f',secondAction:second==='r'?'rotation r':'reflection f',start:`top/right/left · ${start.join('')}`,middle:`top/right/left · ${middle.join('')}`,end:`top/right/left · ${end.join('')}`};}
}
