import { Component, computed, signal } from '@angular/core';

type Token='r'|'e';
interface RewriteEntry{rule:string;text:string;}

@Component({selector:'app-algebra-v3-relation-rewrite',standalone:true,template:`
  <article class="algebra-v3-lesson alg-ch8-lesson">
    <header class="hero"><p class="eyebrow">Abstract Algebra · 8.2</p><h2>刪掉 closed loop，word 變短，endpoint 不動</h2><p class="lede">已知 <code>r³=e</code>，連續三個 r 就是一段回到目前位置的 detour。化簡不是把相同字母隨便擦掉；每次 rewrite 都必須引用 relation 或 identity law，並保住同一個 total effect。</p></header>
    <section class="prediction"><p class="kicker">先預測 endpoint</p><h3>已知 <code>r³=e</code>，能把 <code>r⁸</code> rewrite 成 <code>r²</code> 嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(true)">能，刪兩圈</button><button type="button" (click)="prediction.set(false)">不能</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="!prediction()">{{prediction()?'對。8=3+3+2；兩段 r³ 都是 identity detour，剩下 r²。':'r⁸=r³r³r²=eer²=r²；每一步都保留 evaluation。'}}</p>}</section>
    <section class="lab"><div class="lab-heading"><div><p class="kicker">Relation rewrite bench</p><h3>先折疊 rrr → e，再用 identity law 刪 e</h3></div><p>橘框標出下一段可用 relation 的 window。折疊與刪除分成兩個 buttons，讓「relation equality」和「identity 不改 effect」不會被藏成一步魔術。</p></div>
      <div class="control-row"><button type="button" (click)="load(4)">載入 r⁴</button><button type="button" class="primary" (click)="load(8)">載入 r⁸</button><button type="button" (click)="load(11)">載入 r¹¹</button></div>
      <div class="control-row"><button type="button" class="primary" (click)="collapseLoop()" [disabled]="loopStart()<0">套用 rrr → e</button><button type="button" (click)="eraseIdentity()" [disabled]="!tokens().includes('e')">套用 ex=xe=x</button><button type="button" (click)="reset()" [disabled]="isReset()">回到原 word</button></div>
      <div class="stage rewrite-layout"><div class="rewrite-bench"><p class="kicker">CURRENT WORD</p><div class="rewrite-tape" aria-label="目前 action word">@for(token of tokens();track $index){<span class="rewrite-chip" [class.loop-window]="inLoopWindow($index)" [class.identity]="token==='e'">{{token}}</span>}@if(tokens().length===0){<span class="rewrite-chip identity">ε</span>}</div><div class="button-equation">{{wordLabel()}} · {{tokens().length}} visible chips</div><div class="rewrite-history">@for(entry of history();track $index){<div><span>{{entry.rule}}</span><strong>{{entry.text}}</strong></div>}</div></div><section class="endpoint-console" aria-live="polite"><p class="kicker">EFFECT CHECK</p><h4>原 word r{{superNumber(originalLength())}} 與目前 word</h4><div class="effect-triad">@for(label of effectLabels;track $index){<div [class.current]="currentEffect()===$index"><strong>{{$index===0?'✓ ':'○ '}}{{label}}</strong></div>}</div><div class="relation-stamp">✓ ENDPOINT INVARIANT · effect 始終是 {{effectLabels[currentEffect()]}}</div><p>{{rewriteReading()}}</p></section></div>
    </section>
    <aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>u · loop · v</span><i>loop = e</i><span>u · e · v</span><i>identity</i><span>u · v</span></div><p><strong>Relation 是可以放進任何相同 context 的合法 path rewrite。</strong>它改變描述長度，不改變 before/after action；因此每一步都能用 equality 解釋，而不是靠字形猜消去。</p></aside>
    <section class="transfer"><p class="kicker">Modulo 5 addition</p><h3>連按七次 +1，是否能刪掉一個五步 loop，留下兩次 +1？</h3><div class="choice-row"><button type="button" (click)="transfer.set(true)">可以</button><button type="button" (click)="transfer.set(false)">不可以</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="!transfer()">{{transfer()?'對。五次 +1 回到 0，是 identity detour；七步與兩步同落在 residue 2。':'relation 是五步回到 identity，所以可以在七步 path 中刪掉它。'}}</p>}</section>
    <section class="secondary"><p>SECONDARY LAYER</p><details><summary>Context rewrite 的正式說法</summary><div>若 u=v 是已知 equality，對任意 words x、y 都可把 xuy 改寫成 xvy，因為 group operation 與 equality 相容。本頁使用 u=rrr、v=e。</div></details><details><summary>完整 equality chain：r⁸=r²</summary><div>r⁸=r³r³r²=eer²=r²。第一個 equality 只是重新分組；第二個兩次使用 r³=e；第三個使用 identity law。</div></details><details><summary>邊界：shortest word 不一定唯一</summary><div>合法 reduction 能保證 effect 不變，卻不保證每套 relations 都有簡單、唯一的 canonical form。這一節只要求每一步可追溯，不把 general word problem 假裝成已解決。</div></details></section>
  </article>
`})
export class AlgebraV3RelationRewriteComponent{
  readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly originalLength=signal(8);readonly tokens=signal<readonly Token[]>(Array(8).fill('r'));readonly history=signal<readonly RewriteEntry[]>([{rule:'LOAD',text:'r⁸ · effect r²'}]);readonly effectLabels=['e','r','r²'] as const;
  readonly loopStart=computed(()=>{const word=this.tokens();for(let index=0;index<=word.length-3;index++)if(word[index]==='r'&&word[index+1]==='r'&&word[index+2]==='r')return index;return-1;});readonly currentEffect=computed(()=>this.tokens().filter(token=>token==='r').length%3);readonly isReset=computed(()=>this.tokens().length===this.originalLength()&&this.tokens().every(token=>token==='r'));
  load(length:number){this.originalLength.set(length);this.reset();}reset(){this.tokens.set(Array(this.originalLength()).fill('r'));this.history.set([{rule:'LOAD',text:`r${this.superNumber(this.originalLength())} · effect ${this.effectLabels[this.originalLength()%3]}`}]);}
  collapseLoop(){const start=this.loopStart();if(start<0)return;this.tokens.update(word=>[...word.slice(0,start),'e',...word.slice(start+3)]);this.history.update(entries=>[...entries,{rule:'RELATION r³=e',text:'把一段 rrr closed loop 折成 identity chip e'}]);}
  eraseIdentity(){const index=this.tokens().indexOf('e');if(index<0)return;this.tokens.update(word=>[...word.slice(0,index),...word.slice(index+1)]);this.history.update(entries=>[...entries,{rule:'IDENTITY LAW',text:'刪除 e；相鄰 composite 的 effect 不變'}]);}
  inLoopWindow(index:number){return this.loopStart()>=0&&index>=this.loopStart()&&index<this.loopStart()+3;}wordLabel(){return this.tokens().length?this.tokens().join(' · '):'ε';}superNumber(value:number){const digits='⁰¹²³⁴⁵⁶⁷⁸⁹';return String(value).split('').map(digit=>digits[+digit]).join('');}
  rewriteReading(){if(this.loopStart()>=0)return '下一段橘框 rrr 可引用 relation 折成 e；先不要直接刪字母。';if(this.tokens().includes('e'))return '目前沒有 rrr，但還有 identity chip；可用 identity law 移除。';return '目前 word 已沒有可見 rrr loop；它是這條 rewrite path 的 reduced result。';}
}
