import { Component, computed, signal } from '@angular/core';

@Component({selector:'app-algebra-v3-divisor-filter',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch13-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 13.4</p><h2>Divides 是通行證，不是存在證明</h2><p class="lede">Lagrange 給的是 necessary condition：若 H 已存在，|H| 必須整除 |G|。把箭頭倒過來會犯錯；整除只能讓 candidate 留在場上，不能憑空建出 subgroup。</p></header>
<section class="prediction"><p class="kicker">先判斷</p><h3>d divides |G|，就能立刻宣稱 G 有 order d 的 subgroup 嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不能</button><button type="button" (click)="prediction.set(true)">能</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'Theorem says subgroup ⇒ divisor，不是 divisor ⇒ subgroup。':'對。Passing the filter means「尚未被 Lagrange 排除」。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Divisor possibility filter</p><h3>輸入 group size 與 candidate size，看 theorem 真正允許說什麼</h3></div><p>REJECTED 與 NOT RULED OUT 都附文字；綠燈不使用 PROVED 或 EXISTS。</p></div><div class="filter-controls"><label>|G| <input type="range" min="2" max="24" [value]="n()" (input)="setGroupSize(+$any($event.target).value)"><strong>{{n()}}</strong></label><label>candidate d <input type="range" min="1" [max]="n()" [value]="d()" (input)="d.set(+$any($event.target).value)"><strong>{{d()}}</strong></label></div><div class="stage filter-layout"><div class="division-machine"><span>{{n()}}</span><i>÷</i><span>{{d()}}</span><i>=</i><strong>{{quotientReading()}}</strong><div class="remainder-track"><b [style.width.%]="remainderPercent()"></b></div><small>remainder {{remainder()}}</small></div><section class="count-console" aria-live="polite"><p class="kicker">LAGRANGE FILTER</p><div class="filter-verdict" [class.rejected]="!divides()">{{verdict()}}</div><p>{{explanation()}}</p><div class="logic-arrow"><span>H≤G</span><b>⇒</b><span>|H| divides |G|</span><strong>one-way theorem</strong></div></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>fails divide</span><i>→ reject</i><span>passes divide</span><i>→ investigate</i></div><p><strong>Necessary conditions 擅長排除，不擅長創造。</strong>不整除時結論確定；整除時保持誠實，只能說「仍有可能」。</p></aside>
<section class="transfer"><p class="kicker">語言精度</p><h3>看到 4 divides 12，最強的合法結論是什麼？</h3><div class="choice-row"><button type="button" (click)="transfer.set(true)">order 4 subgroup 尚未被排除</button><button type="button" (click)="transfer.set(false)">一定存在 order 4 subgroup</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="!transfer()">{{transfer()?'對。還要建造 subgroup 或使用額外 theorem。':'整除只是 necessary，不是 sufficient。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>Converse 為何不是 Lagrange theorem？</summary><div>Lagrange 只從「H 已是 subgroup」推出大小限制。一般有限群不保證每個 divisor 都對應 subgroup；例如 A₄ 的 order 是 12，但沒有 order 6 subgroup。這個反例的結構證明留待後續工具成熟後回看。</div></details><details><summary>Cauchy theorem 的精確預告</summary><div>若 prime p divides |G|，則 G 確實有 order p element。這是額外且更強的 existence theorem，不能從 Lagrange 的 converse 猜出；Ch29 才正式建立。</div></details></section></article>`})
export class AlgebraV3DivisorFilterComponent{
 readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly n=signal(12);readonly d=signal(5);readonly remainder=computed(()=>this.n()%this.d());readonly divides=computed(()=>this.remainder()===0);
 setGroupSize(value:number):void{this.n.set(value);if(this.d()>value)this.d.set(value);}
 verdict():string{return this.divides()?'○ NOT RULED OUT · STILL NEED AN EXISTENCE ARGUMENT':'× REJECTED · CANNOT BE A SUBGROUP ORDER';}
 explanation():string{return this.divides()?`${this.d()} divides ${this.n()}，所以 Lagrange 沒有反對；但目前沒有建出任何 subgroup。`:`若 H 的大小是 ${this.d()}，完整 tiles 會留下 remainder ${this.remainder()}，不可能 partition ${this.n()} elements。`;}
 quotientReading():string{return this.divides()?String(this.n()/this.d()):`${Math.floor(this.n()/this.d())} r ${this.remainder()}`;}remainderPercent():number{return 100*this.remainder()/this.d();}
}
