import { Component, computed, signal } from '@angular/core';

interface IndexPreset{generator:number;members:number[];cosets:number[][];}
@Component({selector:'app-algebra-v3-index-lens',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch13-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 13.2</p><h2>Index 不是新運算：它只是在數 distinct coset tiles</h2><p class="lede">固定 ambient group ℤ₁₂，切換不同 subgroups。每塊越大，需要的 tiles 越少；符號 [G:H] 只是把「有幾塊」命名起來。</p></header>
<section class="prediction"><p class="kicker">先判斷</p><h3>[G:H] 表示 H 裡有幾個 elements 嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不是，是 cosets 數</button><button type="button" (click)="prediction.set(true)">是</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'|H| 是 tile size；[G:H] 是 tile count。兩者相乘才是 |G|。':'對。Index 量的是 H 在 G 中有多少 distinct translates。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Index lens</p><h3>改變 H，同步看 tile size 與 tile count</h3></div><p>每個 box 是一個 coset；box 內列出 members，避免只從面積或顏色猜大小。</p></div><div class="index-picker" role="group" aria-label="選擇 ℤ₁₂ 的 subgroup">@for(key of keys;track key){<button type="button" [attr.aria-pressed]="selected()===key" (click)="selected.set(key)">H=⟨{{key}}⟩</button>}</div><div class="stage index-layout"><div class="coset-grid" [style.--coset-count]="preset().cosets.length">@for(tile of preset().cosets;track $index){<section><span>TILE {{$index+1}}</span><strong>{{'{'+tile.join(',')+'}'}}</strong></section>}</div><section class="count-console" aria-live="polite"><p class="kicker">INDEX READOUT</p><div class="index-measures"><div><span>|G|</span><strong>12</strong><small>whole group</small></div><div><span>|H|</span><strong>{{preset().members.length}}</strong><small>per tile</small></div><div><span>[G:H]</span><strong>{{preset().cosets.length}}</strong><small>tiles</small></div></div><div class="lagrange-verdict">12 = {{preset().members.length}} × {{preset().cosets.length}}</div><p>{{preset().members.length}} elements per tile；{{preset().cosets.length}} distinct translates cover ℤ₁₂。</p></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>|H| grows</span><i>→</i><span>[G:H] shrinks</span></div><p><strong>Index 是 subgroup 在 ambient group 中的「平移副本數」。</strong>它不是 H 的大小，也不是一個需要另外想像的抽象除法。</p></aside>
<section class="transfer"><p class="kicker">讀圖</p><h3>ℤ₁₂ 中 H=⟨3⟩ 的 order 與 index 分別是多少？</h3><div class="choice-row"><button type="button" (click)="transfer.set(true)">|H|=4，[G:H]=3</button><button type="button" (click)="transfer.set(false)">|H|=3，[G:H]=4</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="!transfer()">{{transfer()?'對。⟨3⟩={0,3,6,9}，每塊四點，共三塊。':'Generator 3 不代表 subgroup size 是 3。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>Index 的正式定義</summary><div>[G:H] 是 H 在 G 中 distinct left cosets 的 cardinality。有限情形 [G:H]=|G|/|H|；定義本身不依賴先做除法。</div></details></section></article>`})
export class AlgebraV3IndexLensComponent{
 readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly selected=signal(3);readonly keys=[1,2,3,4,6,0];
 readonly preset=computed<IndexPreset>(()=>this.makePreset(this.selected()));
 private makePreset(generator:number):IndexPreset{const members:number[]=[];let x=0;do{members.push(x);x=(x+generator)%12;}while(x!==0);const unseen=new Set(Array.from({length:12},(_,i)=>i));const cosets:number[][]=[];while(unseen.size){const representative=Math.min(...unseen);const tile=members.map(h=>(representative+h)%12).sort((a,b)=>a-b);cosets.push(tile);tile.forEach(value=>unseen.delete(value));}return{generator,members,cosets};}
}
