import { Component, computed, signal } from '@angular/core';

@Component({selector:'app-algebra-v3-element-cycle-tiler',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch13-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 13.3</p><h2>Element order 會整除 group order，因為它自己就是一塊 subgroup tile</h2><p class="lede">Ch9 的 repeated-action cycle 現在接上 Ch12：a 的 powers 形成 ⟨a⟩，其大小正是 ord(a)。既然 ⟨a⟩≤G，它的 cosets 必須以完整 cycle tiles 鋪滿 G。</p></header>
<section class="prediction"><p class="kicker">先預測</p><h3>12-element group 中可能有 order 5 的 element 嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不可能</button><button type="button" (click)="prediction.set(true)">可能</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'Order 5 會生成大小 5 的 subgroup，但 5 不能用完整 tiles 鋪滿 12。':'對。Lagrange applied to ⟨a⟩ gives ord(a) divides |G|。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Element-cycle tiler</p><h3>選 a：先走完 cycle，再看它如何鋪群</h3></div><p>模型使用 additive ℤ₁₂。每個 tile 都是 generated subgroup ⟨a⟩ 的 translate。</p></div><div class="element-picker" role="group" aria-label="選擇 ℤ₁₂ element">@for(value of candidates;track value){<button type="button" [attr.aria-pressed]="a()===value" (click)="a.set(value)">a={{value}}</button>}</div><div class="stage cycle-tiler-layout"><div><div class="cycle-track">@for(value of orbit();track value;let index=$index){<span>{{value}}<small>{{index===0?'IDENTITY':index+' presses'}}</small></span>}<b>↺ first return</b></div><div class="cycle-tiles">@for(tile of cosets();track $index){<section><small>translate {{$index+1}}</small><strong>{{'{'+tile.join(',')+'}'}}</strong></section>}</div></div><section class="count-console" aria-live="polite"><p class="kicker">ORDER → TILE SIZE</p><div class="index-measures"><div><span>ord(a)</span><strong>{{orbit().length}}</strong><small>|⟨a⟩|</small></div><div><span>tiles</span><strong>{{cosets().length}}</strong><small>[G:⟨a⟩]</small></div><div><span>|G|</span><strong>12</strong><small>whole</small></div></div><div class="lagrange-verdict">{{orbit().length}} × {{cosets().length}} = 12 · therefore {{orbit().length}} ∣ 12</div><p>Repeated action 的 first-return time，現在變成一個合法 subgroup 的 tile size。</p></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>cycle of a</span><i>=</i><span>⟨a⟩ tile</span><i>→</i><span>ord(a) ∣ |G|</span></div><p><strong>Element-order corollary 是 Lagrange 的直接應用。</strong>不是每個 divisor 都必然出現為 element order；但任何實際出現的 order 都必須整除 group order。</p></aside>
<section class="transfer"><p class="kicker">排除</p><h3>10-element group 能有 order 4 的 element 嗎？</h3><div class="choice-row"><button type="button" (click)="transfer.set(false)">不能</button><button type="button" (click)="transfer.set(true)">能</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="transfer()">{{transfer()?'4 不整除 10；大小 4 的 generated subgroup 無法鋪滿 group。':'對。這是必要條件的可靠排除。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>Corollary proof</summary><div>⟨a⟩ 是 G 的 subgroup，且 |⟨a⟩|=ord(a)。Lagrange theorem 給 |⟨a⟩| divides |G|，所以 ord(a) divides |G|。</div></details><details><summary>為何 a^|G|=e？</summary><div>寫 |G|=k·ord(a)。則 a^|G|=(a^ord(a))^k=e^k=e。</div></details></section></article>`})
export class AlgebraV3ElementCycleTilerComponent{
 readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly a=signal(3);readonly candidates=[0,1,2,3,4,6];
 readonly orbit=computed(()=>{const values:number[]=[];let x=0;do{values.push(x);x=(x+this.a())%12;}while(x!==0);return values;});
 readonly cosets=computed(()=>{const unseen=new Set(Array.from({length:12},(_,i)=>i));const tiles:number[][]=[];while(unseen.size){const r=Math.min(...unseen);const tile=this.orbit().map(x=>(r+x)%12).sort((a,b)=>a-b);tiles.push(tile);tile.forEach(x=>unseen.delete(x));}return tiles;});
}
