import { Component, computed, signal } from '@angular/core';
import { D3_ELEMENTS, D3Element, label, multiply } from '../algebra-v3-ch16/d3-model';
@Component({selector:'app-algebra-v3-canonical-projection',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch17-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 17.3</p><h2>Canonical projection 沒有發明新規則：它只把 action 丟進自己的 bucket</h2><p class="lede">π:D₃→D₃/R 定義為 π(g)=gR。它天然 surjective，kernel 正是 R；normality 讓上方先合成與下方先壓縮得到同一桶。</p></header>
<section class="prediction"><p class="kicker">先預測</p><h3>π 的 image 可能漏掉某個 quotient coset 嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不會</button><button type="button" (click)="prediction.set(true)">可能</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'每個 coset gR 本來就由 g 映到，projection 自動覆蓋。':'對。Quotient elements 的命名已內建 preimage。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Canonical projection square</p><h3>選 a、b，同時跑兩條 pipeline</h3></div><p>上路在 D₃ 合成後投影；下路先投影，再用 quotient operation 合成 buckets。</p></div><div class="projection-controls"><label>a <select [value]="a()" (change)="a.set(+$any($event.target).value)">@for(item of elements;track item){<option [value]="item">{{label(item)}}</option>}</select></label><label>b <select [value]="b()" (change)="b.set(+$any($event.target).value)">@for(item of elements;track item){<option [value]="item">{{label(item)}}</option>}</select></label></div><div class="stage projection-stage"><section class="projection-square"><div><span>D₃</span><strong>({{label(a())}}, {{label(b())}})</strong></div><i>multiply</i><div><span>D₃</span><strong>{{label(product())}}</strong></div><b>π × π ↓</b><b>↓ π</b><div><span>D₃/R</span><strong>({{bucketLabel(a())}}, {{bucketLabel(b())}})</strong></div><i>quotient multiply</i><div><span>D₃/R</span><strong>{{quotientProductLabel()}}</strong></div></section><section class="projection-console"><p class="kicker">TWO PATHS</p><div><span>π(ab)</span><strong>{{bucketLabel(product())}}</strong></div><div><span>π(a)π(b)</span><strong>{{quotientProductLabel()}}</strong></div><div class="map-verdict">✓ COMMUTES · HOMOMORPHISM</div><p>π 忘掉 exact pose，但保留 bucket composition。</p></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>D₃</span><i>π · forget within-coset detail</i><span>D₃/R</span></div><p><strong>Canonical projection 是 quotient 隨附的自然壓縮 map。</strong>它的 kernel=R、image=D₃/R；這會在下一章成為 general compression blueprint 的一半。</p></aside>
<section class="transfer"><p class="kicker">遷移</p><h3>一般 G/N 的 canonical projection kernel 是什麼？</h3><div class="choice-row"><button type="button" (click)="transfer.set(true)">N</button><button type="button" (click)="transfer.set(false)">整個 G</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="!transfer()">{{transfer()?'對。π(g)=N 恰在 g∈N 時成立。':'只有落入 identity coset N 的 elements 才在 kernel。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>Quotient operation</summary><div>(aN)(bN)=abN。N normal 保證這個結果與 a、b 的 representative choices 無關。</div></details><details><summary>Projection 的三個性質</summary><div>π(ab)=abN=(aN)(bN)；每個 aN 都由 a 抵達，所以 π surjective；π(a)=N iff a∈N，所以 ker π=N。</div></details></section></article>`})
export class AlgebraV3CanonicalProjectionComponent{readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly a=signal(1);readonly b=signal(3);readonly elements=D3_ELEMENTS;readonly product=computed(()=>multiply(this.a() as D3Element,this.b() as D3Element));label=(item:number)=>label(item as D3Element);bucket(item:number):number{return item<3?0:1;}bucketLabel(item:number):string{return this.bucket(item)===0?'R':'F';}quotientProductLabel():string{return (this.bucket(this.a())^this.bucket(this.b()))===0?'R':'F';}}
