import { Component, computed, signal } from '@angular/core';
import { D3Element, label, multiply, setLabel } from '../algebra-v3-ch16/d3-model';
type Mode='normal'|'nonnormal';
@Component({selector:'app-algebra-v3-representative-swap',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch17-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 17.2</p><h2>Well-defined 的意思：換 representatives，product bucket 不能跟著變</h2><p class="lede">公式 (aH)(bH)=abH 看似簡單，但 a、b 只是桶內代表。若同兩個 input buckets 能算出不同 output bucket，operation 根本沒有定義成功。</p></header>
<section class="prediction"><p class="kicker">先判斷</p><h3>只要每個 coset 挑一個固定代表，是否就能掩蓋不一致？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不能</button><button type="button" (click)="prediction.set(true)">可以</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'Operation 應屬於 buckets 本身，不能依賴偷偷固定的命名慣例。':'對。任意合法 representative 都必須給同一 bucket。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Representative swap bench</p><h3>固定 input buckets，只替換桶內代表</h3></div><p>Normal R 與 non-normal M 使用同一張 test bench；SAME／SPLIT 直接顯示結果。</p></div><div class="mode-picker" role="group" aria-label="選擇 quotient candidate"><button type="button" [attr.aria-pressed]="mode()==='normal'" (click)="selectMode('normal')">D₃/R · NORMAL</button><button type="button" [attr.aria-pressed]="mode()==='nonnormal'" (click)="selectMode('nonnormal')">D₃/M · NOT NORMAL</button></div><div class="stage representative-stage"><section class="bucket-inputs"><article><span>INPUT BUCKET A</span><strong>{{bucketLabel(inputA())}}</strong><div>@for(item of buckets()[inputA()];track item){<button type="button" [attr.aria-pressed]="repA()===item" (click)="repA.set(item)">{{label(item)}}</button>}</div></article><i>×</i><article><span>INPUT BUCKET B</span><strong>{{bucketLabel(inputB())}}</strong><div>@for(item of buckets()[inputB()];track item){<button type="button" [attr.aria-pressed]="repB()===item" (click)="repB.set(item)">{{label(item)}}</button>}</div></article></section><section class="product-track" aria-live="polite"><div><span>RAW PRODUCT</span><strong>{{label(repA())}}·{{label(repB())}}={{label(product())}}</strong></div><i>lands in</i><div><span>OUTPUT BUCKET</span><strong>{{bucketLabel(productBucket())}}</strong></div></section><section class="representative-console"><p class="kicker">BASELINE {{baselineLabel()}}</p><button type="button" (click)="tryAlternative()">換另一組 representatives</button><div class="map-verdict" [class.fail]="!stable()">{{stable()?'✓ SAME OUTPUT BUCKET · WELL-DEFINED':'× DIFFERENT OUTPUT BUCKET · AMBIGUOUS'}}</div><p>{{reading()}}</p></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>same input cosets</span><i>any representatives</i><span>same output coset</span></div><p><strong>Normality 的工作，就是把 representative noise 關在原 buckets 裡。</strong>若 noise 能改變 product bucket，quotient operation 就不是 function。</p></aside>
<section class="transfer"><p class="kicker">遷移</p><h3>「Well-defined」是在檢查答案是否存在，還是是否不依賴表示法？</h3><div class="choice-row"><button type="button" (click)="transfer.set(true)">不依賴表示法</button><button type="button" (click)="transfer.set(false)">只要存在一個答案</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="!transfer()">{{transfer()?'對。同一 abstract input 的不同 representations 必須給同一 output。':'存在但不唯一於 representation，仍不是合法 function。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>Representative independence proof</summary><div>若 a'=ah₁、b'=bh₂，則 a'b'=ab(b⁻¹h₁b)h₂。H normal 使 b⁻¹h₁b∈H，因此 a'b'H=abH。</div></details><details><summary>Non-normal witness</summary><div>對 M={{'{e,s}'}}，同一 bucket rM 的 representatives r、rs 給 r·r=r²∈r²M，但 (rs)(rs)=e∈M，product bucket 分岔。</div></details></section></article>`})
export class AlgebraV3RepresentativeSwapComponent{readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly mode=signal<Mode>('normal');readonly inputA=signal(1);readonly inputB=signal(1);readonly repA=signal<D3Element>(3);readonly repB=signal<D3Element>(3);readonly buckets=computed<D3Element[][]>(()=>this.mode()==='normal'?[[0,1,2],[3,4,5]]:[[0,3],[1,4],[2,5]]);readonly product=computed(()=>multiply(this.repA(),this.repB()));readonly productBucket=computed(()=>this.findBucket(this.product()));label=label;selectMode(mode:Mode):void{this.mode.set(mode);this.inputA.set(1);this.inputB.set(1);const first=this.buckets()[1][0];this.repA.set(first);this.repB.set(first);}findBucket(item:D3Element):number{return this.buckets().findIndex(bucket=>bucket.includes(item));}bucketLabel(index:number):string{return `${this.mode()==='normal'?['R','F'][index]:['M','rM','r²M'][index]} ${setLabel(this.buckets()[index])}`;}baselineProduct():D3Element{return multiply(this.buckets()[this.inputA()][0],this.buckets()[this.inputB()][0]);}baselineBucket():number{return this.findBucket(this.baselineProduct());}baselineLabel():string{return `${label(this.buckets()[this.inputA()][0])}·${label(this.buckets()[this.inputB()][0])} → ${this.bucketLabel(this.baselineBucket())}`;}stable():boolean{return this.productBucket()===this.baselineBucket();}tryAlternative():void{this.repA.set(this.buckets()[this.inputA()][1]??this.buckets()[this.inputA()][0]);this.repB.set(this.buckets()[this.inputB()][1]??this.buckets()[this.inputB()][0]);}reading():string{return this.stable()?'Representative 改變只改 raw product，不改 quotient answer。':'同一對 input buckets 產生兩個 output buckets；不能定義 quotient group。';}}
