import { Component, computed, signal } from '@angular/core';
import { D3_ELEMENTS, D3Element, label } from '../algebra-v3-ch16/d3-model';
type Question='parity'|'exact';
@Component({selector:'app-algebra-v3-information-dashboard',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch17-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 17.4</p><h2>Quotient 不是單純變小；它精確決定哪些問題仍能回答</h2><p class="lede">D₃/R 保留「orientation 是否 flipped」，遺忘 exact rotation 或 reflection axis。資訊是否 survive，要看同一 bucket 內所有 raw states 是否給相同答案。</p></header>
<section class="prediction"><p class="kicker">先判斷</p><h3>知道 quotient state=F，能否推出原 action 一定是 s？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不能</button><button type="button" (click)="prediction.set(true)">能</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'F 同時代表 s、rs、r²s；exact axis 已被刪除。':'對。Quotient 只保證發生 reflection。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Information dashboard</p><h3>選 raw action 與問題，檢查答案能否只靠 bucket 決定</h3></div><p>若同桶 members 對問題給不同答案，就明確標記 LOST。</p></div><div class="information-controls"><div role="group" aria-label="選擇 raw action">@for(item of elements;track item){<button type="button" [attr.aria-pressed]="selected()===item" (click)="selected.set(item)">{{label(item)}}</button>}</div><div role="group" aria-label="選擇問題"><button type="button" [attr.aria-pressed]="question()==='parity'" (click)="question.set('parity')">有沒有 reflection？</button><button type="button" [attr.aria-pressed]="question()==='exact'" (click)="question.set('exact')">exact action 是什麼？</button></div></div><div class="stage information-stage"><section class="information-pipeline"><article><span>RAW STATE</span><strong>{{label(selected())}}</strong><small>exact detail available</small></article><i>π →</i><article><span>QUOTIENT STATE</span><strong>{{bucketLabel()}}</strong><small>possible: {{possibilities()}}</small></article></section><section class="question-console" aria-live="polite"><p class="kicker">QUESTION TEST</p><h3>{{questionText()}}</h3><div class="answer-grid"><div><span>RAW ANSWER</span><strong>{{rawAnswer()}}</strong></div><div><span>FROM BUCKET ALONE</span><strong>{{quotientAnswer()}}</strong></div></div><div class="map-verdict" [class.fail]="!survives()">{{survives()?'✓ KEPT · BUCKET DETERMINES ANSWER':'× LOST · BUCKET HAS MULTIPLE ANSWERS'}}</div><p>{{reading()}}</p></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>exact pose</span><i>discarded</i><span>reflection parity</span><i>kept</i></div><p><strong>Quotient 是有目的的 information compression。</strong>能在每個 coset 上保持 constant 的觀察才會 survive；桶內會變動的 detail 永久無法從 quotient 還原。</p></aside>
<section class="transfer"><p class="kicker">遷移</p><h3>一個 function f:G→X 能只靠 quotient G/N 定義，直覺上需要什麼？</h3><div class="choice-row"><button type="button" (click)="transfer.set(true)">f 在每個 coset 上 constant</button><button type="button" (click)="transfer.set(false)">f 必須 injective</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="!transfer()">{{transfer()?'對。被 quotient 合併的 inputs 必須有相同 f-value。':'Injective 反而會區分桶內 elements，無法穿過 quotient。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>Factor through quotient</summary><div>若 f 對每個 coset constant，就存在唯一的 f̄:G/N→X 使 f=f̄∘π。這是「observable survives compression」的正式版本。</div></details><details><summary>本例的兩個 observables</summary><div>Sign σ 在 R 上為 0、F 上為 1，所以穿過 D₃/R；exact-element label 在每桶內改變，所以無法穿過。</div></details></section></article>`})
export class AlgebraV3InformationDashboardComponent{readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly selected=signal<D3Element>(4);readonly question=signal<Question>('parity');readonly elements=D3_ELEMENTS;readonly bucketMembers=computed<D3Element[]>(()=>this.selected()<3?[0,1,2]:[3,4,5]);label=label;bucketLabel():string{return this.selected()<3?'R':'F';}possibilities():string{return this.bucketMembers().map(label).join(', ');}questionText():string{return this.question()==='parity'?'這個 action 有 reflection 嗎？':'原本 exact action 是哪一個？';}rawAnswer():string{return this.question()==='parity'?(this.selected()<3?'NO':'YES'):label(this.selected());}quotientAnswer():string{return this.question()==='parity'?(this.selected()<3?'NO':'YES'):'NOT DETERMINED';}survives():boolean{return this.question()==='parity';}reading():string{return this.survives()?'同一 bucket 內答案一致，所以 quotient 足夠回答。':'同一 bucket 內有三個不同 labels；壓縮後無法逆推出原值。';}}
