import { Component, computed, signal } from '@angular/core';
import { D3_ELEMENTS, D3Element, label } from '../algebra-v3-ch16/d3-model';

@Component({selector:'app-algebra-v3-coset-compressor',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch17-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 17.1</p><h2>Quotient element 不是一個代表，而是一整桶被視為相同的 actions</h2><p class="lede">在 D₃ 中把 rotations R={{'{e,r,r²}'}} 當成不可見差異。六個 raw actions 只剩兩種可辨識 states：rotation bucket R 與 reflection bucket F。</p></header>
<section class="prediction"><p class="kicker">先預測</p><h3>在 D₃/R 裡，r 與 r² 是兩個不同 elements 嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不是，同一 coset</button><button type="button" (click)="prediction.set(true)">是</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'Quotient 已刻意忘掉 exact rotation；兩者都在 R。':'對。Raw actions 不同，但新世界無法分辨。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Coset compressor</p><h3>點一個 raw action，看整個 coset bucket 一起被選中</h3></div><p>被框起來的是同一個 quotient element，不是「其他可能答案」。</p></div><div class="stage quotient-compressor"><section class="raw-actions" aria-label="D3 raw actions">@for(item of elements;track item){<button type="button" [class.same-bucket]="bucket(item)===selectedBucket()" [attr.aria-pressed]="selected()===item" (click)="selected.set(item)"><strong>{{label(item)}}</strong><small>{{bucketName(item)}}</small></button>}</section><div class="compression-gate"><span>forget exact pose</span><i>→</i><strong>6 → 2</strong></div><section class="quotient-buckets" aria-live="polite"><article [class.active]="selectedBucket()===0"><span>QUOTIENT ELEMENT</span><strong>R</strong><small>{{'{e,r,r²}'}}</small></article><article [class.active]="selectedBucket()===1"><span>QUOTIENT ELEMENT</span><strong>F</strong><small>{{'{s,rs,r²s}'}}</small></article></section><section class="quotient-console"><p class="kicker">π({{label(selected())}})={{selectedBucket()===0?'R':'F'}}</p><div class="map-verdict">✓ ONE BUCKET = ONE NEW ELEMENT</div><p>{{bucketReading()}}</p></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>many raw actions</span><i>one coset</i><span>one quotient element</span></div><p><strong>D₃/R 是 cosets 的集合 {{'{R,F}'}}。</strong>每桶內部的差異被有意刪除；之後的 operation 必須只依賴桶，而不能偷看代表。</p></aside>
<section class="transfer"><p class="kicker">遷移</p><h3>若 |G|=24、|H|=6，有限 quotient G/H 有幾個 elements？</h3><div class="choice-row"><button type="button" (click)="transfer.set(true)">4</button><button type="button" (click)="transfer.set(false)">18</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="!transfer()">{{transfer()?'對。Cosets 是 4 個等大 buckets。':'Quotient 數的是 buckets：24/6=4。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>Quotient set</summary><div>對 H≤G，left cosets 的集合寫作 G/H={{'{gH:g∈G}'}}。只有 H normal 時，這個 set 才自然帶有 group operation。</div></details><details><summary>本例 partition</summary><div>D₃/R={{'{R,sR}'}}，而 sR={{'{s,rs,r²s}'}}。Lagrange theorem 給 |D₃/R|=6/3=2。</div></details></section></article>`})
export class AlgebraV3CosetCompressorComponent{readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly selected=signal<D3Element>(1);readonly elements=D3_ELEMENTS;readonly selectedBucket=computed(()=>this.bucket(this.selected()));label=label;bucket(item:D3Element):number{return item<3?0:1;}bucketName(item:D3Element):string{return this.bucket(item)===0?'R · ROTATION BUCKET':'F · REFLECTION BUCKET';}bucketReading():string{return this.selectedBucket()===0?'Exact angle 被遺忘，只保留「沒有 reflection」。':'三條 reflection axes 被合併，只保留「有 reflection」。';}}
