import { Component, computed, signal } from '@angular/core';

@Component({selector:'app-algebra-v3-induced-isomorphism',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch18-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 18.2</p><h2>把 collisions 精確收桶後，剩下的 map 不再壓縮：它是一對一的結構翻譯</h2><p class="lede">原 φ 把 12 個 inputs 壓到 4 個 image outputs。Quotient 先把每個 fiber 變成一個 element，induced map φ̄ 便成為四桶對四點的 bijection。</p></header>
<section class="prediction"><p class="kicker">先預測</p><h3>G/ker φ 會不會壓得太狠，導致兩個 quotient elements 仍映到同一 image point？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不會，剛好消除 collisions</button><button type="button" (click)="prediction.set(true)">可能</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'若兩桶仍 collision，它們原本就該是同一 kernel coset。':'對。Kernel partition 是 exact collision partition。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Lossless induced map</p><h3>選一個 quotient bucket，沿唯一 wire 抵達 image</h3></div><p>左側仍保留三個 raw members；中央以整桶為單位後，每個 output 只接一條 wire。</p></div><div class="stage induced-stage"><section class="original-fibers"><span>ORIGINAL G · 12 ELEMENTS</span>@for(bucket of buckets;track $index){<article [class.active]="selected() === $index"><div>@for(n of bucket;track n){<i>{{n}}</i>}</div><small>3 raw inputs collide</small></article>}</section><div class="quotient-collapse"><span>÷ ker φ</span><i>→</i><strong>12 → 4</strong></div><section class="quotient-elements"><span>G / ker φ</span>@for(bucket of buckets;track $index){<button type="button" [attr.aria-pressed]="selected()===$index" (click)="selected.set($index)"><strong>[{{$index}}]</strong><small>{{setLabel(bucket)}}</small></button>}</section><div class="induced-wire"><span>φ̄</span><i>→</i><strong>ONE-TO-ONE</strong></div><section class="image-elements"><span>im φ</span>@for(y of image;track y){<article [class.active]="y===selectedOutput()"><strong>{{y}}</strong><small>ONE PREIMAGE BUCKET</small></article>}</section></div><section class="isomorphism-console" aria-live="polite"><div><span>SELECTED QUOTIENT ELEMENT</span><strong>[{{selected()}}] = {{setLabel(buckets[selected()])}}</strong></div><i>φ̄([{{selected()}}])</i><div><span>UNIQUE IMAGE ELEMENT</span><strong>{{selectedOutput()}}</strong></div><div class="gate-pair"><b>✓ INJECTIVE · no bucket collisions</b><b>✓ SURJECTIVE · every image point reached</b></div><div class="map-verdict">✓ BIJECTIVE HOMOMORPHISM · ISOMORPHISM</div></section></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>G</span><i>remove exactly kernel collisions</i><span>G/ker φ</span><i>lossless relabel</i><span>im φ</span></div><p><strong>Quotient 處理資訊遺失；φ̄ 只負責重新命名結構。</strong>所以 G/ker φ 與 im φ 不是剛好同 size，而是自然 isomorphic。</p></aside>
<section class="transfer"><p class="kicker">遷移</p><h3>若 φ 本來 injective，G/ker φ 會和哪個 group 對齊？</h3><div class="choice-row"><button type="button" (click)="transfer.set(true)">G 本身</button><button type="button" (click)="transfer.set(false)">trivial group</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="!transfer()">{{transfer()?'對。Kernel trivial 時，每個 coset 只有一個 element。':'Trivial kernel 不合併不同 elements，所以 quotient 保留 G。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>Induced map 的定義</summary><div>φ̄:G/ker φ→im φ 定義為 φ̄(g ker φ)=φ(g)。Well-definedness 來自同一 coset 恰有同一 φ-value。</div></details><details><summary>為何是 isomorphism？</summary><div>它保 operation；由 image 定義自動 surjective；若 φ̄(aK)=φ̄(bK)，則 φ(a)=φ(b)，所以 aK=bK，故 injective。</div></details></section></article>`})
export class AlgebraV3InducedIsomorphismComponent{readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly selected=signal(1);readonly buckets=[[0,4,8],[1,5,9],[2,6,10],[3,7,11]];readonly image=[0,2,4,6];readonly selectedOutput=computed(()=>2*this.selected());setLabel(items:number[]):string{return`{${items.join(', ')}}`;}}
