import { Component, computed, signal } from '@angular/core';
type WorldId='square'|'triangle'|'integer';
interface World{label:string;action:string;period:number|null;state:(step:number)=>string;}
const WORLDS:Record<WorldId,World>={square:{label:'90° square rotation',action:'r',period:4,state:step=>['e','90°','180°','270°'][step%4]},triangle:{label:'120° triangle rotation',action:'r',period:3,state:step=>['e','120°','240°'][step%3]},integer:{label:'ℤ under +1',action:'+1',period:null,state:step=>String(step)}};
@Component({selector:'app-algebra-v3-first-return',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch9-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 9.1</p><h2>Order 記錄的是第一次正步數回到 identity</h2><p class="lede">固定同一個 element a，從 e 出發反覆執行。Step 0 當然在 e；真正有資訊的是最小的正整數 n，使第 n 步第一次再回到 e。</p></header>
<section class="prediction"><p class="kicker">先分清角度與步數</p><h3>90° rotation 的 element order 是 90 嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不是，是 4</button><button type="button" (click)="prediction.set(true)">是 90</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'90 是單次旋轉角度；order 數的是按幾次才第一次回到 identity。':'對。90°、180°、270°、360°，第四步才第一次回到原 action。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">First-return counter</p><h3>每次只按同一顆 action button</h3></div><p>Finite examples 在第一次回返自動停表；integer +1 則保留「目前仍未回來」，提醒有限 viewport 不能證明 infinite order。</p></div><div class="world-picker" role="group" aria-label="選擇 repeated action world">@for(id of worldIds;track id){<button type="button" [attr.aria-pressed]="worldId()===id" (click)="selectWorld(id)">{{worlds[id].label}}</button>}</div><div class="control-row"><button type="button" class="primary" (click)="advance()" [disabled]="returned()||steps()>=10">再按一次 {{current().action}}</button><button type="button" (click)="steps.set(0)" [disabled]="steps()===0">重設 counter</button></div><div class="stage counter-layout"><div class="counter-track">@for(state of path();track $index){<div class="counter-state" [class.return]="$index>0&&state===identityLabel()"><strong>{{state}}</strong><span>step {{$index}}{{$index>0&&state===identityLabel()?' · RETURN':''}}</span></div>}</div><section class="counter-console" aria-live="polite"><p class="kicker">{{current().label}}</p><h4>目前 step {{steps()}} · state {{current().state(steps())}}</h4><div class="order-readout" [class.waiting]="!returned()">{{orderVerdict()}}</div><p>{{reading()}}</p></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>e</span><i>a, a, a…</i><span>first positive return</span><i>→</i><span>ord(a)</span></div><p><strong>Order 是 fundamental cycle length，不是任一次回返時間。</strong>若第三步第一次回來，第六步也會回來，但 6 只是週期的倍數，不是新的 order。</p></aside>
<section class="transfer"><p class="kicker">Reflection</p><h3>一個非 identity reflection 做兩次回到 e，它的 order 是 2 嗎？</h3><div class="choice-row"><button type="button" (click)="transfer.set(true)">是</button><button type="button" (click)="transfer.set(false)">不是</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="!transfer()">{{transfer()?'對。第一步仍是 reflection，第二步第一次回到 identity。':'order 要找第一次正回返；reflection 正好在第 2 步首次回來。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>Element order 的正式定義</summary><div>ord(a) 是滿足 aⁿ=e 的最小正整數 n；若不存在這樣的 n，就說 a 有 infinite order。</div></details><details><summary>為什麼 a⁶=e 不一定代表 order 6？</summary><div>若 a³=e，則 a⁶=(a³)²=e。一般地，已知 aⁿ=e 只能推出 ord(a) divides n；還必須排除更早的正回返。</div></details><details><summary>有限測試無法證明 infinite order</summary><div>在 ℤ under addition，+1 的 repeated sums 是 1、2、3、…，可用整數沒有正數等於 0 證明永不回返。只按十次沒回來仍只是 evidence。</div></details></section></article>`})
export class AlgebraV3FirstReturnComponent{readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly worldId=signal<WorldId>('square');readonly steps=signal(0);readonly worlds=WORLDS;readonly worldIds=Object.keys(WORLDS) as WorldId[];readonly current=computed(()=>WORLDS[this.worldId()]);readonly returned=computed(()=>this.current().period!==null&&this.steps()===this.current().period);readonly path=computed(()=>Array.from({length:this.steps()+1},(_,step)=>this.current().state(step)));selectWorld(id:WorldId){this.worldId.set(id);this.steps.set(0);}advance(){this.steps.update(value=>value+1);}identityLabel(){return this.current().state(0);}orderVerdict(){return this.returned()?`✓ FIRST RETURN · ord(a)=${this.steps()}`:'○ NO POSITIVE RETURN YET';}reading(){if(this.returned())return `第 ${this.steps()} 步第一次回到 identity，counter 在此停止。`;if(this.current().period===null&&this.steps()>=10)return 'Viewport 已走十步仍未回返；正式 infinite 結論需要 general reason。';return '尚未回到 identity；下一次按鈕仍使用同一個 element。';}}
