import { Component, computed, signal } from '@angular/core';
type ScanWorld='z6'|'triangle';
const TRIANGLE_ELEMENTS=['e','r','r²','f','rf','r²f'] as const;
@Component({selector:'app-algebra-v3-cyclic-scanner',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch9-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 9.3</p><h2>只要存在一顆 button 走遍，整個 group 就是 cyclic</h2><p class="lede">Cyclic 不是說 graph 畫成圓，也不是每個 element 都能生成全群。它是一個 existence claim：至少有一個 a，使它的 powers 覆蓋 G 的每個 effect。</p></header>
<section class="prediction"><p class="kicker">先掃描 triangle symmetries</p><h3>三角形全部六個 symmetries 是 cyclic group 嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不是</button><button type="button" (click)="prediction.set(true)">是</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'rotation powers 只能到三個 rotations；任何 reflection powers 只在 e 與自身間切換。':'對。沒有單一 symmetry 的 powers 能同時覆蓋 rotations 與三個 reflections。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Cyclic scanner</p><h3>逐顆選 candidate，看 single-action coverage</h3></div><p>切換 world 後可掃描所有 element types。粗框 node 是 selected candidate 的 powers；右側同時給 candidate verdict 與 whole-group existence verdict。</p></div><div class="world-picker" role="group" aria-label="選擇要掃描 cyclic property 的 group"><button type="button" [attr.aria-pressed]="world()==='z6'" (click)="selectWorld('z6')">ℤ₆ addition</button><button type="button" [attr.aria-pressed]="world()==='triangle'" (click)="selectWorld('triangle')">Triangle symmetries D₃</button></div><div class="candidate-picker" role="group" aria-label="選擇 candidate generator">@for(item of candidates();track item){<button type="button" [attr.aria-pressed]="candidate()===item" (click)="candidate.set(item)">{{item}}</button>}</div><div class="stage scanner-layout"><div class="coverage-board">@for(item of elements();track item){<div class="coverage-node" [class.reached]="coverage().includes(item)"><strong>{{coverage().includes(item)?'✓':'×'}} {{item}}</strong><span>{{coverage().includes(item)?'POWER REACHED':'NOT IN ORBIT'}}</span></div>}</div><section class="scanner-console" aria-live="polite"><p class="kicker">CANDIDATE {{candidate()}}</p><h4>coverage {{coverage().length}} / {{elements().length}}</h4><div class="order-readout" [class.waiting]="coverage().length!==elements().length">{{coverage().length===elements().length?'✓ THIS ELEMENT GENERATES G':'○ THIS ELEMENT DOES NOT GENERATE G'}}</div><p>{{coverageReading()}}</p><div class="relation-stamp">{{world()==='z6'?'✓ WHOLE GROUP IS CYCLIC · candidates 1 and 5 work':'× WHOLE GROUP IS NOT CYCLIC · no single element type covers all 6'}}</div></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>∃ a</span><i>such that</i><span>⟨a⟩ = G</span><i>→</i><span>G cyclic</span></div><p><strong>Cyclic 是 whole-group 的存在性特徵。</strong>找到一顆全覆蓋 button 就足以證明；要推翻則必須排除每種 candidate，而不是只看到一顆失敗。</p></aside>
<section class="transfer"><p class="kicker">結構 consequence</p><h3>每個 cyclic group 都是 abelian 嗎？</h3><div class="choice-row"><button type="button" (click)="transfer.set(true)">是</button><button type="button" (click)="transfer.set(false)">不是</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="!transfer()">{{transfer()?'對。任意 x、y 都是同一 a 的 powers，exponents 相加可交換。':'若 x=aⁱ、y=aʲ，則 xy=aⁱ⁺ʲ=aʲ⁺ⁱ=yx。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>Cyclic group 的正式定義</summary><div>若存在 a∈G 使 G=⟨a⟩，稱 G cyclic，a 稱為 generator of G。Generator 可以不唯一；ℤ₆ 中 1 與 5 都生成全群。</div></details><details><summary>Proof Lab：cyclic 為何必然 abelian？</summary><div>任取 x,y∈G。因 G=⟨a⟩，可寫 x=aⁱ、y=aʲ。於是 xy=aⁱ⁺ʲ=aʲ⁺ⁱ=yx。證明使用整數加法可交換，不是假設原群先交換。</div></details><details><summary>Finite cyclic groups 的預告</summary><div>有 n 個 elements 的 finite cyclic group，其 power network 與 ℤₙ addition 有相同節奏。Ch10 會正式說明「相同結構」需要怎樣的可逆翻譯。</div></details></section></article>`})
export class AlgebraV3CyclicScannerComponent{readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly world=signal<ScanWorld>('z6');readonly candidate=signal('1');readonly candidates=computed(()=>this.world()==='z6'?['0','1','2','3','4','5']:[...TRIANGLE_ELEMENTS]);readonly elements=computed(()=>this.world()==='z6'?['0','1','2','3','4','5']:[...TRIANGLE_ELEMENTS]);readonly coverage=computed(()=>{if(this.world()==='z6'){const k=+this.candidate();const order=6/this.gcd(6,k);return Array.from({length:order},(_,step)=>String((step*k)%6));}const item=this.candidate();if(item==='e')return['e'];if(item==='r'||item==='r²')return['e','r','r²'];return['e',item];});readonly coverageReading=computed(()=>this.coverage().length===this.elements().length?`Powers of ${this.candidate()} hit every element；這一顆 witness 已足以證明 cyclic。`:`Powers of ${this.candidate()} 只形成 ${this.coverage().join('、')}；selected candidate 失敗。`);selectWorld(world:ScanWorld){this.world.set(world);this.candidate.set(world==='z6'?'1':'r');}private gcd(a:number,b:number):number{return b===0?a:this.gcd(b,a%b);}}
