import { Component, computed, signal } from '@angular/core';
@Component({selector:'app-algebra-v3-orbit-vs-world',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch9-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 9.2</p><h2>Element order 量一條 orbit；group order 數整個世界</h2><p class="lede">同一個六元素 group 裡，不同 buttons 會切出不同長度的 repeated-action cycles。兩個量都叫 order，但一個屬於 element，一個屬於 whole group。</p></header>
<section class="prediction"><p class="kicker">先拒絕全世界大小的暗示</p><h3>六元素 group 的每個 non-identity element 都必須有 order 6 嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不必</button><button type="button" (click)="prediction.set(true)">必須</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'在 ℤ₆ 中，+2 的 cycle 是 0→2→4→0，order 只有 3。':'對。group 有六點，不代表每顆 button 的 orbit 都覆蓋六點。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Orbit-vs-world lens</p><h3>點一個 k，沿 repeated +k 直到第一次回 0</h3></div><p>六個 tiles 始終代表整個 G；粗框只標出目前 element 的 powers。每個 orbit tile 顯示它在 cycle 中第幾步出現。</p></div><div class="candidate-picker" role="group" aria-label="選擇模六中的 element">@for(value of residues;track value){<button type="button" [attr.aria-pressed]="element()===value" (click)="element.set(value)">k={{value}}</button>}</div><div class="stage orbit-layout"><div class="world-grid">@for(value of residues;track value){<div class="world-node" [class.orbit]="orbit().includes(value)"><strong>{{orbit().includes(value)?'✓':'×'}} {{value}}</strong><span>{{orbit().includes(value)?'power step '+orbit().indexOf(value):'outside ⟨'+element()+'⟩'}}</span></div>}</div><section class="orbit-console" aria-live="polite"><p class="kicker">REPEATED +{{element()}}</p><h4>{{orbitPath()}}</h4><div class="measure-pair"><div><span>element order</span><strong>ord({{element()}}) = {{order()}}</strong></div><div><span>group order</span><strong>|G| = 6</strong></div></div><div class="order-readout">{{order()===6?'✓ ORBIT COVERS WORLD':'○ ORBIT IS '+order()+' OF 6 NODES'}}</div><p>{{reading()}}</p></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>ord(a)</span><i>=</i><span>|⟨a⟩|</span><i>may differ from</i><span>|G|</span></div><p><strong>Element order 是它自己生成的 cyclic subworld 大小。</strong>只有這條 orbit 剛好覆蓋全群時，ord(a) 才等於 |G|；否則它只是大世界中的較短 cycle。</p></aside>
<section class="transfer"><p class="kicker">Square symmetry group</p><h3>正方形有 8 個 symmetries，所以 90° rotation 的 order 是 8 嗎？</h3><div class="choice-row"><button type="button" (click)="transfer.set(false)">不是，是 4</button><button type="button" (click)="transfer.set(true)">是 8</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="transfer()">{{transfer()?'rotation powers 只走 e、90°、180°、270°，第四步回返；另外四個 reflections 不在這條 orbit。':'對。group order 8，這個 element order 4；兩個量的對象不同。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>為什麼第一次回返前 powers 不重複？</summary><div>若 aⁱ=aʲ 且 0≤i&lt;j，左乘 a⁻ⁱ 得 e=aʲ⁻ⁱ，於是更早出現長度 j−i 的 identity loop。因此在 ord(a) 之前，e、a、a²、… 必須彼此不同。</div></details><details><summary>Identity element 的 order</summary><div>e¹=e，所以 identity 的 order 是 1。它的 generated subgroup 只有 e 自己；本頁選 k=0 會顯示單點 orbit。</div></details><details><summary>術語中的兩種 order</summary><div>Group order |G| 是 element 數；element order ord(a) 是 repeated-action period。閱讀時必須看 order 修飾的對象，不靠上下文猜數字。</div></details></section></article>`})
export class AlgebraV3OrbitVsWorldComponent{readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly element=signal(2);readonly residues=[0,1,2,3,4,5] as const;readonly order=computed(()=>6/this.gcd(6,this.element()));readonly orbit=computed(()=>Array.from({length:this.order()},(_,step)=>(step*this.element())%6));readonly orbitPath=computed(()=>[...this.orbit(),0].join(' → '));readonly reading=computed(()=>this.order()===6?'這顆 button 的 powers 走遍 whole group。':`全群仍有 6 elements，但這顆 button 在 ${this.order()} 步就回到 0。`);private gcd(a:number,b:number):number{return b===0?a:this.gcd(b,a%b);}}
