import type { AlgebraV2Lesson } from './algebra-v2-lessons';
import { check, makeLesson as L, networkNodes as nodes } from './algebra-v2-lesson-builder';

type Part5ChapterId = 'ch28' | 'ch29' | 'ch30' | 'ch31' | 'ch32';

export const ALGEBRA_V2_PART5_LESSONS: Record<Part5ChapterId, AlgebraV2Lesson[]> = {
  ch28: [
    L({
      id: '28.1',
      title: 'Direct product 把兩套獨立 actions 放進座標',
      lede: 'Element (g,h) 同時攜帶 G-action 與 H-action；兩個 coordinates 可各自執行、各自撤銷，互不竄改。',
      predict: [
        '在 G×H 中，(g,e_H) 與 (e_G,h) 是否一定 commute？',
        true,
        '兩種順序都得到 (g,h)。',
        '它們操作不同 coordinates。',
      ],
      kind: 'mapping',
      modelTitle: '一個 element，兩條獨立 action channels',
      prompt: '切換 coordinates，看哪個 state component 改變。',
      presets: [
        {
          label: '只動 G',
          mapping: [{ from: '(x,y)', to: '(gx,y)', accent: true }],
          formula: '(g,e)·(x,y)',
          detail: '第二 coordinate 完全保持。',
          status: 'good',
        },
        {
          label: '只動 H',
          mapping: [{ from: '(x,y)', to: '(x,hy)', accent: true }],
          formula: '(e,h)·(x,y)',
          detail: '第一 coordinate 完全保持。',
          status: 'good',
        },
        {
          label: '同時動',
          mapping: [{ from: '(x,y)', to: '(gx,hy)' }],
          formula: '(g,h)=(g,e)(e,h)',
          detail: '任意 pair action 分解成兩個獨立 modules。',
          status: 'good',
        },
      ],
      insight:
        'Direct product 是 action independence 的代數模型：每個 coordinate 有自己的 group contract。',
      transfer: [
        '平面 translations 是否可看成 x-direction 與 y-direction translations 的 direct product？',
        true,
        '兩方向獨立相加且 commute。',
        '每個 translation 由兩個 coordinates 決定。',
      ],
      formal: [
        'Direct product',
        'G×H={(g,h)}，operation componentwise：(g₁,h₁)(g₂,h₂)=(g₁g₂,h₁h₂)。',
      ],
      proof: [
        'Group contract 分 coordinate 驗證',
        'Closure 由 G、H 各自 closure。',
        'Identity 是 (e_G,e_H)。',
        'Inverse 是 (g⁻¹,h⁻¹)。',
        'Associativity 逐 coordinate 繼承。',
      ],
      boundary:
        '一般 group 內有兩個 subgroups 不代表整群自動是 direct product；還需 independence 與完整生成。',
    }),
    L({
      id: '28.2',
      title: 'Pair 的週期要等兩個 coordinates 同時回來',
      lede: '反覆做 (g,h)，第一 coordinate 每 ord(g) 步回來，第二 coordinate 每 ord(h) 步回來；共同第一次歸零是 lcm。',
      predict: [
        '若 ord(g)=4、ord(h)=6，ord((g,h)) 是否為 24？',
        false,
        '兩者第一次同時回來是 lcm(4,6)=12。',
        '不是乘積，因週期可能共享因數。',
      ],
      kind: 'network',
      modelTitle: '同步兩個 cycle clocks',
      prompt: '比較 coordinate clocks 與 pair clock。',
      presets: [
        {
          label: 'orders 2 and 3',
          nodes: nodes(['0', '1', '2', '3', '4', '5'], ['1', '2', '3', '4', '5'], '0'),
          actions: ['G clock:2', 'H clock:3'],
          formula: 'lcm(2,3)=6',
          detail: '互質週期的 pair 走滿六步。',
          status: 'good',
        },
        {
          label: 'orders 4 and 6',
          nodes: nodes(
            ['0', '1', '2', '3', '4', '5', '6', '…', '11'],
            ['1', '2', '3', '4', '5', '6', '…', '11'],
            '0',
          ),
          actions: ['G clock:4', 'H clock:6'],
          formula: 'lcm(4,6)=12',
          detail: '第 12 步第一次雙雙歸零。',
          status: 'good',
        },
        {
          label: 'orders 4 and 4',
          nodes: nodes(['0', '1', '2', '3'], ['1', '2', '3'], '0'),
          actions: ['4', '4'],
          formula: 'lcm(4,4)=4',
          detail: '同步週期不會乘成 16。',
          status: 'neutral',
        },
      ],
      insight: 'ord((g,h))=lcm(ord(g),ord(h))；direct product 把週期問題變成同步 clocks。',
      transfer: [
        'C₂×C₃ 是否有 order 6 element？',
        true,
        '(generator,generator) 的 order lcm(2,3)=6。',
        '因此它其實 cyclic。',
      ],
      formal: ['Order in product', 'Finite orders 時 ord(g,h)=lcm(ord(g),ord(h))。'],
      proof: [
        '最小共同回歸時間',
        '(g,h)^n=(g^n,h^n)。',
        '它等於 identity iff ord(g)∣n 且 ord(h)∣n。',
        '最小同時被兩者整除的正數是 lcm。',
        '故得到公式。',
      ],
      boundary: '若某 coordinate infinite order，pair 也 infinite order。',
    }),
    L({
      id: '28.3',
      title: 'Internal direct product 要先辨認兩個獨立 subgroups',
      lede: '有時 coordinates 已藏在同一群 K 裡。若 G,H normal、交集 trivial、共同生成 K，就能把 gh 唯一解碼成 pair (g,h)。',
      predict: [
        '若 subgroups G,H 只有交集 {e}，是否已足以推出 K≅G×H？',
        false,
        '還要它們生成 K，並有相容的 commuting／normality。',
        '只有不重疊，還沒有完整 coordinate system。',
      ],
      kind: 'diagnostic',
      modelTitle: 'Internal product 的三個結構檢查',
      prompt: '每一關各排除一種 coordinate 故障。',
      presets: [
        {
          label: 'valid split',
          checks: [
            check('G∩H={e}', true, 'representation 不 collision。'),
            check('GH=K', true, '每個 k 可表示。'),
            check('G,H normal', true, 'coordinates commute。'),
          ],
          detail: 'K≅G×H。',
          status: 'good',
        },
        {
          label: 'overlap',
          checks: [
            check('G∩H={e}', false, '同 element 可移到兩 coordinates。'),
            check('unique decoding', false, 'pair representation collision。'),
          ],
          detail: '不能當獨立 coordinates。',
          status: 'bad',
        },
        {
          label: 'not generating',
          checks: [
            check('trivial intersection', true, '不 collision。'),
            check('GH=K', false, '有 elements 無 coordinates。'),
          ],
          detail: '只能描述 K 的一部分。',
          status: 'bad',
        },
      ],
      insight: 'Direct-product coordinates 需要「不重複、無遺漏、彼此獨立」三種保證。',
      transfer: [
        '在 abelian K 中，G,H 是否自動 commute？',
        true,
        '所有 pairs commute。',
        '此時只需再查交集與生成。',
      ],
      formal: ['Internal direct product', '若 G,H◁K、G∩H={e}、GH=K，則 K≅G×H。'],
      proof: [
        '構造 isomorphism',
        '定義 φ:G×H→K, φ(g,h)=gh。',
        'Normality 加 trivial intersection 推出 G,H elementwise commute，故 φ homomorphism。',
        'GH=K 給 surjective。',
        'gh=e 推出 g=h⁻¹∈G∩H，故 kernel trivial。',
      ],
      boundary: 'Semidirect product 正是拿掉 complete independence 後的下一種結構；本章不展開。',
    }),
    L({
      id: '28.4',
      title: 'Finite cyclic groups 何時能拆成 product',
      lede: 'C_m×C_n 是否由一個 pair 走遍，取決於 pair order 能否達到 mn；這恰好要求 m,n coprime。',
      predict: [
        'C₄×C₆ 是否 cyclic？',
        false,
        '最大 pair order lcm(4,6)=12，小於 group order 24。',
        '沒有單一 element 能走遍。',
      ],
      kind: 'diagnostic',
      modelTitle: '用 order capacity 判斷 cyclicity',
      prompt: '比較 group size mn 與可達最大 lcm。',
      presets: [
        {
          label: 'C₂×C₃',
          checks: [
            check('group order', true, '6。'),
            check('pair max order', true, 'lcm(2,3)=6。'),
            check('cyclic', true, '存在 order 6 element。'),
          ],
          detail: '互質 clocks 合成完整 cycle。',
          status: 'good',
        },
        {
          label: 'C₄×C₆',
          checks: [
            check('group order', true, '24。'),
            check('pair max order', false, '最多 12。'),
            check('cyclic', false, '無 order 24 element。'),
          ],
          detail: '共享 factor 2 造成同步提早。',
          status: 'bad',
        },
        {
          label: 'C₅×C₇',
          checks: [
            check('gcd', true, '1。'),
            check('pair order', true, '35。'),
            check('cyclic', true, '與 C₃₅ isomorphic。'),
          ],
          detail: 'coprime components 可合成單一 generator。',
          status: 'good',
        },
      ],
      insight:
        'C_m×C_n cyclic iff gcd(m,n)=1；Chinese remainder 是同一 coordinate-splitting insight。',
      transfer: [
        'Z/12Z 是否 isomorphic to Z/3Z×Z/4Z？',
        true,
        '3、4 coprime，map [x]↦([x]_3,[x]_4) bijective 且保留加法。',
        '這是 CRT 的 group form。',
      ],
      formal: ['Cyclic product criterion', 'C_m×C_n≅C_{mn} iff gcd(m,n)=1。'],
      proof: [
        '由 lcm 判斷',
        '任何 pair order 至多 lcm(m,n)。',
        '要生成 mn elements，必須有 lcm(m,n)=mn。',
        '這等價 gcd(m,n)=1。',
        '若互質，generator pair 的 order 正是 mn。',
      ],
      boundary:
        '多個 cyclic factors 的 general classification 需要 invariant factors／primary decomposition，留到後續。',
    }),
  ],

  ch29: [
    L({
      id: '29.1',
      title: 'Prime divisor 必須在群裡留下 p-cycle',
      lede: 'Lagrange 只說 element order 必須整除 |G|；Cauchy 給出反方向的一小塊存在性：每個 prime divisor 都真的出現。',
      predict: [
        '若 5 divides |G|，G 是否一定有 order 5 element？',
        true,
        '這正是 Cauchy theorem。',
        'Prime 條件把「可能」升級成「必定存在」。',
      ],
      kind: 'network',
      modelTitle: '從 order factor 尋找 forced cycle',
      prompt: '綠色 cycle 表示 theorem 保證存在，不需先知道 group classification。',
      presets: [
        {
          label: '|G|=15, p=5',
          nodes: nodes(['e', 'a', 'a²', 'a³', 'a⁴', 'other states'], ['a', 'a²', 'a³', 'a⁴']),
          actions: ['repeat a'],
          formula: 'ord(a)=5 exists',
          detail: '五點 cyclic subgroup 被 group order 強迫存在。',
          status: 'good',
        },
        {
          label: '|G|=12, p=3',
          nodes: nodes(['e', 'b', 'b²', 'other states'], ['b', 'b²']),
          actions: ['repeat b'],
          formula: 'ord(b)=3 exists',
          detail: '三點 cycle 必定存在。',
          status: 'good',
        },
        {
          label: 'd=4',
          nodes: nodes(['divisor 4', 'existence?'], [], 'divisor 4'),
          actions: ['Cauchy only primes'],
          formula: 'not guaranteed by Cauchy',
          detail: 'Composite divisor 不在 theorem 承諾範圍。',
          status: 'neutral',
        },
      ],
      insight:
        'Cauchy theorem 說 finite group order 的每個 prime factor，都對應一個真實的 prime-length action cycle。',
      transfer: [
        'Order 21 group 是否一定有 subgroups of orders 3 and 7？',
        true,
        'Cauchy 分別給 order 3、7 elements，它們生成相應 cyclic subgroups。',
        '兩個 prime factors 都會出現。',
      ],
      formal: ['Cauchy theorem', '若 prime p divides finite |G|，則存在 a∈G with ord(a)=p。'],
      proof: [
        '存在性結論的責任',
        'Theorem 只保證至少一個 element。',
        '它生成 subgroup ⟨a⟩ of order p。',
        '不保證唯一。',
        '也不直接保證 composite divisor order 的 subgroup。',
      ],
      boundary: '「d divides |G| ⇒ element order d exists」對 composite d 為 false。',
    }),
    L({
      id: '29.2',
      title: 'Cauchy proof 把 element search 變成 p-tuple orbit count',
      lede: '直接找 a 很難。改看 product 為 e 的 p-tuples，讓 cyclic shift 作用；nontrivial fixed tuple 正好給 a^p=e。',
      predict: [
        'Product e 的 p-tuples 數是否為 |G|^{p−1}？',
        true,
        '前 p−1 個任選，最後一個被迫為 inverse of product。',
        '若 p divides |G|，這個總數也 divisible by p。',
      ],
      kind: 'diagnostic',
      modelTitle: '四步 action-counting proof scaffold',
      prompt: '每一步只負責一個轉換，不把 orbit-counting 魔術化。',
      presets: [
        {
          label: '建 state set X',
          checks: [
            check('states', true, '(a₁,…,a_p) with product e。'),
            check('size', true, '|G|^{p−1}。'),
            check('divisible by p', true, '因 p∣|G|。'),
          ],
          detail: '把找 element 改成數 structured tuples。',
          status: 'good',
        },
        {
          label: 'cyclic shift action',
          checks: [
            check('closed', true, 'shift 後 product 是 conjugate of e，仍 e。'),
            check('orbit sizes', true, '1 or p，因 p prime。'),
            check('fixed tuples', true, '(a,…,a) with a^p=e。'),
          ],
          detail: 'Fixed points 精確編碼所需 elements。',
          status: 'good',
        },
        {
          label: 'mod p conclusion',
          checks: [
            check('|X|≡0', true, 'mod p。'),
            check('nonfixed orbits', true, '各貢獻 p。'),
            check('#fixed≡0', true, 'mod p。'),
            check('identity only?', false, '1 不可 divisible by p。'),
          ],
          detail: '除 identity tuple 外必有 nontrivial fixed tuple。',
          status: 'good',
        },
      ],
      insight:
        '存在性 proof 的核心是設計 action，使 wanted objects 恰好成為 fixed points，再用 orbit sizes 逼它們出現。',
      transfer: [
        'Fixed tuple (a,…,a) 且 a≠e 是否必有 ord(a)=p？',
        true,
        'a^p=e，order divides prime p；非identity 排除 order 1。',
        '因此 order 正是 p。',
      ],
      formal: [
        'Cauchy action proof',
        'C_p cyclically shifts X={(a₁,…,a_p):a₁…a_p=e}；fixed points count is divisible by p and exceeds 1。',
      ],
      proof: [
        '最後邏輯鏈',
        '|X| divisible by p。',
        'Non-singleton C_p-orbits size p。',
        '所以 fixed-point count divisible by p。',
        'Identity tuple 是一個 fixed point；因此至少還有 p−1 個 nonidentity fixed tuples。',
      ],
      boundary: 'Proof 使用 p prime 以確保 orbit size 只有 1 或 p。',
    }),
    L({
      id: '29.3',
      title: 'p-group 的所有週期尺度都只含 p',
      lede: '若 |G|=p^n，Lagrange 迫使每個 element order、subgroup order 與 orbit size 都是 p-powers；單一 prime 控制整個有限世界。',
      predict: [
        '有限 p-group 的 nonidentity element order 是否必為 p 的正次方？',
        true,
        'element order divides p^n。',
        '沒有其他 prime factor 可出現。',
      ],
      kind: 'diagnostic',
      modelTitle: '把 Lagrange filter 套到 p-power world',
      prompt: '區分「必為 p-power」與「一定等於 p」。',
      presets: [
        {
          label: 'element orders',
          checks: [
            check('divide p^n', true, 'Lagrange。'),
            check('p-power', true, '只有 p factors。'),
            check('都等於 p', false, '可能有 p²,p³ cycles。'),
          ],
          detail: '尺度受控，但仍有多層。',
          status: 'good',
        },
        {
          label: 'subgroup orders',
          checks: [
            check('divide p^n', true, 'Lagrange。'),
            check('p-power', true, '任何 subgroup 也是 p-group。'),
          ],
          detail: 'Substructure 不會引入新 primes。',
          status: 'good',
        },
        {
          label: 'quotients',
          checks: [
            check('normal N', true, '|G/N|=p^{n-k}。'),
            check('仍 p-group', true, 'quotient 也只含 p。'),
          ],
          detail: '壓縮後仍留在同一 prime world。',
          status: 'good',
        },
      ],
      insight:
        'p-group 是由單一 prime 組成的有限 action ecosystem；許多 divisibility constraints 因而變得剛性。',
      transfer: [
        'Order 8 group 是否一定有 order 2 element？',
        true,
        'Cauchy with p=2。',
        '至少有一個 involution。',
      ],
      formal: ['p-group', 'Finite G with |G|=p^n for prime p。'],
      proof: [
        'Cauchy 的第一個 consequence',
        'p divides |G|。',
        'Cauchy 給 order p element。',
        '其 generated subgroup order p。',
        '所以每個 nontrivial finite p-group 都含最小 p-cycle。',
      ],
      boundary: 'p-group 不表示每個 element order 都是 p；cyclic C_{p^n} 有更長週期。',
    }),
    L({
      id: '29.4',
      title: 'Finite p-group 一定有 nontrivial center',
      lede: 'Class equation 中，noncentral conjugacy classes 都有 p 的倍數個 elements；總數也是 p 的倍數，因此 center 不可能只剩 identity。',
      predict: [
        'Nontrivial finite p-group 的 center 可能只有 {e} 嗎？',
        false,
        'class equation mod p 迫使 |Z(G)| divisible by p。',
        '至少有 p 個 central elements。',
      ],
      kind: 'partition',
      modelTitle: '把 class equation 對 p 取餘數',
      prompt: '先移除 noncentral classes 的 p-multiple tiles，看剩下什麼。',
      presets: [
        {
          label: 'noncentral classes',
          blocks: [
            { label: 'class A', items: ['p-multiple'] },
            { label: 'class B', items: ['p-multiple'] },
            { label: '…', items: ['p-multiple'] },
          ],
          formula: 'each size ≡0 mod p',
          detail: 'Noncentral stabilizer proper，index 是大於 1 的 p-power。',
          status: 'good',
        },
        {
          label: 'center remainder',
          blocks: [
            { label: 'Z(G)', items: ['remaining elements'], state: 'active' },
            { label: 'noncentral', items: ['0 mod p'] },
          ],
          formula: '|G|≡|Z(G)| mod p',
          detail: '左側 0 mod p，所以 center size 也 0 mod p。',
          status: 'good',
        },
        {
          label: 'nontrivial',
          blocks: [{ label: 'Z(G)', items: ['e', '至少 p−1 others'], state: 'active' }],
          formula: '|Z(G)|≥p',
          detail: 'center 不可能只有一個 identity。',
          status: 'good',
        },
      ],
      insight:
        'p-group center theorem 是 class equation 的整除餘數效應：noncentral movement 留下 central fixed core。',
      transfer: [
        'Order p² group 是否一定 abelian？',
        true,
        'center order 是 p 或 p²；若 p² 就完成，若 p 則 quotient G/Z cyclic，仍推出 G abelian。',
        '這是 nontrivial center 的強力後果。',
      ],
      formal: [
        'Center theorem',
        'Every nontrivial finite p-group has nontrivial center；indeed p divides |Z(G)|。',
      ],
      proof: [
        'Class equation mod p',
        'Noncentral class size=[G:C_G(a)] 是大於 1 的 p-power。',
        '所以每項 divisible by p。',
        '|G|=|Z(G)|+sum class sizes，兩側 mod p。',
        '0≡|Z(G)| mod p，且 identity 在 center，故 |Z(G)|≥p。',
      ],
      boundary: '一般 finite group center 可 trivial；prime-power order 是關鍵前提。',
    }),
  ],

  ch30: [
    L({
      id: '30.1',
      title: 'Sylow subgroup 收集群裡能容納的最大 p-power',
      lede: '若 |G|=p^n m 且 p∤m，p-subgroup 最大可能大小是 p^n。Sylow I 說這個 upper bound 一定真的達到。',
      predict: [
        '若 |G|=72=2³·3²，是否一定有 order 8 subgroup？',
        true,
        'Sylow I with p=2。',
        '群必能容納全部三個 2-factors。',
      ],
      kind: 'partition',
      modelTitle: '把 group order 拆成 p-primary capacity',
      prompt: '選 prime，觀察 theorem 強迫存在的最大 tile。',
      presets: [
        {
          label: 'p=2 in 72',
          blocks: [
            { label: 'Sylow 2-subgroup', items: ['8 elements'], state: 'active' },
            { label: 'odd remainder index', items: ['9 cosets'] },
          ],
          formula: '72=8×9',
          detail: '全部 2³ 被 subgroup 吸收。',
          status: 'good',
        },
        {
          label: 'p=3 in 72',
          blocks: [
            { label: 'Sylow 3-subgroup', items: ['9 elements'], state: 'active' },
            { label: 'non-3 index', items: ['8 cosets'] },
          ],
          formula: '72=9×8',
          detail: '全部 3² 被 subgroup 吸收。',
          status: 'good',
        },
        {
          label: 'order 6 subgroup?',
          blocks: [{ label: 'mixed primes', items: ['2·3'], state: 'warning' }],
          formula: 'not promised by Sylow I',
          detail: 'Theorem 分別保證 maximal p-subgroups，不保證任意 mixed divisor。',
          status: 'neutral',
        },
      ],
      insight: 'Sylow I 把 group order 中某個 prime 的全部 multiplicity，實現成一個真實 subgroup。',
      transfer: [
        'Order 60 group 是否必有 order 4 與 order 5 subgroups？',
        true,
        '60=2²·3·5。',
        'Sylow 2-subgroup order 4，Sylow 5-subgroup order 5。',
      ],
      formal: [
        'Sylow p-subgroup',
        '若 |G|=p^n m、p∤m，order p^n 的 subgroup 稱 Sylow p-subgroup；Sylow I 保證存在。',
      ],
      proof: [
        '與 Cauchy 的差別',
        'Cauchy 只保證一個 order p cycle。',
        'Sylow I 要把 p-subgroup 從 p 擴到 p^n。',
        '每一步都需維持 subgroup closure，不是只找更多 p-elements。',
        '結論達到 Lagrange 允許的 maximal p-power。',
      ],
      boundary:
        'Sylow subgroup 對指定 p maximal；它不一定是 maximal subgroup in inclusion among all proper subgroups。',
    }),
    L({
      id: '30.2',
      title: '存在性 proof 是逐層擴張 p-subgroup',
      lede: '從 Cauchy 的 order p seed 開始，若尚未達 p^n，就利用 normalizer／quotient 找到新的 p-step，把 subgroup 放大一個 p factor。',
      predict: [
        '一個非-Sylow p-subgroup P 是否總能被包含在更大的 p-subgroup？',
        true,
        'Sylow extension lemma 保證可逐層擴張直到 maximal p-power。',
        '這是 Sylow I 的強版本。',
      ],
      kind: 'lattice',
      modelTitle: '沿 p-power subgroup chain 向上走',
      prompt: '每一層 index p，只增加一個 prime factor。',
      presets: [
        {
          label: 'p-chain',
          blocks: [
            { label: 'P_n', items: ['order pⁿ (Sylow)'], level: 0, state: 'active' },
            { label: 'P₂', items: ['order p²'], level: 1 },
            { label: 'P₁', items: ['order p'], level: 2 },
          ],
          formula: '{e}<P₁<P₂<…<P_n',
          detail: '概念圖顯示逐層擴張，不宣稱 subgroup 唯一。',
          status: 'good',
        },
        {
          label: 'current P',
          blocks: [
            { label: 'target pⁿ', items: ['capacity'], level: 0 },
            { label: 'larger pP', items: ['next layer'], level: 1, state: 'active' },
            { label: 'P', items: ['not maximal'], level: 2, state: 'active' },
          ],
          formula: '[P′:P]=p',
          detail: '尚未吸收全部 p-factor 就存在下一層。',
          status: 'good',
        },
      ],
      insight:
        'Sylow existence 不是一次猜中大 subgroup，而是「只要 p-capacity 尚未用完，就能再擴一層」。',
      transfer: [
        '任何 p-subgroup 是否包含在某個 Sylow p-subgroup 中？',
        true,
        '反覆套 extension 直到 order p^n。',
        '有限性保證過程停止。',
      ],
      formal: [
        'Extension form of Sylow I',
        'Every p-subgroup of a finite group is contained in a Sylow p-subgroup。',
      ],
      proof: [
        'Proof roadmap（細節折疊）',
        '讓 P 作用或研究 normalizer N_G(P)，把「可再擴張」轉成 quotient 中的 p-divisibility。',
        '若 P 非 Sylow，相關 index 仍含 factor p。',
        'Cauchy 在 quotient／fixed structure 中提供 order p 的新方向。',
        '把它 lift 回 G 得到包含 P 的更大 p-subgroup，induct 到 p^n。',
      ],
      boundary: 'Normalizer proof 的技術細節比核心 insight 複雜；主流程只要求能解釋擴張策略。',
    }),
    L({
      id: '30.3',
      title: 'Sylow I 把可能的 subgroup orders 變成保證存在',
      lede: 'Lagrange 提供上限與必要整除；Cauchy 提供第一層；Sylow I 完成指定 prime 的全部層級。三者責任不同。',
      predict: [
        '若 p^k divides |G|，是否一定存在 order p^k subgroup？',
        true,
        '先取 Sylow p-subgroup，再使用 finite p-group 的 subgroup chain。',
        '對每 0≤k≤n 都可實現。',
      ],
      kind: 'diagnostic',
      modelTitle: '三個存在／限制定理的責任表',
      prompt: '不要把 theorem names 當同義詞。',
      presets: [
        {
          label: 'Lagrange',
          checks: [
            check('若 H exists', true, '|H| divides |G|。'),
            check('保證 H exists', false, '一般不保證。'),
          ],
          detail: '必要條件 filter。',
          status: 'neutral',
        },
        {
          label: 'Cauchy',
          checks: [
            check('prime p divides', true, '有 order p element/subgroup。'),
            check('p^n full power', false, '只給第一層。'),
          ],
          detail: 'Prime seed existence。',
          status: 'good',
        },
        {
          label: 'Sylow I',
          checks: [
            check('max p-power', true, '有 order p^n subgroup。'),
            check('contains any P', true, '可擴張到 Sylow。'),
          ],
          detail: '完整 p-primary existence。',
          status: 'good',
        },
      ],
      insight: 'Lagrange 說不能有什麼；Cauchy 與 Sylow I 逐步說一定有什麼。',
      transfer: [
        'Order 12 group 是否一定有 order 4 subgroup？',
        true,
        '4 是 12 的 maximal 2-power。',
        'Sylow I 保證。',
      ],
      formal: ['p^k consequence', '若 p^n divides |G|，對每 k≤n 存在 order p^k subgroup。'],
      proof: [
        '由 Sylow subgroup 內部取得',
        '取 Sylow P of order p^n。',
        'Finite p-group 有 nontrivial center。',
        '用 central order-p subgroup 與 induction 建立各層 subgroup。',
        '因此 P 內出現所有 p^k orders。',
      ],
      boundary: 'Mixed order divisors 仍不由 Sylow I 一般保證。',
    }),
  ],

  ch31: [
    L({
      id: '31.1',
      title: '所有 Sylow p-subgroups 只是不同座標版本',
      lede: 'Sylow II 說 maximal p-structure 沒有不同「種類」：任兩個 Sylow p-subgroups 彼此 conjugate。',
      predict: [
        '兩個 Sylow p-subgroups 必須是同一 subset 嗎？',
        false,
        '它們可能不同，但一定 conjugate。',
        '唯一性比 conjugacy 更強。',
      ],
      kind: 'network',
      modelTitle: '讓 G conjugate 一個 Sylow subgroup',
      prompt: '亮點是 subgroup-space 中的整個 orbit。',
      presets: [
        {
          label: 'one Sylow P',
          nodes: nodes(['P₁', 'P₂', 'P₃', 'other subgroups'], ['P₂', 'P₃'], 'P₁'),
          actions: ['gPg⁻¹'],
          formula: 'all Sylow p-subgroups in one orbit',
          detail: 'Conjugation 只換 ambient coordinates。',
          status: 'good',
        },
        {
          label: 'P normal',
          nodes: nodes(['P'], [], 'P'),
          actions: ['gPg⁻¹=P'],
          formula: 'n_p=1',
          detail: 'Orbit singleton 正好表示 unique and normal。',
          status: 'good',
        },
      ],
      insight:
        'Sylow II 把所有 maximal p-subgroups 放進同一 conjugacy orbit；差異只是位置，不是 type。',
      transfer: [
        '若 Sylow p-subgroup unique，是否 normal？',
        true,
        '所有 conjugates 仍是 Sylow；唯一性迫使 gPg⁻¹=P。',
        '反之 normal Sylow 的 orbit 也 singleton。',
      ],
      formal: [
        'Sylow II',
        'Any two Sylow p-subgroups are conjugate。Hence P normal iff it is unique。',
      ],
      proof: [
        'Action proof roadmap',
        '固定 Sylow Q，讓 Q 以 left multiplication 作用在 G/P cosets。',
        '因 |G/P| 不 divisible by p，Q-action 必有 fixed coset。',
        'Fixed gP 表示 Q≤gPg⁻¹。',
        '兩邊 order 都 p^n，所以 Q=gPg⁻¹。',
      ],
      boundary: '不同非-maximal p-subgroups 不一定全部 conjugate。',
    }),
    L({
      id: '31.2',
      title: 'Sylow 數量必須整除非-p 部分',
      lede: 'Conjugation action 在 Sylow set 上 transitive，所以 n_p 是一個 orbit size；它等於 normalizer 的 index，必整除 |G|，且自身不含 p-factor。',
      predict: [
        '若 |G|=p^n m，n_p 是否必整除 m？',
        true,
        'n_p=[G:N_G(P)]，且 P≤N_G(P) 吸收全部 p^n。',
        '剩餘 index 只能來自 m。',
      ],
      kind: 'partition',
      modelTitle: '把 G 按同一 Sylow stabilizer 分成 fibers',
      prompt: '每塊 coordinate changes 產生同一 conjugate subgroup。',
      presets: [
        {
          label: 'normalizer fibers',
          blocks: [
            { label: 'P₁', items: ['N_G(P) coset'] },
            { label: 'P₂', items: ['same size'] },
            { label: '…', items: ['n_p blocks'] },
          ],
          formula: 'n_p=[G:N_G(P)]',
          detail: 'Orbit–stabilizer applied to subgroup conjugation。',
          status: 'good',
        },
        {
          label: 'p-part absorbed',
          blocks: [
            { label: 'N_G(P)', items: ['contains P of pⁿ'], state: 'active' },
            { label: 'index', items: ['divides m'] },
          ],
          formula: 'n_p | m',
          detail: 'Normalizer 已包含 group order 的全部 p-power。',
          status: 'good',
        },
      ],
      insight:
        'n_p 的 divisibility constraint 來自 orbit–stabilizer；Sylow set 的 movement 受 normalizer 控制。',
      transfer: [
        'Order 12 group 的 n_3 是否只能是 1 或 4？',
        true,
        'n_3 divides 4；再配合下一節 n_3≡1 mod3。',
        '兩條限制合併後只剩 1,4。',
      ],
      formal: ['First Sylow III constraint', '若 |G|=p^n m，則 n_p divides m。'],
      proof: [
        'Normalizer index',
        'G conjugates Sylow subgroups transitively。',
        'Stabilizer of P 是 N_G(P)={g:gPg⁻¹=P}。',
        '所以 n_p=[G:N_G(P)]。',
        'P≤N_G(P)，故 p^n divides |N_G(P)|，index divides m。',
      ],
      boundary: 'n_p divides m 仍可能留下多個 candidates；需要 congruence condition 一起使用。',
    }),
    L({
      id: '31.3',
      title: 'Sylow 數量除以 p 會餘 1',
      lede: '讓 P 自己 conjugate 全部 Sylow p-subgroups。P 固定自己；其他 P-orbits 大小是 p 的倍數，因此總數 n_p≡1 mod p。',
      predict: [
        'n_p 能否等於 p？',
        false,
        'p≡0 mod p，不符合 n_p≡1。',
        '可能是 1、p+1、2p+1…且還需整除 m。',
      ],
      kind: 'partition',
      modelTitle: '把 Sylow set 按 P-orbits 分塊',
      prompt: '先找 fixed subgroup，再看其他 p-sized movement blocks。',
      presets: [
        {
          label: 'fixed P',
          blocks: [
            { label: 'P itself', items: ['1 fixed point'], state: 'active' },
            { label: 'other Sylows', items: ['unclassified'] },
          ],
          formula: 'at least one fixed',
          detail: 'P conjugates itself to itself。',
          status: 'neutral',
        },
        {
          label: 'remaining orbits',
          blocks: [
            { label: 'P', items: ['1'] },
            { label: 'orbit A', items: ['p-multiple'] },
            { label: 'orbit B', items: ['p-multiple'] },
          ],
          formula: 'n_p=1+kp',
          detail: 'Nontrivial P-orbits have p-power sizes divisible by p。',
          status: 'good',
        },
      ],
      insight:
        'n_p≡1 mod p 是 p-group orbit arithmetic：一個 forced fixed point，加上若干 p-multiple blocks。',
      transfer: [
        '若 n_p divides m 且唯一符合 ≡1 mod p 的 divisor 是 1，P 是否 normal？',
        true,
        'n_p=1，unique Sylow is normal。',
        '這是最常用的 normal subgroup detector。',
      ],
      formal: ['Second Sylow III constraint', 'n_p≡1 (mod p)。'],
      proof: [
        '為何唯一 fixed point 是 P',
        'P acts by conjugation on Sylow set。',
        '若 Q fixed by all P，則 P≤N_G(Q)。',
        'PQ 在 N_G(Q) 中形成 p-subgroup；Q maximal 迫使 P≤Q。',
        'Orders equal，故 P=Q；其他 orbits size divisible by p。',
      ],
      boundary:
        'Congruence 與 divisibility 都是必要條件；candidate 數量可能仍需其他 arguments 排除。',
    }),
    L({
      id: '31.4',
      title: '兩條數量限制能逼出有限群骨架',
      lede: '對每個 prime 列出 n_p candidates。若某個 n_p 被迫為 1，就得到 normal subgroup；再用 quotient、actions 或 products 繼續拆解。',
      predict: [
        'Order 15 group 的 Sylow 5-subgroup 是否必 normal？',
        true,
        'n_5 divides 3 且 n_5≡1 mod5，只能 1。',
        '最大 5-structure 唯一。',
      ],
      kind: 'diagnostic',
      modelTitle: 'Small-order group 的 Sylow worksheet',
      prompt: '先列 candidates，再讀結構 consequence。',
      presets: [
        {
          label: '|G|=15',
          checks: [
            check('n₅|3', true, 'candidates 1,3。'),
            check('n₅≡1 mod5', true, '只剩 1。'),
            check('5-Sylow normal', true, 'unique。'),
            check('n₃', true, '1 or 5。'),
          ],
          detail: '至少得到一個 normal building block。',
          status: 'good',
        },
        {
          label: '|G|=12',
          checks: [
            check('n₃|4', true, '1,2,4。'),
            check('n₃≡1 mod3', true, '1 or 4。'),
            check('normal?', false, '尚有兩候選。'),
          ],
          detail: 'Constraints 縮小但未唯一決定。',
          status: 'neutral',
        },
        {
          label: '錯誤推論',
          checks: [
            check('n_p candidate', true, '通過數論限制。'),
            check('一定實現', false, 'conditions 不保證每 candidate 都存在。'),
          ],
          detail: 'Sylow III 給必要條件，不是 construction theorem。',
          status: 'bad',
        },
      ],
      insight:
        'Sylow analysis 是 constraint solver：prime-power subgroups 是骨架，normality 則提供 quotient 與重建入口。',
      transfer: [
        'Order 21 group 的 Sylow 7-subgroup是否必 normal？',
        true,
        'n_7 divides 3 且 ≡1 mod7，只能 1。',
        '因此可從 normal C₇-like structure 開始分析。',
      ],
      formal: [
        'Sylow workflow',
        'For each p: compute p^n, list n_p divisors of m congruent 1 mod p, infer normality when n_p=1。',
      ],
      proof: [
        '負責任的結論層級',
        '唯一 candidate 1 ⇒ normal Sylow。',
        '多 candidates ⇒ 保留 branches。',
        '可再用 element counting、group actions 或 conjugation 排除 branches。',
        '不可僅因某 candidate 好看就選它。',
      ],
      boundary: 'Sylow data 通常不會單獨 classify group；它提供的是骨架與下一步問題。',
    }),
  ],

  ch32: [
    L({
      id: '32.1',
      title: '先問元素是 actions，還是只看到一張表',
      lede: '面對陌生群，第一步不是搜尋可套定理；先找它作用在哪個 state space，或建立 Cayley／permutation model，讓 composition 產生可追蹤的因果。',
      predict: [
        '陌生 operation table 一上來就列所有 subgroups，是否總是最佳第一步？',
        false,
        '先找 identity、orders、generators 與 action pattern 通常更能壓縮問題。',
        '結構掃描應先於暴力枚舉。',
      ],
      kind: 'diagnostic',
      modelTitle: '陌生群的第一分鐘掃描',
      prompt: '依問題表面選 representation，不必每項都做。',
      presets: [
        {
          label: 'table given',
          checks: [
            check('identity/inverses', true, '定位 contract roles。'),
            check('element orders', true, '找 cycles。'),
            check('generators', true, '看 connectivity。'),
            check('commutativity', true, '找 order-sensitive pair。'),
          ],
          detail: '從 operation data 提取 action skeleton。',
          status: 'good',
        },
        {
          label: 'symmetries given',
          checks: [
            check('state space', true, '什麼被操作？'),
            check('basic moves', true, 'generators。'),
            check('relations', true, '哪些 loops close？'),
            check('orbits', true, '哪些 objects 可互達？'),
          ],
          detail: '直接利用 transformation semantics。',
          status: 'good',
        },
      ],
      insight:
        'Representation 是解題的第一個選擇；好的 state model 會讓群元素重新變成可理解的 actions。',
      transfer: [
        '若 group abstract，Cayley theorem 是否永遠提供一個 fallback action model？',
        true,
        '讓 G left-act on itself。',
        '它未必最小，但一定 faithful。',
      ],
      formal: [
        'Structural scan',
        'Useful first invariants: |G|、element orders、center、commutativity、generators/relations、obvious actions。',
      ],
      proof: [
        '避免 theorem roulette',
        '先寫問題要求的是 equality、existence、counting 還是 classification。',
        '選能讓目標可見的 representation。',
        '再挑相應工具。',
        '定理是 response to structure，不是隨機嘗試。',
      ],
      boundary: 'Checklist 不是每題固定流程；若問題已給自然 action，就不必先重建 operation table。',
    }),
    L({
      id: '32.2',
      title: '遇到壓縮問題，就找 map、kernel、quotient、image',
      lede: '若題目把某些 differences 視為相同，或只保留某個 observable，homomorphism pipeline 通常比直接操作 equivalence classes 更清楚。',
      predict: [
        '要證 G/N≅H，先找 surjective φ:G→H with kernel N 是否常是好策略？',
        true,
        'First isomorphism theorem 會完成 quotient-to-image 對齊。',
        'map 直接解釋哪些資訊被忘掉。',
      ],
      kind: 'timeline',
      modelTitle: 'Compression route selector',
      prompt: '從 observable 開始，而不是從 slash notation 開始。',
      presets: [
        {
          label: 'define observable',
          before: 'G',
          actions: ['φ 保留 operation'],
          after: 'imφ',
          formula: 'what remains visible?',
          detail: '先說清楚 output meaning。',
          status: 'neutral',
        },
        {
          label: 'find invisible differences',
          before: 'G',
          actions: ['solve φ(g)=e'],
          after: 'kerφ',
          formula: 'what is forgotten?',
          detail: 'Kernel 決定 fibers。',
          status: 'good',
        },
        {
          label: 'compress and align',
          before: 'G',
          actions: ['quotient by kerφ', 'induced isomorphism'],
          after: 'imφ',
          formula: 'G/kerφ≅imφ',
          detail: '完成受控壓縮。',
          status: 'good',
        },
      ],
      insight: 'Quotient 不是技巧終點；它是觀察 map 的自然資料結構。',
      transfer: [
        'Normal subgroup 不知如何理解時，嘗試把它實現為 projection kernel 是否有效？',
        true,
        'N◁G gives π:G→G/N with kernel N。',
        '每個 normal subgroup 都是某 map 的 invisible part。',
      ],
      formal: [
        'Map route',
        'Homomorphism problems: verify law → kernel → image → induced quotient isomorphism。',
      ],
      proof: [
        '常見錯誤防線',
        '先證 homomorphism，不能只說 map natural。',
        'Kernel 與 image 要精確雙向包含。',
        'Quotient operation 要有 normality／well-definedness。',
        '最後再引用 first isomorphism theorem。',
      ],
      boundary:
        '不是每個 equivalence relation 都與 group operation 相容；只有 congruence-like／normal fibers 可形成 quotient group。',
    }),
    L({
      id: '32.3',
      title: '遇到移動與計數，就選 action、orbit、stabilizer',
      lede: '「哪些 objects 視為相同」「一個 object 有多少 symmetries」「總共有幾類」都是 action questions，只是固定的變數不同。',
      predict: [
        '要數 symmetry classes，orbit–stabilizer 是否總比 Burnside 直接？',
        false,
        'Orbit sizes 不一致時，Burnside 的 fixed-point average 更合適。',
        '工具取決於已知的是單點 local symmetry 還是每個 action 的 fixed states。',
      ],
      kind: 'diagnostic',
      modelTitle: 'Action route selector',
      prompt: '依 question type 選觀察方向。',
      presets: [
        {
          label: '能到哪裡？',
          checks: [
            check('tool', true, 'orbit。'),
            check('fixed variable', true, 'state x。'),
            check('scan', true, 'all g。'),
          ],
          detail: 'Reachability question。',
          status: 'good',
        },
        {
          label: '誰不動它？',
          checks: [
            check('tool', true, 'stabilizer。'),
            check('output', true, 'subgroup G_x。'),
            check('count link', true, 'orbit–stabilizer。'),
          ],
          detail: 'Local symmetry question。',
          status: 'good',
        },
        {
          label: '有幾類？',
          checks: [
            check('tool', true, 'Burnside。'),
            check('count', true, 'Fix(g) by action type。'),
            check('average', true, 'divide by |G|。'),
          ],
          detail: 'Global orbit count。',
          status: 'good',
        },
      ],
      insight: 'Orbit、stabilizer、Burnside 不是三套公式，而是同一 action table 的三種讀法。',
      transfer: [
        'Conjugacy class size 是否也是 action tool 的結果？',
        true,
        'conjugation orbit + centralizer stabilizer。',
        'class equation 也來自這條 route。',
      ],
      formal: [
        'Action route',
        'Model G↷X → identify orbits/stabilizers → apply orbit–stabilizer or fixed-point double counting。',
      ],
      proof: [
        '選工具前的三問',
        'States X 是什麼？',
        '何時兩 states 應算 equivalent？',
        '哪些 g fix a state，或每個 g fix 多少 states？',
        '回答後公式才有可解釋的 inputs。',
      ],
      boundary: '若 equivalence 不是 group action orbit，Burnside average 沒有適用基礎。',
    }),
    L({
      id: '32.4',
      title: 'Finite group analysis 是逐步縮小可能世界',
      lede: 'Group order 提供 prime capacity；Cauchy/Sylow 逼出 subgroups；unique Sylow 給 normality；quotient 與 action 再把問題降階。',
      predict: [
        'Sylow constraints 留下兩個 n_p candidates 時，是否應任選一個繼續？',
        false,
        '必須保留 branches 或找額外 counting/action constraint。',
        'Classification 是排除與重建，不是猜答案。',
      ],
      kind: 'lattice',
      modelTitle: '從 order data 長出 structural decision tree',
      prompt: '每上一層不是「更難定理」，而是更多可用結構。',
      presets: [
        {
          label: 'finite workflow',
          blocks: [
            {
              label: 'reconstruct / classify',
              items: ['final candidates'],
              level: 0,
              state: 'active',
            },
            { label: 'normal subgroup + quotient', items: ['reduce order'], level: 1 },
            { label: 'Sylow candidates', items: ['n_p constraints'], level: 2 },
          ],
          formula: 'order → p-parts → normality → quotient',
          detail: '每一步縮小可能 structures。',
          status: 'good',
        },
        {
          label: 'action branch',
          blocks: [
            { label: 'count / contradiction', items: ['orbit data'], level: 0 },
            {
              label: 'choose action',
              items: ['cosets, subgroups, objects'],
              level: 1,
              state: 'active',
            },
            { label: 'group order', items: ['divisibility'], level: 2 },
          ],
          formula: 'action exposes hidden constraints',
          detail: '若 subgroup data 不夠，讓群作用在有意義的 set。',
          status: 'good',
        },
      ],
      insight:
        'Finite group theory 是 constraint-guided reconstruction：每個 theorem 都提供可見骨架或降階入口。',
      transfer: [
        '找到 proper nontrivial normal N 後，分析 N 與 G/N 是否常比直接分析 G 容易？',
        true,
        '兩者 orders 較小，且 G 是它們的 extension。',
        '但重建 extension 仍可能有多種方式。',
      ],
      formal: [
        'Finite-group route',
        'Factor |G| → Sylow counts → normal subgroups → quotients/actions → extensions or contradictions。',
      ],
      proof: [
        '分類結論的責任',
        '列出所有 surviving cases。',
        '對每 case 構造或證明不可能。',
        '證明不同 constructions 是否 isomorphic。',
        '不能只展示一個 example 就宣稱唯一。',
      ],
      boundary:
        'Sylow theorems 不會自動完成 classification；extensions 可能產生多個 nonisomorphic groups。',
    }),
  ],
};
