import type { AlgebraV2Lesson } from './algebra-v2-lessons';
import { check, makeLesson as L, networkNodes as nodes } from './algebra-v2-lesson-builder';

type Part3ChapterId = 'ch14' | 'ch15' | 'ch16' | 'ch17' | 'ch18';

export const ALGEBRA_V2_PART3_LESSONS: Record<Part3ChapterId, AlgebraV2Lesson[]> = {
  ch14: [
    L({
      id: '14.1',
      title: '翻譯可以壓縮，但不能改寫合成',
      lede: 'Isomorphism 要求沒有資訊損失；homomorphism 放寬這點，允許多個 inputs 看成同一 output，但 action chain 的運作方式仍必須保留。',
      predict: [
        '把整數只記成奇偶，是否一定會破壞加法？',
        false,
        '奇偶仍滿足「和的奇偶由兩數奇偶合成」。',
        '對；它遺忘數值，卻保留 addition。',
      ],
      kind: 'mapping',
      modelTitle: '看見 many-to-one 的結構翻譯',
      prompt: '切換映射，分開檢查 collision 與 operation preservation。',
      presets: [
        {
          label: 'mod 2',
          mapping: [
            { from: '…,-2,0,2,…', to: 'even' },
            { from: '…,-1,1,3,…', to: 'odd' },
          ],
          checks: [
            check('injective', false, '很多 integers 共用 output。'),
            check('保留加法', true, 'parity(a+b)=parity(a)+parity(b)。'),
          ],
          detail: '資訊被壓縮，但合成規律留下。',
          status: 'good',
        },
        {
          label: '取絕對值',
          mapping: [
            { from: '−2', to: '2' },
            { from: '1', to: '1' },
          ],
          checks: [
            check('injective', false, '±a collision。'),
            check('保留加法', false, '|−2+1|≠|−2|+|1|。'),
          ],
          detail: '不只壓縮，還改壞 operation。',
          status: 'bad',
        },
      ],
      insight: 'Homomorphism 可以遺忘「是哪個 element」，但不能遺忘「elements 如何合成」。',
      transfer: [
        'det:GL₂(R)→R× 是否可能是 homomorphism？',
        true,
        'det(AB)=det(A)det(B)。',
        '它保留 multiplication，雖然很多矩陣有相同 determinant。',
      ],
      formal: [
        'Group homomorphism',
        'Map φ:G→H 若對所有 a,b∈G 都滿足 φ(ab)=φ(a)φ(b)，就是 group homomorphism。',
        '\\varphi(ab)=\\varphi(a)\\varphi(b)',
      ],
      proof: [
        '壓縮不是故障',
        '判斷重點是 commuting square。',
        '任取 a,b。',
        '比較 φ(ab) 與 φ(a)φ(b)。',
        '相等即可保留 operation；injectivity 是另一個問題。',
      ],
      boundary: '任意 function、bijection 或「看起來自然」的摘要都不自動是 homomorphism。',
    }),
    L({
      id: '14.2',
      title: '兩條處理路徑必須永遠同終點',
      lede: 'Homomorphism law 是一張 commuting square：先在 G 合成再翻譯，或先翻譯到 H 再合成，結果不可分岔。',
      predict: [
        '只檢查 φ(e)=e，是否足夠證明 φ 是 homomorphism？',
        false,
        'identity 只是一個 input，law 要控制所有 pairs。',
        '對；許多壞 maps 也會把 identity 送到 identity。',
      ],
      kind: 'timeline',
      modelTitle: '沿方形的上路與下路行走',
      prompt: '同一 pair 走兩條 pipeline；終點一致才通過。',
      presets: [
        {
          label: '先合成',
          before: '(7,5)',
          actions: ['7+5=12', 'mod 4'],
          after: '0',
          formula: 'φ(7+5)=0',
          detail: '上路先使用 domain operation。',
          status: 'good',
        },
        {
          label: '先映射',
          before: '(7,5)',
          actions: ['7↦3, 5↦1', '3+₄1'],
          after: '0',
          formula: 'φ(7)+φ(5)=0',
          detail: '下路同終點，這個 pair 相容。',
          status: 'good',
        },
        {
          label: '平方 map',
          before: '(2,3)',
          actions: ['(2+3)²', '2²+3²'],
          after: '25 vs 13',
          formula: 'φ(a+b)≠φ(a)+φ(b)',
          detail: '一個分岔 pair 足以推翻。',
          status: 'bad',
        },
      ],
      insight:
        'Structure preservation 不是 output 長得像，而是 mapping 與 composition 的先後順序可交換。',
      transfer: [
        'φ:Z→Z₅, φ(n)=[n] 是否保留 addition？',
        true,
        '[a+b]=[a]+[b]。',
        '兩條路對任意 integers 都同終點。',
      ],
      formal: [
        'Commuting law',
        'Homomorphism law 是全稱 equality；有限群可查 table，無限群需要 general argument。',
      ],
      proof: [
        '如何用 generators 減少檢查？',
        '若 G 由 S 生成，先指定 generators 的 images。',
        '確認 defining relations 在 H 仍成立。',
        '每個 word 的 image 就由 operation law 被迫決定。',
        '因此可把無限 pairs 壓縮成 generator／relation 檢查。',
      ],
      boundary: '只在抽樣 pairs 上成功仍不是證明；一個失敗 pair 則已是完整反例。',
    }),
    L({
      id: '14.3',
      title: 'Identity 與 inverse 不必另外要求',
      lede: '一旦 map 保留 composition，identity 與 undo 的角色會被 operation 自動帶過去；這些是 law 的後果。',
      predict: [
        'Group homomorphism 可能把 e_G 送到 H 的非 identity element 嗎？',
        false,
        'φ(e)=φ(e)φ(e)，cancel 後只能是 e_H。',
        '對；group cancellation 強迫 identity 對齊。',
      ],
      kind: 'symbols',
      modelTitle: '追蹤 roles 如何穿過 mapping',
      prompt: '切換 consequence，看 formal symbol 背後的 action role。',
      presets: [
        {
          label: 'identity',
          mapping: [{ from: 'e_G：不改變', to: 'e_H：不改變' }],
          formula: 'φ(e_G)=e_H',
          detail: '停留 action 被翻成停留 action。',
          status: 'good',
        },
        {
          label: 'inverse',
          mapping: [{ from: 'a⁻¹：撤銷 a', to: 'φ(a)⁻¹：撤銷 φ(a)' }],
          formula: 'φ(a⁻¹)=φ(a)⁻¹',
          detail: 'undo role 也被保留。',
          status: 'good',
        },
        {
          label: 'powers',
          mapping: [{ from: 'aⁿ：重複 n 次', to: 'φ(a)ⁿ：重複 n 次' }],
          formula: 'φ(aⁿ)=φ(a)ⁿ',
          detail: '整條 repeated-action chain 可逐步翻譯。',
          status: 'good',
        },
      ],
      insight: '保留合成後，identity、inverse 與 powers 都不是額外規則，而是結構角色的必然影子。',
      transfer: [
        '若 a 的 order 是 6，φ(a) 的 order 必須等於 6 嗎？',
        false,
        'homomorphism 可壓縮 cycle，image order 只保證整除 6。',
        '對；例如 mod 3 projection 把六步 cycle 壓成三步。',
      ],
      formal: [
        'Automatic consequences',
        '任意 group homomorphism 滿足 φ(e)=e、φ(a⁻¹)=φ(a)⁻¹、φ(aⁿ)=φ(a)ⁿ。',
      ],
      proof: [
        '證明 inverse 被保留',
        'aa⁻¹=e_G。',
        '映射得 φ(a)φ(a⁻¹)=φ(e_G)=e_H。',
        '所以 φ(a⁻¹) 是 φ(a) 的 inverse。',
        'Inverse 唯一，故 φ(a⁻¹)=φ(a)⁻¹。',
      ],
      boundary: 'Element order 可能在 homomorphism 下縮短；只有 isomorphism 才保證完整保留。',
    }),
  ],

  ch15: [
    L({
      id: '15.1',
      title: 'Image 是鏡頭真正看得到的輸出世界',
      lede: 'Codomain 是允許的整個畫布；image 只包含實際被某個 input 命中的 outputs。兩者不能混為一談。',
      predict: [
        'Map φ:Z→Z₆, φ(n)=[2n] 的 image 是全部 Z₆ 嗎？',
        false,
        '只能命中 0、2、4。',
        '對；1、3、5 雖在 codomain，卻沒有 preimage。',
      ],
      kind: 'network',
      modelTitle: '從 inputs 點亮真正可達的 outputs',
      prompt: '亮點屬於 image，暗點只是 codomain 的未命中位置。',
      presets: [
        {
          label: 'φ(n)=2n mod 6',
          nodes: nodes(['0', '1', '2', '3', '4', '5'], ['2', '4'], '0'),
          actions: ['0↦0', '1↦2', '2↦4'],
          formula: 'im φ={0,2,4}',
          detail: 'image 只有三個 reachable outputs。',
          status: 'good',
        },
        {
          label: 'φ(n)=n mod 6',
          nodes: nodes(['0', '1', '2', '3', '4', '5'], ['1', '2', '3', '4', '5'], '0'),
          actions: ['0…5'],
          formula: 'im φ=Z₆',
          detail: '每個 output 都有 preimage，map 是 surjective。',
          status: 'good',
        },
      ],
      insight: 'Image 是 map 能表達的全部 effects；surjective 表示鏡頭覆蓋整個 codomain。',
      transfer: [
        'det:GL₂(R)→R× 的 image 是全部 nonzero reals 嗎？',
        true,
        'diag(r,1) 的 determinant 是任意 r≠0。',
        '所以每個 codomain element 都可被命中。',
      ],
      formal: [
        'Image',
        'im φ={φ(g):g∈G}，也常寫 φ(G)。',
        '\\operatorname{im}\\varphi=\\{\\varphi(g):g\\in G\\}',
      ],
      proof: [
        'Image 為何是 subgroup？',
        '使用 subgroup test。',
        '取 φ(a),φ(b)∈im φ。',
        'φ(a)φ(b)⁻¹=φ(a)φ(b⁻¹)=φ(ab⁻¹)。',
        '結果仍是某個 input 的 image。',
      ],
      boundary: 'Codomain 可被刻意選大；image 才反映 map 實際到達的結構。',
    }),
    L({
      id: '15.2',
      title: 'Kernel 是鏡頭完全看不見的 actions',
      lede: '若某個 action 映到 output identity，這個觀察方式就無法分辨「做了它」與「什麼都沒做」。',
      predict: [
        'Parity map Z→Z₂ 的 kernel 是所有偶整數嗎？',
        true,
        '偶數都映到 0，也只有偶數如此。',
        '它們對 parity 鏡頭都等同不動。',
      ],
      kind: 'mapping',
      modelTitle: '反向尋找 identity 的整條 fiber',
      prompt: '不要找所有 collisions；先專注 output identity 下方有哪些 inputs。',
      presets: [
        {
          label: 'mod 2',
          mapping: [
            { from: '…,-4,-2,0,2,4,…', to: '0 identity', accent: true },
            { from: 'odd integers', to: '1' },
          ],
          formula: 'ker φ=2Z',
          detail: '所有偶數差異被壓成 identity。',
          status: 'good',
        },
        {
          label: 'det',
          mapping: [
            { from: 'det(A)=1 matrices', to: '1 identity', accent: true },
            { from: '其他 invertible matrices', to: 'r≠1' },
          ],
          formula: 'ker(det)=SL₂(R)',
          detail: 'determinant 看不見 area-preserving matrices 之間的細節。',
          status: 'good',
        },
      ],
      insight: 'Kernel 不只是「被刪掉的資料」；它精確列出哪些 domain actions 對此 map 完全不可見。',
      transfer: [
        'Injective homomorphism 的 kernel 是否只能是 {e}？',
        true,
        '若 φ(g)=e=φ(e)，injectivity 迫使 g=e。',
        '沒有非平凡 action 被壓成 identity。',
      ],
      formal: [
        'Kernel',
        'ker φ 是 identity output 的 preimage。',
        '\\ker\\varphi=\\{g\\in G:\\varphi(g)=e_H\\}',
      ],
      proof: [
        'Kernel 為何是 subgroup？',
        '套用 subgroup test。',
        '若 a,b∈ker φ，則 φ(a)=φ(b)=e。',
        'φ(ab⁻¹)=φ(a)φ(b)⁻¹=ee⁻¹=e。',
        '所以 ab⁻¹∈ker φ。',
      ],
      boundary: 'Kernel 屬於 domain；image 屬於 codomain。把兩者畫在同一側會破壞因果。',
    }),
    L({
      id: '15.3',
      title: '相同 output 表示兩 inputs 只差一個 kernel action',
      lede: 'Kernel 不只描述 identity fiber。每一條 output fiber 都是 kernel 的 translate，因此所有 collisions 都由同一套不可見差異控制。',
      predict: [
        '對 homomorphism φ，若 φ(a)=φ(b)，是否必有 b⁻¹a∈ker φ？',
        true,
        'φ(b⁻¹a)=φ(b)⁻¹φ(a)=e。',
        '兩 inputs 的相對差異對鏡頭不可見。',
      ],
      kind: 'partition',
      modelTitle: '把 domain 按相同 output 分成 fibers',
      prompt: '每塊 tile 是一個 kernel coset；塊內 elements 映到同一 output。',
      presets: [
        {
          label: 'mod 3 fibers',
          blocks: [
            { label: 'output 0', items: ['…', '−3', '0', '3', '…'], state: 'active' },
            { label: 'output 1', items: ['…', '−2', '1', '4', '…'] },
            { label: 'output 2', items: ['…', '−1', '2', '5', '…'] },
          ],
          formula: 'fibers = cosets of 3Z',
          detail: '每個 residue class 是 kernel 的 translate。',
          status: 'good',
        },
        {
          label: '同一 fiber',
          blocks: [{ label: 'a ker φ = b ker φ', items: ['a', 'b', '同 output'], state: 'active' }],
          formula: 'φ(a)=φ(b) ⇔ a kerφ=b kerφ',
          detail: 'Map 無法分辨的正是同一 coset。',
          status: 'good',
        },
      ],
      insight: 'Kernel 是 collision 的共同模板；每個 output fiber 都是一塊 kernel coset。',
      transfer: [
        'mod 5 map 下，7 與 22 是否在同一 kernel coset？',
        true,
        '22−7=15∈5Z。',
        '兩者都映到 residue 2。',
      ],
      formal: ['Fiber–coset principle', 'φ(a)=φ(b) iff b⁻¹a∈ker φ，iff a kerφ=b kerφ。'],
      proof: [
        '推導 collision criterion',
        'φ(a)=φ(b)。',
        '左乘 φ(b)⁻¹，得 φ(b)⁻¹φ(a)=e。',
        '由 homomorphism law，這是 φ(b⁻¹a)=e。',
        '所以 b⁻¹a∈ker φ；反向逐步倒推。',
      ],
      boundary: '一般 function 的 fibers 不必是 cosets；這個整齊結構來自 homomorphism law。',
    }),
    L({
      id: '15.4',
      title: 'Injective 與 surjective 可直接從 kernel、image 讀出',
      lede: '與其逐對找 collision 或逐點找 preimage，homomorphism 有兩個結構儀表：kernel 是否只剩 identity、image 是否覆蓋 codomain。',
      predict: [
        'ker φ={e} 且 im φ=H，是否足以推出 φ:G→H 是 isomorphism？',
        true,
        '前者給 injective，後者給 surjective，且 φ 已保留 operation。',
        '三項合起來就是 bijective homomorphism。',
      ],
      kind: 'diagnostic',
      modelTitle: '用兩個儀表診斷 map',
      prompt: 'Kernel 控制資訊損失；image 控制輸出覆蓋。',
      presets: [
        {
          label: 'embedding',
          checks: [
            check('kernel={e}', true, '沒有 collision。'),
            check('image=H', false, '只命中一個 subgroup。'),
            check('結論', false, 'injective 但非 surjective。'),
          ],
          detail: '把小群嵌入大群。',
          status: 'neutral',
        },
        {
          label: 'quotient map',
          checks: [
            check('kernel={e}', false, '整個 N 被壓平。'),
            check('image=H', true, '每個 coset 命中。'),
            check('結論', false, 'surjective 但非 injective。'),
          ],
          detail: '完整覆蓋輸出，但有受控壓縮。',
          status: 'neutral',
        },
        {
          label: 'isomorphism',
          checks: [
            check('kernel={e}', true, 'injective。'),
            check('image=H', true, 'surjective。'),
            check('結論', true, 'isomorphism。'),
          ],
          detail: '沒有遺失也沒有缺漏。',
          status: 'good',
        },
      ],
      insight:
        'Kernel 回答「壓掉多少」；image 回答「看見多少」。兩者合起來描述 homomorphism 的資訊流。',
      transfer: [
        '若 finite G,H 大小相同，injective homomorphism 是否自動 surjective？',
        true,
        '有限等大 sets 的 injection 必為 bijection。',
        '因此可直接得到 isomorphism。',
      ],
      formal: ['Two structural tests', 'φ injective iff kerφ={e}；φ surjective iff imφ=H。'],
      proof: [
        '證明 trivial kernel 推出 injective',
        '假設 φ(a)=φ(b)。',
        '則 b⁻¹a∈kerφ。',
        'Kernel 只有 e，所以 b⁻¹a=e。',
        '因此 a=b。',
      ],
      boundary:
        '這兩個測試預設 φ 已是 homomorphism；對任意 function，identity fiber 無法控制所有 collisions。',
    }),
  ],

  ch16: [
    L({
      id: '16.1',
      title: 'Kernel 搬到任何座標仍然不可見',
      lede: '若 n 被 map 壓成 identity，把它放進任意 context gng⁻¹ 後仍會映到 identity。這種對 conjugation 的穩定性就是 normality 的來源。',
      predict: [
        '每個 homomorphism 的 kernel 都是 normal subgroup 嗎？',
        true,
        'φ(gng⁻¹)=φ(g)eφ(g)⁻¹=e。',
        '不可見差異在換座標後仍不可見。',
      ],
      kind: 'timeline',
      modelTitle: '把不可見 action 搬到另一個 context',
      prompt: '追蹤 g、n、g⁻¹ 經過 map 後如何消失。',
      presets: [
        {
          label: 'domain path',
          before: 'state',
          actions: ['g⁻¹ 換座標', 'n', 'g 換回'],
          after: 'gng⁻¹',
          formula: 'n∈kerφ',
          detail: 'Conjugation 改變 n 所在的座標位置。',
          status: 'neutral',
        },
        {
          label: 'mapped path',
          before: 'output',
          actions: ['φ(g)', 'e', 'φ(g)⁻¹'],
          after: 'e',
          formula: 'φ(gng⁻¹)=e',
          detail: '中間不可見，外側又彼此撤銷。',
          status: 'good',
        },
      ],
      insight: 'Normal subgroup 是一套在任何 group context 中都保持同類的「可忽略差異」。',
      transfer: [
        'Abelian group 的每個 subgroup 都 normal 嗎？',
        true,
        'gng⁻¹=ngg⁻¹=n。',
        'commutativity 讓 conjugation 不改變元素。',
      ],
      formal: ['Normal subgroup', 'N≤G 若對所有 g∈G 有 gNg⁻¹=N，記作 N◁G。', 'N\\trianglelefteq G'],
      proof: [
        'Kernel normality',
        '取 n∈kerφ 與任意 g∈G。',
        'φ(gng⁻¹)=φ(g)φ(n)φ(g)⁻¹。',
        '=φ(g)eφ(g)⁻¹=e。',
        '所以 gng⁻¹∈kerφ；反向 inclusion 用 g⁻¹。',
      ],
      boundary: 'Normal 不表示 n 與所有 g commute；它只保證 conjugate 仍留在 N。',
    }),
    L({
      id: '16.2',
      title: 'Normality 讓 left tiles 與 right tiles 對齊',
      lede: '一般 subgroup 從左搬與從右搬會得到不同 tiles。若 N normal，gN 與 Ng 對每個 g 都是同一塊，quotient multiplication 才有一致方向。',
      predict: [
        '只要某一個 g 滿足 gH=Hg，就能推出 H normal 嗎？',
        false,
        'normality 要求所有 g 都對齊。',
        '對；單一代表只是一個局部觀察。',
      ],
      kind: 'partition',
      modelTitle: '比較 left 與 right translates',
      prompt: '切換 subgroup，查看兩種搬移是否逐塊重合。',
      presets: [
        {
          label: 'normal N',
          blocks: [
            { label: 'gN', items: ['gn₁', 'gn₂', 'gn₃'], state: 'active' },
            { label: 'Ng', items: ['n′₁g', 'n′₂g', 'n′₃g'], state: 'active' },
          ],
          formula: 'gN=Ng for every g',
          detail: '元素配對可不同，但兩個 sets 完全相等。',
          status: 'good',
        },
        {
          label: 'non-normal H',
          blocks: [
            { label: 'gH', items: ['x', 'y'] },
            { label: 'Hg', items: ['x', 'z'], state: 'warning' },
          ],
          formula: 'gH≠Hg for some g',
          detail: '出現半重疊或不同 element，normality 失敗。',
          status: 'bad',
        },
      ],
      insight: 'Normality 可視為 left／right coset 系統完全對齊，而不是 subgroup 在圖上「置中」。',
      transfer: [
        'Index 2 subgroup 必定 normal 嗎？',
        true,
        '只有兩塊；非 H 的 left 與 right coset 都只能是其補集。',
        '因此每個 g 的兩種 tiles 對齊。',
      ],
      formal: ['Equivalent tests', 'N◁G iff gNg⁻¹=N for all g，iff gN=Ng for all g。'],
      proof: [
        '由 conjugation 推出 coset 對齊',
        'gNg⁻¹=N。',
        '右乘 g 得 gN=Ng。',
        '反向則由 gN=Ng 再右乘 g⁻¹。',
        '兩種條件等價。',
      ],
      boundary: 'Left cosets 與 right cosets 即使數量、大小相同，也不表示逐塊相等。',
    }),
    L({
      id: '16.3',
      title: 'Normal detector 要測 context stability',
      lede: 'Subgroup test 只問能否自行運作；normal test 多問一層：被 ambient group 任意搬動後，是否仍是同一個子世界。',
      predict: [
        'S₃ 中由一個 reflection 生成的二階 subgroup normal 嗎？',
        false,
        '不同 rotations conjugate 它到另外兩個 reflection subgroups。',
        '它能自行運作，卻不對 ambient context 穩定。',
      ],
      kind: 'diagnostic',
      modelTitle: '分開 subgroup 與 normality 兩關',
      prompt: '先確認 H≤G，再找 conjugation witness 或 general reason。',
      presets: [
        {
          label: 'A₃≤S₃',
          checks: [
            check('是 subgroup', true, '三個 rotations 封閉。'),
            check('conjugation stable', true, 'conjugate of 3-cycle 仍在 A₃。'),
            check('normal', true, '通過兩關。'),
          ],
          detail: 'A₃ 是 kernel of sign map。',
          status: 'good',
        },
        {
          label: '⟨(12)⟩≤S₃',
          checks: [
            check('是 subgroup', true, '{e,(12)} 自行運作。'),
            check('conjugation stable', false, '(123)(12)(123)⁻¹=(23)。'),
            check('normal', false, '一個 witness 已推翻。'),
          ],
          detail: 'Subgroup 不自動 normal。',
          status: 'bad',
        },
        {
          label: '任意 H≤abelian G',
          checks: [
            check('是 subgroup', true, '前提。'),
            check('conjugation stable', true, 'ghg⁻¹=h。'),
            check('normal', true, '全部 subgroups normal。'),
          ],
          detail: 'Abelianity 提供 general proof。',
          status: 'good',
        },
      ],
      insight: 'Normality 不是 subgroup 的內部能力，而是它與整個 ambient group 的相容性。',
      transfer: [
        '若 H 是某 homomorphism 的 kernel，還需要逐個 conjugate 才能知道 normal 嗎？',
        false,
        'kernel normality theorem 已給 general reason。',
        '可以直接引用結構來源。',
      ],
      formal: [
        'Normality verification',
        '常用方法：直接測 gHg⁻¹、證明 left=right cosets、找 kernel representation，或用 index 2。',
      ],
      proof: [
        '反例的最小責任',
        '要推翻 H normal。',
        '先確認 H 的確是 subgroup。',
        '找一個 g∈G 與 h∈H。',
        '展示 ghg⁻¹∉H 即完成。',
      ],
      boundary: '「Normal」不是「常見」「重要」或「commutative」的同義詞。',
    }),
  ],

  ch17: [
    L({
      id: '17.1',
      title: 'Quotient 把整塊不可見差異壓成一點',
      lede: '不再把 G 的 elements 全部分開看；同一 N-coset 中的 elements 只差一個可忽略 action，因此成為 quotient 裡的一個新 element。',
      predict: [
        'G/N 的 elements 是 G 中剩下來的代表元嗎？',
        false,
        '新 elements 是整個 cosets，不是任意挑出的單點。',
        '代表元只是命名 tile 的方式。',
      ],
      kind: 'partition',
      modelTitle: '從細粒度 elements 切換成 coset pixels',
      prompt: '每個 block 在 quotient 視野中縮成一個 node。',
      presets: [
        {
          label: '原本 Z₆',
          blocks: [
            { label: '0+N', items: ['0', '3'] },
            { label: '1+N', items: ['1', '4'] },
            { label: '2+N', items: ['2', '5'] },
          ],
          formula: 'N={0,3}',
          detail: '六個 elements 先按不可見差異分成三塊。',
          status: 'neutral',
        },
        {
          label: 'quotient view',
          nodes: nodes(['N', '1+N', '2+N'], ['1+N', '2+N'], 'N'),
          actions: ['每個 coset ↦ 一點'],
          formula: 'Z₆/N has 3 elements',
          detail: '每塊內部差異不再被分辨。',
          status: 'good',
        },
      ],
      insight:
        'Quotient 的新元素是 indistinguishability classes；它把 kernel-like 差異系統性地忘掉。',
      transfer: [
        'Z/5Z 的 element [2] 是否代表所有與 2 相差 5 的倍數？',
        true,
        '[2]=2+5Z。',
        '它是一整個 coset，不是單一 integer 2。',
      ],
      formal: ['Quotient set', '若 N◁G，G/N={gN:g∈G}。', 'G/N=\\{gN:g\\in G\\}'],
      proof: [
        'Canonical projection 的 fibers',
        '定義 π(g)=gN。',
        'π(a)=π(b) iff aN=bN。',
        '這等價 b⁻¹a∈N。',
        '所以每個 fiber 正是一個 N-coset。',
      ],
      boundary: 'Slash 不是數值 division；它表示把 N-cosets 當成新 elements。',
    }),
    L({
      id: '17.2',
      title: 'Coset multiplication 必須不依賴代表元',
      lede: '若同一 tile 可用很多 representatives 命名，操作結果不能隨挑法改變。Normality 正是 well-definedness 的保證。',
      predict: [
        '可否對任意 subgroup H 定義 (aH)(bH)=abH 成為 group？',
        false,
        '非-normal 時換 representatives 可能得到不同 coset。',
        '對；公式看得懂不代表 operation well-defined。',
      ],
      kind: 'timeline',
      modelTitle: '換 representatives，結果仍要同一 tile',
      prompt: '比較 a′=an₁、b′=bn₂ 與原 representatives。',
      presets: [
        {
          label: '原 representatives',
          before: '(aN,bN)',
          actions: ['選 a,b', '相乘 ab'],
          after: 'abN',
          formula: '(aN)(bN)=abN',
          detail: '這是候選 quotient operation。',
          status: 'neutral',
        },
        {
          label: '換 representatives',
          before: '(an₁,bn₂)',
          actions: ['相乘 an₁bn₂', '用 normality 搬動 n₁'],
          after: 'abN',
          formula: 'an₁bn₂N=abN',
          detail: 'Normality 讓額外 N-factors 被吸回同一 coset。',
          status: 'good',
        },
        {
          label: 'H non-normal',
          before: '(aH,bH)',
          actions: ['換代表', '相乘'],
          after: '可能不同 coset',
          formula: 'not well-defined',
          detail: '同一 inputs 的命名方式導致不同 output。',
          status: 'bad',
        },
      ],
      insight: 'Well-defined 意味著 operation 作用在 cosets 本身，而不是偷偷依賴 representatives。',
      transfer: [
        '在 abelian group 中，任何 subgroup 都能形成 quotient group 嗎？',
        true,
        '每個 subgroup normal，所以代表元相容。',
        'quotient operation 因此 well-defined。',
      ],
      formal: ['Quotient operation', '對 N◁G 定義 (aN)(bN)=abN；identity 是 N，inverse 是 a⁻¹N。'],
      proof: [
        'Normality 如何吸收差異',
        '令 a′=an₁、b′=bn₂。',
        'a′b′=an₁bn₂=ab(b⁻¹n₁b)n₂。',
        'Normality 給 b⁻¹n₁b∈N。',
        '最後兩 factors 在 N，故 a′b′N=abN。',
      ],
      boundary: '「選一個代表算」只有在已證明 well-defined 後才合法。',
    }),
    L({
      id: '17.3',
      title: 'Projection map 的 kernel 正是被壓平的 N',
      lede: 'Quotient 自帶一個最自然的 homomorphism π:G→G/N。它把每個 element 送到所在 tile，並且恰好看不見 N。',
      predict: [
        'π(g)=gN 是否一定 surjective？',
        true,
        '每個 quotient element 本來就是某個 gN。',
        'Codomain 的定義直接提供 preimage。',
      ],
      kind: 'mapping',
      modelTitle: '把 elements 投影到 coset nodes',
      prompt: '看 image 是否覆蓋，並反查 identity coset N 的 fiber。',
      presets: [
        {
          label: 'projection',
          mapping: [
            { from: 'n∈N', to: 'N identity', accent: true },
            { from: 'aN 中所有 a', to: 'aN' },
            { from: 'bN 中所有 b', to: 'bN' },
          ],
          formula: 'π(g)=gN',
          detail: '每個 coset 都被命中。',
          status: 'good',
        },
        {
          label: 'kernel',
          mapping: [{ from: 'N 的全部 elements', to: 'N identity', accent: true }],
          formula: 'kerπ=N',
          detail: '只有原 subgroup tile 被壓成 quotient identity。',
          status: 'good',
        },
      ],
      insight: 'Quotient projection 是「忘掉 N-differences」的標準鏡頭；它的 kernel 精確等於 N。',
      transfer: [
        '每個 normal subgroup 都能實現成某個 homomorphism 的 kernel 嗎？',
        true,
        '使用 canonical projection G→G/N。',
        '這也解釋 normal subgroups 為何正是 kernels。',
      ],
      formal: ['Canonical projection', 'π:G→G/N, π(g)=gN 是 surjective homomorphism，kerπ=N。'],
      proof: [
        '驗證 homomorphism',
        'π(ab)=abN。',
        'Quotient operation 給 (aN)(bN)=abN。',
        '因此 π(ab)=π(a)π(b)。',
        'π(g)=N iff g∈N，所以 kernel=N。',
      ],
      boundary: 'Projection 不是任意挑代表；它把 input 送到唯一所屬的 coset。',
    }),
    L({
      id: '17.4',
      title: 'Quotient 保留跨 tiles 的運作，忘掉 tile 內細節',
      lede: 'Quotient 不是單純縮小集合；它選擇性保留哪些 differences 仍有意義。好的模型要同時說清楚留下與捨棄的資訊。',
      predict: [
        'Z/3Z 能分辨 7 與 10 嗎？',
        false,
        '兩者相差 3，都落在 [1]。',
        '但它仍能分辨 residue classes 如何相加。',
      ],
      kind: 'diagnostic',
      modelTitle: '做一份資訊保留清單',
      prompt: '比較三種 quotient lenses。',
      presets: [
        {
          label: 'Z/3Z',
          checks: [
            check('忘掉', false, '相差 3 的 multiples。'),
            check('保留', true, 'addition mod 3。'),
            check('新大小', true, '3 cosets。'),
          ],
          detail: '留下週期位置，丟掉完整整數座標。',
          status: 'good',
        },
        {
          label: 'G/{e}',
          checks: [
            check('忘掉', true, '只有 identity difference。'),
            check('保留', true, '全部 group structure。'),
            check('結果', true, '與 G isomorphic。'),
          ],
          detail: '幾乎沒有壓縮。',
          status: 'good',
        },
        {
          label: 'G/G',
          checks: [
            check('忘掉', false, '所有 differences。'),
            check('保留', true, '只剩 trivial operation。'),
            check('結果', true, 'one-element group。'),
          ],
          detail: '最大壓縮。',
          status: 'neutral',
        },
      ],
      insight: 'Quotient 的意義由 N 決定：N 指定哪些 differences 被宣告為 invisible。',
      transfer: [
        '若 N 越大，finite quotient G/N 通常越小嗎？',
        true,
        '每個 coset 越大，tile 數 |G|/|N| 越少。',
        '壓平更多差異，剩下的可辨狀態更少。',
      ],
      formal: ['Quotient size', 'Finite case 有 |G/N|=[G:N]=|G|/|N|。'],
      proof: [
        '兩個極端 quotient',
        '若 N={e}，每個 coset gN={g}。',
        '因此 projection 不合併不同 elements。',
        '若 N=G，只有 coset G。',
        '所以所有 elements 都被壓成一點。',
      ],
      boundary: '較小 quotient 不代表較差；是否有用取決於它是否忘掉問題不需要的差異。',
    }),
  ],

  ch18: [
    L({
      id: '18.1',
      title: '每個 homomorphism 都先按 kernel 分塊',
      lede: 'Map 看似直接從 G 跳到 H，其實所有資訊壓縮都先發生在 domain：同 kernel coset 的 elements 必定落到同一 output。',
      predict: [
        'φ 能在同一 kernel coset 內產生兩個不同 outputs 嗎？',
        false,
        'aK=bK 等價 b⁻¹a∈K，因而 φ(a)=φ(b)。',
        '對；φ 對每塊必為常數。',
      ],
      kind: 'partition',
      modelTitle: '把 mapping 拆成「分塊」再「命名」',
      prompt: '依序切換 raw domain、kernel cosets、image labels。',
      presets: [
        {
          label: 'domain G',
          blocks: [
            { label: 'K', items: ['k₁', 'k₂'] },
            { label: 'aK', items: ['a₁', 'a₂'] },
            { label: 'bK', items: ['b₁', 'b₂'] },
          ],
          formula: 'K=kerφ',
          detail: '先找到 map 無法分辨的 differences。',
          status: 'neutral',
        },
        {
          label: 'quotient G/K',
          nodes: nodes(['K', 'aK', 'bK'], ['aK', 'bK'], 'K'),
          actions: ['每塊壓成一點'],
          formula: 'G→G/K',
          detail: '所有必要 collisions 一次完成。',
          status: 'good',
        },
        {
          label: 'image',
          mapping: [
            { from: 'K', to: 'e' },
            { from: 'aK', to: 'φ(a)' },
            { from: 'bK', to: 'φ(b)' },
          ],
          formula: 'G/K→imφ',
          detail: '剩下只是對 image elements 的一一重新命名。',
          status: 'good',
        },
      ],
      insight:
        'Homomorphism 的壓縮形狀完全由 kernel 決定；image 只是 quotient blocks 在 output 端的名字。',
      transfer: [
        'Parity map Z→Z₂ 是否先形成 Z/2Z 再對齊 image？',
        true,
        'kernel=2Z，兩個 cosets 正好對應 even/odd。',
        '這是 first isomorphism pattern 的最小例子。',
      ],
      formal: ['Factorization', '若 K=kerφ，φ 可分解為 G→G/K→imφ。'],
      proof: [
        '為何 quotient 上的 map 可定義',
        '候選 map 定義 φ̄(gK)=φ(g)。',
        '若 gK=hK，則 h⁻¹g∈K。',
        '所以 φ(h)⁻¹φ(g)=e，亦即 φ(g)=φ(h)。',
        '因此不依賴 representative。',
      ],
      boundary: 'Factorization 的中間 quotient 使用 kernel，不是任意 normal subgroup。',
    }),
    L({
      id: '18.2',
      title: 'Quotient 與 image 之間沒有剩餘資訊損失',
      lede: 'Kernel collisions 已全部在 G/K 中處理。由 coset 到 output 的 induced map 既不 collision，也不漏掉 image，因此是 isomorphism。',
      predict: [
        'Induced map G/K→imφ 還可能有 nontrivial kernel 嗎？',
        false,
        '若 gK 映到 e，g 已在 K，所以 gK=K identity。',
        '壓縮已經做完。',
      ],
      kind: 'diagnostic',
      modelTitle: '檢查 induced map 的三關',
      prompt: '把 homomorphism、injective、surjective 分開驗證。',
      presets: [
        {
          label: 'φ̄:gK↦φ(g)',
          checks: [
            check('well-defined', true, '同 coset 給同 output。'),
            check('homomorphism', true, 'φ̄((aK)(bK))=φ(ab)。'),
            check('injective', true, 'kernel 只剩 K。'),
            check('surjective onto image', true, '每個 φ(g) 都被 gK 命中。'),
          ],
          detail: 'Induced map 是 isomorphism。',
          status: 'good',
        },
      ],
      insight: '先 quotient 掉全部不可見差異後，剩餘結構與 image 完全一一對齊。',
      transfer: [
        '若 φ 本來 surjective onto H，是否有 G/kerφ≅H？',
        true,
        '此時 image=H。',
        'First isomorphism theorem 直接給出。',
      ],
      formal: [
        'First isomorphism theorem',
        '對 homomorphism φ:G→H，有 G/kerφ ≅ imφ。',
        'G/\\ker\\varphi\\cong\\operatorname{im}\\varphi',
      ],
      proof: [
        'Injectivity 的核心一步',
        '若 φ̄(aK)=φ̄(bK)，則 φ(a)=φ(b)。',
        '所以 b⁻¹a∈kerφ=K。',
        '因此 aK=bK。',
        '故 quotient blocks 不再 collision。',
      ],
      boundary: 'Theorem 對齊的是 image，不一定是整個 codomain H。',
    }),
    L({
      id: '18.3',
      title: '第一同構定理是一張可重用的壓縮藍圖',
      lede: '整數取餘數、determinant、sign map 看起來不同，背後都在做同一件事：找不可見差異、按差異分塊、把 blocks 對齊 outputs。',
      predict: [
        '要猜一個 quotient G/N 與某群 H isomorphic，找 surjective map G→H 且 kernel=N 是有效策略嗎？',
        true,
        'First isomorphism theorem 立即給 G/N≅H。',
        '這比直接硬造 coset-to-H bijection 通常更自然。',
      ],
      kind: 'diagnostic',
      modelTitle: '在三個表面辨認同一骨架',
      prompt: '每個例子都填入 domain、kernel、image、quotient。',
      presets: [
        {
          label: 'mod n',
          checks: [
            check('domain', true, 'Z。'),
            check('kernel', true, 'nZ。'),
            check('image', true, 'Zₙ。'),
            check('結論', true, 'Z/nZ≅Zₙ。'),
          ],
          detail: 'Residue classes 是 fibers。',
          status: 'good',
        },
        {
          label: 'sign',
          checks: [
            check('domain', true, 'Sₙ。'),
            check('kernel', true, 'Aₙ。'),
            check('image', true, '{±1}。'),
            check('結論', true, 'Sₙ/Aₙ≅C₂。'),
          ],
          detail: 'Parity 是 quotient lens。',
          status: 'good',
        },
        {
          label: 'determinant',
          checks: [
            check('domain', true, 'GLₙ(R)。'),
            check('kernel', true, 'SLₙ(R)。'),
            check('image', true, 'R×。'),
            check('結論', true, 'GLₙ/SLₙ≅R×。'),
          ],
          detail: '只保留 volume scaling。',
          status: 'good',
        },
      ],
      insight:
        '面對 quotient 猜想時，先找自然的 observable；它的 kernel 與 image 往往直接揭露答案。',
      transfer: [
        '若 map 不 surjective，能否仍使用 first isomorphism theorem？',
        true,
        '結論改為 quotient isomorphic to image。',
        '不需要 map 覆蓋整個 codomain。',
      ],
      formal: ['Reusable workflow', '定義 homomorphism → 算 kernel → 算 image → 套 G/kerφ≅imφ。'],
      proof: [
        '使用定理前的責任',
        '先證明 map 真正保留 operation。',
        '精確求出 kernel。',
        '精確描述 image。',
        '最後才代入 theorem，不用 theorem 反過來猜前提。',
      ],
      boundary: '定理不替你計算 kernel 或 image；最具問題特色的工作仍在這兩步。',
    }),
  ],
};
