import type {
  AlgebraV2Choice,
  AlgebraV2Lesson,
  AlgebraV2ModelKind,
  AlgebraV2Node,
  AlgebraV2Preset,
} from './algebra-v2-lessons';

type Part2ChapterId = 'ch7' | 'ch8' | 'ch9' | 'ch10' | 'ch11' | 'ch12' | 'ch13';

interface LessonSeed {
  id: string;
  title: string;
  lede: string;
  predict: [question: string, yesCorrect: boolean, yesFeedback: string, noFeedback: string];
  kind: AlgebraV2ModelKind;
  modelTitle: string;
  prompt: string;
  presets: AlgebraV2Preset[];
  insight: string;
  transfer: [question: string, yesCorrect: boolean, yesFeedback: string, noFeedback: string];
  formal: [title: string, body: string, notation?: string];
  proof: [title: string, goal: string, ...steps: string[]];
  boundary: string;
}

const yesNo = (correct: boolean, yes: string, no: string): AlgebraV2Choice[] => [
  { label: '是', correct, feedback: yes },
  { label: '不是', correct: !correct, feedback: no },
];

const lesson = (seed: LessonSeed): AlgebraV2Lesson => ({
  id: seed.id,
  eyebrow: `Abstract Algebra v2 · ${seed.id}`,
  title: seed.title,
  lede: seed.lede,
  prediction: {
    question: seed.predict[0],
    choices: yesNo(seed.predict[1], seed.predict[2], seed.predict[3]),
  },
  model: {
    kind: seed.kind,
    eyebrow: 'Structure explorer',
    title: seed.modelTitle,
    prompt: seed.prompt,
    presets: seed.presets,
  },
  insight: seed.insight,
  transfer: {
    question: seed.transfer[0],
    choices: yesNo(seed.transfer[1], seed.transfer[2], seed.transfer[3]),
  },
  formal: { title: seed.formal[0], body: seed.formal[1], notation: seed.formal[2] },
  proof: {
    title: seed.proof[0],
    goal: seed.proof[1],
    steps: seed.proof.slice(2),
  },
  boundary: seed.boundary,
});

const networkNodes = (labels: string[], active: string[], origin = 'e'): AlgebraV2Node[] =>
  labels.map((label) => ({
    label,
    state: label === origin ? 'origin' : active.includes(label) ? 'active' : 'dim',
  }));

const z6 = ['0', '1', '2', '3', '4', '5'];
const z8 = ['0', '1', '2', '3', '4', '5', '6', '7'];

export const ALGEBRA_V2_PART2_LESSONS: Record<Part2ChapterId, AlgebraV2Lesson[]> = {
  ch7: [
    lesson({
      id: '7.1',
      title: 'Generator 是一顆可以重複按的按鈕',
      lede: '不要先找「最重要的元素」。固定從 identity 出發，只問：允許重複與反向使用這些 actions，我究竟能走到哪裡？',
      predict: [
        '在模 8 加法中，只准重複加 2，能走遍全部八個狀態嗎？',
        false,
        '每次都保持偶數，只能到 0、2、4、6。',
        '對；reachable set 只有四個狀態。',
      ],
      kind: 'network',
      modelTitle: '從 identity 展開可達範圍',
      prompt: '切換允許的按鈕，觀察亮起的 nodes；暗點就是目前無法抵達的 effects。',
      presets: [
        {
          label: '只准 +2',
          nodes: networkNodes(z8, ['2', '4', '6'], '0'),
          actions: ['+2', '+2', '+2'],
          formula: '⟨2⟩={0,2,4,6}',
          detail: '步長 2 把圓環切成兩條互不相通的路。',
          status: 'bad',
        },
        {
          label: '只准 +3',
          nodes: networkNodes(z8, z8.slice(1), '0'),
          actions: ['+3', '+3', '+3'],
          formula: '⟨3⟩=Z₈',
          detail: '3 與 8 互質，反覆走會造訪全部狀態。',
          status: 'good',
        },
        {
          label: '准 +2、+3',
          nodes: networkNodes(z8, z8.slice(1), '0'),
          actions: ['+2', '+3', '−2'],
          formula: '⟨2,3⟩=Z₈',
          detail: '兩種按鈕合用也能連通全世界。',
          status: 'good',
        },
      ],
      insight:
        'Generating set 是允許使用的基本 actions；它生成的是從 identity 能抵達的全部 effects。',
      transfer: [
        '三角形的所有 rotations 能由單一 120° rotation 生成嗎？',
        true,
        '重複 0、1、2 次正好得到三個 rotations。',
        '第三次回到 identity；三種 rotations 都已出現。',
      ],
      formal: [
        'Generated subgroup',
        '由 S 中元素及其 inverses 組成的所有有限 products，形成 S 所生成的 subgroup。',
        '\\langle S\\rangle',
      ],
      proof: [
        '為何 reachable set 是 subgroup？',
        '把可達路徑接起來或倒著走，結果仍可達。',
        '空路徑給出 identity。',
        '兩條有限路徑串接仍是有限路徑，所以 closed。',
        '把路徑倒序並反轉每一步，就得到 inverse。',
      ],
      boundary: 'Generator 不必唯一，也不必是單一元素；「生成」描述可達性，不描述元素的重要程度。',
    }),
    lesson({
      id: '7.2',
      title: '有些世界一顆按鈕足夠，有些不夠',
      lede: '能否由單一 action 走遍，是群的結構特徵；換一顆表面相似的按鈕，可達範圍可能完全不同。',
      predict: [
        '模 6 中反覆加 2，會因為一直走而終究造訪所有狀態嗎？',
        false,
        '它只循環 0→2→4→0。',
        '正確；重複本身不保證擴大可達範圍。',
      ],
      kind: 'network',
      modelTitle: '同一世界，換一組基本按鈕',
      prompt: '比較一顆按鈕與兩顆按鈕，不要用按鈕數量猜可達範圍。',
      presets: [
        {
          label: '{+1}',
          nodes: networkNodes(z6, z6.slice(1), '0'),
          actions: ['+1'],
          formula: '一顆就走遍',
          detail: '+1 是 Z₆ 的 generator。',
          status: 'good',
        },
        {
          label: '{+2}',
          nodes: networkNodes(z6, ['2', '4'], '0'),
          actions: ['+2'],
          formula: '困在三點 cycle',
          detail: '+2 只生成一個三元素 subgroup。',
          status: 'bad',
        },
        {
          label: '{+2,+3}',
          nodes: networkNodes(z6, z6.slice(1), '0'),
          actions: ['+2', '+3'],
          formula: '兩顆合力走遍',
          detail: '任何 residue 都能寫成 2 與 3 的整數組合。',
          status: 'good',
        },
      ],
      insight: '生成能力由 actions 造成的 connectivity 決定，不由 generator 的數量或外觀決定。',
      transfer: [
        '只用 rotations 能生成包含 reflections 的三角形 symmetry group 嗎？',
        false,
        '旋轉的 composite 仍是旋轉，不會突然變成反射。',
        '對；至少還需要一個 reflection button。',
      ],
      formal: [
        'Generating set',
        '若 ⟨S⟩=G，稱 S generates G；若某個單一 a 能生成 G，則 G 為 cyclic。',
        '\\langle S\\rangle=G',
      ],
      proof: [
        '證明 {2,3} 生成 Z₆',
        '對每個 residue 找到一條由 +2、+3 及逆向組成的路。',
        '0 是空路徑；2、3 直接可達。',
        '4=2+2，5=2+3，1=3−2。',
        '六個 residues 全可達，所以生成 Z₆。',
      ],
      boundary:
        'Minimal generating set 指移除任何一顆都失去生成能力，不等於 generators 數量在所有 generating sets 中最少。',
    }),
    lesson({
      id: '7.3',
      title: 'Action word 是路徑，群元素是總效果',
      lede: '同一個效果可能有很多走法。若把路徑拼法誤當元素，就會把群看得比實際大得多。',
      predict: [
        '模 6 中，連按六次 +1 與完全不按，是相同的 word 嗎？',
        false,
        'words 不同，但 evaluation 後的 effect 相同。',
        '對；要分清「字串相同」與「總效果相同」。',
      ],
      kind: 'timeline',
      modelTitle: '不同拼字，落在同一終點',
      prompt: '切換 action chains；START 與 RESULT 決定 effect，chips 記錄的是 word。',
      presets: [
        {
          label: '空 word',
          before: '0',
          actions: ['不按'],
          after: '0',
          formula: 'ε ↦ 0',
          detail: '空路徑代表 identity effect。',
          status: 'neutral',
        },
        {
          label: '六次 +1',
          before: '0',
          actions: ['+1', '+1', '+1', '+1', '+1', '+1'],
          after: '0',
          formula: '111111 ↦ 0',
          detail: 'word 很長，但總 effect 仍是 identity。',
          status: 'good',
        },
        {
          label: '+2 再 −1',
          before: '0',
          actions: ['+2', '−1'],
          after: '1',
          formula: '2(−1) ↦ 1',
          detail: '另一條路徑與單獨 +1 有相同 effect。',
          status: 'good',
        },
      ],
      insight:
        'Word 記錄如何走；group element 記錄走完後的總 action。多條 paths 可以代表同一 element。',
      transfer: [
        '「旋轉 120° 三次」與 identity 是相同 action 嗎？',
        true,
        '對所有三角形 states 的總效果都不動。',
        '雖然執行歷史不同，group element 比較的是總 transformation。',
      ],
      formal: [
        'Word evaluation',
        '由 generators 與 formal inverses 組成的 word，經 evaluation 得到 G 中的一個 element。',
        's_1^{\\epsilon_1}\\cdots s_k^{\\epsilon_k}\\mapsto g',
      ],
      proof: [
        '如何證明兩個 words 代表同一 effect？',
        '比較它們 evaluation 後的 group elements。',
        '先依 operation order 計算第一個 word。',
        '再計算第二個 word。',
        '若結果相等，words 即使字面不同也代表同一 effect。',
      ],
      boundary: 'Group element 不保存執行歷史；若問題需要時間或路徑成本，必須額外建模。',
    }),
    lesson({
      id: '7.4',
      title: '生成就是把 contract 強迫補齊',
      lede: '放入一個 seed 後，identity、inverse 與 composites 會迫使更多元素加入；直到這個小世界能自行運作。',
      predict: [
        '在 Z₈ 中，任何包含 2 的 subgroup 都必須也包含 6 嗎？',
        true,
        '6 是 2 的 additive inverse，因此不能漏掉。',
        '若漏掉 6，這個 subset 無法履行 inverse contract。',
      ],
      kind: 'network',
      modelTitle: '看 closure wave 一輪輪擴張',
      prompt: '每個 preset 是下一輪被 contract 強迫加入的 elements。',
      presets: [
        {
          label: 'seed',
          nodes: networkNodes(z8, ['2'], '0'),
          actions: ['放入 2'],
          formula: '{0,2}',
          detail: '先放 seed；identity 也必須存在。',
          status: 'bad',
        },
        {
          label: '補 inverse',
          nodes: networkNodes(z8, ['2', '6'], '0'),
          actions: ['−2=6'],
          formula: '{0,2,6}',
          detail: 'inverse contract 強迫加入 6。',
          status: 'bad',
        },
        {
          label: '補 composites',
          nodes: networkNodes(z8, ['2', '4', '6'], '0'),
          actions: ['2+2=4'],
          formula: '⟨2⟩={0,2,4,6}',
          detail: '加入 4 後，集合終於對合成與 inverse 穩定。',
          status: 'good',
        },
      ],
      insight: '⟨S⟩ 是包含 seeds 且能自行履行 group contract 的最小世界。',
      transfer: [
        'Z₈ 中 ⟨3⟩ 會比 ⟨2⟩ 小嗎？',
        false,
        '3 反覆相加會走遍八個 residues。',
        '正確；seed 數值較大不代表生成世界較小。',
      ],
      formal: [
        'Smallest subgroup',
        '⟨S⟩ 等於所有包含 S 的 subgroups 的 intersection，因此它同時存在且最小。',
        '\\langle S\\rangle=\\bigcap_{S\\subseteq H\\le G}H',
      ],
      proof: [
        '為何是最小的？',
        '任一包含 S 的 subgroup 都必須包含 S 的 inverses 與所有有限 products。',
        '因此它必須包含所有由 S 形成的 words。',
        '這些 words 正是 ⟨S⟩。',
        '所以 ⟨S⟩ 包含於每個候選 subgroup。',
      ],
      boundary: '「最小」是 inclusion 意義，不是元素名稱最小，也不是挑出最短 word。',
    }),
  ],

  ch8: [
    lesson({
      id: '8.1',
      title: 'Relation 是回到原點的 action loop',
      lede: 'Relations 不只是符號等式；它們告訴你哪些 action chains 對所有 states 的總效果等於不動。',
      predict: [
        '若 r 是 120° rotation，r³=e 是否表示三次旋轉的執行歷史消失了？',
        false,
        '它只表示總 effect 是 identity，不刪除曾經走過的路徑。',
        '對；group equality 比較總 action。',
      ],
      kind: 'network',
      modelTitle: '播放路徑，看它是否閉合',
      prompt: '只有終點回到 origin，word 才形成 identity relation。',
      presets: [
        {
          label: 'r',
          nodes: networkNodes(['e', 'r', 'r²'], ['r'], 'e'),
          actions: ['r'],
          formula: 'r≠e',
          detail: '走一步停在另一個 effect。',
          status: 'bad',
        },
        {
          label: 'r²',
          nodes: networkNodes(['e', 'r', 'r²'], ['r', 'r²'], 'e'),
          actions: ['r', 'r'],
          formula: 'r²≠e',
          detail: '兩步還沒閉合。',
          status: 'bad',
        },
        {
          label: 'r³',
          nodes: networkNodes(['e', 'r', 'r²'], ['r', 'r²'], 'e'),
          actions: ['r', 'r', 'r'],
          formula: 'r³=e',
          detail: '第三步回到 origin，形成 closed loop。',
          status: 'good',
        },
      ],
      insight: 'Relation 是一條 effect 為 identity 的 word；在 Cayley graph 上就是 closed loop。',
      transfer: [
        '時鐘每次前進一格，按 12 次形成 relation 嗎？',
        true,
        '總 effect 回到相同鐘點。',
        '12-step path 首尾相接，所以可寫成 a¹²=e。',
      ],
      formal: ['Relation', '對 generators 形成的 word w，等式 w=e 稱為一條 relation。', 'w=e'],
      proof: [
        '由 r³=e 推出 r⁴=r',
        '在等式同一側辨認 relation loop。',
        'r⁴=r³r。',
        '以 e 取代 r³。',
        'er=r。',
      ],
      boundary:
        '回到某一個特定 state 不一定是 identity；relation 要求對整個 state space 的總 action 都不變。',
    }),
    lesson({
      id: '8.2',
      title: 'Relation 可以縮短 word 而不改效果',
      lede: '已知某個 loop 等於 identity，就能在路徑中插入或刪除它；這是化簡的因果，不是字面消去遊戲。',
      predict: [
        '已知 r³=e，能把 r⁸ 化成 r² 嗎？',
        true,
        '刪掉兩個 r³ loops，剩下 r²。',
        '8=3+3+2，所以兩個 closed loops 不改總 effect。',
      ],
      kind: 'timeline',
      modelTitle: '刪除閉合 loop，保留終點',
      prompt: '切換化簡階段，觀察 word 變短但 RESULT 不變。',
      presets: [
        {
          label: '原 word',
          before: 'e',
          actions: ['r³', 'r³', 'r²'],
          after: 'r²',
          formula: 'r⁸',
          detail: '把長 word 看成兩個 loop 加剩餘路徑。',
          status: 'neutral',
        },
        {
          label: '刪一圈',
          before: 'e',
          actions: ['e', 'r³', 'r²'],
          after: 'r²',
          formula: 'er⁵=r⁵',
          detail: '第一個 r³ 以 identity 取代。',
          status: 'good',
        },
        {
          label: '最短 effect',
          before: 'e',
          actions: ['r²'],
          after: 'r²',
          formula: 'r⁸=r²',
          detail: '第二個 loop 也刪掉，終點仍相同。',
          status: 'good',
        },
      ],
      insight: 'Relation 是合法的 path rewrite：改變 word 的寫法，不改變它代表的 effect。',
      transfer: [
        '模 5 加法中，連加 1 七次等於連加兩次嗎？',
        true,
        '五步是一個回到 0 的 loop。',
        '7=5+2；刪除五步 relation 後剩兩步。',
      ],
      formal: [
        'Word reduction',
        '若 u=v 是已知 relation，可在較長 word 的相同 context 中以 v 取代 u。',
      ],
      proof: [
        '每一步都要標示 equality',
        '不要一次跳到答案。',
        'r⁸=r³r³r²。',
        '=eer²，兩次使用 r³=e。',
        '=r²，兩次使用 identity law。',
      ],
      boundary: '最短 word 可能不唯一；化簡程序也不一定自動給出 canonical form。',
    }),
    lesson({
      id: '8.3',
      title: '交換次序是一條額外 relation',
      lede: 'Associativity 允許移動括號，但不允許交換 actions。只有兩條不同順序的路真的同終點，才可寫 ab=ba。',
      predict: [
        '任何 group 的任意 a,b 都滿足 ab=ba 嗎？',
        false,
        'group contract 沒有 commutativity。',
        '正確；三角形 rotation 與 reflection 就提供反例。',
      ],
      kind: 'timeline',
      modelTitle: '比較 ab 與 ba 的終點',
      prompt: '同樣兩顆按鈕，只交換執行順序。',
      presets: [
        {
          label: '平移 x,y',
          before: '(0,0)',
          actions: ['右移', '上移'],
          after: '(1,1)',
          formula: 'ab=ba',
          detail: '兩種順序同終點，形成 commuting square。',
          status: 'good',
        },
        {
          label: '交換平移',
          before: '(0,0)',
          actions: ['上移', '右移'],
          after: '(1,1)',
          formula: 'ba=ab',
          detail: '終點與前一條 path 相同。',
          status: 'good',
        },
        {
          label: '轉後翻',
          before: '△',
          actions: ['旋轉 r', '反射 f'],
          after: '標記排列 A',
          formula: 'rf≠fr',
          detail: '與反向次序落在不同 symmetry。',
          status: 'bad',
        },
      ],
      insight: 'Commutativity 是某個世界的額外路徑 equality，不是「可以省略括號」的另一種說法。',
      transfer: [
        '矩陣乘法在可逆矩陣群中一定可交換嗎？',
        false,
        '可逆只保證 inverse；不保證 AB=BA。',
        '對，找到一對不交換矩陣即可推翻。',
      ],
      formal: [
        'Commuting pair',
        '若 ab=ba，稱 a 與 b commute；若所有 pairs 都 commute，群稱 abelian。',
        'ab=ba',
      ],
      proof: [
        '如何推翻 abelian？',
        '只需要一個 order-sensitive pair。',
        '選定具體 a,b。',
        '分別算出 ab 與 ba。',
        '展示兩結果不同。',
      ],
      boundary: '某一對 elements commute，不代表整個 group abelian。',
    }),
    lesson({
      id: '8.4',
      title: 'Presentation 用按鈕與回路描述世界',
      lede: '不必列出所有元素。說明有哪些基本按鈕，以及哪些 loops 應折疊為 identity，就可能壓縮描述整個群。',
      predict: [
        '只寫 generators 而沒有 relations，是否已唯一決定有限群？',
        false,
        '還不知道哪些 words 應代表同一 effect。',
        '對；word tree 可能繼續無限展開。',
      ],
      kind: 'diagnostic',
      modelTitle: '同一按鈕，加入不同回路規則',
      prompt: '比較 relations 如何把無限 words 折疊成不同 action worlds。',
      presets: [
        {
          label: '⟨r | r³=e⟩',
          checks: [
            { label: '基本按鈕', pass: true, reason: '只有 r。' },
            { label: '閉合規則', pass: true, reason: '每三步回到 e。' },
            { label: 'effects', pass: true, reason: 'e,r,r²。' },
          ],
          detail: 'relation 把所有 powers 折疊成三個 effects。',
          status: 'good',
        },
        {
          label: '⟨r | r⁴=e⟩',
          checks: [
            { label: '基本按鈕', pass: true, reason: '仍只有 r。' },
            { label: '閉合規則', pass: true, reason: '每四步回到 e。' },
            { label: 'effects', pass: true, reason: 'e,r,r²,r³。' },
          ],
          detail: '同一 generator、不同 relation，得到四階世界。',
          status: 'good',
        },
      ],
      insight:
        'Presentation = generators 告訴你如何走，relations 告訴你哪些 paths 要視為同一 effect。',
      transfer: [
        '⟨r∣r⁴=e⟩ 可以作為正方形 rotations 的壓縮描述嗎？',
        true,
        '四次 90° rotation 回到 identity，四個 powers 給出四種 rotations。',
        '這正是 cyclic order-4 action world。',
      ],
      formal: [
        'Group presentation',
        '記號 ⟨S∣R⟩ 表示由 S 生成，並施加 R 中 relations 的群。',
        '\\langle S\\mid R\\rangle',
      ],
      proof: [
        '這一章不形式建構 quotient',
        '先學會可靠地讀 presentation。',
        '列出 generator buttons。',
        '把每條 relation 畫成 loop。',
        '用 loops 比較 words 的 effects。',
      ],
      boundary: '給出的 relations 可能隱含更多 relations；presentation 也通常不唯一。',
    }),
  ],

  ch9: [
    lesson({
      id: '9.1',
      title: 'Element order 是第一次回到 identity 的時間',
      lede: '固定一個 action 反覆執行。不要數看過幾個符號；數從 identity 出發，第一次真正閉合需要幾步。',
      predict: [
        '90° rotation 的 order 是 90 嗎？',
        false,
        '90 是角度；order 是四次才回到 identity。',
        '對，單位與問題都不同。',
      ],
      kind: 'network',
      modelTitle: '按同一顆按鈕直到第一次閉合',
      prompt: '每個 preset 顯示一種 repeated-action orbit。',
      presets: [
        {
          label: '90° rotation',
          nodes: networkNodes(['e', 'r', 'r²', 'r³'], ['r', 'r²', 'r³']),
          actions: ['r', 'r', 'r', 'r'],
          formula: 'ord(r)=4',
          detail: '第四次第一次回到 e。',
          status: 'good',
        },
        {
          label: '120° rotation',
          nodes: networkNodes(['e', 'r', 'r²'], ['r', 'r²']),
          actions: ['r', 'r', 'r'],
          formula: 'ord(r)=3',
          detail: '第三次第一次閉合。',
          status: 'good',
        },
        {
          label: '整數 +1',
          nodes: networkNodes(['0', '1', '2', '3', '…'], ['1', '2', '3', '…'], '0'),
          actions: ['+1', '+1', '+1'],
          formula: 'ord(1)=∞',
          detail: '在 integers 中永不回到 0。',
          status: 'neutral',
        },
      ],
      insight:
        'ord(a) 是 repeated action a 形成的 cycle length；若永不回到 identity，就是 infinite order。',
      transfer: [
        'Reflection 做兩次的 order 是 2 嗎？',
        true,
        '一次不是 identity，兩次撤銷回到 identity。',
        '所以第一次閉合正好在第二步。',
      ],
      formal: [
        'Element order',
        'ord(a) 是滿足 aⁿ=e 的最小正整數 n；若不存在則為 infinite。',
        '\\operatorname{ord}(a)=\\min\\{n>0:a^n=e\\}',
      ],
      proof: [
        '為何一定要「最小正整數」？',
        '較晚回到 e 的時間通常只是週期的倍數。',
        '若 a³=e，則 a⁶=(a³)²=e。',
        '但 6 不是第一次回來。',
        'order 應記錄 fundamental cycle length 3。',
      ],
      boundary: 'aⁿ=e 只能推出 order divides n，不能直接說 order=n。',
    }),
    lesson({
      id: '9.2',
      title: '一個元素的週期不等於整個群的大小',
      lede: 'Group order 數全世界有幾個 effects；element order 只數單一按鈕反覆使用能走過的 cycle。',
      predict: [
        '六元素群中的每個非 identity 元素都必須有 order 6 嗎？',
        false,
        '不同元素可以生成大小不同的 cycles。',
        '正確；在 Z₆ 中 2 的 order 是 3。',
      ],
      kind: 'network',
      modelTitle: '同一張圖，從不同按鈕展開 cycle',
      prompt: '比較亮點數與全圖 node 數。',
      presets: [
        {
          label: 'Z₆ 的 1',
          nodes: networkNodes(z6, z6.slice(1), '0'),
          actions: ['+1'],
          formula: 'ord(1)=6, |G|=6',
          detail: '這個元素的 powers 走遍全群。',
          status: 'good',
        },
        {
          label: 'Z₆ 的 2',
          nodes: networkNodes(z6, ['2', '4'], '0'),
          actions: ['+2'],
          formula: 'ord(2)=3, |G|=6',
          detail: '只走過三元素 cycle。',
          status: 'neutral',
        },
        {
          label: 'Z₆ 的 3',
          nodes: networkNodes(z6, ['3'], '0'),
          actions: ['+3'],
          formula: 'ord(3)=2, |G|=6',
          detail: '走一步到 3，再一步回 0。',
          status: 'neutral',
        },
      ],
      insight: 'ord(a)=|⟨a⟩|；它量的是 a 生成的 cyclic subgroup，不一定是 |G|。',
      transfer: [
        '在八個 symmetries 的正方形群中，90° rotation 的 order 是 8 嗎？',
        false,
        '四次旋轉已回到 identity。',
        '對；group 有八元素，但該 cycle 只有四元素。',
      ],
      formal: [
        'Element order 與 generated subgroup',
        'a 的不同 powers 在第一次回到 identity 前互異，所以 ord(a)=|⟨a⟩|。',
      ],
      proof: [
        '第一次重複為何迫使回到 e？',
        '假設 aⁱ=aʲ 且 0≤i<j。',
        '左乘 a⁻ⁱ 得 e=aʲ⁻ⁱ。',
        '因此出現長度 j−i 的 identity loop。',
        '最早重複正好對應 fundamental period。',
      ],
      boundary: '「order」會同時用於 group 與 element；必須由對象判斷是在數全群還是單一 cycle。',
    }),
    lesson({
      id: '9.3',
      title: '一個 cycle 若覆蓋全世界，群就是 cyclic',
      lede: 'Cyclic 不是指圖一定畫成圓，而是某一個 element 的 powers 已包含群中每個 effect。',
      predict: [
        '三角形的全部六個 symmetries 是 cyclic group 嗎？',
        false,
        '任何單一 symmetry 的 powers 都無法同時產生 rotations 與三種 reflections。',
        '對；rotation subgroup 只有三元素。',
      ],
      kind: 'network',
      modelTitle: '掃描候選 generator 的覆蓋範圍',
      prompt: '亮點覆蓋全部 nodes 才能稱為 generator of G。',
      presets: [
        {
          label: 'Z₆：選 1',
          nodes: networkNodes(z6, z6.slice(1), '0'),
          actions: ['+1'],
          formula: 'Z₆=⟨1⟩',
          detail: '單一 cycle 覆蓋全群。',
          status: 'good',
        },
        {
          label: 'Z₆：選 2',
          nodes: networkNodes(z6, ['2', '4'], '0'),
          actions: ['+2'],
          formula: '⟨2⟩≠Z₆',
          detail: '只覆蓋一半，2 不是 generator of G。',
          status: 'bad',
        },
        {
          label: 'triangle rotations',
          nodes: networkNodes(['e', 'r', 'r²'], ['r', 'r²']),
          actions: ['r'],
          formula: 'R₃=⟨r⟩',
          detail: '三個 rotations 形成 cyclic group。',
          status: 'good',
        },
      ],
      insight: 'Cyclic group 是「存在一顆按鈕能走遍」，不是「每顆按鈕都能走遍」。',
      transfer: [
        '所有 cyclic groups 都是 abelian 嗎？',
        true,
        'aⁱaʲ=aⁱ⁺ʲ=aʲ⁺ⁱ=aʲaⁱ。',
        '任意兩元素都是同一 generator 的 powers，所以可交換。',
      ],
      formal: [
        'Cyclic group',
        '若存在 a∈G 使 G=⟨a⟩，稱 G cyclic，a 稱 generator。',
        'G=\\langle a\\rangle',
      ],
      proof: [
        'Cyclic 為何推出 abelian？',
        '把任意 x,y 寫成 a 的 powers。',
        '令 x=aⁱ、y=aʲ。',
        'xy=aⁱ⁺ʲ=aʲ⁺ⁱ。',
        '=yx。',
      ],
      boundary: '群可有多個 generators，也可能完全沒有單一 generator。',
    }),
    lesson({
      id: '9.4',
      title: '模 n 的步長會把圓環切成 gcd 個 cycles',
      lede: '重複加 k 是否走遍，不靠試到最後；關鍵是 k 與 n 共享多少尺度。',
      predict: [
        '在 Z₈ 中，3 能生成全群嗎？',
        true,
        'gcd(3,8)=1，所以不會提早回到 0。',
        '依序 0,3,6,1,4,7,2,5,0，八點全到。',
      ],
      kind: 'network',
      modelTitle: '改變 step，看 cycle 如何分裂',
      prompt: '共同因數越大，可達 cycle 越短。',
      presets: [
        {
          label: 'n=8, k=1',
          nodes: networkNodes(z8, z8.slice(1), '0'),
          actions: ['+1'],
          formula: '8/gcd(8,1)=8',
          detail: '一條八點 cycle。',
          status: 'good',
        },
        {
          label: 'n=8, k=2',
          nodes: networkNodes(z8, ['2', '4', '6'], '0'),
          actions: ['+2'],
          formula: '8/gcd(8,2)=4',
          detail: '分成兩條四點 cycles。',
          status: 'neutral',
        },
        {
          label: 'n=8, k=3',
          nodes: networkNodes(z8, z8.slice(1), '0'),
          actions: ['+3'],
          formula: '8/gcd(8,3)=8',
          detail: '3 是 generator。',
          status: 'good',
        },
        {
          label: 'n=8, k=4',
          nodes: networkNodes(z8, ['4'], '0'),
          actions: ['+4'],
          formula: '8/gcd(8,4)=2',
          detail: '只在 0 與 4 間切換。',
          status: 'bad',
        },
      ],
      insight: '在 Zₙ 中，ord([k])=n/gcd(n,k)；能生成全群恰好等於 gcd(n,k)=1。',
      transfer: ['Z₁₂ 中 5 是 generator 嗎？', true, 'gcd(5,12)=1。', '所以它的 order 是 12。'],
      formal: [
        'Order formula in Zₙ',
        '最小 m>0 使 mk≡0 mod n，等價於 n∣mk，最小值為 n/gcd(n,k)。',
        '\\operatorname{ord}([k])=\\frac{n}{\\gcd(n,k)}',
      ],
      proof: [
        '由 divisibility 找最小 m',
        '令 d=gcd(n,k)，寫 n=dn′、k=dk′ 且 gcd(n′,k′)=1。',
        'n∣mk 等價 n′∣mk′。',
        '因 n′ 與 k′ 互質，必有 n′∣m。',
        '最小正 m 是 n′=n/d。',
      ],
      boundary:
        '這個 gcd 公式專屬 cyclic additive model；一般群的 element order 不能直接套元素的數值 gcd。',
    }),
  ],

  ch10: [
    lesson({
      id: '10.1',
      title: '換名字不會改變 action network',
      lede: '抽象代數忽略標籤與材質，只保留 actions 如何合成。第一步先學會看穿純粹 relabeling。',
      predict: [
        '把 Z₄ 的 0,1,2,3 改名為 e,r,r²,r³，會改變群結構嗎？',
        false,
        '若 operation table 的連接方式同步保留，就只是改名。',
        '正確；元素身分可換，relations 不變。',
      ],
      kind: 'mapping',
      modelTitle: '把兩個表面逐點對齊',
      prompt: '每列是候選翻譯；先檢查是否一一配對。',
      presets: [
        {
          label: '角度命名',
          mapping: [
            { from: '0', to: '0°' },
            { from: '1', to: '90°' },
            { from: '2', to: '180°' },
            { from: '3', to: '270°' },
          ],
          detail: '四個 residues 對上四個 rotations。',
          status: 'good',
        },
        {
          label: '複數命名',
          mapping: [
            { from: '0', to: '1' },
            { from: '1', to: 'i' },
            { from: '2', to: '−1' },
            { from: '3', to: '−i' },
          ],
          detail: '表面完全不同，但 cyclic path 可逐點對齊。',
          status: 'good',
        },
        {
          label: '有 collision',
          mapping: [
            { from: '0', to: '1' },
            { from: '1', to: 'i' },
            { from: '2', to: '−1' },
            { from: '3', to: '1', accent: true },
          ],
          detail: '兩元素被翻成同一目標，資訊被壓縮。',
          status: 'bad',
        },
      ],
      insight:
        'Isomorphism 想捕捉的是同一 action network 的不同命名；bijection 先確保沒有遺漏或合併。',
      transfer: [
        '四個 rotations 與四個方向標籤 N,E,S,W 可以只是 relabeling 嗎？',
        true,
        '若「再轉 90°」的連接規則同步保留，就可以。',
        '幾何名稱不同不妨礙一一對齊。',
      ],
      formal: [
        'Bijection 只是第一關',
        'Isomorphism 必須是 bijective homomorphism；一一配對本身尚未檢查 operation。',
      ],
      proof: [
        '如何檢查有限 mapping 為 bijection？',
        '確認每個 source 有唯一 target。',
        '確認不同 sources 不 collision。',
        '確認每個 target 都被命中。',
        '三項合起來即一一且 onto。',
      ],
      boundary: '兩個 sets 大小相同只保證存在 bijection，不保證群結構相同。',
    }),
    lesson({
      id: '10.2',
      title: '好的翻譯讓「先合成」與「先翻譯」同終點',
      lede: 'Structure-preserving 的真正測試不是元素個別長得像，而是 operation square 是否 commute。',
      predict: [
        '任何 bijection between groups 都自動保留 operation 嗎？',
        false,
        '可以任意亂配元素，破壞 products。',
        '對；還必須逐對滿足 homomorphism law。',
      ],
      kind: 'timeline',
      modelTitle: '沿 commuting square 的兩條路走',
      prompt: '比較 φ(ab) 與 φ(a)φ(b) 的終點。',
      presets: [
        {
          label: '先合成再翻',
          before: '([1],[2])',
          actions: ['1+2=3', 'φ(3)=−i'],
          after: '−i',
          formula: 'φ(a+b)',
          detail: '上路先在 Z₄ 合成。',
          status: 'good',
        },
        {
          label: '先翻再合成',
          before: '([1],[2])',
          actions: ['φ(1)=i, φ(2)=−1', 'i·(−1)=−i'],
          after: '−i',
          formula: 'φ(a)φ(b)',
          detail: '下路與上路同終點。',
          status: 'good',
        },
        {
          label: '壞翻譯',
          before: '([1],[1])',
          actions: ['φ(2)', 'φ(1)φ(1)'],
          after: '兩個不同結果',
          formula: 'φ(2)≠φ(1)²',
          detail: '方形分岔，所以不保留 operation。',
          status: 'bad',
        },
      ],
      insight: 'Homomorphism law 是翻譯與合成相容：走哪一條處理順序都抵達同一結果。',
      transfer: [
        'φ([k])=iᵏ 是否把模 4 加法翻成複數乘法？',
        true,
        'i^(a+b)=i^a i^b，且模 4 正好對應 i⁴=1。',
        '兩種合成在 φ 下同步。',
      ],
      formal: [
        'Homomorphism',
        'φ:G→H 保留 operation，若對所有 a,b 都有 φ(ab)=φ(a)φ(b)。',
        '\\varphi(ab)=\\varphi(a)\\varphi(b)',
      ],
      proof: [
        '有限例子為何仍需所有 pairs？',
        'homomorphism 是全稱承諾。',
        '任取 a,b。',
        '分別沿兩條路計算。',
        '只有任意 pair 都同終點才通過。',
      ],
      boundary:
        '檢查幾個漂亮例子只能提供證據；除非 generators 與 relations 足以控制全部，否則不是完整證明。',
    }),
    lesson({
      id: '10.3',
      title: 'Isomorphism 是沒有資訊損失的結構翻譯',
      lede: 'Homomorphism 可以壓縮；bijection 可以亂配。兩項同時成立，才表示兩個群只是不同表示。',
      predict: [
        '一個保留 operation 但把兩元素合併的 map，是 isomorphism 嗎？',
        false,
        'collision 使 inverse translation 不存在。',
        '正確；它是可能的 homomorphism，但不是 isomorphism。',
      ],
      kind: 'diagnostic',
      modelTitle: '三種故障分開檢查',
      prompt: '每個 mapping 依序檢查 injective、surjective、operation-preserving。',
      presets: [
        {
          label: 'Z₄ → 4th roots',
          checks: [
            { label: '無 collision', pass: true, reason: '四元素對四個不同 roots。' },
            { label: '無 missing', pass: true, reason: '每個 root 被命中。' },
            { label: '保留 operation', pass: true, reason: '加法對應乘法。' },
          ],
          detail: '三關都過，是 isomorphism。',
          status: 'good',
        },
        {
          label: 'Z₄ → Z₂',
          checks: [
            { label: '無 collision', pass: false, reason: '0,2 都映到 0。' },
            { label: '無 missing', pass: true, reason: '兩個 targets 都命中。' },
            { label: '保留 operation', pass: true, reason: 'mod 2 projection 保留加法。' },
          ],
          detail: '有資訊壓縮，不可逆。',
          status: 'bad',
        },
        {
          label: '任意重排',
          checks: [
            { label: '無 collision', pass: true, reason: '確實是 permutation。' },
            { label: '無 missing', pass: true, reason: '每個 target 命中。' },
            { label: '保留 operation', pass: false, reason: '某 pair 的 product 不相容。' },
          ],
          detail: 'bijection 仍可破壞結構。',
          status: 'bad',
        },
      ],
      insight:
        'Isomorphism = bijection + operation preservation；它是一個可逆且不改 action logic 的翻譯。',
      transfer: [
        'Z₄ 與正方形 rotations 可視為同一抽象群嗎？',
        true,
        '以 k↦旋轉 90k° 建立 bijective homomorphism。',
        '兩者都有同一四步 cyclic composition。',
      ],
      formal: [
        'Isomorphism',
        'Bijective homomorphism 稱為 isomorphism；存在時寫 G≅H。',
        'G\\cong H',
      ],
      proof: [
        'inverse 為何也保留 operation？',
        '令 x=φ(a), y=φ(b)。',
        'xy=φ(a)φ(b)=φ(ab)。',
        '套 φ⁻¹ 得 φ⁻¹(xy)=ab。',
        '=φ⁻¹(x)φ⁻¹(y)。',
      ],
      boundary: 'Isomorphic 不等於元素相等；它表示所有純群論敘述可經翻譯對應。',
    }),
    lesson({
      id: '10.4',
      title: 'Invariant 可以一票否決錯誤的同構猜想',
      lede: '與其暴力搜尋所有 mappings，先找 isomorphism 不可能改變的結構痕跡；只要一項不同就結束。',
      predict: [
        '兩個四元素群大小相同，就必定 isomorphic 嗎？',
        false,
        'C₄ 有 order 4 元素，V₄ 沒有。',
        '對；相同 cardinality 遠遠不夠。',
      ],
      kind: 'diagnostic',
      modelTitle: '比較結構指紋',
      prompt: '一項 invariant mismatch 足以排除；全部相同只表示尚未排除。',
      presets: [
        {
          label: 'C₄ vs V₄',
          checks: [
            { label: '群大小', pass: true, reason: '都是 4。' },
            { label: 'abelian', pass: true, reason: '兩者皆可交換。' },
            { label: 'order 4 元素', pass: false, reason: 'C₄ 有；V₄ 無。' },
          ],
          detail: 'order distribution mismatch，不能 isomorphic。',
          status: 'bad',
        },
        {
          label: 'Z₄ vs roots',
          checks: [
            { label: '群大小', pass: true, reason: '都是 4。' },
            { label: 'identity', pass: true, reason: '0 對 1。' },
            { label: 'element orders', pass: true, reason: '1,4,2,4 對齊。' },
          ],
          detail: '沒有被這些 invariants 排除，且前節已構造 isomorphism。',
          status: 'good',
        },
      ],
      insight:
        'Invariant mismatch 證明不可能；invariants match 通常只代表候選仍存活，不自動證明同構。',
      transfer: [
        '一個 abelian 群能與 nonabelian 群 isomorphic 嗎？',
        false,
        'isomorphism 會把 xy=yx 翻譯到另一邊。',
        '對，commutativity 是 invariant。',
      ],
      formal: [
        'Isomorphism invariants',
        'identity、inverse、element order、group order、commutativity 與 subgroup pattern 都在 isomorphism 下保留。',
      ],
      proof: [
        '為何 element order 被保留？',
        '若 aⁿ=e，套 φ 得 φ(a)ⁿ=e。',
        '所以 ord(φ(a))≤ord(a)。',
        '對 inverse isomorphism 重複同一論證，得反向不等式。',
        '兩者因此相等。',
      ],
      boundary:
        '列出許多相同 invariants 仍可能無法證明 isomorphic；positive claim 通常需要真正構造 map。',
    }),
  ],

  ch11: [
    lesson({
      id: '11.1',
      title: 'Subgroup 是能自行運作的封閉子機器',
      lede: 'Subset 只是在圈元素；subgroup 要求圈內 actions 合成、停留與反轉時，完全不需要跑到圈外借元素。',
      predict: [
        'Z₆ 中 {0,2} 是 subgroup 嗎？',
        false,
        '2+2=4 掉出 subset。',
        '對；只少一個必要 element 就無法自行運作。',
      ],
      kind: 'closure',
      modelTitle: '在 ambient group 裡測試子世界',
      prompt: '看 output 是否留在候選邊界內，並檢查 inverse。',
      presets: [
        {
          label: '{0,3}',
          setLabel: 'H={0,3}⊂Z₆',
          before: '3,3',
          operation: '+',
          output: '0',
          checks: [
            { label: 'identity', pass: true, reason: '0∈H' },
            { label: 'inverse', pass: true, reason: '−3=3∈H' },
            { label: 'closure', pass: true, reason: '3+3=0∈H' },
          ],
          detail: '候選可獨立完成 group contract。',
          status: 'good',
        },
        {
          label: '{0,2}',
          setLabel: 'K={0,2}⊂Z₆',
          before: '2,2',
          operation: '+',
          output: '4',
          checks: [
            { label: 'identity', pass: true, reason: '0∈K' },
            { label: 'inverse', pass: false, reason: '−2=4∉K' },
            { label: 'closure', pass: false, reason: '2+2=4∉K' },
          ],
          detail: '需要圈外的 4，並不是 subgroup。',
          status: 'bad',
        },
      ],
      insight: 'Subgroup 是 ambient group 裡對同一 operation 完整封閉的 action world。',
      transfer: [
        '偶整數在整數加法群中是 subgroup 嗎？',
        true,
        '0 是偶數，偶數和與負數仍為偶數。',
        '它不需要離開偶整數就能完成加法群 contract。',
      ],
      formal: ['Subgroup', 'H⊆G 若在 G 的 operation 下本身為 group，記作 H≤G。', 'H\\le G'],
      proof: [
        '哪些公理可以繼承？',
        'H 使用與 G 相同的 operation。',
        'Associativity 自動由 G 繼承。',
        '仍需確保 identity、inverse 與 closure 留在 H。',
        '全部成立才是 subgroup。',
      ],
      boundary:
        'Subgroup 必須沿用 ambient group 的 operation；換 operation 是另一個 system，不是同一群的 subgroup。',
    }),
    lesson({
      id: '11.2',
      title: '一個 ab⁻¹ test 濃縮 subgroup 檢查',
      lede: 'Ambient group 已提供 associativity。對非空 subset，只要任取 a,b 後 a 接上 b 的 reverse 仍不逃出，就能同時逼出 identity、inverse 與 closure。',
      predict: [
        '非空 H⊆G 且對所有 a,b∈H 有 ab⁻¹∈H，是否足夠推出 H≤G？',
        true,
        '這正是 one-step subgroup test。',
        '由 a=b 得 e，再由 a=e 得 b⁻¹，最後用 inverse 得一般 product。',
      ],
      kind: 'closure',
      modelTitle: '先反轉 b，再接在 a 後面',
      prompt: '切換候選 subset，尋找 escape witness 或 general pattern。',
      presets: [
        {
          label: 'even integers',
          setLabel: '2Z⊂Z',
          before: 'a=2m, b=2n',
          operation: 'a−b',
          output: '2(m−n)',
          detail: '任意輸出仍為 even integer。',
          status: 'good',
        },
        {
          label: 'positive integers',
          setLabel: 'Z₊⊂Z',
          before: 'a=2, b=5',
          operation: 'a−b',
          output: '−3',
          detail: '一個 witness 掉出 subset，測試失敗。',
          status: 'bad',
        },
        {
          label: 'nonzero rationals',
          setLabel: 'Q×⊂Q',
          before: 'a,b≠0',
          operation: 'a/b',
          output: 'a/b≠0',
          detail: '任意 pair 都留在 nonzero rationals。',
          status: 'good',
        },
      ],
      insight: 'Subgroup test 把三個待查能力封裝成「任意 a,b 的 a·b⁻¹ 不逃出」。',
      transfer: [
        '奇整數能通過 Z 加法中的 a−b test 嗎？',
        false,
        '奇數減奇數是偶數，會掉出。',
        '對；它也不含 additive identity 0。',
      ],
      formal: [
        'One-step subgroup test',
        '非空 H⊆G 是 subgroup，若且唯若對所有 a,b∈H，ab⁻¹∈H。',
        'a,b\\in H\\Rightarrow ab^{-1}\\in H',
      ],
      proof: [
        '由 test 重建 contract',
        '非空，取 h∈H。',
        '令 a=b=h，得 hh⁻¹=e∈H。',
        '令 a=e、b=h，得 h⁻¹∈H。',
        '給 x,y∈H，已知 y⁻¹∈H；代 b=y⁻¹ 得 xy∈H。',
      ],
      boundary: '必須先知道 H 非空；空集會讓全稱條件 vacuously true，卻不是 subgroup。',
    }),
    lesson({
      id: '11.3',
      title: 'Seeds 會張成唯一的最小 subgroup',
      lede: 'Ch7 的 reachability 現在回到 subgroup 語言：選 seeds，再補齊所有被 contract 強迫加入的元素。',
      predict: [
        '同一 subset S 在固定群 G 中，可能生成兩個不同的最小 subgroups 嗎？',
        false,
        '所有 words 的 effects 已唯一決定。',
        '對；兩個都最小會互相包含，因此相等。',
      ],
      kind: 'network',
      modelTitle: '在 S₃ 中切換 seeds',
      prompt: '比較 rotation seed、reflection seed 與兩者合用的 closure。',
      presets: [
        {
          label: '⟨r⟩',
          nodes: networkNodes(['e', 'r', 'r²', 'f', 'rf', 'r²f'], ['r', 'r²']),
          actions: ['r'],
          formula: '{e,r,r²}',
          detail: 'rotation seed 張成三元素 subgroup。',
          status: 'good',
        },
        {
          label: '⟨f⟩',
          nodes: networkNodes(['e', 'r', 'r²', 'f', 'rf', 'r²f'], ['f']),
          actions: ['f'],
          formula: '{e,f}',
          detail: 'reflection 的 square 是 e，只張成兩元素 subgroup。',
          status: 'good',
        },
        {
          label: '⟨r,f⟩',
          nodes: networkNodes(['e', 'r', 'r²', 'f', 'rf', 'r²f'], ['r', 'r²', 'f', 'rf', 'r²f']),
          actions: ['r', 'f'],
          formula: 'S₃',
          detail: 'rotation 與 reflection 合力生成全部六個 symmetries。',
          status: 'good',
        },
      ],
      insight: 'Generated subgroup 把「能抵達哪些 effects」與「最小封閉子世界」說成同一件事。',
      transfer: [
        '若 S⊆H≤G，是否必有 ⟨S⟩⊆H？',
        true,
        'H 已包含 seeds 且對所有必要操作封閉。',
        '最小性迫使 generated subgroup 留在任何包含 S 的 subgroup 內。',
      ],
      formal: [
        'Two views of ⟨S⟩',
        '它既是所有 S-words 的 effects，也是所有包含 S 的 subgroups 的 intersection。',
      ],
      proof: [
        '兩個定義為何相同？',
        'S-words 形成包含 S 的 subgroup W。',
        '任何包含 S 的 subgroup 都必包含每個 S-word。',
        '所以 W 包含於所有候選。',
        '而 W 自己也是候選，故正是 intersection。',
      ],
      boundary: '生成 subgroup 的大小不是 seeds 數量的簡單函數；relations 決定 closure 何時停止。',
    }),
    lesson({
      id: '11.4',
      title: 'Subgroup lattice 畫的是包含關係',
      lede: '知道有哪些 subgroups 只是清單；lattice 顯示從限制 actions 到增加 actions 的結構階層。',
      predict: [
        '兩個 subgroups 的 union 一定仍是 subgroup 嗎？',
        false,
        '跨兩邊各取一個元素，product 可能不在 union。',
        '對；除非其中一個包含另一個，通常會失去 closure。',
      ],
      kind: 'lattice',
      modelTitle: '沿 inclusion 從最小走到全群',
      prompt: '切換 lattice；每往上一層表示允許更多 effects。',
      presets: [
        {
          label: 'Z₆ lattice',
          blocks: [
            { label: 'Z₆', items: ['0', '1', '2', '3', '4', '5'], level: 0, state: 'active' },
            { label: '⟨2⟩', items: ['0', '2', '4'], level: 1 },
            { label: '⟨3⟩', items: ['0', '3'], level: 1 },
            { label: '{0}', items: ['0'], level: 2 },
          ],
          detail: '兩個中間 subgroups 都包含 identity subgroup，並被全群包含。',
          status: 'good',
        },
        {
          label: '只看 ⟨2⟩ 路徑',
          blocks: [
            { label: 'Z₆', items: ['全部'], level: 0 },
            { label: '⟨2⟩', items: ['0', '2', '4'], level: 1, state: 'active' },
            { label: '{0}', items: ['0'], level: 2, state: 'active' },
          ],
          detail: '一條上行路徑代表 inclusion chain。',
          status: 'good',
        },
      ],
      insight: 'Subgroup lattice 的線條代表 inclusion，不代表 elements 之間的 multiplication。',
      transfer: [
        '兩個 subgroups 的 intersection 一定是 subgroup 嗎？',
        true,
        '共同部分保留 identity，且對 product 與 inverse 同時封閉。',
        'intersection 繼承每個 subgroup 的 closure。',
      ],
      formal: [
        'Subgroup lattice',
        '以 inclusion 排序全部 subgroups；meet 是 intersection，join 是兩者 union 所生成的 subgroup。',
      ],
      proof: [
        '為何 intersection 是 subgroup？',
        'identity 在每個 subgroup 中，所以在交集中。',
        'a,b 在交集中表示它們在每個 subgroup 中。',
        '因此 ab⁻¹ 在每個 subgroup 中。',
        '所以 ab⁻¹ 仍在交集。',
      ],
      boundary: '圖上上下位置是 inclusion 的排版，不表示大小比例、距離或生成步數。',
    }),
  ],

  ch12: [
    lesson({
      id: '12.1',
      title: 'Coset 是把 subgroup 整塊平移',
      lede: '固定 subgroup H，再把同一個 g 接到 H 的每個 element 前面。內部 pattern 沒有重算，只是整塊搬到群的另一區。',
      predict: [
        '在 Z₆ 中，1+{0,3} 等於 {1,4} 嗎？',
        true,
        '1+0=1 且 1+3=4。',
        '兩個 elements 被同一 translation 一起搬移。',
      ],
      kind: 'partition',
      modelTitle: '保持模板，切換 translate',
      prompt: '比較 tile 內的相對差異；每塊都是 H 的平移副本。',
      presets: [
        {
          label: 'H',
          blocks: [
            { label: 'H', items: ['0', '3'], state: 'active' },
            { label: '未覆蓋', items: ['1', '2', '4', '5'] },
          ],
          formula: '0+H=H',
          detail: 'identity translation 保留原 subgroup。',
          status: 'neutral',
        },
        {
          label: '1+H',
          blocks: [
            { label: 'H', items: ['0', '3'] },
            { label: '1+H', items: ['1', '4'], state: 'active' },
            { label: '未覆蓋', items: ['2', '5'] },
          ],
          formula: '1+H={1,4}',
          detail: '兩個 elements 同時加 1。',
          status: 'good',
        },
        {
          label: '2+H',
          blocks: [
            { label: 'H', items: ['0', '3'] },
            { label: '1+H', items: ['1', '4'] },
            { label: '2+H', items: ['2', '5'], state: 'active' },
          ],
          formula: '2+H={2,5}',
          detail: '第三塊補完 Z₆。',
          status: 'good',
        },
      ],
      insight:
        'gH 是 H 經由「左乘 g」得到的整塊 translate；g 是搬移指令，不是額外塞入 tile 的元素。',
      transfer: [
        'multiplicative group 中 gH 是把 g 加進 H 嗎？',
        false,
        '它是集合 {gh:h∈H}，每個元素都被左乘。',
        '對；operation 必須跟 ambient group 一致。',
      ],
      formal: ['Left coset', '對 H≤G 與 g∈G，left coset gH={gh:h∈H}。', 'gH=\\{gh:h\\in H\\}'],
      proof: [
        '為何 H 本身也是 coset？',
        '取代表元 e。',
        'eH={eh:h∈H}。',
        'identity law 給 eh=h。',
        '所以 eH=H。',
      ],
      boundary:
        '一般 nonabelian group 中 left coset gH 與 right coset Hg 可能不同；本章主線先固定 left cosets。',
    }),
    lesson({
      id: '12.2',
      title: '每個 coset 都和 H 一樣大',
      lede: '左乘 g 是可逆 action：先乘 g，再乘 g⁻¹ 就回來。因此不可能把兩個 H-elements 壓成一個，也不可能漏掉 coset 裡的點。',
      predict: [
        '無限群裡也能說 h↦gh 是 bijection 嗎？',
        true,
        '可逆性不依賴 finite counting。',
        'inverse map 是 x↦g⁻¹x。',
      ],
      kind: 'mapping',
      modelTitle: '一對一搬移，再反向恢復',
      prompt: '切換 forward 與 inverse translation。',
      presets: [
        {
          label: 'H → gH',
          mapping: [
            { from: 'h₁', to: 'gh₁' },
            { from: 'h₂', to: 'gh₂' },
            { from: 'h₃', to: 'gh₃' },
          ],
          formula: 'L_g(h)=gh',
          detail: '每個 H-element 都有明確 image。',
          status: 'good',
        },
        {
          label: 'gH → H',
          mapping: [
            { from: 'gh₁', to: 'h₁' },
            { from: 'gh₂', to: 'h₂' },
            { from: 'gh₃', to: 'h₃' },
          ],
          formula: 'L_{g⁻¹}(x)=g⁻¹x',
          detail: '反向 translation 完整撤銷 forward map。',
          status: 'good',
        },
      ],
      insight: 'Cosets 等大不是巧合計數，而是 left translation 本身有 inverse。',
      transfer: [
        '若 |H|=5，每個 left coset 都有 5 個 elements 嗎？',
        true,
        'bijection h↦gh 保留 cardinality。',
        '代表元不同不會改 tile size。',
      ],
      formal: ['Translation bijection', 'L_g:H→gH, h↦gh 的 inverse 是 L_{g⁻¹}。'],
      proof: [
        '直接驗證兩方向 composition',
        '從 h∈H 出發。',
        'L_{g⁻¹}(L_g(h))=g⁻¹gh=h。',
        '從 x=gh∈gH 出發。',
        'L_g(L_{g⁻¹}(x))=gg⁻¹x=x。',
      ],
      boundary: '等大不表示 cosets 是 subgroups；只有含 identity 的 coset H 必然是原 subgroup。',
    }),
    lesson({
      id: '12.3',
      title: '兩個 cosets 只要碰到，就整塊重合',
      lede: 'Coset tiles 不能只重疊一角。共享元素提供一個對齊方程，足以把兩個代表元的差吸收到 H 裡。',
      predict: [
        '兩個 left cosets 可能恰好共享一個 element 但其他部分不同嗎？',
        false,
        '一個交點已迫使兩塊相等。',
        '對；cosets 要嘛 identical，要嘛 disjoint。',
      ],
      kind: 'partition',
      modelTitle: '從 disjoint 到 snap-to-equal',
      prompt: '比較模 8 的 ⟨2⟩ translates。',
      presets: [
        {
          label: 'H 與 1+H',
          blocks: [
            { label: 'H', items: ['0', '2', '4', '6'], state: 'active' },
            { label: '1+H', items: ['1', '3', '5', '7'] },
          ],
          formula: 'H∩(1+H)=∅',
          detail: '偶數 tile 與奇數 tile 完全分離。',
          status: 'good',
        },
        {
          label: '1+H 與 3+H',
          blocks: [
            { label: '1+H', items: ['1', '3', '5', '7'], state: 'active' },
            { label: '3+H', items: ['3', '5', '7', '1'], state: 'active' },
          ],
          formula: '1+H=3+H',
          detail: '3−1=2∈H，所以只是同一 tile 的不同代表。',
          status: 'good',
        },
        {
          label: '不合法半重疊',
          blocks: [
            { label: '候選 A', items: ['1', '3', '5', '7'] },
            { label: '候選 B', items: ['3', '0'], state: 'warning' },
          ],
          formula: '這不可能是兩個 H-cosets',
          detail: '半重疊形狀違反 coset translate 的一致性。',
          status: 'bad',
        },
      ],
      insight: 'Cosets 的 overlap 不是部分關係：一個共同點就能把整塊 translate 對齊。',
      transfer: [
        '在 Z₈ 中，1+⟨2⟩ 與 5+⟨2⟩ 相同嗎？',
        true,
        '5−1=4∈⟨2⟩。',
        '兩個代表元落在同一 odd coset。',
      ],
      formal: ['Equal-or-disjoint lemma', '若 aH∩bH≠∅，則 aH=bH。'],
      proof: [
        '用交點對齊代表元',
        '取 x∈aH∩bH，故 x=ah₁=bh₂。',
        '得 a=bh₂h₁⁻¹。',
        '因 h₂h₁⁻¹∈H，所以 aH⊆bH。',
        '交換 a,b 同理得 bH⊆aH，故相等。',
      ],
      boundary: '不同代表元可以命名同一 coset；coset 數不能靠代表元數直接計算。',
    }),
    lesson({
      id: '12.4',
      title: 'Cosets 把群鋪成沒有縫隙的等大 tiles',
      lede: '每個 element 至少在自己的 gH 裡；前節又保證兩 tiles 不會部分重疊。覆蓋與不重疊合起來就是 partition。',
      predict: [
        '一個 group element 可能不屬於任何 H-coset 嗎？',
        false,
        'g=ge 且 e∈H，所以 g∈gH。',
        '對；每個點都會被自己的 translate 收進去。',
      ],
      kind: 'partition',
      modelTitle: '逐塊吸收所有未分類 elements',
      prompt: '切換 subgroup，看 tile size 與 tile count 如何改變。',
      presets: [
        {
          label: 'Z₁₂, H=⟨4⟩',
          blocks: [
            { label: 'H', items: ['0', '4', '8'], state: 'active' },
            { label: '1+H', items: ['1', '5', '9'] },
            { label: '2+H', items: ['2', '6', '10'] },
            { label: '3+H', items: ['3', '7', '11'] },
          ],
          formula: '4 blocks × 3 elements',
          detail: '四塊無重疊地覆蓋 12 個 residues。',
          status: 'good',
        },
        {
          label: 'Z₁₂, K=⟨3⟩',
          blocks: [
            { label: 'K', items: ['0', '3', '6', '9'], state: 'active' },
            { label: '1+K', items: ['1', '4', '7', '10'] },
            { label: '2+K', items: ['2', '5', '8', '11'] },
          ],
          formula: '3 blocks × 4 elements',
          detail: '換較大 subgroup，tile 數相應變少。',
          status: 'good',
        },
      ],
      insight:
        'Left cosets cover G，而且任兩塊 identical or disjoint；因此它們構成等大 partition。',
      transfer: [
        'Z₁₂ 的 ⟨4⟩ 是否恰好有 4 個 distinct cosets？',
        true,
        '是；每塊三元素，四塊覆蓋 12。',
        '每塊三元素，四塊覆蓋 12。',
      ],
      formal: ['Coset partition', '關係 a~b iff a⁻¹b∈H 的 equivalence classes 正是 left cosets。'],
      proof: [
        '為何沒有遺漏？',
        '任取 g∈G。',
        'identity e∈H。',
        '所以 g=ge∈gH。',
        '因此每個 g 至少落在一塊；equal-or-disjoint lemma 排除部分重疊。',
      ],
      boundary:
        'Partition 只描述 set 被分塊；一般 left cosets 之間還不能直接定義 quotient group operation。',
    }),
  ],

  ch13: [
    lesson({
      id: '13.1',
      title: 'Lagrange 定理只是等大拼圖的計數',
      lede: '別先背「整除」。群被 cosets 無縫覆蓋，每塊和 H 等大，所以全體大小必然是 tile size 的整數倍。',
      predict: [
        '有限群 G 有 12 個 elements、H 有 3 個，left cosets 必有 4 塊嗎？',
        true,
        '12 個點由每塊 3 點的 disjoint tiles 覆蓋。',
        '既不能重疊也不能漏掉，所以恰為 4。',
      ],
      kind: 'partition',
      modelTitle: '把三個已證明的 facts 組起來',
      prompt: '切換證明階段：等大、不重疊、覆蓋，缺一不可。',
      presets: [
        {
          label: '每塊等大',
          blocks: [
            { label: 'H', items: ['h₁', 'h₂', 'h₃'], state: 'active' },
            { label: 'gH', items: ['gh₁', 'gh₂', 'gh₃'], state: 'active' },
          ],
          formula: '|gH|=|H|',
          detail: 'left translation 提供 bijection。',
          status: 'good',
        },
        {
          label: '無重疊',
          blocks: [
            { label: 'H', items: ['3 items'] },
            { label: 'aH', items: ['3 items'] },
            { label: 'bH', items: ['3 items'] },
          ],
          formula: 'distinct cosets are disjoint',
          detail: '沒有 element 被重複計數。',
          status: 'good',
        },
        {
          label: '完整覆蓋',
          blocks: [
            { label: 'H', items: ['3'] },
            { label: 'aH', items: ['3'] },
            { label: 'bH', items: ['3'] },
            { label: 'cH', items: ['3'] },
          ],
          formula: '12=4×3',
          detail: '沒有剩餘 elements，乘法計數成立。',
          status: 'good',
        },
      ],
      insight: '|H| divides |G| 的原因是 G 被 copies of H 等大、無重疊、無遺漏地鋪滿。',
      transfer: [
        '若 |G|=15，subgroup 能有 6 個 elements 嗎？',
        false,
        '6 不能整除 15。',
        'Lagrange 直接排除這種 tile size。',
      ],
      formal: [
        'Lagrange theorem',
        '有限群 G 與 H≤G 滿足 |G|=[G:H]|H|，故 |H| divides |G|。',
        '|G|=[G:H]\\,|H|',
      ],
      proof: [
        '把前章 lemmas 組裝',
        'Left cosets partition G。',
        '每個 coset 與 H bijective，所以大小皆 |H|。',
        'distinct cosets disjoint，因此總大小可直接相加。',
        '若 coset 數為 [G:H]，便得 |G|=[G:H]|H|。',
      ],
      boundary:
        '定理針對 finite group 的 cardinality 計數；無限 cardinal arithmetic 不能用同樣的「整除」語氣。',
    }),
    lesson({
      id: '13.2',
      title: 'Index 數的是 coset tiles，不是新運算',
      lede: '[G:H] 只是 H 在 G 中有多少個 distinct translates。Subgroup 越大，每塊越大，通常需要的塊數越少。',
      predict: [
        '若 H=G，index [G:H] 是 1 嗎？',
        true,
        '整個群本身就是唯一 coset。',
        '只有一塊 tile 就覆蓋全群。',
      ],
      kind: 'partition',
      modelTitle: '固定 G，改變 H 的 tile 尺寸',
      prompt: '比較同一個 Z₁₂ 的三種 subgroup。',
      presets: [
        {
          label: 'H={0}',
          blocks: Array.from({ length: 12 }, (_, i) => ({ label: `${i}+H`, items: [`${i}`] })),
          formula: '[Z₁₂:{0}]=12',
          detail: '每塊一點，共十二塊。',
          status: 'neutral',
        },
        {
          label: 'H=⟨4⟩',
          blocks: [
            { label: 'H', items: ['0', '4', '8'] },
            { label: '1+H', items: ['1', '5', '9'] },
            { label: '2+H', items: ['2', '6', '10'] },
            { label: '3+H', items: ['3', '7', '11'] },
          ],
          formula: '[Z₁₂:H]=4',
          detail: '每塊三點，共四塊。',
          status: 'good',
        },
        {
          label: 'H=Z₁₂',
          blocks: [{ label: 'H=G', items: z8.concat(['8', '9', '10', '11']), state: 'active' }],
          formula: '[G:G]=1',
          detail: '一塊就是全群。',
          status: 'good',
        },
      ],
      insight: 'Index [G:H] 是 coset 數；在 finite case，它等於 |G|/|H|。',
      transfer: [
        'Z₁₂ 中 H=⟨3⟩ 有 4 個 elements，因此 index 是 3 嗎？',
        true,
        '12/4=3，正是三個 cosets。',
        'tile size 4、tile count 3。',
      ],
      formal: ['Index', 'H 在 G 中的 distinct left cosets 數稱為 index，記作 [G:H]。', '[G:H]'],
      proof: [
        '兩個極端 index',
        '若 H={e}，每個 gH={g}，故 index=|G|。',
        '若 H=G，每個 gG=G。',
        '所以只有一個 distinct coset。',
        '故 [G:G]=1。',
      ],
      boundary:
        'Index 可以在 infinite groups 中定義為 coset cardinality；但不能總以普通整數除法處理。',
    }),
    lesson({
      id: '13.3',
      title: 'Element order 會整除 group order',
      lede: '每個 element 都生成 cyclic subgroup。把 Lagrange 套在 ⟨a⟩≤G，就把單一 action 的 cycle length 接到全群大小。',
      predict: [
        '10 階群中可能有 order 4 的 element 嗎？',
        false,
        '4 不整除 10。',
        '若有，⟨a⟩ 會是四元素 subgroup，違反 Lagrange。',
      ],
      kind: 'network',
      modelTitle: '先生成 cycle，再把 cycle 當 tile',
      prompt: '從 element order 轉成 subgroup size，再套 divisibility。',
      presets: [
        {
          label: '|G|=12, ord(a)=3',
          nodes: networkNodes(
            ['e', 'a', 'a²', 'tile 2', 'tile 3', 'tile 4'],
            ['a', 'a²', 'tile 2', 'tile 3', 'tile 4'],
          ),
          actions: ['生成 ⟨a⟩', '鋪成 4 tiles'],
          formula: '3∣12',
          detail: '三點 cycle 可作為四塊等大 tiles 的模板。',
          status: 'good',
        },
        {
          label: '|G|=12, ord(a)=4',
          nodes: networkNodes(
            ['e', 'a', 'a²', 'a³', 'tile 2', 'tile 3'],
            ['a', 'a²', 'a³', 'tile 2', 'tile 3'],
          ),
          actions: ['生成 ⟨a⟩', '鋪成 3 tiles'],
          formula: '4∣12',
          detail: '四點 cycle 也符合 Lagrange。',
          status: 'good',
        },
        {
          label: '|G|=10, ord(a)=4',
          nodes: networkNodes(['e', 'a', 'a²', 'a³', '剩 6 點'], ['a', 'a²', 'a³']),
          actions: ['嘗試鋪 tiles'],
          formula: '4∤10',
          detail: '無法用四點 tiles 無縫鋪滿十點。',
          status: 'bad',
        },
      ],
      insight: 'ord(a)=|⟨a⟩|，而 ⟨a⟩ 是 subgroup；所以 element order 必須整除 finite group order。',
      transfer: [
        '七階群的任一非 identity element 都有 order 7 嗎？',
        true,
        'order 大於 1 且整除 prime 7，只能是 7。',
        '因此每個非 identity element 都生成全群。',
      ],
      formal: [
        'Lagrange corollary',
        '對 finite G 中任意 a，ord(a) divides |G|；因此 a^{|G|}=e。',
        '\\operatorname{ord}(a)\\mid |G|',
      ],
      proof: [
        '推出 a^{|G|}=e',
        '令 n=ord(a)。',
        'Lagrange 給 n∣|G|，故 |G|=kn。',
        'a^{|G|}=a^{kn}=(a^n)^k。',
        '=e^k=e。',
      ],
      boundary: 'a^{|G|}=e 不表示 ord(a)=|G|；order 可能是 |G| 的較小 divisor。',
    }),
    lesson({
      id: '13.4',
      title: '整除只是不被排除，不保證存在',
      lede: 'Lagrange 是必要條件過濾器。通過 divisibility 只代表「可能」，仍需構造 subgroup 或使用更強定理。',
      predict: [
        '因為 4 divides 12，所以每個 12 階群都一定有 order 4 的 element 嗎？',
        false,
        'Lagrange 沒有提供存在性；A₄ 就沒有 order 4 element。',
        '對；必要條件的 converse 不能自動使用。',
      ],
      kind: 'diagnostic',
      modelTitle: '把 impossible 與 unresolved 分開',
      prompt: '紅燈代表被 Lagrange 排除；黃燈代表仍需額外證明。',
      presets: [
        {
          label: '|G|=12, order 5?',
          checks: [
            { label: 'divisibility', pass: false, reason: '5∤12。' },
            { label: '結論', pass: false, reason: '不可能存在。' },
          ],
          detail: '必要條件失敗，可直接排除。',
          status: 'bad',
        },
        {
          label: '|G|=12, order 4?',
          checks: [
            { label: 'divisibility', pass: true, reason: '4∣12。' },
            { label: '存在性', pass: false, reason: '尚未證明；A₄ 無此元素。' },
          ],
          detail: '通過過濾器不等於存在。',
          status: 'neutral',
        },
        {
          label: '|G|=12, subgroup order 3?',
          checks: [
            { label: 'divisibility', pass: true, reason: '3∣12。' },
            { label: '存在性', pass: false, reason: '需要 Cauchy/Sylow 或構造。' },
          ],
          detail: 'Lagrange 在這裡保持沉默。',
          status: 'neutral',
        },
      ],
      insight: 'Lagrange 能說「不整除就不可能」；不能反過來說「整除就一定存在」。',
      transfer: [
        '若 d 不整除 |G|，G 是否一定沒有 order d 的 subgroup？',
        true,
        'subgroup order 必須整除 group order。',
        '這是 Lagrange 的直接 contrapositive。',
      ],
      formal: ['Necessary, not sufficient', 'H≤G ⇒ |H| divides |G|；converse 在一般群中為 false。'],
      proof: [
        '辨認邏輯方向',
        '定理形式是 P⇒Q：是 subgroup 推出整除。',
        'Contrapositive ¬Q⇒¬P 合法：不整除推出不是 subgroup。',
        'Converse Q⇒P 是另一個命題。',
        '原定理沒有證明 converse。',
      ],
      boundary:
        'Cauchy theorem 對 prime divisors 提供元素存在性，但那是下一階段的新結果，不能冒充 Lagrange 的內容。',
    }),
  ],
};
