import type { AlgebraV2Lesson } from './algebra-v2-lessons';
import { check, makeLesson as L, networkNodes as nodes } from './algebra-v2-lesson-builder';

type Part4BChapterId = 'ch24' | 'ch25' | 'ch26' | 'ch27';

export const ALGEBRA_V2_PART4B_LESSONS: Record<Part4BChapterId, AlgebraV2Lesson[]> = {
  ch24: [
    L({
      id: '24.1',
      title: '到同一位置的 actions 正好是一塊 stabilizer coset',
      lede: 'Evaluation map ε_x:g↦g·x 把 actions 送到 positions。產生同一 position 的 actions 彼此只差一個固定 x 的 action。',
      predict: [
        '若 g·x=h·x，是否有 h⁻¹g∈G_x？',
        true,
        'h⁻¹g·x=h⁻¹·(h·x)=x。',
        '兩條 paths 的差異固定起點。',
      ],
      kind: 'partition',
      modelTitle: '按相同 destination 分組 actions',
      prompt: '每個 block 是 evaluation map 的 fiber，也是 G_x 的 coset。',
      presets: [
        {
          label: 'to x',
          blocks: [
            { label: 'x 的 fiber = G_x', items: ['e', 's'], state: 'active' },
            { label: 'to y', items: ['g', 'gs'] },
            { label: 'to z', items: ['h', 'hs'] },
          ],
          formula: 'gG_x ↦ g·x',
          detail: '固定 x 的 actions 形成 identity fiber。',
          status: 'good',
        },
        {
          label: 'to y',
          blocks: [
            { label: 'x', items: ['e', 's'] },
            { label: 'y fiber = gG_x', items: ['g', 'gs'], state: 'active' },
            { label: 'z', items: ['h', 'hs'] },
          ],
          formula: 'g·x=gs·x',
          detail: '右接 stabilizer action 不改 destination。',
          status: 'good',
        },
      ],
      insight: 'Orbit positions 是 actions 按 stabilizer cosets 分組後的 labels。',
      transfer: [
        'Orbit 是否可與 left coset set G/G_x 建立 bijection？',
        true,
        'gG_x↦g·x well-defined 且一一 onto。',
        '每塊 fiber 對應一個 reachable position。',
      ],
      formal: ['Orbit–coset bijection', 'Map G/G_x→Orb(x), gG_x↦g·x 是 bijection of sets。'],
      proof: [
        'Well-defined 與 injective',
        '若 gG_x=hG_x，則 h⁻¹g∈G_x。',
        '所以 h⁻¹g·x=x，亦即 g·x=h·x。',
        '反向同理：相同 output 推得同 coset。',
        '每個 orbit point 本來就是 g·x，所以 onto。',
      ],
      boundary: 'G_x 不一定 normal，因此 G/G_x 在此通常只是 coset set，不是 quotient group。',
    }),
    L({
      id: '24.2',
      title: 'Orbit size × stabilizer size = 全部 actions',
      lede: '每個 reachable position 有恰好 |G_x| 個 actions 抵達；所有 positions 的 fibers 等大且 partition G。',
      predict: [
        '八個 square symmetries 作用在四 vertices，vertex stabilizer 是否有 2 個 actions？',
        true,
        '8=4 positions×2 actions per position。',
        'identity 與一條 diagonal reflection 固定該 vertex。',
      ],
      kind: 'partition',
      modelTitle: '用等大 action fibers 鋪滿 G',
      prompt: '切換 object，看 orbit 大小與 local symmetry 如何互補。',
      presets: [
        {
          label: 'vertex',
          blocks: [
            { label: 'to A', items: ['2 actions'] },
            { label: 'to B', items: ['2 actions'] },
            { label: 'to C', items: ['2 actions'] },
            { label: 'to D', items: ['2 actions'] },
          ],
          formula: '8=4×2',
          detail: '移動自由度大，local symmetry 較小。',
          status: 'good',
        },
        {
          label: 'center',
          blocks: [{ label: 'to center', items: ['8 actions'], state: 'active' }],
          formula: '8=1×8',
          detail: '完全不能移動，但全部 actions 都固定它。',
          status: 'good',
        },
        {
          label: 'diagonal',
          blocks: [
            { label: 'to d₁', items: ['4 actions'] },
            { label: 'to d₂', items: ['4 actions'] },
          ],
          formula: '8=2×4',
          detail: '兩個 reachable positions，每個有四條 action paths。',
          status: 'good',
        },
      ],
      insight:
        'Orbit–stabilizer 是 reachability 與 invisibility 的守恆：可達位置越多，每個位置的 action redundancy 越少。',
      transfer: [
        '若 finite G action freely（所有 stabilizers trivial），每個 orbit 是否有 |G| 個 points？',
        true,
        '|Orb(x)|=|G|/1。',
        '沒有兩個 actions 產生同一 destination。',
      ],
      formal: [
        'Orbit–stabilizer theorem',
        'Finite G action 滿足 |G|=|Orb(x)|·|G_x|。',
        '|G|=|G\\cdot x|\\,|G_x|',
      ],
      proof: [
        '由 fibers 計數',
        'Evaluation ε_x:G→Orb(x) surjective。',
        '每個 fiber 是 G_x 的一個 coset，大小 |G_x|。',
        'Fibers 由 orbit points 索引且 partition G。',
        '所以總大小等於 block 數乘 block size。',
      ],
      boundary: 'Theorem 計數的是一個指定 x 的 orbit 與 stabilizer；不同 orbits 要分開套用。',
    }),
    L({
      id: '24.3',
      title: '不列出全部 actions，也能算 orbit 或 stabilizer',
      lede: '知道三個 quantities 中兩個，就能求第三個。重點是先選有意義的 action stage，而不是機械代公式。',
      predict: [
        '24 個 rotations 作用在 cube 的 8 vertices；vertex stabilizer order 是否為 3？',
        true,
        '24/8=3。',
        '三種 rotations 保持指定 vertex：繞對角軸 0°,120°,240°。',
      ],
      kind: 'cube',
      modelTitle: '在陌生 symmetry problem 中選對三個量',
      prompt: '先辨認 G、X、x，再決定已知的 orbit。',
      presets: [
        {
          label: 'cube vertex',
          cube: {
            axis: [1, 1, 1],
            angle: 120,
            focus: 'vertex',
            focusLabel: '固定 vertex v',
            invariant: '每轉 120°，v 留在原位；其餘 vertices 以 3-cycles 移動。',
          },
          checks: [
            check('|G|', true, '24 rotations。'),
            check('|Orb(v)|', true, '8 vertices，action transitive。'),
            check('|G_v|', true, '24/8=3。'),
          ],
          detail: '不用列 24 個 rotations。',
          status: 'good',
        },
        {
          label: 'cube face',
          cube: {
            axis: [0, 1, 0],
            angle: 90,
            focus: 'face',
            focusLabel: '固定 face f',
            invariant: '每轉 90°，整個 face setwise 固定，但 face 上的 vertices 互換。',
          },
          checks: [
            check('|G|', true, '24。'),
            check('|Orb(f)|', true, '6 faces。'),
            check('|G_f|', true, '4。'),
          ],
          detail: '固定 face 的 rotations 是四個 quarter turns。',
          status: 'good',
        },
        {
          label: '錯誤套法',
          cube: {
            axis: [1, 0, 0],
            angle: 45,
            focus: 'none',
            focusLabel: '任意 45° 並非 cube symmetry',
            invariant: '操作若沒有把 cube 搬回自己，就不屬於 rotation group。',
          },
          checks: [
            check('先證 transitive', false, '不能直接把 |X| 當 orbit size。'),
            check('指定 point', false, 'stabilizer 必須相對某 x。'),
          ],
          detail: '公式前要先確認 action geometry。',
          status: 'bad',
        },
      ],
      insight: 'Orbit–stabilizer 是 action model 的計數工具；模型選對，枚舉工作會大幅縮小。',
      transfer: [
        '若 orbit size 不整除 |G|，這個 action description 是否可能正確？',
        false,
        'orbit size=[G:G_x] 必整除 finite |G|。',
        '可立即偵測建模或計數錯誤。',
      ],
      formal: ['Index form', '|Orb(x)|=[G:G_x]；orbit size 是 point stabilizer 的 index。'],
      proof: [
        '使用 checklist',
        '明確寫出 group G 與 state set X。',
        '選定 x 並求/證明其 orbit size。',
        '套 |G|=|Orb(x)||G_x|。',
        '最後用幾何回看 stabilizer 是否合理。',
      ],
      boundary: '相同數字分解可能來自不同 actions；公式不取代結構解釋。',
    }),
  ],

  ch25: [
    L({
      id: '25.1',
      title: 'Conjugation 是換座標、做 action、再換回來',
      lede: 'gag⁻¹ 不是三個互不相關的 factors。它把 action a 搬到由 g 指定的新觀察座標，因此保留 action type。',
      predict: [
        '在 permutation group 中，g(12)g⁻¹ 是否交換 g(1) 與 g(2)？',
        true,
        'g⁻¹ 先找回舊 labels，(12) 交換，再由 g 換成新 labels。',
        '所以 conjugation 只是 relabeling moved points。',
      ],
      kind: 'timeline',
      modelTitle: '逐層播放 coordinate sandwich',
      prompt: '本課 convention 最右側先作用。',
      presets: [
        {
          label: '換回舊座標',
          before: 'new state',
          actions: ['g⁻¹'],
          after: 'old coordinates',
          formula: 'g⁻¹',
          detail: '先把新 observer 拉回 a 熟悉的座標。',
          status: 'neutral',
        },
        {
          label: '執行 a',
          before: 'old coordinates',
          actions: ['a'],
          after: 'old transformed',
          formula: 'ag⁻¹',
          detail: '在舊座標做原 action type。',
          status: 'neutral',
        },
        {
          label: '換到新座標',
          before: 'old transformed',
          actions: ['g'],
          after: 'new transformed',
          formula: 'gag⁻¹',
          detail: '回到原 observer，得到 conjugate action。',
          status: 'good',
        },
      ],
      insight: 'Conjugate elements 是同一種 action pattern 在不同 labels／座標中的版本。',
      transfer: [
        'Conjugation 是否保留 element order？',
        true,
        '(gag⁻¹)^n=ga^ng⁻¹。',
        'a 第一次回到 e 的時間不會被 relabeling 改變。',
      ],
      formal: ['Conjugate elements', 'a,b∈G conjugate 若存在 g 使 b=gag⁻¹。'],
      proof: [
        'Powers 穿過 conjugation',
        '(gag⁻¹)²=gag⁻¹gag⁻¹。',
        '中間 g⁻¹g=e，化成 ga²g⁻¹。',
        'Induction 得 (gag⁻¹)^n=ga^ng⁻¹。',
        '所以 orders 相同。',
      ],
      boundary: 'Conjugate 不等於 commute；gag⁻¹ 通常不是 a。',
    }),
    L({
      id: '25.2',
      title: 'Conjugacy class 收集所有座標版本',
      lede: '固定 a，讓所有 g 改變 observer。得到的 orbit {gag⁻¹} 就是 a 的 conjugacy class。',
      predict: [
        'Abelian group 的 conjugacy classes 都只有一個 element 嗎？',
        true,
        'gag⁻¹=agg⁻¹=a。',
        '換座標不改任何 action。',
      ],
      kind: 'network',
      modelTitle: '讓 G 以 conjugation 作用在自己身上',
      prompt: '亮點是 a 的所有 conjugate coordinate versions。',
      presets: [
        {
          label: 'S₃ transpositions',
          nodes: nodes(['e', '(12)', '(13)', '(23)', '(123)', '(132)'], ['(13)', '(23)'], '(12)'),
          actions: ['relabel 1,2,3'],
          formula: 'Cl((12))={(12),(13),(23)}',
          detail: '三種 swaps 是同一 action type。',
          status: 'good',
        },
        {
          label: 'S₃ 3-cycles',
          nodes: nodes(['e', '(12)', '(13)', '(23)', '(123)', '(132)'], ['(132)'], '(123)'),
          actions: ['relabel'],
          formula: 'Cl((123))={(123),(132)}',
          detail: '兩個方向的 3-cycle conjugate。',
          status: 'good',
        },
        {
          label: 'identity',
          nodes: nodes(['e', 'others'], [], 'e'),
          actions: ['geg⁻¹'],
          formula: 'Cl(e)={e}',
          detail: 'identity 在任何座標都不動。',
          status: 'neutral',
        },
      ],
      insight:
        'Conjugacy classes 是 conjugation action 的 orbits；它們按 action type partition G。',
      transfer: [
        'Sₙ 中有相同 cycle type 的 permutations 是否 conjugate？',
        true,
        'relabeling 可把每個 cycle 的 labels 對齊。',
        'cycle lengths 是 coordinate-free action pattern。',
      ],
      formal: ['Conjugacy class', 'Cl_G(a)={gag⁻¹:g∈G}=Orb under conjugation。'],
      proof: [
        'Conjugacy 是 equivalence relation',
        'eae⁻¹=a，故 reflexive。',
        '若 b=gag⁻¹，則 a=g⁻¹bg，故 symmetric。',
        '若 c=hbh⁻¹ 且 b=gag⁻¹，則 c=(hg)a(hg)⁻¹，故 transitive。',
        '所以 classes partition G。',
      ],
      boundary: '相同 order 不保證 conjugate；order 只是較粗 invariant。',
    }),
    L({
      id: '25.3',
      title: 'Center 是任何座標都不變的 actions',
      lede: '若 a 與每個 g commute，gag⁻¹=a；它在 conjugation action 下 fixed by all G。這些 elements 組成 center。',
      predict: [
        'a 的 conjugacy class 是 singleton，是否等價於 a∈Z(G)？',
        true,
        'gag⁻¹=a 等價 ga=ag for every g。',
        '全域 fixed point 正是 central element。',
      ],
      kind: 'diagnostic',
      modelTitle: '用 conjugation fixed-point test 找 center',
      prompt: '比較 commute with all 與 commute with some。',
      presets: [
        {
          label: 'a central',
          checks: [
            check('對所有 g', true, 'ga=ag。'),
            check('conjugates', true, 'gag⁻¹=a。'),
            check('class size', true, '1。'),
          ],
          detail: 'a 是 global fixed point。',
          status: 'good',
        },
        {
          label: 'a noncentral',
          checks: [
            check('對某些 g', true, '可能 commute。'),
            check('對所有 g', false, '至少一個 witness 不 commute。'),
            check('class size', false, '大於 1。'),
          ],
          detail: '局部 commuting 不足以 central。',
          status: 'bad',
        },
        {
          label: 'G abelian',
          checks: [
            check('每個 pair commute', true, '定義。'),
            check('Z(G)=G', true, '全部 central。'),
            check('all classes singleton', true, 'conjugation trivial。'),
          ],
          detail: 'Center 達到最大。',
          status: 'good',
        },
      ],
      insight:
        'Center Z(G) 是 conjugation action 完全看不見的部分，也是所有 coordinate systems 都同意的 actions。',
      transfer: [
        'Z(G) 是否一定 normal？',
        true,
        'central elements conjugate 後仍是自己。',
        '它也是 conjugation action 的 fixed set。',
      ],
      formal: ['Center', 'Z(G)={a∈G:ag=ga for all g∈G}。'],
      proof: [
        'Center 是 subgroup',
        'e commute with all。',
        '若 a,b central，則 (ab)g=a(bg)=a(gb)=(ag)b=(ga)b=g(ab)。',
        'a⁻¹也與所有 g commute。',
        '故 Z(G)≤G，且 normal。',
      ],
      boundary:
        'Centralizer C_G(a) 只要求 commute with 指定 a；center 是所有 centralizers 的 intersection。',
    }),
  ],

  ch26: [
    L({
      id: '26.1',
      title: 'Centralizer 是 conjugation action 的 stabilizer',
      lede: '哪些 g 換座標後仍讓 a 看起來相同？條件 gag⁻¹=a 正好等價 ga=ag，因此 stabilizer of a 就是 centralizer。',
      predict: [
        'C_G(a) 是否一定是 subgroup？',
        true,
        '它就是 action stabilizer。',
        '固定 a 的 coordinate changes 能合成與撤銷。',
      ],
      kind: 'symbols',
      modelTitle: '把 action language 翻成 commuting language',
      prompt: '兩條定義不是巧合，而是同一 equation 的重排。',
      presets: [
        {
          label: 'stabilizer view',
          mapping: [{ from: 'g·a=gag⁻¹', to: 'a fixed' }],
          formula: 'Stab(a)',
          detail: 'g 在 conjugation action 中固定 a。',
          status: 'good',
        },
        {
          label: 'commuting view',
          mapping: [{ from: 'gag⁻¹=a', to: 'ga=ag' }],
          formula: 'C_G(a)',
          detail: '右乘 g 把 fixed equation 改寫成 commute。',
          status: 'good',
        },
      ],
      insight:
        'Centralizer C_G(a) 是能與 a 相容的 coordinate changes；它控制 a 有多少不同 conjugates。',
      transfer: [
        '若 a central，C_G(a) 是否等於 G？',
        true,
        '每個 g 都與 a commute。',
        'stabilizer 最大，orbit 因而只有一點。',
      ],
      formal: ['Centralizer', 'C_G(a)={g∈G:ga=ag}=Stab_G(a) under conjugation。'],
      proof: [
        'Centralizer subgroup test',
        'e commute with a。',
        '若 g,h commute with a，h⁻¹也 commute with a。',
        '因此 gh⁻¹ 與 a commute。',
        '故 C_G(a)≤G。',
      ],
      boundary: 'C_G(a) 依賴 a；Z(G) 才是對所有 a 同時 commute 的 elements。',
    }),
    L({
      id: '26.2',
      title: 'Conjugacy class size 是 centralizer 的 index',
      lede: '直接數 a 的 coordinate versions 很難；orbit–stabilizer 把它改成算有哪些 group elements 不會改變 a。',
      predict: [
        '若 |G|=24、|C_G(a)|=6，a 是否有 4 個 conjugates？',
        true,
        '|Cl(a)|=[G:C_G(a)]=24/6。',
        '對；共有四個 orbit positions。',
      ],
      kind: 'partition',
      modelTitle: '把 coordinate changes 按相同 conjugate 分組',
      prompt: '每塊是 C_G(a) coset，對應一個 class element。',
      presets: [
        {
          label: 'class of a',
          blocks: [
            { label: 'a', items: ['6 coordinate changes'] },
            { label: 'a₂', items: ['6'] },
            { label: 'a₃', items: ['6'] },
            { label: 'a₄', items: ['6'] },
          ],
          formula: '24=4×6',
          detail: '四個 conjugates，每個有六種 g 產生。',
          status: 'good',
        },
        {
          label: 'a central',
          blocks: [{ label: 'a only', items: ['all 24 changes'], state: 'active' }],
          formula: '24=1×24',
          detail: 'Centralizer=G，class singleton。',
          status: 'neutral',
        },
      ],
      insight: 'Action type 的版本數與保留該版本的 coordinate changes 數互補。',
      transfer: [
        'Conjugacy class size 是否一定整除 |G|？',
        true,
        '它是 subgroup C_G(a) 的 index。',
        'orbit–stabilizer／Lagrange 都給整除。',
      ],
      formal: ['Class size formula', '|Cl_G(a)|=[G:C_G(a)]=|G|/|C_G(a)|。'],
      proof: [
        '直接套 orbit–stabilizer',
        'G 以 conjugation 作用在 G。',
        'Orbit of a 是 Cl_G(a)。',
        'Stabilizer of a 是 C_G(a)。',
        '所以 |G|=|Cl(a)||C_G(a)|。',
      ],
      boundary: 'Class size 不是 element order；兩者可能完全不同。',
    }),
    L({
      id: '26.3',
      title: 'Class equation 把群按 action types 完整分帳',
      lede: 'Conjugacy classes partition G。Central elements 各自形成 singleton，其餘 classes 的大小由 centralizer indices 決定。',
      predict: [
        'Class equation 是否只是把 |G| 寫成任意整數分割？',
        false,
        '每一項必是實際 conjugacy class size，受 centralizers 控制。',
        '這些 summands 帶有 group structure。',
      ],
      kind: 'partition',
      modelTitle: '把 elements 吸入 conjugacy class tiles',
      prompt: '先分出 center singleton，再加入 noncentral classes。',
      presets: [
        {
          label: 'center',
          blocks: [
            { label: 'Z(G)', items: ['z₁', 'z₂'], state: 'active' },
            { label: '未分類', items: ['noncentral elements'] },
          ],
          formula: '|Z(G)| singleton classes',
          detail: '每個 central element 自成一類。',
          status: 'neutral',
        },
        {
          label: '完整分類',
          blocks: [
            { label: 'Z(G)', items: ['z₁', 'z₂'] },
            { label: 'Cl(a₁)', items: ['index size'] },
            { label: 'Cl(a₂)', items: ['index size'] },
            { label: '…', items: ['全部覆蓋'] },
          ],
          formula: '|G|=|Z(G)|+Σ[G:C_G(a_i)]',
          detail: '無重疊且無遺漏。',
          status: 'good',
        },
      ],
      insight:
        'Class equation 是 conjugation action 的 orbit partition 加上 orbit–stabilizer，不是憑空的新公式。',
      transfer: [
        '有限 p-group 的 noncentral class sizes 是否都是 p 的倍數？',
        true,
        '它們是 p-power |G| 的非一 index divisors。',
        '這會迫使 center 大小可被 p 整除。',
      ],
      formal: [
        'Class equation',
        '取每個 noncentral conjugacy class representative a_i，則 |G|=|Z(G)|+Σ_i[G:C_G(a_i)]。',
      ],
      proof: [
        '公式組裝',
        'Conjugacy classes partition G。',
        'Central classes 恰為 singleton，共 |Z(G)| 個 elements。',
        '每個 noncentral class size 是 [G:C_G(a_i)]。',
        '把 disjoint class sizes 相加即得。',
      ],
      boundary: '選 representatives 可不同，但每個 class 只能計一次。',
    }),
  ],

  ch27: [
    L({
      id: '27.1',
      title: '要數不同 objects，其實是在數 action orbits',
      lede: '兩個 colorings 若可由 symmetry 互相轉換，就屬於同一 orbit。直接列 representatives 常重複或漏掉，先把問題翻成 orbit count。',
      predict: [
        '正方形四頂點用黑白染色，共 16 個 raw colorings；不同 necklaces 也一定有 16 個嗎？',
        false,
        'rotations 會把多個 raw colorings 合併成同一 orbit。',
        '要數的是 orbit 數，不是 state 數。',
      ],
      kind: 'partition',
      modelTitle: '讓 symmetry 把 raw states 吸成 classes',
      prompt: '比較 orbit size 4、2、1；高度對稱 states 的 orbit 較小。',
      presets: [
        {
          label: 'generic coloring',
          blocks: [{ label: 'one orbit', items: ['x', 'r·x', 'r²·x', 'r³·x'], state: 'active' }],
          formula: 'orbit size 4',
          detail: '無 nontrivial rotation 固定它。',
          status: 'good',
        },
        {
          label: 'half-turn symmetry',
          blocks: [{ label: 'one orbit', items: ['x', 'r·x'], state: 'active' }],
          formula: 'orbit size 2',
          detail: '180° rotation 已固定 coloring。',
          status: 'good',
        },
        {
          label: 'all same',
          blocks: [{ label: 'one orbit', items: ['x'], state: 'active' }],
          formula: 'orbit size 1',
          detail: '所有 rotations 都固定它。',
          status: 'neutral',
        },
      ],
      insight:
        'Symmetry-aware counting 的對象是 orbits；高對稱 objects 不能用固定 orbit size 粗暴相除。',
      transfer: [
        '若 action free，orbit count 是否等於 |X|/|G|？',
        true,
        '每個 orbit 都有 |G| 個 states。',
        '但有 fixed points 時這個捷徑失敗。',
      ],
      formal: [
        'Orbit counting problem',
        'Unlabeled configurations 對應 finite action G↷X 的 orbit set X/G。',
      ],
      proof: [
        '為何不能總除以 |G|',
        'Orbit–stabilizer 給 |Orb(x)|=|G|/|G_x|。',
        '不同 x 的 stabilizer sizes 可能不同。',
        '所以 orbit sizes 不一致。',
        '必須用能校正 fixed points 的方法。',
      ],
      boundary: '先確認 equivalence 真由 group action 產生；不是所有「看起來相似」都應放同 orbit。',
    }),
    L({
      id: '27.2',
      title: '改數 action–state 的 fixed incidences',
      lede: '建立表格：rows 是 g∈G，columns 是 x∈X；若 g fixes x 就打勾。同一批勾可按 rows 或按 orbit blocks 兩種方式計數。',
      predict: [
        'Σ_g |Fix(g)| 是否與 Σ_x |G_x| 相等？',
        true,
        '兩者都在數 pairs (g,x) with g·x=x。',
        '只是先固定 action 或先固定 state。',
      ],
      kind: 'table',
      modelTitle: '用雙重計數改變困難方向',
      prompt: '每個高亮 cell 是一個 fixed incidence。',
      presets: [
        {
          label: 'fixed-point grid',
          table: {
            headers: ['x₁', 'x₂', 'x₃', 'x₄'],
            rowHeaders: ['e', 'r', 'r²', 'r³'],
            rows: [
              ['✓', '✓', '✓', '✓'],
              ['×', '×', '×', '×'],
              ['✓', '×', '✓', '×'],
              ['×', '✓', '×', '✓'],
            ],
          },
          tableNote: 'rows 是 actions，columns 是 states；✓ 表示 fixed incidence。',
          formula: 'row sums = |Fix(g)|',
          detail: '沿 rows 數每個 action 固定多少 states。',
          status: 'good',
        },
        {
          label: 'column view',
          table: {
            headers: ['x₁', 'x₂', 'x₃', 'x₄'],
            rowHeaders: ['e', 'r', 'r²', 'r³'],
            rows: [
              ['✓', '✓', '✓', '✓'],
              ['×', '×', '×', '×'],
              ['✓', '×', '✓', '×'],
              ['×', '✓', '×', '✓'],
            ],
          },
          tableNote: 'rows 是 actions，columns 是 states；✓ 表示 fixed incidence。',
          formula: 'column sums = |G_x|',
          detail: '沿 columns 數每個 state 的 stabilizer。',
          status: 'good',
        },
      ],
      insight:
        'Burnside 的引擎是 double counting：同一張 fixed-incidence 表從 action side 與 state side 各數一次。',
      transfer: [
        'Identity action 的 Fix(e) 是否等於全部 X？',
        true,
        'identity 固定每個 state。',
        '它通常是平均中的最大 row。',
      ],
      formal: ['Fixed set', 'Fix(g)={x∈X:g·x=x}。Double count gives Σ_g|Fix(g)|=Σ_x|G_x|。'],
      proof: [
        '按 orbit 重組 column sum',
        '同一 orbit O 中，每個 x 的 stabilizer order 相同。',
        '更直接地 Σ_{x∈O}|G_x|=Σ_{x∈O}|G|/|O|。',
        '=|O|·|G|/|O|=|G|。',
        '每個 orbit 對總 incidence 貢獻恰 |G|。',
      ],
      boundary: 'Fix(g) 是 state subset；不要與 kernel（固定所有 states 的 actions）混淆。',
    }),
    L({
      id: '27.3',
      title: '平均 fixed points 恰好等於 orbit 數',
      lede: '每個 orbit 對 fixed-incidence 總數貢獻 |G|。除以 actions 數後，每個 orbit 正好貢獻 1。',
      predict: [
        'Burnside average 可能得到非整數嗎？',
        false,
        '它等於 orbit count，必為 integer。',
        '若算出分數，fixed-point 計數有誤。',
      ],
      kind: 'diagnostic',
      modelTitle: '把 double count 壓成一條可重建公式',
      prompt: '三步依序檢查 action、fixed counts、average。',
      presets: [
        {
          label: '公式骨架',
          checks: [
            check('列出每個 g', true, '按 action types 可合併。'),
            check('數 |Fix(g)|', true, '逐類找 constraints。'),
            check('取平均', true, '除以 |G|。'),
            check('結果', true, '#orbits。'),
          ],
          formula: '|X/G|=(1/|G|)Σ_g|Fix(g)|',
          detail: '不是背平均，而是每 orbit 貢獻 1。',
          status: 'good',
        },
        {
          label: 'sanity checks',
          checks: [
            check('identity fixes |X|', true, '必查。'),
            check('average integer', true, '必查。'),
            check('average≤|X|', true, 'orbits 不多於 states。'),
          ],
          detail: '三項可快速抓錯。',
          status: 'good',
        },
      ],
      insight:
        'Burnside lemma 把難數的 orbits 換成通常較容易按 symmetry type 計算的 fixed states。',
      transfer: [
        '若只有 identity 有 fixed points，Burnside 是否退化為 |X|/|G|？',
        true,
        'sum 只有 |Fix(e)|=|X|。',
        '這正是 free action case。',
      ],
      formal: [
        'Burnside lemma',
        '對 finite G↷X，orbit 數為 (1/|G|)Σ_{g∈G}|Fix(g)|。',
        '|X/G|=\\frac1{|G|}\\sum_{g\\in G}|\\operatorname{Fix}(g)|',
      ],
      proof: [
        '從 incidence 到公式',
        '總 incidences I=Σ_g|Fix(g)|。',
        '按 orbits 分組時，每個 orbit 貢獻 |G|。',
        '若 orbit 數為 m，I=m|G|。',
        '兩邊除以 |G| 得 m。',
      ],
      boundary: 'Burnside lemma 不是 Burnside p^aq^b theorem；兩者只是人名相同。',
    }),
    L({
      id: '27.4',
      title: '按 symmetry type 數 fixed colorings',
      lede: '真正的工作不是代公式，而是理解「被某 rotation 固定」對 colors 加了哪些 equality constraints。Cycles 越長，自由選擇越少。',
      predict: [
        '四珠二色 necklace 被 90° rotation 固定的 colorings 是否只有 2 個？',
        true,
        '四個位置必須同色，只剩全黑或全白。',
        '一條 4-cycle 只能選一個共同 color。',
      ],
      kind: 'diagnostic',
      modelTitle: '四珠二色 necklace 的 Burnside worksheet',
      prompt: '逐 rotation type 計算 fixed colorings，再平均。',
      presets: [
        {
          label: 'identity',
          checks: [
            check('position cycles', true, '4 個 1-cycles。'),
            check('自由選色', true, '2⁴=16。'),
          ],
          formula: 'Fix(e)=16',
          detail: '沒有 equality constraint。',
          status: 'good',
        },
        {
          label: '90° / 270°',
          checks: [
            check('position cycles', true, '1 個 4-cycle。'),
            check('自由選色', true, '2¹=2 each。'),
          ],
          formula: 'Fix(r)=Fix(r³)=2',
          detail: '四珠必須同色。',
          status: 'good',
        },
        {
          label: '180°',
          checks: [
            check('position cycles', true, '2 個 2-cycles。'),
            check('自由選色', true, '2²=4。'),
          ],
          formula: 'Fix(r²)=4',
          detail: '相對珠成對同色。',
          status: 'good',
        },
        {
          label: 'average',
          checks: [check('sum', true, '16+2+4+2=24。'), check('divide by 4', true, '6 orbits。')],
          formula: '24/4=6',
          detail: '得到六種 rotation-distinct necklaces。',
          status: 'good',
        },
      ],
      insight:
        'Coloring 被 permutation 固定，等價於每個 position cycle 上顏色一致；fixed count 是 colors^{#cycles}。',
      transfer: [
        '若有 k 種 colors、position permutation 有 c 個 cycles，fixed colorings 是否為 k^c？',
        true,
        '每個 cycle 可獨立選一種共同 color。',
        'Cycle decomposition 直接轉成自由度。',
      ],
      formal: [
        'Coloring fixed-point rule',
        'Permutation g on positions has c(g) cycles 時，k-colorings fixed by g 的數量為 k^{c(g)}。',
      ],
      proof: [
        '為何每 cycle 一個自由選擇',
        'Fixed coloring 要求 color(i)=color(g·i)。',
        '沿 cycle 重複，整條 cycle colors 相同。',
        '不同 disjoint cycles 互不限制。',
        '每個 cycle k choices，共 k^c。',
      ],
      boundary: '若還有限制每色使用次數，k^c 不能直接套用，需在 cycle constraints 下重新計數。',
    }),
  ],
};
