import type { AlgebraV2Lesson } from './algebra-v2-lessons';
import { check, makeLesson as L, networkNodes as nodes } from './algebra-v2-lesson-builder';

type Part4AChapterId = 'ch19' | 'ch20' | 'ch21' | 'ch22' | 'ch23';

export const ALGEBRA_V2_PART4A_LESSONS: Record<Part4AChapterId, AlgebraV2Lesson[]> = {
  ch19: [
    L({
      id: '19.1',
      title: 'Permutation 是不遺失 state 的重新排列',
      lede: 'Permutation 不是一串數字，而是 finite state set 上的 bijective transformation；每個 input 有唯一去處，而且每個位置恰好被一個 input 佔據。',
      predict: [
        '把 A,B,C 都送到 A，算是一個 permutation 嗎？',
        false,
        'outputs collision，無法 reverse。',
        '對；這是 function，但不是 bijection。',
      ],
      kind: 'mapping',
      modelTitle: '檢查重新排列是否可逆',
      prompt: '追蹤 collision、missing target 與完整配對。',
      presets: [
        {
          label: '3-cycle',
          mapping: [
            { from: 'A', to: 'B' },
            { from: 'B', to: 'C' },
            { from: 'C', to: 'A' },
          ],
          checks: [
            check('每個 input 有 output', true, 'function。'),
            check('無 collision', true, 'injective。'),
            check('無空位', true, 'surjective。'),
          ],
          detail: '完整 bijection，因此是 permutation。',
          status: 'good',
        },
        {
          label: 'collision',
          mapping: [
            { from: 'A', to: 'A' },
            { from: 'B', to: 'A', accent: true },
            { from: 'C', to: 'C' },
          ],
          checks: [
            check('每個 input 有 output', true, 'function。'),
            check('無 collision', false, 'A、B 同到 A。'),
            check('可逆', false, 'output A 無法判斷來源。'),
          ],
          detail: '資訊被合併，不是 permutation。',
          status: 'bad',
        },
      ],
      insight:
        'Permutation 是 finite states 的 reversible action；bijection 正是「可完整 undo」的 set-language。',
      transfer: [
        '洗牌若保留每張牌且不重複，是否是 permutation？',
        true,
        '每張牌有唯一新位置，每個位置有唯一牌。',
        '因此存在 inverse shuffle。',
      ],
      formal: [
        'Permutation',
        'Set X 上的 permutation 是 bijection σ:X→X；全部 permutations 組成 Sym(X)。',
      ],
      proof: [
        'Inverse 為何仍是 permutation',
        'σ bijective，所以 inverse function σ⁻¹ 存在。',
        'σ⁻¹ 對每個 output 找回唯一 input。',
        '它同樣一一且 onto。',
        '因此 reverse shuffle 仍是 permutation。',
      ],
      boundary: 'Permutation 保留的是 elements 的身分與數量，不必保留幾何距離或圖形。',
    }),
    L({
      id: '19.2',
      title: 'Permutation composition 要從右邊先執行',
      lede: 'Notation στ 表示先做 τ、再做 σ，因為 composition 讀作 σ(τ(x))。與其背方向，固定追蹤一個 token 就不會弄反。',
      predict: [
        '若 σ=(交換 A,B)、τ=(交換 B,C)，στ 與 τσ 一定相同嗎？',
        false,
        '兩條 action order 會把 A 送到不同位置。',
        '對；permutation group 通常 nonabelian。',
      ],
      kind: 'timeline',
      modelTitle: '固定 token A，交換執行順序',
      prompt: '從同一 START 逐步讀每個 action chip。',
      presets: [
        {
          label: 'στ：先 τ',
          before: 'A',
          actions: ['τ: A→A', 'σ: A→B'],
          after: 'B',
          formula: '(στ)(A)=B',
          detail: '右側 τ 先作用。',
          status: 'neutral',
        },
        {
          label: 'τσ：先 σ',
          before: 'A',
          actions: ['σ: A→B', 'τ: B→C'],
          after: 'C',
          formula: '(τσ)(A)=C',
          detail: '同一 token 落到不同終點。',
          status: 'bad',
        },
        {
          label: '完整 mapping',
          before: 'A,B,C',
          actions: ['τ', 'σ'],
          after: 'A→B, B→C, C→A',
          formula: 'στ=(ABC)',
          detail: '追完所有 inputs 才得到完整 permutation。',
          status: 'good',
        },
      ],
      insight: 'Composition order 是 action pipeline 的時間順序；追蹤 token 比背「右到左」更可靠。',
      transfer: [
        'Function composition f∘g 是否同樣先做 g？',
        true,
        '(f∘g)(x)=f(g(x))。',
        'permutation composition 就是 function composition。',
      ],
      formal: ['Composition convention', '本課採 στ=σ∘τ，因此最右側 action 最先執行。'],
      proof: [
        '如何證明兩 permutations 不同',
        'Functions 不同只需一個 witness input。',
        '挑一個 token x。',
        '分別追蹤 στ(x) 與 τσ(x)。',
        '若終點不同，就已證明 στ≠τσ。',
      ],
      boundary: '不同教材可能採相反的 action convention；先確認定義，再保持全程一致。',
    }),
    L({
      id: '19.3',
      title: 'Sₙ 是 n 個 states 的全部 reversible actions',
      lede: 'Identity、inverse 與 composition 都留在 permutations 中，因此全部 n-state rearrangements 自然形成一個群。',
      predict: [
        'S₃ 只有三個 permutations 嗎？',
        false,
        '第一格 3 種、第二格 2 種、最後 1 種，共 3!=6。',
        '對；states 數與 permutations 數不是同一件事。',
      ],
      kind: 'network',
      modelTitle: '展開三個 states 的全部 arrangements',
      prompt: '亮起一種 action family，觀察六個 effects。',
      presets: [
        {
          label: 'identity',
          nodes: nodes(['e', '(12)', '(13)', '(23)', '(123)', '(132)'], []),
          actions: ['不動'],
          formula: '1 element',
          detail: '所有 tokens 留在原位。',
          status: 'neutral',
        },
        {
          label: 'transpositions',
          nodes: nodes(['e', '(12)', '(13)', '(23)', '(123)', '(132)'], ['(12)', '(13)', '(23)']),
          actions: ['交換一對'],
          formula: '3 elements',
          detail: '三種單次交換。',
          status: 'good',
        },
        {
          label: '3-cycles',
          nodes: nodes(['e', '(12)', '(13)', '(23)', '(123)', '(132)'], ['(123)', '(132)']),
          actions: ['循環三點'],
          formula: '2 elements',
          detail: '兩種方向的三點循環。',
          status: 'good',
        },
      ],
      insight: 'Sₙ 是所有 n-state bijections 的 action group；其 order 是 n!。',
      transfer: ['S₄ 的大小是否為 24？', true, '4·3·2·1=24。', '逐格安排四個 distinct tokens。'],
      formal: [
        'Symmetric group',
        'Sₙ 是 {1,…,n} 上全部 permutations，在 composition 下形成 order n! 的群。',
        '|S_n|=n!',
      ],
      proof: [
        '為何 permutations 形成群',
        'Bijections composition 後仍 bijective。',
        'Function composition associative。',
        'Identity function 是 permutation。',
        '每個 bijection 有 inverse bijection。',
      ],
      boundary: 'Sₙ 的元素是 functions，不是被排列的 n 個 objects 本身。',
    }),
  ],

  ch20: [
    L({
      id: '20.1',
      title: 'Cycle notation 只記錄 token 的閉合軌道',
      lede: '從一個 token 出發反覆套 permutation，直到回到起點；括號記錄這條 orbit，沒有出現的 tokens 就固定不動。',
      predict: [
        '(1 3 2) 是否表示 1→3、3→2、2→1？',
        true,
        '括號依序連接，最後回到第一個。',
        '這是同一個三點 closed orbit。',
      ],
      kind: 'network',
      modelTitle: '沿 permutation 反覆追蹤同一 token',
      prompt: '每個 preset 增加一步，直到 path 閉合。',
      presets: [
        {
          label: '從 1 開始',
          nodes: nodes(['1', '2', '3', '4'], ['3'], '1'),
          actions: ['1→3'],
          formula: '(1 3 …)',
          detail: '尚未回到起點。',
          status: 'neutral',
        },
        {
          label: '繼續',
          nodes: nodes(['1', '2', '3', '4'], ['3', '2'], '1'),
          actions: ['1→3', '3→2'],
          formula: '(1 3 2 …)',
          detail: '下一個 token 是 2。',
          status: 'neutral',
        },
        {
          label: '閉合',
          nodes: nodes(['1', '2', '3', '4'], ['3', '2'], '1'),
          actions: ['1→3', '3→2', '2→1'],
          formula: '(1 3 2), 4 fixed',
          detail: '回到 1，cycle 完成。',
          status: 'good',
        },
      ],
      insight: 'Cycle 是 repeated permutation 形成的 closed orbit；notation 壓縮的是完整 mapping。',
      transfer: [
        '(1 2 3) 與 (2 3 1) 是否為同一 cycle？',
        true,
        '只是從同一圓環的不同起點開始寫。',
        '每個 token 的 next image 完全相同。',
      ],
      formal: [
        'Cycle notation',
        '(a₁…a_k) 把 a_i 送到 a_{i+1}，把 a_k 送回 a₁，其他 points fixed。',
      ],
      proof: [
        '旋轉 cycle notation 不改 function',
        '比較 (a₁a₂…a_k) 與 (a₂…a_ka₁)。',
        '每個 a_i 的 successor 相同。',
        '未列 points 都 fixed。',
        '兩 functions 對所有 inputs 相同。',
      ],
      boundary: '反轉書寫通常得到 inverse cycle，不是同一 permutation。',
    }),
    L({
      id: '20.2',
      title: 'Disjoint cycles 是互不干擾的 action modules',
      lede: '若兩 cycles 操作不同 token sets，執行哪個先都不影響另一個；任何 permutation 都能按 orbits 唯一拆成 disjoint cycles。',
      predict: [
        'Disjoint cycles 一定 commute 嗎？',
        true,
        '每個 token 最多只被其中一個 cycle 移動。',
        '兩種順序對所有 tokens 結果相同。',
      ],
      kind: 'timeline',
      modelTitle: '同時追蹤兩組互不相干的 tokens',
      prompt: '交換 cycles 的執行順序，觀察完整 output。',
      presets: [
        {
          label: '(12) 再 (345)',
          before: '1,2 | 3,4,5',
          actions: ['(345)', '(12)'],
          after: '2,1 | 4,5,3',
          formula: '(12)(345)',
          detail: '兩個 modules 各自更新。',
          status: 'good',
        },
        {
          label: '交換順序',
          before: '1,2 | 3,4,5',
          actions: ['(12)', '(345)'],
          after: '2,1 | 4,5,3',
          formula: '(345)(12)',
          detail: '終點完全相同。',
          status: 'good',
        },
        {
          label: '有重疊',
          before: '1,2,3',
          actions: ['(12)', '(23)'],
          after: 'order-dependent',
          formula: '(12)(23)≠(23)(12)',
          detail: '共享 token 2，干擾出現。',
          status: 'bad',
        },
      ],
      insight: 'Disjoint cycle decomposition 把一個 permutation 分成彼此獨立的 orbit modules。',
      transfer: [
        'Permutation 的 order 是否為 disjoint cycle lengths 的 lcm？',
        true,
        '所有 cycles 同時回到起點的最早時間是最小公倍數。',
        '每個 module 各自週期運作。',
      ],
      formal: [
        'Disjoint cycle decomposition',
        '每個 finite permutation 可寫為互不相交 cycles 的 product；忽略 1-cycles 後分解除順序外唯一。',
      ],
      proof: [
        '為何分解覆蓋所有 points',
        '從未處理 point 開始追蹤 orbit。',
        'Finite bijection 必定回到起點，形成 cycle。',
        '移除該 orbit，從下一個未處理 point 重複。',
        'Orbits disjoint 且覆蓋全部 points。',
      ],
      boundary: '一般 non-disjoint cycles 不可任意交換順序。',
    }),
    L({
      id: '20.3',
      title: '任何 permutation 都能拆成 swaps',
      lede: 'Transposition 是最小的局部交換。長 cycle 可用一串 swaps 建造，但分解方式不唯一。',
      predict: [
        '3-cycle (123) 能否用兩個 transpositions 完成？',
        true,
        '例如 (123)=(13)(12)，按右到左執行。',
        '兩次 swaps 足以讓三個 tokens 循環。',
      ],
      kind: 'timeline',
      modelTitle: '用交換逐步合成 cycle',
      prompt: '切換分解，確認總 mapping 而非只看字串。',
      presets: [
        {
          label: '(123)',
          before: '1,2,3',
          actions: ['(12)', '(13)'],
          after: '2,3,1',
          formula: '(123)=(13)(12)',
          detail: '兩個 swaps 合成三點 cycle。',
          status: 'good',
        },
        {
          label: '4-cycle',
          before: '1,2,3,4',
          actions: ['(12)', '(13)', '(14)'],
          after: '2,3,4,1',
          formula: '(1234)=(14)(13)(12)',
          detail: 'k-cycle 可用 k−1 swaps。',
          status: 'good',
        },
        {
          label: '加入冗餘',
          before: 'same',
          actions: ['(12)', '(12)', '原分解'],
          after: 'same effect',
          formula: 'τ²=e',
          detail: '插入兩個相同 swaps 不改總 action。',
          status: 'neutral',
        },
      ],
      insight:
        'Transpositions 是 permutation 的 generators；word 可變，但 effect 與某些 invariants 不變。',
      transfer: [
        '每個 element of Sₙ 都能由 transpositions 生成嗎？',
        true,
        '先拆 disjoint cycles，再把每個 cycle 拆成 swaps。',
        '兩層分解涵蓋所有 permutations。',
      ],
      formal: ['Transposition decomposition', '(a₁…a_k)=(a₁a_k)…(a₁a₃)(a₁a₂)。'],
      proof: [
        '構造 k-cycle',
        '最右 swap 先把 a₁ 送到 a₂。',
        '後續 swaps 不再移動 a₂。',
        '逐一得到 a_i→a_{i+1}。',
        '最後 a_k 被最左 swap 送回 a₁。',
      ],
      boundary: '分解不唯一；不能把某一串 swaps 當成 permutation 的唯一身分。',
    }),
    L({
      id: '20.4',
      title: 'Swap 數量可變，奇偶性卻不變',
      lede: '同一 permutation 可能有很多 transposition words，但它們的長度不會一奇一偶；parity 是 effect 的結構指紋。',
      predict: [
        '能否把同一 permutation 同時寫成 2 個 swaps 與 3 個 swaps？',
        false,
        '任何兩種分解長度 parity 相同。',
        '可以加兩個冗餘 swaps，但不能只改一個。',
      ],
      kind: 'diagnostic',
      modelTitle: '比較不同分解，保留 parity',
      prompt: 'word length 可變；只觀察 even／odd 標記。',
      presets: [
        {
          label: '3-cycle',
          checks: [
            check('分解 A', true, '2 swaps，even。'),
            check('分解 B', true, '4 swaps，even。'),
            check('parity', true, '一致。'),
          ],
          detail: '冗餘 pair 讓長度加 2。',
          status: 'good',
        },
        {
          label: 'single swap',
          checks: [
            check('分解 A', true, '1 swap，odd。'),
            check('其他分解', true, '3、5、… swaps。'),
            check('parity', true, '始終 odd。'),
          ],
          detail: '無法用 even swaps 表示。',
          status: 'good',
        },
        {
          label: '錯誤猜法',
          checks: [
            check('只看 cycle 數', false, 'fixed points 也需納入 n。'),
            check('正確 sign', true, 'k-cycle sign=(−1)^{k−1}。'),
          ],
          detail: 'Parity 要由合法 invariant 計算。',
          status: 'bad',
        },
      ],
      insight: 'Parity 把 Sₙ 壓成兩類 effects；它是 sign homomorphism，不是某次分解的偶然。',
      transfer: [
        '兩個 odd permutations 合成是否 even？',
        true,
        'sign product (−1)(−1)=+1。',
        'parity 像 mod 2 addition。',
      ],
      formal: ['Sign', 'sgn:Sₙ→{±1}，even permutations 映到 +1，odd 映到 −1；kernel 是 Aₙ。'],
      proof: [
        '為何 parity well-defined（視覺版）',
        '讓 permutation 作用在 Vandermonde product ∏_{i<j}(x_i−x_j)。',
        '每個 transposition 使 product 變號一次。',
        '同一 permutation 對 product 的最終 sign 唯一。',
        '因此任何分解的 swap parity 必相同。',
      ],
      boundary: 'Parity 只保留一 bit；不同 even permutations 仍可能結構完全不同。',
    }),
  ],

  ch21: [
    L({
      id: '21.1',
      title: '讓群在自己身上做 left translation',
      lede: '抽象 element g 可以變成具體 permutation L_g:x↦gx。Group contract 保證這個 state rearrangement 可逆。',
      predict: [
        'Left multiplication L_g 可能把兩個不同 x,y 送到同一點嗎？',
        false,
        'gx=gy 可左 cancel 得 x=y。',
        '所以 L_g 是 injective，inverse 是 L_{g⁻¹}。',
      ],
      kind: 'mapping',
      modelTitle: '把 abstract action 變成 state permutation',
      prompt: '選 g，查看它如何一致搬動 G 的每個 element。',
      presets: [
        {
          label: 'Z₄ 的 +1',
          mapping: [
            { from: '0', to: '1' },
            { from: '1', to: '2' },
            { from: '2', to: '3' },
            { from: '3', to: '0' },
          ],
          formula: 'L₁=(0 1 2 3)',
          detail: 'Abstract addition element 1 成為四點 cycle。',
          status: 'good',
        },
        {
          label: 'Z₄ 的 +2',
          mapping: [
            { from: '0', to: '2' },
            { from: '1', to: '3' },
            { from: '2', to: '0' },
            { from: '3', to: '1' },
          ],
          formula: 'L₂=(0 2)(1 3)',
          detail: '另一 element 成為另一 permutation。',
          status: 'good',
        },
      ],
      insight: '群元素可藉由「它如何搬動所有 group states」具體化成 permutation。',
      transfer: [
        'L_g 的 inverse 是否為 L_{g⁻¹}？',
        true,
        'g⁻¹(gx)=x。',
        '兩個 translations 完整撤銷。',
      ],
      formal: ['Left regular action', 'L_g:G→G, L_g(x)=gx 是 G underlying set 的 permutation。'],
      proof: [
        '驗證 bijection',
        '候選 inverse 是 L_{g⁻¹}。',
        'L_{g⁻¹}(L_g(x))=g⁻¹gx=x。',
        'L_g(L_{g⁻¹}(x))=gg⁻¹x=x。',
        '所以 L_g 可逆。',
      ],
      boundary: '這裡 G 同時扮演 actions 的集合與被作用的 state set；兩個角色要分清。',
    }),
    L({
      id: '21.2',
      title: 'Composition table 原封不動地進入 permutations',
      lede: 'Map ρ:g↦L_g 不只逐點配對；L_g∘L_h=L_{gh}，因此 abstract multiplication 被 permutation composition 完整保留。',
      predict: [
        'ρ:G→Sym(G) 是否可能把不同 g,h 送到同一 permutation？',
        false,
        '只看 identity state：L_g(e)=g、L_h(e)=h。',
        '若 permutations 相同，g=h。',
      ],
      kind: 'timeline',
      modelTitle: '比較先 multiply 與先 translate',
      prompt: '固定任意 state x，走兩條 composition path。',
      presets: [
        {
          label: '兩次 translation',
          before: 'x',
          actions: ['L_h: x→hx', 'L_g: hx→ghx'],
          after: 'ghx',
          formula: 'L_g∘L_h',
          detail: '連續搬動的總效果。',
          status: 'good',
        },
        {
          label: '一次 product',
          before: 'x',
          actions: ['先算 gh', 'L_{gh}:x→ghx'],
          after: 'ghx',
          formula: 'L_{gh}',
          detail: '兩 permutations 對每個 x 相同。',
          status: 'good',
        },
      ],
      insight:
        'Regular representation 把 group operation 變成 function composition，且沒有資訊損失。',
      transfer: [
        '這是否表示任何 finite group 都 isomorphic to Sₙ 本身？',
        false,
        '它只 isomorphic to Sₙ 的某個 subgroup。',
        'image ρ(G) 通常只是全部 permutations 的一小部分。',
      ],
      formal: ['Cayley embedding', 'ρ:G→S_G, ρ(g)=L_g 是 injective homomorphism。'],
      proof: [
        'Homomorphism 與 injectivity',
        'L_gL_h(x)=g(hx)=(gh)x=L_{gh}(x)。',
        '故 ρ(gh)=ρ(g)ρ(h)。',
        '若 L_g=L_h，套在 e 得 g=h。',
        '所以 ρ injective。',
      ],
      boundary: 'Cayley theorem 保證存在 permutation model，不保證它是最小或最有洞察力的 model。',
    }),
    L({
      id: '21.3',
      title: '每個抽象群都有一個完全具體的 action model',
      lede: 'Cayley theorem 消除「抽象群是否真的代表 transformations」的疑慮；任何群都能忠實地看成某個 state set 上的 permutations。',
      predict: [
        '群的 elements 若原本不是幾何動作，是否仍能成為 transformations？',
        true,
        '讓它們 left-multiply G 自身即可。',
        'action interpretation 對所有 groups 都存在。',
      ],
      kind: 'diagnostic',
      modelTitle: '從 abstract table 到 permutation machine',
      prompt: '沿三個驗收點確認 model 沒有改變結構。',
      presets: [
        {
          label: 'Cayley model',
          checks: [
            check('每個 g 產生 permutation', true, 'L_g 可逆。'),
            check('保留 products', true, 'L_gL_h=L_{gh}。'),
            check('不合併 elements', true, '在 e 上可辨認 g。'),
          ],
          detail: 'G≅ρ(G)≤Sym(G)。',
          status: 'good',
        },
        {
          label: '模型代價',
          checks: [
            check('一定存在', true, '普遍保證。'),
            check('一定最小', false, 'state set 大小可縮。'),
            check('一定直觀', false, '其他 actions 可能更有意義。'),
          ],
          detail: 'Existence 與 usefulness 是不同問題。',
          status: 'neutral',
        },
      ],
      insight: 'Group 可以被理解為 reversible actions，這不是比喻：Cayley theorem 給出精確實現。',
      transfer: [
        '一個 order n 的 finite group 是否必嵌入 Sₙ？',
        true,
        '它作用在自身 n 個 states 上。',
        'left regular action 直接構造 embedding。',
      ],
      formal: [
        'Cayley theorem',
        'Every group G is isomorphic to a subgroup of Sym(G)。Finite |G|=n 時，G embeds in Sₙ。',
      ],
      proof: [
        'Theorem 已由前兩步完成',
        '構造 ρ(g)=L_g。',
        '前一步證明每個 L_g 是 permutation。',
        '再證明 ρ homomorphism 且 injective。',
        '因此 G≅imρ≤Sym(G)。',
      ],
      boundary:
        '「Every group is a permutation group」不表示原本的語意應被丟棄；representation 是觀察鏡頭。',
    }),
  ],

  ch22: [
    L({
      id: '22.1',
      title: 'Group action 把抽象 elements 接到另一個世界',
      lede: '不必讓 G 只作用在自己身上。Action 指定每個 g 如何變換 states X，並要求 group multiplication 與 transformation composition 同步。',
      predict: [
        '只要每個 g 都指定一個 X→X function，就自動是 group action 嗎？',
        false,
        '還需 identity 不動，且 gh 的效果等於先 h 再 g。',
        '對；actions 不能各自任意。',
      ],
      kind: 'mapping',
      modelTitle: '同一 group，接上具體 state space',
      prompt: '切換 action 對象，觀察 group elements 的角色如何具體化。',
      presets: [
        {
          label: 'rotations on vertices',
          mapping: [
            { from: 'r', to: 'A→B→C→A' },
            { from: 'r²', to: 'A→C→B→A' },
            { from: 'e', to: 'all fixed' },
          ],
          formula: 'C₃ ↷ {A,B,C}',
          detail: 'Abstract cyclic group 操作三角形頂點。',
          status: 'good',
        },
        {
          label: 'Z on integers',
          mapping: [{ from: 'n', to: 'x↦x+n' }],
          formula: 'Z ↷ Z',
          detail: '每個 integer 是 translation action。',
          status: 'good',
        },
        {
          label: '壞指定',
          mapping: [{ from: 'e', to: 'swap A,B', accent: true }],
          formula: 'e·x≠x',
          detail: 'identity 沒有 acts trivially，action law 失敗。',
          status: 'bad',
        },
      ],
      insight:
        'Group action 是 homomorphism G→Sym(X)：把 abstract composition 翻成 X 上的 reversible transformations。',
      transfer: [
        'Matrix group 作用在 vectors 上是否是 group action？',
        true,
        'I v=v 且 (AB)v=A(Bv)。',
        'matrix multiplication 與 transformation composition 對齊。',
      ],
      formal: [
        'Group action',
        'Action G↷X 滿足 e·x=x 與 (gh)·x=g·(h·x)。等價於 homomorphism G→Sym(X)。',
      ],
      proof: [
        '兩個 action axioms 的角色',
        'Identity axiom 確保 e 對應 identity permutation。',
        'Compatibility 確保 product 對應 composition。',
        '每個 g 的 inverse g⁻¹ 給出 inverse transformation。',
        '所以每個 action map 自動 bijective。',
      ],
      boundary:
        'Action 不要求 X 本身是 group；X 可以是 vertices、colorings、subgroups 或 solutions。',
    }),
    L({
      id: '22.2',
      title: '同一群換作用對象，會揭露不同資訊',
      lede: 'Group 本身不變，但選擇 vertices、edges、colorings 或 subgroups 作為 states，能看見不同 orbit 與 symmetry pattern。',
      predict: [
        '同一 g 在不同 actions 中必須有相同 fixed points 數嗎？',
        false,
        'fixed points 取決於 state space X。',
        '同一 rotation 可固定中心，卻不固定任何頂點。',
      ],
      kind: 'diagnostic',
      modelTitle: '固定 D₄，切換它作用的世界',
      prompt: '觀察不變的是 group law，改變的是 states 與可見結構。',
      presets: [
        {
          label: '作用在 4 vertices',
          checks: [
            check('states', true, '四個角。'),
            check('90° fixed', false, '無固定 vertex。'),
            check('orbit', true, '四角互相可達。'),
          ],
          detail: '看見 vertex transitivity。',
          status: 'good',
        },
        {
          label: '作用在 2 diagonals',
          checks: [
            check('states', true, '兩條對角線。'),
            check('90° fixed', false, '兩線交換。'),
            check('180° fixed', true, '各自回到自身。'),
          ],
          detail: '同一 group 顯露另一個 quotient-like view。',
          status: 'good',
        },
        {
          label: '作用在 center',
          checks: [
            check('states', true, '只有中心。'),
            check('all fixed', true, '每個 symmetry 固定中心。'),
            check('information', false, 'action 看不見任何 group 差異。'),
          ],
          detail: '合法但完全不 faithful。',
          status: 'neutral',
        },
      ],
      insight: 'Action 是觀察選擇；不同 X 讓同一 group 的不同 features 變得可見或不可見。',
      transfer: [
        '研究 necklace colorings 時，讓 rotation group 作用在所有 colorings 上是否合理？',
        true,
        'orbits 正好對應旋轉視為相同的 necklaces。',
        '選 X 直接編碼要分類的 objects。',
      ],
      formal: [
        'Action representation',
        '每個 action 對應 ρ_X:G→Sym(X)；其 image 描述可見 transformations。',
      ],
      proof: [
        'Action 如何形成 observation map',
        '對每個 g 定義 permutation ρ_X(g):x↦g·x。',
        'Compatibility 給 ρ_X(gh)=ρ_X(g)ρ_X(h)。',
        '所以 ρ_X 是 homomorphism。',
        '可用 kernel/image 分析 action 看見多少。',
      ],
      boundary: '換 action space 不是改變 group；但 action-dependent quantities 不可跨 X 混用。',
    }),
    L({
      id: '22.3',
      title: 'Action kernel 記錄整個世界都看不見的 elements',
      lede: '若 g 固定 X 的每個 state，它在這個 action 中與 identity 完全相同。所有這類 elements 形成 action homomorphism 的 kernel。',
      predict: [
        '某 g 固定一個 state，是否代表 g 在 action kernel 中？',
        false,
        'kernel 要求固定所有 states。',
        '固定一點只表示 g 在那一點的 stabilizer。',
      ],
      kind: 'mapping',
      modelTitle: '分開「固定某點」與「固定全世界」',
      prompt: '切換 element，掃描它對全部 X 的 effects。',
      presets: [
        {
          label: 'identity',
          mapping: [
            { from: 'x₁', to: 'x₁' },
            { from: 'x₂', to: 'x₂' },
            { from: 'x₃', to: 'x₃' },
          ],
          formula: 'e∈kerρ',
          detail: '所有 states fixed。',
          status: 'good',
        },
        {
          label: '局部固定',
          mapping: [
            { from: 'x₁', to: 'x₁' },
            { from: 'x₂', to: 'x₃', accent: true },
            { from: 'x₃', to: 'x₂', accent: true },
          ],
          formula: 'g∉kerρ',
          detail: '即使固定 x₁，仍被其他 states 看見。',
          status: 'bad',
        },
        {
          label: '全域不可見',
          mapping: [
            { from: 'x₁', to: 'x₁' },
            { from: 'x₂', to: 'x₂' },
            { from: 'x₃', to: 'x₃' },
          ],
          formula: 'g≠e but ρ(g)=id_X',
          detail: 'Non-faithful action 可能壓掉 nontrivial elements。',
          status: 'neutral',
        },
      ],
      insight:
        'Action kernel 是對所有 states 都不可見的 group differences；faithful action 的 kernel 只有 e。',
      transfer: [
        'Cayley left action 是否 faithful？',
        true,
        'L_g(e)=g，因此 nonidentity g 不可能固定全部 G。',
        '它的 kernel trivial。',
      ],
      formal: [
        'Faithful action',
        'Action G↷X faithful iff homomorphism ρ:G→Sym(X) injective iff kerρ={e}。',
      ],
      proof: [
        'Action kernel normal',
        '它是 homomorphism ρ 的 kernel。',
        '所有 homomorphism kernels 都 normal。',
        '因此 globally invisible actions 在 conjugation 下仍 globally invisible。',
        '不需重新逐點證明。',
      ],
      boundary: 'Stabilizer G_x 通常不 normal；action kernel 是所有 stabilizers 的 intersection。',
    }),
    L({
      id: '22.4',
      title: 'Action detector 檢查的是相容性，不是動畫感',
      lede: '看起來像「移動物件」的 rule 仍可能不 obey group multiplication；反之，抽象地 permute polynomials 或 subgroups 也能是合法 action。',
      predict: [
        '定義 Z 作用在 R：n·x=x+n²，是否為 action？',
        false,
        '(m+n)² 通常不等於 m²+n²，compatibility 失敗。',
        '它有 motions，卻不保留 addition。',
      ],
      kind: 'diagnostic',
      modelTitle: '逐關驗證候選 action',
      prompt: '檢查 identity、compatibility、state closure。',
      presets: [
        {
          label: 'n·x=x+n',
          checks: [
            check('identity', true, '0·x=x。'),
            check('compatibility', true, '(m+n)·x=m·(n·x)。'),
            check('留在 X', true, 'real 加 integer 仍 real。'),
          ],
          detail: '合法 translation action。',
          status: 'good',
        },
        {
          label: 'n·x=x+n²',
          checks: [
            check('identity', true, '0²=0。'),
            check('compatibility', false, 'cross term 2mn 出現。'),
            check('結論', false, '不是 action。'),
          ],
          detail: '一條 axiom 失敗即停止。',
          status: 'bad',
        },
        {
          label: 'conjugation on subgroups',
          checks: [
            check('identity', true, 'eHe⁻¹=H。'),
            check('compatibility', true, 'g(hHh⁻¹)g⁻¹=(gh)H(gh)⁻¹。'),
            check('states', true, 'conjugate 仍是 subgroup。'),
          ],
          detail: '沒有幾何動畫也是真正 action。',
          status: 'good',
        },
      ],
      insight: 'Group action 的本質是 operation-preserving assignment，不是物理移動的外觀。',
      transfer: [
        'Rule g·x=gxg⁻¹ 是否定義 G 在自身上的 action？',
        true,
        'e 固定且 (gh)x(gh)⁻¹=g(hxh⁻¹)g⁻¹。',
        '這就是 conjugation action。',
      ],
      formal: ['Action verification', '證明 e·x=x、(gh)·x=g·(h·x)，並確認 outputs 留在 X。'],
      proof: [
        '推翻 action 的方法',
        '找出 identity axiom 的 failure；或',
        '找 g,h,x 使 (gh)·x≠g·(h·x)，或。',
        '展示 output 不在 X。',
        '任一 witness 已足夠。',
      ],
      boundary:
        '若 G 使用 multiplicative notation、X 不是 group，g·x 的 dot 只是 action，不一定是 X 內 operation。',
    }),
  ],

  ch23: [
    L({
      id: '23.1',
      title: 'Orbit 是一個 state 的全部可達位置',
      lede: '固定 x，允許所有 group actions。Orbit 不記錄怎麼走，只收集可能抵達哪些 states。',
      predict: [
        '若 y 在 orbit of x，x 是否也在 orbit of y？',
        true,
        '若 y=g·x，則 x=g⁻¹·y。',
        'reversibility 讓 reachability 對稱。',
      ],
      kind: 'network',
      modelTitle: '從一個 state 展開所有 group moves',
      prompt: '切換起點，觀察 reachable component。',
      presets: [
        {
          label: 'square vertex A',
          nodes: nodes(['A', 'B', 'C', 'D', 'center'], ['B', 'C', 'D'], 'A'),
          actions: ['rotations', 'reflections'],
          formula: 'Orb(A)={A,B,C,D}',
          detail: '四個 vertices 互相可達，center 不在其中。',
          status: 'good',
        },
        {
          label: 'center',
          nodes: nodes(['A', 'B', 'C', 'D', 'center'], [], 'center'),
          actions: ['all D₄'],
          formula: 'Orb(center)={center}',
          detail: '所有 symmetries 都固定中心。',
          status: 'neutral',
        },
      ],
      insight:
        'Orbit 是 action graph 的 connected component：它回答「這個 object 能變成哪些 objects」。',
      transfer: [
        '同一 orbit 中的 two states 是否必有相同 local symmetry size？',
        true,
        '它們的 stabilizers conjugate，因而等大。',
        '換一個可達座標不改 local symmetry 的數量。',
      ],
      formal: ['Orbit', 'Orb_G(x)=G·x={g·x:g∈G}。'],
      proof: [
        'Orbits 為何相同或分離',
        '若 z∈Orb(x)∩Orb(y)，則 z=g·x=h·y。',
        '所以 y=h⁻¹g·x，y 可由 x 抵達。',
        '因此從 y 可達的 states 與從 x 可達的完全相同。',
        '故兩 orbits 相等；否則 disjoint。',
      ],
      boundary: 'Orbit 依賴 action；同一 group、同一 x 放在不同 state space 不能直接比較。',
    }),
    L({
      id: '23.2',
      title: 'Stabilizer 是對某個 state 看起來沒做事的 actions',
      lede: '固定 x，反過來掃描 group elements。Stabilizer 收集所有把 x 留在原位的 actions；它是 point-specific invisibility。',
      predict: [
        '固定正方形某個 vertex 的 symmetries 只有 identity 嗎？',
        false,
        '沿通過該 vertex 的 diagonal reflection 也固定它。',
        '所以 stabilizer 有兩個 elements。',
      ],
      kind: 'diagnostic',
      modelTitle: '固定 state，掃描每個 action',
      prompt: '✓/× 同時提供非色彩線索；pass 表示固定 x。',
      presets: [
        {
          label: 'vertex A in D₄',
          checks: [
            check('identity', true, 'A→A。'),
            check('diagonal reflection', true, 'A→A。'),
            check('90° rotation', false, 'A→B。'),
            check('180° rotation', false, 'A→C。'),
          ],
          formula: '|Stab(A)|=2',
          detail: 'Local symmetry 有兩個 actions。',
          status: 'good',
        },
        {
          label: 'center in D₄',
          checks: [
            check('all rotations', true, 'center fixed。'),
            check('all reflections', true, 'center fixed。'),
            check('total', true, '8 actions。'),
          ],
          formula: 'Stab(center)=D₄',
          detail: '單點 orbit 對應最大 stabilizer。',
          status: 'good',
        },
      ],
      insight:
        'Stabilizer 回答「哪些 actions 對這個 observer 看不見」；它固定 state，不固定整個 world。',
      transfer: [
        'Stab(x) 一定是 subgroup 嗎？',
        true,
        '固定 x 的 actions 合成仍固定，inverse 也固定。',
        '它能自行運作。',
      ],
      formal: ['Stabilizer', 'G_x=Stab_G(x)={g∈G:g·x=x}。'],
      proof: [
        'Stabilizer subgroup test',
        'e 固定 x，所以非空。',
        '若 g,h 固定 x，則 h⁻¹也固定 x。',
        '(gh⁻¹)·x=g·(h⁻¹·x)=g·x=x。',
        '故 gh⁻¹∈G_x。',
      ],
      boundary: '固定 x 不表示 action element 是 identity；它可能移動其他 states。',
    }),
    L({
      id: '23.3',
      title: 'Orbits partition states，stabilizers live inside actions',
      lede: 'Orbit 與 stabilizer 看同一 action stage 的兩個方向：固定 action set 掃 states，或固定 state 掃 actions。它們不在同一個集合裡。',
      predict: [
        'Orbit of x 是 G 的 subset 嗎？',
        false,
        'Orbit 位於 X；stabilizer 才位於 G。',
        '對；除非 X 恰好也是 G，也不能混側。',
      ],
      kind: 'symbols',
      modelTitle: '把兩個掃描方向放回正確側',
      prompt: '切換 object，觀察輸入固定的是 state 還是 action。',
      presets: [
        {
          label: 'orbit scan',
          mapping: [
            { from: '固定 x∈X', to: '改變 g∈G' },
            { from: 'outputs', to: 'Orb(x)⊆X' },
          ],
          formula: 'g ↦ g·x',
          detail: '掃 actions，收集 states。',
          status: 'good',
        },
        {
          label: 'stabilizer scan',
          mapping: [
            { from: '固定 x∈X', to: '測試 g·x=x' },
            { from: 'passing actions', to: 'Stab(x)≤G' },
          ],
          formula: 'actions fixing x',
          detail: '掃 actions，篩出 group elements。',
          status: 'good',
        },
      ],
      insight:
        'Orbit 位於 state world X；stabilizer 位於 action world G。兩者由同一 evaluation map g↦g·x 接起來。',
      transfer: [
        'Action transitive 是否表示只有一個 orbit？',
        true,
        '任兩 states 都可由某 action 連接。',
        '整個 X 是單一 reachable component。',
      ],
      formal: ['Transitive action', 'G↷X transitive iff Orb(x)=X for some/every x。'],
      proof: [
        '為何 orbits partition X',
        '每個 x∈Orb(x)，所以覆蓋 X。',
        '前面已證明 two orbits 相交就相等。',
        '因此 distinct orbits disjoint。',
        '覆蓋與 disjoint 合成 partition。',
      ],
      boundary: 'Stabilizers of different points 不必相等，但同 orbit 中會 conjugate。',
    }),
    L({
      id: '23.4',
      title: '沿 orbit 移動 observer，stabilizer 只換座標',
      lede: '若 y=g·x，固定 y 的 actions 正是 gG_xg⁻¹。Local symmetry pattern 沒變，只是由 g 搬到新座標。',
      predict: [
        '同 orbit 的 points 是否有相同 stabilizer order？',
        true,
        'conjugation 是 bijection G_x→G_y。',
        'stabilizers 可能不是同一 subset，但大小相同。',
      ],
      kind: 'timeline',
      modelTitle: '把固定 x 的 action 搬到 y',
      prompt: '追蹤 observer 換座標、執行 local symmetry、再換回。',
      presets: [
        {
          label: 'x-view',
          before: 'x',
          actions: ['h∈G_x'],
          after: 'x',
          formula: 'h·x=x',
          detail: 'h 在原 observer 看來不動。',
          status: 'neutral',
        },
        {
          label: 'y=g·x view',
          before: 'y',
          actions: ['g⁻¹ 回 x', 'h 固定 x', 'g 回 y'],
          after: 'y',
          formula: 'ghg⁻¹∈G_y',
          detail: '同一 local symmetry 被搬到 y。',
          status: 'good',
        },
      ],
      insight:
        '同 orbit points 的 stabilizers 是 conjugate coordinate versions；local symmetry size 因而一致。',
      transfer: [
        '若 action transitive，所有 point stabilizers 是否同 order？',
        true,
        '所有 points 在同 orbit。',
        'conjugate subgroups 有相同大小。',
      ],
      formal: ['Conjugate stabilizers', '若 y=g·x，則 G_y=gG_xg⁻¹。'],
      proof: [
        '證明 subgroup equality',
        '取 h∈G_x。',
        '(ghg⁻¹)·y=ghg⁻¹·(g·x)=g·(h·x)=g·x=y。',
        '所以 gG_xg⁻¹⊆G_y。',
        '用 g⁻¹ 反向推得 equality。',
      ],
      boundary: '不同 orbits 的 stabilizers 可能剛好同大小，但不是由此定理保證。',
    }),
  ],
};
