import { Component, computed, signal } from '@angular/core';
import { D3_ELEMENTS, label } from '../algebra-v3-ch16/d3-model';
import { ACTION_WORLDS, type WorldId, actionSignature, actorSetLabel, isInvisible, kernel, signatureGroups, worldById } from './action-model';

@Component({selector:'app-algebra-v3-kernel-scanner',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch22-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 22.3</p><h2>Action kernel 是這個觀察 world 完全看不見的 actors</h2><p class="lede">不是只看某一個 state，而是把 world 裡每個 state 都掃過。若 g 對全部 states 都像 identity，它就落進這個 action 的資訊盲區。</p></header>
<section class="prediction"><p class="kicker">先預測</p><h3>一個合法 group action 可以把多個不同 g 顯示成同一張 permutation 嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(true)">可以，action 不一定 faithful</button><button type="button" (click)="prediction.set(false)">不可以，合法就必須一對一</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="!prediction()">{{prediction()?'對。合法只要求保存 multiplication；injective 是額外的 faithful 條件。':'Orientation action 就是反例：e、r、r² 都顯示成 identity permutation。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Global invisibility scanner</p><h3>換 world，逐張掃描六個 action cards</h3></div><p>實線框表示至少動了一個 state；虛線框表示所有 states 都原地不動。</p></div><div class="world-picker">@for(item of worlds;track item.id){<button type="button" [attr.aria-pressed]="world()===item.id" (click)="world.set(item.id)">{{item.title}}</button>}</div>
<div class="stage kernel-stage"><section class="actor-scan" [attr.aria-label]="scanLabel()">@for(actor of elements;track actor){<article [class.invisible]="invisible(actor)"><header><strong>{{name(actor)}}</strong><small>{{invisible(actor)?'INVISIBLE':'VISIBLE'}}</small></header><p>{{signature(actor)}}</p><span>{{invisible(actor)?'moves 0 states':'moves ≥ 1 state'}}</span></article>}</section><section class="kernel-console" aria-live="polite"><p class="kicker">INFORMATION DASHBOARD</p><div class="kernel-set"><span>ACTION KERNEL</span><b>{{kernelLabel()}}</b><small>acts as identity on every state</small></div><div class="faithful-meter" [class.pass]="faithful()"><span>{{faithful()?'FAITHFUL':'NOT FAITHFUL'}}</span><b>{{groups().length}} / 6</b><small>DISTINCT ACTION CARDS</small></div><div class="collision-list"><span>CARDS THAT LOOK THE SAME</span>@for(group of groups();track group[0]){<p>{{groupLabel(group)}}</p>}</div></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>kernel = invisible actors</span><i>trivial?</i><span>faithful action</span></div><p><strong>Faithful 不是「action 很有用」，而是「它沒有把兩個 group elements 認成同一個 move」。</strong>kernel 只有 e 時，observer 才保留整個群的身份資訊。</p></aside>
<section class="transfer"><p class="kicker">遷移</p><h3>Center world 只有一個 state；它的 action kernel 會有多大？</h3><div class="choice-row"><button type="button" (click)="transfer.set(6)">全部 6 個 elements</button><button type="button" (click)="transfer.set(1)">只有 identity</button></div>@if(transfer()){<p class="feedback" [class.warning]="transfer()!==6">{{transfer()===6?'對。唯一 state 無處可去，所以每個 actor 都顯示成 identity。':'一點 world 看不見任何 motion，因此不是只有 e，而是整個 D₃ 都在 kernel。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>Kernel 與 faithful 的正式版本</summary><div>對 action homomorphism ρ:G→Sym(X)，kerρ 由所有「對每個 x∈X 都滿足 g·x=x」的 g 組成。ρ injective 當且僅當 kerρ 只有 e；此時 action 稱為 faithful。因為它是 homomorphism kernel，所以 kerρ 是 G 的 normal subgroup。</div></details></section></article>`})
export class AlgebraV3KernelScannerComponent{readonly elements=D3_ELEMENTS;readonly worlds=ACTION_WORLDS;readonly world=signal<WorldId>('orientation');readonly prediction=signal<boolean|null>(null);readonly transfer=signal<number|null>(null);readonly groups=computed(()=>signatureGroups(this.world()));readonly kernelElements=computed(()=>kernel(this.world()));readonly faithful=computed(()=>this.kernelElements().length===1);name=label;signature(actor:(typeof D3_ELEMENTS)[number]):string{return actionSignature(this.world(),actor);}invisible(actor:(typeof D3_ELEMENTS)[number]):boolean{return isInvisible(this.world(),actor);}kernelLabel():string{return actorSetLabel(this.kernelElements());}groupLabel(group:(typeof D3_ELEMENTS)[number][]):string{return actorSetLabel(group);}scanLabel():string{return `${worldById(this.world()).title}: kernel ${this.kernelLabel()}`;}}
