import { Component, computed, signal } from '@angular/core';
import { D3_ELEMENTS, type D3Element, label } from '../algebra-v3-ch16/d3-model';
import { ACTION_WORLDS, act, actionSignature, signatureGroups } from './action-model';

@Component({selector:'app-algebra-v3-multi-world-lens',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch22-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 22.2</p><h2>群沒有改變；換一個觀察 world，能看見的結構就改變</h2><p class="lede">同一個 D₃ actor 同時送進三個 detectors。vertices 記得完整位置，orientation 只記得有沒有翻面，center 則什麼 motion 都看不見。</p></header>
<section class="prediction"><p class="kicker">先預測</p><h3>r 在 orientation world 看起來像 identity，能推出 r=e 嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不能，可能只是 detector 看不見</button><button type="button" (click)="prediction.set(true)">能，沒變化就是 identity</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'你只知道 r 對這個 world 沒效果，不知道 r 在群裡等於 e。':'對。不可見是 observer 的限制，不一定是 actor 不存在。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Multi-world lens</p><h3>切換同一個 actor，三個 panels 同步更新</h3></div><p>每個 panel 都是合法 action；差別只在 state set X 保存了多少資訊。</p></div><div class="actor-strip" aria-label="選擇 D3 actor">@for(element of elements;track element){<button type="button" [attr.aria-pressed]="actor()===element" (click)="actor.set(element)">g = {{name(element)}}</button>}</div>
<div class="stage worlds-stage">@for(panel of panels();track panel.id){<article class="world-panel" [attr.data-world]="panel.id"><header><p>{{panel.title}}</p><strong>{{panel.question}}</strong></header><div class="world-action">@for(move of panel.moves;track move.from){<span><i>{{move.fromLabel}}</i><b>→</b><i>{{move.toLabel}}</i></span>}</div><div class="world-readout"><span>ACTION SIGNATURE</span><b>{{panel.signature}}</b><small>{{panel.distinctCount}} DISTINCT {{panel.distinctCount===1?'CARD':'CARDS'}} VISIBLE</small></div></article>}</div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>same G</span><i>choose X</i><span>different visible structure</span></div><p><strong>選 action world，就是選擇要向群問什麼問題。</strong>細緻 world 能區分更多 actors；粗糙 world 會把不同 actors 顯示成同一個 move。</p></aside>
<section class="transfer"><p class="kicker">遷移</p><h3>若只想偵測「有沒有 reflection」，哪個 world 已經足夠？</h3><div class="choice-row"><button type="button" (click)="transfer.set('orientation')">Orientation world</button><button type="button" (click)="transfer.set('vertices')">一定要完整 vertices</button></div>@if(transfer()){<p class="feedback" [class.warning]="transfer()==='vertices'">{{transfer()==='orientation'?'對。rotations 保持方向，reflections 翻轉方向；兩-state detector 正好回答這個問題。':'vertices 當然能看見，但保存了超過問題需要的資訊；orientation 已足夠。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>三個 action homomorphisms</summary><div>這三個 panels 分別對應 D₃→S₃、D₃→S₂ 與 D₃→S₁。domain group 相同，但 codomain 與 image 大小分別讓 6、2、1 種 actions 可被區分。</div></details></section></article>`})
export class AlgebraV3MultiWorldLensComponent{readonly elements=D3_ELEMENTS;readonly actor=signal<D3Element>(1);readonly prediction=signal<boolean|null>(null);readonly transfer=signal<'orientation'|'vertices'|null>(null);name=label;readonly panels=computed(()=>ACTION_WORLDS.map(world=>({id:world.id,title:world.title,question:world.question,signature:actionSignature(world.id,this.actor()),distinctCount:signatureGroups(world.id).length,moves:world.states.map(state=>({from:state,fromLabel:world.stateLabels[state],toLabel:world.stateLabels[act(world.id,this.actor(),state)]}))})));}
