import { Component, computed, signal } from '@angular/core';
import { label } from '../algebra-v3-ch16/d3-model';
import { ACTION_CANDIDATES, type ActionCandidate, firstCompositionFailure, firstIdentityFailure, stateLabel } from './action-model';

@Component({selector:'app-algebra-v3-action-detector',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch22-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 22.4</p><h2>Action detector 不問「看起來合理嗎」，它找一個讓規則自相矛盾的 witness</h2><p class="lede">每張 move card 都可逆仍可能接錯。依序檢查 identity 與 composition；只要一組 x 或 g,h,x 走出兩個答案，整份 recipe 就不是 action。</p></header>
<section class="prediction"><p class="kicker">先預測</p><h3>{{candidate().title}} 是一個 valid group action 嗎？</h3><p>{{candidate().description}}</p><div class="choice-row"><button type="button" (click)="guess.set(true)">我預測 valid</button><button type="button" (click)="guess.set(false)">我預測 broken</button></div>@if(guess()!==null){<p class="feedback">預測已鎖定。現在讓 detector 用具體 inputs 檢查，不靠外觀猜。</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Two-gate action detector</p><h3>換一份 recipe，再一步一步開 gate</h3></div><p>第二個 recipe 刻意 non-faithful，但它仍是 valid action；別把兩個問題混在一起。</p></div><div class="candidate-picker">@for(item of candidates;track item.id){<button type="button" [attr.aria-pressed]="candidate().id===item.id" (click)="select(item)"><strong>{{item.title}}</strong><small>{{item.worldLabel}}</small></button>}</div>
<div class="stage detector-stage"><section class="detector-gates"><article [class.pass]="stage()>=1&&!identityFailure()" [class.fail]="stage()>=1&&identityFailure()"><span>GATE 1</span><strong>Identity does nothing</strong><b>{{stage()<1?'WAITING':identityFailure()?'FAIL':'PASS'}}</b></article><article [class.pass]="stage()>=2&&!compositionFailure()" [class.fail]="stage()>=2&&compositionFailure()"><span>GATE 2</span><strong>Combined = sequential</strong><b>{{stage()<2?'WAITING':compositionFailure()?'FAIL':'PASS'}}</b></article><div class="detector-flow"><span>e·x = x</span><i>then</i><span>(gh)·x = g·(h·x)</span></div></section>
<section class="detector-console" aria-live="polite"><p class="kicker">STRUCTURE CHECK</p><strong>{{stageLabel()}}</strong>@if(witness();as item){<div class="failure-witness"><span>COUNTEREXAMPLE WITNESS</span><b>{{item}}</b></div>}@if(stage()>=2&&!identityFailure()&&!compositionFailure()){<div class="valid-verdict"><span>ALL FINITE CASES PASSED</span><b>VALID ACTION</b><small>{{candidate().faithful?'FAITHFUL TOO':'VALID BUT NON-FAITHFUL'}}</small></div>}<button type="button" class="primary" [disabled]="stage()>=2" (click)="advance()">執行下一道 gate</button><button type="button" (click)="stage.set(0)">重設 detector</button></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>identity law</span><i>+</i><span>composition law</span><i>⇒</i><span>action</span></div><p><strong>Valid 與 faithful 是兩個不同開關。</strong>Valid 問 recipe 是否尊重群運算；faithful 才問 observer 有沒有分辨所有 actors。</p></aside>
<section class="transfer"><p class="kicker">遷移</p><h3>Orientation-only recipe 通過兩道 gates，但只看見兩種 actions；它算 group action 嗎？</h3><div class="choice-row"><button type="button" (click)="transfer.set(true)">算，只是 non-faithful</button><button type="button" (click)="transfer.set(false)">不算，action 必須 faithful</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="!transfer()">{{transfer()?'對。action axioms 沒要求 injective；faithful 是額外性質。':'合法 action 可以壓掉資訊。是否 faithful 不在兩條 action axioms 裡。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>Detector 為什麼只需要兩條 laws？</summary><div>若 e·x=x 且 (gh)·x=g·(h·x)，每個 g 的 state map 自動可逆：g⁻¹ 的 map 是它的 inverse。因此這兩條 laws 已經等價於一個 homomorphism G→Sym(X)。本站有限例子會枚舉所有 x 與 g,h；一般 proof 則需對任意 inputs 論證。</div></details></section></article>`})
export class AlgebraV3ActionDetectorComponent{readonly candidates=ACTION_CANDIDATES;readonly candidate=signal<ActionCandidate>(ACTION_CANDIDATES[1]);readonly stage=signal(0);readonly guess=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly identityFailure=computed(()=>firstIdentityFailure(this.candidate()));readonly compositionFailure=computed(()=>firstCompositionFailure(this.candidate()));readonly witness=computed(()=>{if(this.stage()>=1&&this.identityFailure()){const f=this.identityFailure()!;return `e·${stateLabel(this.candidate(),f.state)} = ${stateLabel(this.candidate(),f.actual)} ≠ ${stateLabel(this.candidate(),f.state)}`;}if(this.stage()>=2&&this.compositionFailure()){const f=this.compositionFailure()!;return `g=${label(f.g)}, h=${label(f.h)}, x=${stateLabel(this.candidate(),f.state)}: (gh)·x=${stateLabel(this.candidate(),f.direct)}, but g·(h·x)=${stateLabel(this.candidate(),f.sequential)}`;}return null;});select(candidate:ActionCandidate):void{this.candidate.set(candidate);this.stage.set(0);this.guess.set(null);}advance():void{this.stage.update(value=>Math.min(2,value+1));}stageLabel():string{return ['READY · choose a recipe and predict','GATE 1 · identity scan complete','GATE 2 · composition scan complete'][this.stage()];}}
