import { Component, computed, signal } from '@angular/core';
import { ContractModule } from './rings-ch3-model';

@Component({selector:'app-rings-ch3-ring-blueprint',standalone:true,template:`
<article class="algebra-v3-lesson rings-lesson">
  <header class="hero"><p class="eyebrow">Rings & Ideals · 3.3</p><h2>Ring 不是 axiom wall：三個 modules 各自防止不同故障</h2><p class="lede">先把 ADD backbone 與 MULTIPLY chain 放在同一批 elements 上，再用第二章的 DISTRIBUTIVE gearbox 接合。拔掉哪個 module，就只失去它負責的推理能力。</p></header>
  <section class="prediction"><div><p class="kicker">先接線</p><h3>Additive inverse、multiplicative associativity、distributivity 應該住在同一層嗎？</h3></div><div class="choice-row"><button type="button" (click)="prediction.set(false)">不，各有 module</button><button type="button" (click)="prediction.set(true)">是，都是 closure</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'它們回答三種不同問題：difference 能否撤銷、product chain 能否重組、mixed routes 能否同步。':'對。現在逐一 disconnect，看 failure 是否只出現在對應能力。'}}</p>}</section>
  <div class="control-row"><button type="button" [class.active]="connected('add')" (click)="toggle('add')">ADD BACKBONE</button><button type="button" class="multiply" [class.active]="connected('multiply')" (click)="toggle('multiply')">MULTIPLY CHAIN</button><button type="button" [class.active]="connected('distribute')" (click)="toggle('distribute')">DISTRIBUTIVE GEARBOX</button><button type="button" [class.active]="commutative()" (click)="commutative.update(v=>!v)">COMMUTATIVE MAIN LANE</button><button type="button" (click)="connectAll()">全部接回</button></div>
  <section class="stage stage-grid"><div class="blueprint" role="img" [attr.aria-label]="ariaLabel()"><section class="blueprint-layer multiply" [class.connected]="connected('multiply')"><div><p class="kicker">UPPER LAYER</p><h3>MULTIPLY</h3></div><div class="capability-flow"><span>output stays</span><span>regroup chain</span><span>identity 1</span><span class="scope-badge" [class.out]="!commutative()">{{commutative()?'swap allowed · main lane':'order matters · valid ring'}}</span></div></section><div class="gearbox" [class.connected]="connected('distribute')">⇉</div><section class="blueprint-layer add" [class.connected]="connected('add')"><div><p class="kicker">FOUNDATION</p><h3>ADD</h3></div><div class="capability-flow"><span>combine</span><span>zero</span><span>undo</span><span>regroup + swap</span></div></section></div><aside class="console" aria-live="polite"><p class="kicker">CONTRACT STATUS</p><h3>{{connectedCount()}}/3 modules connected</h3><p>{{reading()}}</p><div class="readout">Ring = additive abelian group + stable multiplication + distributive coupling</div></aside></section>
  <section class="insight"><span class="insight-icon">⌘</span><div><strong>每條 promise 都有自己的結構工作</strong><span>拔掉一個 module，不應把其他層一起誤判。</span></div></section>
  <details><summary>正式 contract 與 conventions</summary><p>本課的 ring 有：<code>(R,+)</code> 是 abelian group；multiplication closed、associative，且有 <code>1</code>；left／right distributivity 成立。主線預設 multiplication commutative，但 noncommutative rings 仍是 rings。Ring homomorphisms 預設 preserve 1。</p></details>
</article>`})
export class RingsCh3RingBlueprintComponent{
  readonly modules=signal<ReadonlySet<ContractModule>>(new Set(['add','multiply','distribute']));readonly commutative=signal(true);readonly prediction=signal<boolean|null>(null);readonly connectedCount=computed(()=>this.modules().size);readonly reading=computed(()=>!this.connected('add')?'ADD backbone 斷線：difference solver 不再保證有 in-world answer。':!this.connected('multiply')?'MULTIPLY chain 斷線：products 無法保證穩定留在 world 並重新分組。':!this.connected('distribute')?'Gearbox 斷線：兩層各自能動，mixed routes 卻可能分岔。':this.commutative()?'三層完成，且位於本課預設 commutative lane。':'三層 core contract 完成；order 可能重要，但它仍可是一個 noncommutative ring。');readonly ariaLabel=computed(()=>`ring blueprint，${this.connectedCount()} 個 modules 已連接，${this.commutative()?'commutative main lane':'noncommutative ring scope'}`);
  connected(module:ContractModule){return this.modules().has(module);}toggle(module:ContractModule){this.modules.update(previous=>{const next=new Set(previous);next.has(module)?next.delete(module):next.add(module);return next;});}connectAll(){this.modules.set(new Set(['add','multiply','distribute']));}
}
