import { Component, computed, signal } from '@angular/core';

@Component({selector:'app-rings-ch3-zero-absorption',standalone:true,template:`
<article class="algebra-v3-lesson rings-lesson">
  <header class="hero"><p class="eyebrow">Rings & Ideals · 3.4</p><h2><code>a·0=0</code> 不是新規則：distributivity 把它複製，addition 再逼它歸零</h2><p class="lede">先把未知 output 命名為 z=a·0。因為 0+0 仍是 0，WHOLE route 留一顆 z，SPLIT route 留兩顆 z；兩條 routes 被 distributivity 鎖成同一結果。</p></header>
  <section class="prediction"><div><p class="kicker">先預測</p><h3>若 z 必須滿足 z=z+z，在 additive group 中它可以是任意 element 嗎？</h3></div><div class="choice-row"><button type="button" (click)="prediction.set(false)">不，只能是 0</button><button type="button" (click)="prediction.set(true)">可以是任意 z</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'兩側同步加 −z：左邊剩 0，右邊剩 z，所以 z 必須是 0。':'對。接著用 tokens 實際做同一個 additive cancellation。'}}</p>}</section>
  <div class="control-row"><span class="kicker">CANDIDATE z</span>@for(value of candidates;track value){<button type="button" [class.active]="z()===value" (click)="setCandidate(value)">{{value}}</button>}<button type="button" [class.active]="phase()==='compare'" (click)="phase.set('compare')">COMPARE ROUTES</button><button type="button" [class.active]="phase()==='cancel'" (click)="phase.set('cancel')">CANCEL ONE COPY</button><button type="button" (click)="reset()">重設</button></div>
  <section class="stage stage-grid"><div class="zero-stage" role="img" [attr.aria-label]="ariaLabel()"><div class="zero-route whole"><strong>WHOLE</strong><span>a(0+0)=a·0</span><div class="token-bin"><span class="z-token" [class.cancelled]="phase()==='cancel'">z</span></div></div><div class="equation-lock">{{phase()==='compare'?'distributivity locks: z = z + z':'add −z to both sides: 0 = z'}}</div><div class="zero-route split"><strong>SPLIT</strong><span>a·0+a·0</span><div class="token-bin"><span class="z-token" [class.cancelled]="phase()==='cancel'">z</span><span class="z-token">z</span></div></div><div class="same-stamp" [class.fail]="phase()==='compare'&&z()!==0">{{phase()==='cancel'?'ONLY z=0 SURVIVES':z()===0?'0 = 0 + 0 · BALANCED':'candidate '+z()+' cannot equal '+z()+'+'+z()}}</div></div><aside class="console" aria-live="polite"><p class="kicker">ZERO ABSORPTION</p><h3>{{phase()==='compare'?'z = z+z':'0 = z'}}</h3><p>{{phase()==='compare'?'WHOLE 與 SPLIT 使用同一個 z=a·0；若 candidate 非零，token counts 無法代表同一 additive result。':'同步取消不是除以 z；是在兩側加入 additive inverse −z。'}}</p><div class="readout">z=a·0，因此 {{phase()==='cancel'?'a·0=0':'a(0+0)=a0+a0'}}</div></aside></section>
  <section class="insight"><span class="insight-icon">0</span><div><strong>Zero 吸收 multiplication</strong><span>因為 multiplication 必須尊重 additive zero。</span></div></section>
  <details><summary>完整 proof 與另一側</summary><p><code>a0=a(0+0)=a0+a0</code>。兩側加上 <code>−a0</code>，得到 <code>0=a0</code>。同理由 right distributivity 得 <code>0a=0</code>；在 commutative main lane 兩側也立即相同。</p></details>
</article>`})
export class RingsCh3ZeroAbsorptionComponent{
  readonly candidates=[-2,-1,0,1,2] as const;readonly z=signal(1);readonly phase=signal<'compare'|'cancel'>('compare');readonly prediction=signal<boolean|null>(null);readonly ariaLabel=computed(()=>`zero absorption token proof，candidate z 是 ${this.z()}，目前${this.phase()==='compare'?'比較 z 與 z 加 z':'兩側取消一份 z 得零等於 z'}`);setCandidate(value:number){this.z.set(value);this.phase.set('compare');}reset(){this.z.set(1);this.phase.set('compare');this.prediction.set(null);}
}
