import { Component, computed, signal } from '@angular/core';
import { groupedProduct } from './rings-ch3-model';

@Component({selector:'app-rings-ch3-multiplication-contract',standalone:true,template:`
<article class="algebra-v3-lesson rings-lesson">
  <header class="hero"><p class="eyebrow">Rings & Ideals · 3.2</p><h2>Multiplication 要能穩定串接，但不必替每個 element 準備倒帶鍵</h2><p class="lede">固定 ordered tape 2→3→4。括號只改 compiler frame，identity 1 可以透明插入；嘗試撤銷 ×2 時需要 1/2，但這不是 ring contract 的故障。</p></header>
  <section class="prediction"><div><p class="kicker">先選 promise</p><h3>「每個 nonzero element 都有 multiplicative inverse」是 ring 的基本入場條件嗎？</h3></div><div class="choice-row"><button type="button" (click)="prediction.set(false)">不是，這是額外能力</button><button type="button" (click)="prediction.set(true)">是，否則不算 ring</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'Integers 的 2 沒有 integer multiplicative inverse，但 ℤ 仍是 ring。':'對。後面才會研究哪些個別 elements 具有這種 undo。'}}</p>}</section>
  <div class="control-row"><button type="button" [class.active]="grouping()==='left'" (click)="grouping.set('left')">(2·3)·4</button><button type="button" class="multiply" [class.active]="grouping()==='right'" (click)="grouping.set('right')">2·(3·4)</button><button type="button" [class.active]="identity()" (click)="identity.update(v=>!v)">{{identity()?'REMOVE 1':'INSERT 1'}}</button><button type="button" [class.active]="tryUndo()" (click)="tryUndo.update(v=>!v)">TRY UNDO ×2</button></div>
  <section class="stage stage-grid"><div class="multiply-tape" role="img" [attr.aria-label]="ariaLabel()"><div class="tape-row">@if(identity()){<span class="factor-block identity">1</span>}@if(grouping()==='left'){<span class="compiler-frame"><span class="factor-block">2</span><b>·</b><span class="factor-block">3</span></span><b>·</b><span class="factor-block">4</span>}@else{<span class="factor-block">2</span><b>·</b><span class="compiler-frame"><span class="factor-block">3</span><b>·</b><span class="factor-block">4</span></span>}</div><div class="same-stamp">{{product().expression}} = {{product().result}}</div><div class="contract-lights"><span class="on">✓ output in ℤ</span><span class="on">✓ regroup safely</span><span class="on">✓ identity 1</span><span class="optional">○ inverse · element ability</span></div>@if(tryUndo()){<div class="optional-socket outside"><div><strong>Undo ×2</strong><small>需要 multiplier 1/2</small></div><span class="missing-card">1/2 ∉ ℤ</span><strong>CONTRACT STILL VALID</strong></div>}</div><aside class="console" aria-live="polite"><p class="kicker">MULTIPLY CHAIN</p><h3>Endpoint 始終是 {{product().result}}</h3><p>{{grouping()==='left'?'先編譯 2·3 得 6，再乘 4。':'先編譯 3·4 得 12，再讓 2 作用。'}} Factor order 沒改。</p><div class="readout">{{tryUndo()?'Inverse socket 空著，不會使 ring contract 失效。':'插入 1 與重新分組都不改 final product。'}}</div></aside></section>
  <section class="insight"><span class="insight-icon">×</span><div><strong>Multiplication 的 undo 是額外成就</strong><span>Stable composition 與 identity 是 contract；universal inverse 不是。</span></div></section>
  <details><summary>本課採用的 multiplication convention</summary><p>本課要求 multiplication closed、associative，並有 identity <code>1</code>。有些教材允許 rings 沒有 1；我們會保持 convention 可見。Unit 的正式定義留到 Ch4。</p></details>
</article>`})
export class RingsCh3MultiplicationContractComponent{
  readonly grouping=signal<'left'|'right'>('left');readonly identity=signal(false);readonly tryUndo=signal(false);readonly prediction=signal<boolean|null>(null);readonly product=computed(()=>groupedProduct(this.grouping(),this.identity()));readonly ariaLabel=computed(()=>`multiplication tape ${this.product().expression}，結果 ${this.product().result}，${this.tryUndo()?'正在顯示乘二沒有 integer inverse':'未顯示 inverse socket'}`);
}
