import { Component, computed, signal } from '@angular/core';
import { CANDIDATE_VERDICTS, CandidateWorld, MATRIX_WITNESS } from './rings-ch3-model';

@Component({selector:'app-rings-ch3-ring-detector',standalone:true,template:`
<article class="algebra-v3-lesson rings-lesson">
  <header class="hero"><p class="eyebrow">Rings & Ideals · 3.5</p><h2>先找哪個 promise 失敗；不要從 objects 的外觀猜它是不是 ring</h2><p class="lede">同一張 detector 分兩行回答：core ring contract 是否通過，以及是否也落在本課預設的 commutative lane。Matrices 的 order mismatch 只關閉第二行。</p></header>
  <section class="prediction"><div><p class="kicker">先判斷</p><h3>Integer matrices 有 AB≠BA，這足以宣判它們完全不是 rings 嗎？</h3></div><div class="choice-row"><button type="button" (click)="prediction.set(false)">不足，仍可為 ring</button><button type="button" (click)="prediction.set(true)">足夠，不是 ring</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'Commutativity 是本課主線 scope，不是 noncommutative rings 的除名條件。':'對。它通過 core contract，只是 multiplication order 不能交換。'}}</p>}</section>
  <div class="control-row"><span class="kicker">CANDIDATE</span><button type="button" [class.active]="candidate()==='integers'" (click)="candidate.set('integers')">ℤ</button><button type="button" [class.active]="candidate()==='naturals'" (click)="candidate.set('naturals')">ℕ</button><button type="button" class="multiply" [class.active]="candidate()==='matrices'" (click)="candidate.set('matrices')">M₂(ℤ)</button><button type="button" [class.active]="candidate()==='functions'" (click)="candidate.set('functions')">Functions</button><button type="button" [class.active]="lens()==='core'" (click)="lens.set('core')">CORE CONTRACT</button><button type="button" [class.active]="lens()==='scope'" (click)="lens.set('scope')">MAIN LANE</button></div>
  <section class="stage"><div class="detector-board"><div class="mini-blueprint" role="img" [attr.aria-label]="ariaLabel()"><section class="mini-module multiply"><strong>MULTIPLY</strong><span>{{multiplyReading()}}</span></section><div class="mini-gear" [style.opacity]="lens()==='scope'?'.3':'1'">⇉</div><section class="mini-module add" [style.opacity]="lens()==='scope'?'.3':'1'"><strong>ADD</strong><span>{{addReading()}}</span></section></div><aside class="witness-panel" aria-live="polite"><p class="kicker">{{lens()==='core'?'DECISIVE CORE WITNESS':'COMMUTATIVITY SCOPE'}}</p><h3>{{candidateLabel()}}</h3><p>{{lens()==='core'?verdict().decisive:scopeReading()}}</p>@if(candidate()==='matrices'){<div class="matrix-pair"><code>AB={{matrix.ab}}</code><strong>≠</strong><code>BA={{matrix.ba}}</code></div>}@if(candidate()==='naturals'&&lens()==='core'){<div class="readout">2 + x = 1 → x = −1 ∉ ℕ</div>}<div class="verdict-line" [class.pass]="verdict().ring" [class.fail]="!verdict().ring"><span>RING CONTRACT</span><strong>{{verdict().ring?'PASS':'FAIL'}}</strong></div><div class="verdict-line" [class.pass]="verdict().ring&&verdict().commutative" [class.out]="verdict().ring&&!verdict().commutative" [class.fail]="!verdict().ring"><span>COMMUTATIVE MAIN LANE</span><strong>{{!verdict().ring?'N/A':verdict().commutative?'IN':'OUT'}}</strong></div></aside></div></section>
  <section class="insight"><span class="insight-icon">✓</span><div><strong>Definition 與 course scope 要分開</strong><span>Noncommutative matrix ring 不是失敗品；它只是需要保留 multiplication order。</span></div></section>
  <details><summary>案例邊界</summary><p><code>ℕ</code> 的兩種 operations 很有用，但 additive inverse 不完整；其他課程會稱這類結構為 semiring。Function world 使用 pointwise operations，逐 lane 繼承 integers 的 commutative unital ring contract。</p></details>
</article>`})
export class RingsCh3RingDetectorComponent{
  readonly candidate=signal<CandidateWorld>('matrices');readonly lens=signal<'core'|'scope'>('core');readonly prediction=signal<boolean|null>(null);readonly matrix=MATRIX_WITNESS;readonly verdict=computed(()=>CANDIDATE_VERDICTS[this.candidate()]);readonly candidateLabel=computed(()=>({integers:'Integers ℤ',naturals:'Nonnegative integers ℕ',matrices:'Integer matrices M₂(ℤ)',functions:'Functions {A,B,C}→ℤ'})[this.candidate()]);readonly addReading=computed(()=>this.candidate()==='naturals'?'MISSING · inverse witness':'CONNECTED · abelian group');readonly multiplyReading=computed(()=>this.candidate()==='matrices'?'CONNECTED · order matters':'CONNECTED · identity 1');readonly scopeReading=computed(()=>!this.verdict().ring?'Core contract 已失敗，因此 main-lane 分類不適用。':this.verdict().commutative?'交換 factors 不改 product；位於本課預設 commutative lane。':'AB 與 BA 給不同 outputs；它仍是 ring，但計算時必須保留 order。');readonly ariaLabel=computed(()=>`${this.candidateLabel()} detector，目前使用${this.lens()==='core'?'核心契約':'交換性範圍'}鏡頭；ring contract ${this.verdict().ring?'通過':'失敗'}，commutative main lane ${this.verdict().ring?(this.verdict().commutative?'符合':'不符合'):'不適用'}`);
}
