import { Component, computed, signal } from '@angular/core';
import { solveDifference } from './rings-ch3-model';

@Component({selector:'app-rings-ch3-additive-backbone',standalone:true,template:`
<article class="algebra-v3-lesson rings-lesson">
  <header class="hero"><p class="eyebrow">Rings & Ideals · 3.1</p><h2>Addition 不只「算得出來」：它讓任何 difference 都能在 world 內表達與撤銷</h2><p class="lede">任取 start a 與 target b。ADD backbone 必須提供一張 shift card x，使 a+x=b；把 card 翻成 −x，又能沿同一條 rail 回到 a。</p></header>
  <section class="prediction"><div><p class="kicker">先預測</p><h3>在 integers 中，start 與 target 任意交換，difference solver 會不會失去答案？</h3></div><div class="choice-row"><button type="button" (click)="prediction.set(false)">不會，負 shift 仍在 ℤ</button><button type="button" (click)="prediction.set(true)">會，不能往左</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'往左只是使用 negative element；additive inverse 讓反向 shift 仍住在 ℤ。':'對。交換 start、target 只反轉 shift direction。'}}</p>}</section>
  <div class="control-row"><span class="kicker">WORLD</span><button type="button" [class.active]="world()==='integers'" (click)="world.set('integers')">Integers ℤ</button><button type="button" [class.active]="world()==='naturals'" (click)="world.set('naturals')">Nonnegative ℕ</button><label class="compact-control">start a <input type="range" min="0" max="6" [value]="start()" (input)="setSignal(start,$event)"><strong>{{start()}}</strong></label><label class="compact-control">target b <input type="range" min="0" max="6" [value]="target()" (input)="setSignal(target,$event)"><strong>{{target()}}</strong></label><button type="button" (click)="phase.set(phase()==='solve'?'undo':'solve')">{{phase()==='solve'?'APPLY SHIFT':'UNDO SHIFT'}}</button><button type="button" (click)="swap()">交換 a、b</button></div>
  <section class="stage stage-grid"><div class="difference-stage" role="img" [attr.aria-label]="ariaLabel()"><div class="difference-rail">@for(value of rail();track value){<div class="difference-node" [class.start]="value===start()" [class.target]="value===target()" [class.missing]="world()==='naturals'&&value<0"><span>{{value}}</span><small>{{value===start()?'START':value===target()?'TARGET':''}}</small></div>}</div>@if(solution().exists){<div class="shift-arrow"><strong>{{phase()==='solve'?'a':'b'}}</strong><span class="shift-line" [class.reverse]="activeShift()<0"></span><div class="readout">{{activeShift()>=0?'+':''}}{{activeShift()}}</div><strong>{{phase()==='solve'?'b':'a'}}</strong></div>}@else{<div class="shift-arrow"><span class="missing-card">需要 shift {{solution().shift}}，但它不在 ℕ</span></div>}</div><aside class="console" aria-live="polite"><p class="kicker">DIFFERENCE SOLVER</p><h3>{{solution().exists?'x = '+solution().shift:'MISSING ADDITIVE INVERSE'}}</h3><p>{{reading()}}</p><div class="readout">{{solution().exists?(phase()==='solve'?start()+' + ('+solution().shift+') = '+target():target()+' + ('+(-solution().shift)+') = '+start()):start()+' + x = '+target()+' 無 in-world solution'}}</div></aside></section>
  <section class="insight"><span class="insight-icon">↔</span><div><strong>Addition 是可撤銷的座標底盤</strong><span>Ring 裡的 additive differences 必須永遠能被表示。</span></div></section>
  <details><summary>連回 Group Theory Foundations</summary><p><code>(R,+)</code> 必須是 abelian group：addition closed、associative，有 zero、每個 element 有 additive inverse，而且可交換。這裡把五項壓縮成「difference solver 對所有 pairs 都能運作」。</p></details>
</article>`})
export class RingsCh3AdditiveBackboneComponent{
  readonly world=signal<'integers'|'naturals'>('integers');readonly start=signal(4);readonly target=signal(1);readonly phase=signal<'solve'|'undo'>('solve');readonly prediction=signal<boolean|null>(null);readonly rail=computed(()=>Array.from({length:13},(_,index)=>index-6));readonly solution=computed(()=>solveDifference(this.start(),this.target(),this.world()));readonly activeShift=computed(()=>this.phase()==='solve'?this.solution().shift:-this.solution().shift);readonly reading=computed(()=>this.solution().exists?this.phase()==='solve'?'Difference card 把 start 精確送到 target；方向不限制 element 的存在。':'把同一張 card 反向成 additive inverse，route 回到 start。':'在 ℕ 中，往較小 target 移動需要 negative shift；solver 因此不再對所有 pairs 有答案。');readonly ariaLabel=computed(()=>`${this.world()==='integers'?'整數':'非負整數'} rail，start ${this.start()} target ${this.target()}，${this.solution().exists?'difference '+this.solution().shift:'difference 不在 world'}`);
  setSignal(target:{set(value:number):void},event:Event){const input=event.currentTarget;if(input instanceof HTMLInputElement)target.set(+input.value);}swap(){const start=this.start();this.start.set(this.target());this.target.set(start);this.phase.set('solve');}
}
