import { Component, computed, signal } from '@angular/core';

type ScannerMap='projection'|'corrupt';
@Component({selector:'app-algebra-v3-universal-commuting-scanner',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch14-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 14.2</p><h2>一格成功只是 sample；整張 square network 才是 universal claim</h2><p class="lede">Homomorphism law 控制所有 input pairs。對 finite ℤ₆→ℤ₃ map，我們可以逐格掃描：每格同時跑「先加再 map」與「先 map 再加」。</p></header>
<section class="prediction"><p class="kicker">先判斷</p><h3>只確認 φ(0)=0，就足以證明 φ 是 homomorphism 嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不足以</button><button type="button" (click)="prediction.set(true)">足以</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'很多壞 maps 也把 identity 送到 identity；law 必須涵蓋所有 pairs。':'對。一個特殊 input 不能代表 universal equality。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Universal commuting scanner</p><h3>逐格掃描兩條 pipeline，直到完成或找到分岔</h3></div><p>Row 是 a、column 是 b。每格顯示 SAME／SPLIT，不只靠顏色。</p></div><div class="map-picker" role="group" aria-label="選擇待掃描 map"><button type="button" [attr.aria-pressed]="mapId()==='projection'" (click)="select('projection')">φ(n)=n mod 3</button><button type="button" [attr.aria-pressed]="mapId()==='corrupt'" (click)="select('corrupt')">scrambled compression</button></div><div class="stage scanner-layout"><div class="commute-matrix" role="grid" aria-label="所有 input pairs 的 commuting scan"><span>a\b</span>@for(b of domain;track b){<b>{{b}}</b>}@for(a of domain;track a){<b>{{a}}</b>@for(b of domain;track b){<button type="button" [class.locked]="!isRevealed(a,b)" [class.split]="isRevealed(a,b)&&!cellPass(a,b)" (click)="inspect(a,b)"><strong>{{cellLabel(a,b)}}</strong><small>{{cellStatus(a,b)}}</small></button>}}</div><section class="scanner-console" aria-live="polite"><p class="kicker">SCANNED {{revealed()}} / 36</p><div class="path-pair"><div><span>combine → map</span><strong>φ({{selectedA()}}+{{selectedB()}})={{left(selectedA(),selectedB())}}</strong></div><div><span>map → combine</span><strong>φ({{selectedA()}})+φ({{selectedB()}})={{right(selectedA(),selectedB())}}</strong></div></div><div class="map-verdict" [class.fail]="isComplete()&&!allPass()">{{scanVerdict()}}</div><div class="control-row"><button type="button" class="primary" [disabled]="isComplete()" (click)="scanNext()">Scan next</button><button type="button" (click)="scanAll()">Scan all</button><button type="button" (click)="revealed.set(0)">重設</button></div><p>{{scopeReading()}}</p></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>one split</span><i>refutes</i><span>all pairs</span><i>or general reason proves</i></div><p><strong>Universal statement 的證據是不對稱的。</strong>一個 SPLIT cell 足以推翻；要證明成立，必須覆蓋所有 pairs 或提供同等範圍的 general argument。</p></aside>
<section class="transfer"><p class="kicker">無限 domain</p><h3>φ:ℤ→ℤ₅, φ(n)=[n] 要逐一掃完 infinite pairs 嗎？</h3><div class="choice-row"><button type="button" (click)="transfer.set(false)">不用，可用 [a+b]=[a]+[b]</button><button type="button" (click)="transfer.set(true)">必須逐對</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="transfer()">{{transfer()?'General equality 一次涵蓋所有 integers。':'對。Exhaustive UI 是 finite model；proof 需要涵蓋 domain。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>有限掃描與 proof 的關係</summary><div>Finite groups 可用完整 operation table 驗證 law。Infinite groups 則需 algebraic argument，或由 generators 的 images 與 defining relations 證明。</div></details><details><summary>Generator／relation shortcut</summary><div>若 G 由 S 生成，指定 generators 的 images 並確認 defining relations 在 H 成立，operation law 會迫使每個 word 的 image；這能取代逐一列出 infinite pairs。</div></details></section></article>`})
export class AlgebraV3UniversalCommutingScannerComponent{
 readonly domain=[0,1,2,3,4,5];readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly mapId=signal<ScannerMap>('projection');readonly revealed=signal(0);readonly selectedA=signal(0);readonly selectedB=signal(0);readonly mapping=computed(()=>this.mapId()==='projection'?[0,1,2,0,1,2]:[0,1,1,0,2,2]);
 cellIndex(a:number,b:number):number{return a*6+b;}isRevealed(a:number,b:number):boolean{return this.cellIndex(a,b)<this.revealed();}left(a:number,b:number):number{return this.mapping()[(a+b)%6];}right(a:number,b:number):number{return(this.mapping()[a]+this.mapping()[b])%3;}cellPass(a:number,b:number):boolean{return this.left(a,b)===this.right(a,b);}cellLabel(a:number,b:number):string{return this.isRevealed(a,b)?`${this.left(a,b)}/${this.right(a,b)}`:'?';}cellStatus(a:number,b:number):string{return this.isRevealed(a,b)?(this.cellPass(a,b)?'SAME':'SPLIT'):'LOCKED';}allPass():boolean{return this.domain.every(a=>this.domain.every(b=>this.cellPass(a,b)));}isComplete():boolean{return this.revealed()===36;}inspect(a:number,b:number):void{this.selectedA.set(a);this.selectedB.set(b);this.revealed.update(v=>Math.max(v,this.cellIndex(a,b)+1));}scanNext():void{const index=this.revealed();this.selectedA.set(Math.floor(index/6));this.selectedB.set(index%6);this.revealed.update(v=>Math.min(36,v+1));}scanAll():void{this.revealed.set(36);const witness=this.domain.flatMap(a=>this.domain.map(b=>[a,b] as const)).find(([a,b])=>!this.cellPass(a,b));if(witness){this.selectedA.set(witness[0]);this.selectedB.set(witness[1]);}}select(id:ScannerMap):void{this.mapId.set(id);this.revealed.set(0);this.selectedA.set(0);this.selectedB.set(0);}scanVerdict():string{return!this.isComplete()?'… UNIVERSAL CLAIM NOT YET CHECKED':this.allPass()?'✓ ALL 36 SQUARES COMMUTE · HOMOMORPHISM':'× SPLIT WITNESS · NOT A HOMOMORPHISM';}scopeReading():string{return!this.isComplete()?'目前 SAME cells 只是 samples，不能代表未掃區域。':this.allPass()?'Finite input-pair universe 已完整覆蓋。':'一個分岔 pair 已完整推翻 universal law。';}
}
