import { Component, computed, signal } from '@angular/core';

type Role='identity'|'inverse'|'powers';
@Component({selector:'app-algebra-v3-role-consequence',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch14-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 14.3</p><h2>保住 operation 之後，identity、undo、repetition 會自己跟過去</h2><p class="lede">它們不是 homomorphism 定義裡另外三條規則，而是同一條 φ(ab)=φ(a)φ(b) 的必然后果。用 projection φ:ℤ₆→ℤ₃ 逐一追蹤 action role。</p></header>
<section class="prediction"><p class="kicker">先判斷</p><h3>Group homomorphism 能把 domain identity 送到 non-identity 嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不能</button><button type="button" (click)="prediction.set(true)">能</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'φ(e)=φ(e)φ(e)，在 target group cancel φ(e) 後，只能得到 φ(e)=e。':'對。Identity role 由 operation law 強迫對齊。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Role consequence conveyor</p><h3>切換角色，看 law 如何把它送過 map</h3></div><p>每個 tab 都從 domain action 出發，經同一 law 抵達 target role；proof steps 留在下方。</p></div><div class="role-picker" role="group" aria-label="選擇 homomorphism consequence"><button type="button" [attr.aria-pressed]="role()==='identity'" (click)="role.set('identity')">identity</button><button type="button" [attr.aria-pressed]="role()==='inverse'" (click)="role.set('inverse')">inverse</button><button type="button" [attr.aria-pressed]="role()==='powers'" (click)="role.set('powers')">powers</button></div>@if(role()!=='identity'){<div class="role-controls"><label>a∈ℤ₆ <input type="range" min="1" max="5" [value]="a()" (input)="a.set(+$any($event.target).value)"><strong>{{a()}}</strong></label>@if(role()==='powers'){<label>repeat n <input type="range" min="1" max="8" [value]="power()" (input)="power.set(+$any($event.target).value)"><strong>{{power()}}</strong></label>}</div>}<div class="stage role-layout"><div class="role-conveyor"><section><span>DOMAIN ROLE</span><strong>{{domainExpression()}}</strong><small>{{domainReading()}}</small></section><b>φ preserves operation →</b><section><span>TARGET ROLE</span><strong>{{targetExpression()}}</strong><small>{{targetReading()}}</small></section></div><section class="role-console" aria-live="polite"><p class="kicker">AUTOMATIC CONSEQUENCE</p><div class="role-formula">{{formula()}}</div>@if(role()==='powers'){<div class="cycle-compression"><div><span>SOURCE ORDER</span><strong>{{sourceOrder()}}</strong></div><i>compressed to</i><div><span>IMAGE ORDER</span><strong>{{imageOrder()}}</strong></div></div>}<p>{{explanation()}}</p></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>composition kept</span><i>forces</i><span>roles kept</span></div><p><strong>Identity、inverse、powers 是 operation structure 的影子。</strong>Homomorphism 必須保留它們的角色；但 many-to-one 壓縮仍可能縮短 cycle length。</p></aside>
<section class="transfer"><p class="kicker">與 isomorphism 分界</p><h3>若 ord(a)=6，homomorphism 是否保證 ord(φ(a))=6？</h3><div class="choice-row"><button type="button" (click)="transfer.set(false)">不保證，只保證 image order divides 6</button><button type="button" (click)="transfer.set(true)">一定等於 6</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="transfer()">{{transfer()?'φ:ℤ₆→ℤ₃ 把 element 1 的六步 cycle 壓成三步。':'對。只有 injective homomorphism，特別是 isomorphism，才不會縮短 order。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>Identity proof</summary><div>φ(e)=φ(ee)=φ(e)φ(e)。左乘 φ(e)⁻¹，得 e=φ(e)。</div></details><details><summary>Inverse proof</summary><div>aa⁻¹=e，所以 φ(a)φ(a⁻¹)=φ(e)=e。Inverse uniqueness 給 φ(a⁻¹)=φ(a)⁻¹。</div></details><details><summary>Powers proof</summary><div>對 positive n 反覆使用 operation law；n=0 用 identity；negative n 再使用 inverse consequence，得到 φ(aⁿ)=φ(a)ⁿ。</div></details></section></article>`})
export class AlgebraV3RoleConsequenceComponent{
 readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly role=signal<Role>('identity');readonly a=signal(1);readonly power=signal(4);
 domainExpression():string{if(this.role()==='identity')return'0 in ℤ₆';if(this.role()==='inverse')return`−${this.a()} = ${(6-this.a())%6}`;return`${this.power()}·${this.a()} = ${(this.power()*this.a())%6}`;}targetExpression():string{if(this.role()==='identity')return'0 in ℤ₃';if(this.role()==='inverse')return`−φ(${this.a()}) = ${(3-(this.a()%3))%3}`;return`${this.power()}·φ(${this.a()}) = ${(this.power()*(this.a()%3))%3}`;}domainReading():string{return this.role()==='identity'?'does nothing':this.role()==='inverse'?'undo inside source':'repeat source action';}targetReading():string{return this.role()==='identity'?'still does nothing':this.role()==='inverse'?'undo translated action':'same repetition after map';}formula():string{return this.role()==='identity'?'φ(e_G)=e_H':this.role()==='inverse'?'φ(a⁻¹)=φ(a)⁻¹':'φ(aⁿ)=φ(a)ⁿ';}explanation():string{return this.role()==='identity'?'Do-nothing action cannot become an action that changes target state.':this.role()==='inverse'?'Undo before mapping and undo after mapping cancel the same translated action.':'Every step of a repeated action chain can be translated; the endpoint commutes.';}sourceOrder():number{return 6/this.gcd(6,this.a());}imageOrder():number{const image=this.a()%3;return 3/this.gcd(3,image);}private gcd(a:number,b:number):number{return b===0?a:this.gcd(b,a%b);}
}
