import { Component, computed, signal } from '@angular/core';

type CompressionMap='parity'|'absolute';
@Component({selector:'app-algebra-v3-compression-lens',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch14-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 14.1</p><h2>Collision 不一定是故障：真正不能丟的是合成規律</h2><p class="lede">Isomorphism 不准合併 inputs；homomorphism 可以。問題不再是「能否唯一翻回」，而是被壓縮後，output operation 是否仍能忠實預測 input composition。</p></header>
<section class="prediction"><p class="kicker">先預測</p><h3>把 integers 只記成 odd／even，一定會破壞 addition 嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不一定，parity 保留加法</button><button type="button" (click)="prediction.set(true)">一定破壞</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'雖然許多 integers collision，sum 的 parity 仍完全由兩個 input parities 決定。':'對。資訊量變少，不等於 operation structure 被改壞。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Compression-vs-corruption lens</p><h3>同樣有 collisions，結果可能一好一壞</h3></div><p>Parity map 與 absolute-value map 都 many-to-one；用同一對 a、b 比較 operation 是否 survive。</p></div><div class="map-picker" role="group" aria-label="選擇 compression map"><button type="button" [attr.aria-pressed]="mapId()==='parity'" (click)="selectMap('parity')">φ(n)=n mod 2</button><button type="button" [attr.aria-pressed]="mapId()==='absolute'" (click)="selectMap('absolute')">ψ(n)=|n|</button></div><div class="pair-controls"><label>a <input type="range" min="-3" max="3" [value]="a()" (input)="a.set(+$any($event.target).value)"><strong>{{a()}}</strong></label><label>b <input type="range" min="-3" max="3" [value]="b()" (input)="b.set(+$any($event.target).value)"><strong>{{b()}}</strong></label></div><div class="stage compression-layout"><div><div class="fiber-board">@for(fiber of fibers();track fiber.output){<section><span>OUTPUT {{fiber.output}}</span><strong>{{fiber.inputs.join(' · ')}}</strong><small>{{fiber.inputs.length>1?'COLLISION VISIBLE':'ONE SAMPLE'}}</small></section>}</div><div class="compression-tape"><span>{{mapName()}}({{a()}}+{{b()}})</span><strong>{{leftEnd()}}</strong><i>vs</i><span>{{mapName()}}({{a()}}) ⊕ {{mapName()}}({{b()}})</span><strong>{{rightEnd()}}</strong></div></div><section class="compression-console" aria-live="polite"><p class="kicker">TWO INDEPENDENT AXES</p><div class="axis-readout"><span>INJECTIVE?</span><strong>NO · COLLISIONS</strong></div><div class="axis-readout"><span>OPERATION KEPT?</span><strong>{{pairPass()?'THIS PAIR PASSES':'× MISMATCH WITNESS'}}</strong></div><div class="map-verdict" [class.fail]="!isHomomorphism()">{{isHomomorphism()?'✓ LEGAL COMPRESSION · HOMOMORPHISM':'× CORRUPTED OPERATION · NOT A HOMOMORPHISM'}}</div><button type="button" (click)="findWitness()">找一個 mismatch witness</button><p>{{isHomomorphism()?'Many-to-one 遺忘了 exact integer，卻保留 addition 的 parity。':'例如 −2+1：先相加取 absolute 得 1，先取 absolute 再加得 3。'}}</p></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>which element</span><i>may forget</i><span>how compose</span><i>must keep</i></div><p><strong>Homomorphism 可以遺忘 element identity，但不能改寫 operation。</strong>Injectivity 與 structure preservation 是兩條不同的檢查軸。</p></aside>
<section class="transfer"><p class="kicker">遷移</p><h3>Determinant 讓很多 matrices collision，為什麼仍可能是 homomorphism？</h3><div class="choice-row"><button type="button" (click)="transfer.set(true)">因為 det(AB)=det(A)det(B)</button><button type="button" (click)="transfer.set(false)">因為 determinant 是 injective</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="!transfer()">{{transfer()?'對。它不保留 matrix identity，卻保留 multiplication structure。':'許多不同 matrices 有同一 determinant；關鍵是保乘法。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>Group homomorphism</summary><div>Map φ:G→H 若對所有 a,b∈G 滿足 φ(ab)=φ(a)φ(b)，稱為 group homomorphism。Injective、surjective 都不是定義的一部分。</div></details><details><summary>為何 parity map 保加法？</summary><div>Write a=2q+r、b=2s+t，其中 r,t∈{{'{0,1}'}}。則 a+b=2(q+s)+(r+t)，所以 [a+b]₂=[a]₂+[b]₂。</div></details></section></article>`})
export class AlgebraV3CompressionLensComponent{
 readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly mapId=signal<CompressionMap>('parity');readonly a=signal(-2);readonly b=signal(1);readonly samples=[-3,-2,-1,0,1,2,3];
 readonly fibers=computed(()=>{const groups=new Map<number,number[]>();for(const n of this.samples){const out=this.map(n);groups.set(out,[...(groups.get(out)??[]),n]);}return[...groups.entries()].map(([output,inputs])=>({output,inputs}));});readonly leftEnd=computed(()=>this.map(this.a()+this.b()));readonly rightEnd=computed(()=>this.mapId()==='parity'?(this.map(this.a())+this.map(this.b()))%2:this.map(this.a())+this.map(this.b()));readonly pairPass=computed(()=>this.leftEnd()===this.rightEnd());readonly isHomomorphism=computed(()=>this.mapId()==='parity');
 map(n:number):number{return this.mapId()==='parity'?((n%2)+2)%2:Math.abs(n);}mapName():string{return this.mapId()==='parity'?'φ':'ψ';}selectMap(id:CompressionMap):void{this.mapId.set(id);this.a.set(-2);this.b.set(1);}findWitness():void{if(this.mapId()==='absolute'){this.a.set(-2);this.b.set(1);}else{this.a.set(2);this.b.set(3);}}
}
