import { Component, computed, signal } from '@angular/core';
import { D3_ELEMENTS, type D3Element, label, multiply } from '../algebra-v3-ch16/d3-model';
import { type ScenePoint, actOnScene, pointLabel, stabilizerOf } from '../algebra-v3-ch23/orbit-model';

@Component({selector:'app-algebra-v3-action-fiber-sorter',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch24-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 24.1</p><h2>把 actors 依 destination 分包，每一包都只是 stabilizer 的平移副本</h2><p class="lede">固定 x=▲，action map 把每個 g 送到 g·x。相同 output 的 recipes 會落在同一條 fiber；它們彼此只差一個「先在 x 原地做完」的 stabilizer move。</p></header>
<section class="prediction"><p class="kicker">先預測</p><h3>r 與 rs 都把 ▲ 送到 ▶；它們的差別能由 Stab(▲) 補上嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(true)">能，rs = r·s</button><button type="button" (click)="prediction.set(false)">不能，同 output 只是巧合</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="!prediction()">{{prediction()?'對。s 先固定 ▲，再由 r 送到 ▶；因此 r 與 rs 必然共享 destination。':'s∈Stab(▲)，所以在 recipe 右側補 s 不改變最後 destination。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Action-fiber sorter</p><h3>逐張投放 actor card，看它落進哪個 output lane</h3></div><p>每條 lane 上方是 X 裡的 point，下方 cards 是 G 裡的 actors；兩種 type 保持分開。</p></div><div class="stage fiber-stage"><section class="fiber-lanes" aria-label="action fibers by destination">@for(lane of lanes();track lane.point){<article><header><span>DESTINATION</span><strong>{{pointName(lane.point)}}</strong></header><div class="lane-cards">@for(actor of lane.actors;track actor){<b>{{name(actor)}}</b>}@if(lane.actors.length===0){<i>WAITING</i>}</div><footer><span>COSET RECIPE</span><strong>{{lane.representative?name(lane.representative):lane.point===0?'e':'?'}} · Stab(▲)</strong></footer></article>}</section><section class="fiber-console" aria-live="polite"><p class="kicker">SORTED {{count()}} / 6</p><div class="incoming-card"><span>NEXT ACTOR</span><b>{{nextActor()}}</b><small>{{count()<6?'READY TO ROUTE':'ALL CARDS ROUTED'}}</small></div><div class="base-stabilizer"><span>BASE PACKET · STAB(▲)</span><b>{{stabilizerLabel()}}</b></div><button type="button" class="primary" [disabled]="count()>=6" (click)="scanNext()">投放下一張 card</button><button type="button" (click)="count.set(6)">全部分包</button><button type="button" (click)="count.set(0)">重設</button></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>fiber over kx</span><i>=</i><span>k · Stab(x)</span></div><p><strong>一條 action fiber 是 stabilizer 的 coset。</strong>先選一個到達 destination 的代表 k，再接上任何不移動 x 的 local move，destination 都不變；而所有同 destination recipes 都能這樣寫。</p></aside>
<section class="transfer"><p class="kicker">遷移</p><h3>既然三條 fibers 都是同一個 stabilizer 的 cosets，它們的 card 數會怎樣？</h3><div class="choice-row"><button type="button" (click)="transfer.set(true)">一定一樣多</button><button type="button" (click)="transfer.set(false)">可能各自不同</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="!transfer()">{{transfer()?'對。乘上 k 是 bijection，所以每個 coset 與 stabilizer 一樣大。':'每條 lane 都由 h↦kh 一對一複製 Stab(x)，大小不會改變。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>Fiber 等於 left coset 的 proof</summary><div>固定 x，令 Gₓ=Stab(x)。若 g·x=k·x，則 k⁻¹g·x=x，所以 k⁻¹g∈Gₓ，亦即 g∈kGₓ。反向若 g=kh 且 h∈Gₓ，則 g·x=k·(h·x)=k·x。因此 action map 在 kx 上的 fiber 正是 kGₓ。</div></details></section></article>`})
export class AlgebraV3ActionFiberSorterComponent{readonly elements=D3_ELEMENTS;readonly destinations=[0,1,2]as const;readonly base=0 as ScenePoint;readonly count=signal(0);readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly stabilizer=stabilizerOf(this.base);readonly lanes=computed(()=>this.destinations.map(point=>{const actors=this.elements.slice(0,this.count()).filter(actor=>actOnScene(actor,this.base)===point);const representative=this.elements.find(actor=>actOnScene(actor,this.base)===point);return{point,actors,representative};}));name=label;pointName=pointLabel;scanNext():void{this.count.update(v=>Math.min(6,v+1));}nextActor():string{return this.count()<6?label(this.elements[this.count()]):'—';}stabilizerLabel():string{return `{${this.stabilizer.map(label).join(', ')}}`;}coset(rep:D3Element):D3Element[]{return this.stabilizer.map(h=>multiply(rep,h));}}
