import { Component, computed, signal } from '@angular/core';
interface Face{code:string;label:string;symbol:string}
@Component({selector:'app-algebra-v3-cube-rotation-counter',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch24-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 24.3</p><h2>不列出 24 個 cube rotations；只問 reference face 去哪裡、到達後怎麼轉</h2><p class="lede">追蹤一個帶箭頭的 reference face。rotation 先決定它落到六個 faces 中哪一個；destination 固定後，還有四種 quarter-turn orientations。</p></header>
<section class="prediction"><p class="kicker">先預測</p><h3>只知道 reference face 被送到 TOP，是否已唯一決定整個 cube rotation？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">還沒有，TOP 上仍可 twist 四種方向</button><button type="button" (click)="prediction.set(true)">已經唯一，destination 足夠</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'同一 face 能朝四個方向落在 TOP；這四個 rotations 都有相同 face destination。':'對。剩下的 stabilizer choices 正是繞該 face normal 的 0°、90°、180°、270°。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Cube rotation counter</p><h3>選 destination face，再選到位後的 twist</h3></div><p>每個 pair 是唯一 rotation address；你只操作兩個有意義的 choices，不必背 24 張清單。</p></div><div class="cube-controls"><fieldset><legend>1 · REFERENCE FACE DESTINATION</legend>@for(face of faces;track face.code){<button type="button" [attr.aria-pressed]="faceIndex()=== $index" (click)="faceIndex.set($index)">{{face.symbol}} {{face.label}}</button>}</fieldset><fieldset><legend>2 · ORIENTATION AFTER ARRIVAL</legend>@for(turn of twists;track turn){<button type="button" [attr.aria-pressed]="twist()=== $index" (click)="twist.set($index)">{{turn}}°</button>}</fieldset></div>
<div class="stage cube-stage"><section class="cube-visual"><div class="iso-cube"><div class="cube-face top"><span [style.transform]="arrowRotation()">↑</span><small>{{selectedFace().label}}</small></div><div class="cube-face left"></div><div class="cube-face right"></div></div><div class="rotation-address"><span>ROTATION ADDRESS</span><b>({{selectedFace().code}}, {{twists[twist()]}}°)</b><small>UNIQUE ROTATION #{{rotationId()}} OF 24</small></div></section><section class="rotation-packets" aria-label="six destinations with four twists each">@for(face of faces;track face.code;let faceNumber=$index){<article [class.selected]="faceIndex()===faceNumber"><header>{{face.code}}</header><div>@for(turn of twists;track turn;let turnNumber=$index){<span [class.active]="faceIndex()===faceNumber&&twist()===turnNumber">{{turn}}°</span>}</div><footer>4 ROTATIONS</footer></article>}</section><section class="cube-console"><p class="kicker">ORBIT × STABILIZER</p><div class="cube-equation"><span>6 face destinations</span><i>×</i><span>4 twists fixing a face</span><b>= 24 rotations</b></div><div class="cube-verdict">6 PACKETS · 4 UNIQUE CARDS EACH</div></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>where can it go?</span><i>×</i><span>what can still fix it?</span></div><p><strong>Orbit–stabilizer 是一種 counting strategy。</strong>把 transformation 拆成「把 reference object 送去哪裡」與「到那裡後還能保住它做什麼」，通常比逐一枚舉容易得多。</p></aside>
<section class="transfer"><p class="kicker">遷移</p><h3>若只標 face 顏色、不標面上的箭頭，為什麼容易少算？</h3><div class="choice-row"><button type="button" (click)="transfer.set(true)">會漏掉固定 face 的四種 twists</button><button type="button" (click)="transfer.set(false)">不會，六個 faces 就是全部 rotations</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="!transfer()">{{transfer()?'對。face orbit 只數 destinations；stabilizer 補回「destination 不變但 cube 仍在轉」的 choices。':'六只數到 orbit size，漏掉每個 destination fiber 裡的四張 cards。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>為什麼每個 address 唯一？</summary><div>一個 orientation-preserving cube symmetry 由一個 face 的 image 與該 face 上一個有方向的 edge image 唯一決定。reference face 有 6 個 images；固定 image face 後，有 4 個 oriented edges 可承接 reference arrow。因此 rotational symmetry group 的 order 是 6·4=24。</div></details></section></article>`})
export class AlgebraV3CubeRotationCounterComponent{readonly faces:readonly Face[]=[{code:'T',label:'TOP',symbol:'⬆'},{code:'F',label:'FRONT',symbol:'⬒'},{code:'R',label:'RIGHT',symbol:'▶'},{code:'B',label:'BACK',symbol:'⬓'},{code:'L',label:'LEFT',symbol:'◀'},{code:'D',label:'BOTTOM',symbol:'⬇'}];readonly twists=[0,90,180,270];readonly faceIndex=signal(0);readonly twist=signal(0);readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly selectedFace=computed(()=>this.faces[this.faceIndex()]);readonly rotationId=computed(()=>this.faceIndex()*4+this.twist()+1);arrowRotation():string{return `rotate(${this.twists[this.twist()]}deg)`;}}
