import { Component, computed, signal } from '@angular/core';
import { D3_ELEMENTS, label } from '../algebra-v3-ch16/d3-model';
import { type ScenePoint, actOnScene, orbitOf, pointLabel, stabilizerOf } from '../algebra-v3-ch23/orbit-model';

@Component({selector:'app-algebra-v3-conservation-dashboard',standalone:true,template:`
<article class="algebra-v3-lesson alg-ch24-lesson"><header class="hero"><p class="eyebrow">Abstract Algebra · 24.2</p><h2>Orbit 變大時，每個 destination 可藏的 local symmetry 就變少</h2><p class="lede">六張 actor cards 一張都不增不減，只是依 action map 重新分包。包數是 orbit size；每包 card 數是 stabilizer size。</p></header>
<section class="prediction"><p class="kicker">先預測</p><h3>同一個 |G|=6，如果 orbit 從 1 個 destination 變成 3 個，每包還能放 6 張嗎？</h3><div class="choice-row"><button type="button" (click)="prediction.set(false)">不能，必須縮成每包 2 張</button><button type="button" (click)="prediction.set(true)">能，orbit 與 stabilizer 無關</button></div>@if(prediction()!==null){<p class="feedback" [class.warning]="prediction()">{{prediction()?'那會需要 3×6=18 張 actors，但群裡只有 6 張；同一 actor 也不能落入兩個 outputs。':'對。fibers partition G，所以包數乘每包大小必須守恆。'}}</p>}</section>
<section class="lab"><div class="lab-heading"><div><p class="kicker">Conservation dashboard</p><h3>切換 seed；同一批六張 cards 會重新分裝</h3></div><p>vertex 有三個可達 outputs；center 只有一個。每條 fiber 的 stripe pattern 相同，表示等大。</p></div><div class="seed-toggle"><button type="button" [attr.aria-pressed]="seed()===0" (click)="seed.set(0)">SEED ▲</button><button type="button" [attr.aria-pressed]="seed()===3" (click)="seed.set(3)">SEED ●</button></div>
<div class="stage conservation-stage"><section class="packet-board">@for(packet of packets();track packet.point){<article><header><span>OUTPUT</span><strong>{{pointName(packet.point)}}</strong></header><div>@for(actor of packet.actors;track actor){<b>{{name(actor)}}</b>}</div><footer>{{packet.actors.length}} ACTORS IN THIS FIBER</footer></article>}</section><section class="conservation-console" aria-live="polite"><p class="kicker">NOTHING CREATED · NOTHING LOST</p><div class="factor-equation"><article><span>TOTAL ACTORS</span><b>|G| = 6</b></article><i>=</i><article><span>DESTINATION PACKETS</span><b>{{orbitSize()}}</b><small>|Orb(x)|</small></article><i>×</i><article><span>CARDS PER PACKET</span><b>{{stabilizerSize()}}</b><small>|Stab(x)|</small></article></div><div class="balance-verdict">6 = {{orbitSize()}} × {{stabilizerSize()}} · CONSERVED</div></section></div></section>
<aside class="insight-card"><div class="insight-visual" aria-hidden="true"><span>|G| actors</span><i>partition</i><span>|Orb(x)| packets × |Gₓ| each</span></div><p><strong>Orbit–stabilizer theorem 是 action fibers 的分裝守恆。</strong>「能去很多地方」與「留在原地的方法很多」共享同一批 group elements，因此此消彼長。</p></aside>
<section class="transfer"><p class="kicker">遷移</p><h3>若一個 action 中只有 identity 能固定 x，Orb(x) 會有多大？</h3><div class="choice-row"><button type="button" (click)="transfer.set(true)">和 G 一樣大</button><button type="button" (click)="transfer.set(false)">只有一個 point</button></div>@if(transfer()!==null){<p class="feedback" [class.warning]="!transfer()">{{transfer()?'對。每包只有一張 card，因此每個 actor 都必須落在不同 destination。':'stabilizer size=1 時，守恆式給 |Orb(x)|=|G|。'}}</p>}</section>
<section class="secondary"><p>SECONDARY LAYER</p><details><summary>有限群版本的 theorem</summary><div>若有限群 G 作用在 X 上，對每個 x∈X，action map 的 image 是 Orb(x)，每條 fiber 是一個 left coset of Gₓ。所有 cosets 大小都是 |Gₓ|，故 |G|=|Orb(x)|·|Gₓ|，等價於 |Orb(x)|=[G:Gₓ]。</div></details></section></article>`})
export class AlgebraV3ConservationDashboardComponent{readonly elements=D3_ELEMENTS;readonly seed=signal<ScenePoint>(0);readonly prediction=signal<boolean|null>(null);readonly transfer=signal<boolean|null>(null);readonly packets=computed(()=>orbitOf(this.seed()).map(point=>({point,actors:this.elements.filter(actor=>actOnScene(actor,this.seed())===point)})));readonly orbitSize=computed(()=>this.packets().length);readonly stabilizerSize=computed(()=>stabilizerOf(this.seed()).length);name=label;pointName=pointLabel;}
